### ISSUE TITLE
Cache top fails

### ISSUE THREAD

**Issue by stgleb** [iovisor/bcc#1045]
Bcc tools works fine, but when I run cachetop utility it gives following error

`Traceback (most recent call last):
  File "./cachetop", line 254, in <module>
    curses.wrapper(handle_loop, args)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "./cachetop", line 229, in handle_loop
    *stat, username=pwd.getpwuid(int(stat[1]))[0]
_curses.error: addstr() returned ERR`

But sometimes it works for a few seconds and gives the same error.

**Comment by goldshtn** [comment]
@chantra Can you please take a look? Any ideas?
