### ISSUE TITLE
Multiple tests in make-test failing on v0.3.0-87-ge2a0377

### ISSUE THREAD

**Issue by rnsanchez** [iovisor/bcc#1101]
After building bcc from master at e2a037779c2b8c6ca83648699f0af670668a92b5 with all optional packages installed, `make test` failed in a number of tests.

Environment:
* Slackware64-current (as of April 7th, 2017)
* Linux kernel 4.11.0-rc3 (most/all things included for verbose tracing)
* GCC-5.4.0
* Clang-4.0.0
* Python-2.7.13
* Lua-5.1.5
* LuaJIT-2.0.4
* Netperf-2.6.0
* iperf-2.0.5
* netaddr-0.7.19

Test summary:

    Total Test time (real) = 306.91 sec
    
    The following tests FAILED:
              3 - test_libbcc (Failed)
              7 - py_test_xlate1_c (Failed)
              8 - py_test_call1 (Failed)
             15 - py_test_brb (Failed)
             17 - py_test_clang (Failed)
             18 - py_test_histogram (Failed)
             24 - py_test_perf_event (Failed)
             28 - py_test_tools_smoke (Failed)
    Errors while running CTest

The `Makefile` was changed to include `-VV` as argument to `ctest`.  I've included the relevant snippet from `dmesg`, and the output for `make test`.

[dmesg.txt](https://github.com/iovisor/bcc/files/906198/dmesg.txt)
[make_test.txt](https://github.com/iovisor/bcc/files/906197/make_test.txt)

**Comment by palmtenor** [comment]
Could it be LLVM related? Buildbot and my personal environment was using LLVM 3.8 or earlier version. And the errors do look like related to Clang-compiled bytecode.

**Comment by rnsanchez** [comment]
I will repeat on a machine with `clang version 3.8.1 (tags/RELEASE_381/final)`, and update the logs.

**Comment by rnsanchez** [comment]
@palmtenor: with all optional packages in place, there were a lot less failures when compared to Clang-4.0.0:

    91% tests passed, 3 tests failed out of 32
    
    Total Test time (real) = 339.47 sec
    
    The following tests FAILED:
              3 - test_libbcc (Failed)
              8 - py_test_call1 (Failed)
             28 - py_test_tools_smoke (Failed)
    Errors while running CTest

[dmesg_clang_381.txt](https://github.com/iovisor/bcc/files/906499/dmesg_clang_381.txt)
[make_test_clang_381.txt](https://github.com/iovisor/bcc/files/906502/make_test_clang_381.txt)

**Comment by relet** [comment]
@rnsanchez: Did you get any further than that? I am at exactly the same stage, with the three tests failing building 648554df57b42806f50460f11c62feb2657f7ff4 on Debian / 4.13.0-1-amd64

**Comment by rnsanchez** [comment]
On 648554df5, still getting 3 tests to fail (though now test 8 passes while 12 fails):

    The following tests FAILED:
              3 - test_libbcc (Failed)
             12 - py_test_trace4 (Failed)
             28 - py_test_tools_smoke (Failed)
    Errors while running CTest

Notes:

* Slackware64-current as of Oct 10th, 2017
* GCC 7.2.0
* LLVM/Clang 5.0.0
* Python 2.7.14 and 3.6.3
* Lua 5.1.5
* LuaJIT 2.0.4

Updated logs attached.

[648554df5-dmesg.log](https://github.com/iovisor/bcc/files/1407971/648554df5-dmesg.log)
[648554df5-test.log](https://github.com/iovisor/bcc/files/1407972/648554df5-test.log)

**Comment by yonghong-song** [comment]
Look at the test log file:
  . test_libbcc: usdt parsing error?
  . py_test_trace4: this relies on certain kernel map-related functions are executing the exact certain number of times. bcc internal retries may change this.
  . py_test_tools_smoke: 
28: Traceback (most recent call last):
28:   File "/home/rnsanchez/apps/bcc/tests/python/test_tools_smoke.py", line 205, in test_mdflush
28:     self.run_with_int("mdflush.py")
28:   File "/home/rnsanchez/apps/bcc/tests/python/test_tools_smoke.py", line 52, in run_with_int
28:     or (rc == 137 and kill), "rc was %d" % rc)
28: AssertionError: rc was 1
  The test may fail just because you have newer kernel.

**Comment by relet** [comment]
That's likely. I had no issues compiling and using bcc (except for the debuild build failing on the tests). 
The issue seems to be only with the test definition then.
