### ISSUE TITLE
Redefinition of methods

### ISSUE THREAD

**Issue by jesperpedersen** [iovisor/bcc#1106]
When I execute ```dbslower postgres``` I get the following:

```
/virtual/main.c:13:19: error: redefinition of '_bpf_readarg_probe_start_1'
static inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
                  ^
/virtual/main.c:2:19: note: previous definition is here
static inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
                  ^
/virtual/main.c:18:19: error: redefinition of '_bpf_readarg_probe_end_1'
static inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
                  ^
/virtual/main.c:7:19: note: previous definition is here
static inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
                  ^
2 errors generated.
```

There are multiple ```postgres``` instances running.

There are other errors as well, but those are solved by changing ```#include <linux/ptrace.h>``` to ```#include <uapi/linux/ptrace.h>```

Using latest master ( d5e5bb3 ) with clang version 3.8.1 on Fedora 24.

**Comment by goldshtn** [comment]
It looks like when you have multiple postgres instances running, the tool will try to attach to all of them, and that won't work because of the way USDT probes are currently generated. I don't have all the code in front of me right now, but I suspect we would need to change bcc, not just the dbslower tool to fix this. (I will look into it later.)

As for this specific problem: does it help when you pass the process id (`-p $PID`), so that only a specific process is traced?

**Comment by jesperpedersen** [comment]
If I do ```dbslower postgres -p 1769``` I get

```
[root@localhost tools]# ./dbslower postgres -p 1769
bpf: Invalid argument

Traceback (most recent call last):
  File "./dbslower", line 109, in <module>
    bpf = BPF(text=program, usdt_contexts=usdts)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 296, in __init__
    usdt_context.attach_uprobes(self)
  File "/usr/lib/python2.7/site-packages/bcc/usdt.py", line 181, in attach_uprobes
    addr=addr, pid=pid)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 818, in attach_uprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 344, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program probe_start: Invalid argument
```

**Comment by goldshtn** [comment]
Could you please add `-v` to the tool invocation so that we get the full BPF program?

**Comment by jesperpedersen** [comment]
I get the same:
```
[root@localhost tools]# ./dbslower postgres -v -p 1769
bpf: Invalid argument

Traceback (most recent call last):
  File "./dbslower", line 109, in <module>
    bpf = BPF(text=program, usdt_contexts=usdts)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 296, in __init__
    usdt_context.attach_uprobes(self)
  File "/usr/lib/python2.7/site-packages/bcc/usdt.py", line 181, in attach_uprobes
    addr=addr, pid=pid)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 818, in attach_uprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 344, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program probe_start: Invalid argument
```

On Linux 4.10.8 btw.

**Comment by goldshtn** [comment]
Oh! Looking at the code, I see that we print the BPF program _after_ we try to load it, so if that fails -- we don't see the program. 😊 That needs to be fixed, of course. In the meantime, could you perhaps move lines 110-112 _before_ line 109, so we can see the BPF program as it is generated?

**Comment by goldshtn** [comment]
BTW I'm on 4.9.13-200.fc25.x86_64 and I can't reproduce this with my build of Postgres.

**Comment by jesperpedersen** [comment]
```
[root@localhost tools]# ./dbslower -v postgres -p 1769
#include <uapi/linux/ptrace.h>
static inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}
static inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}


#include <uapi/linux/ptrace.h>

struct temp_t {
    u64 timestamp;
    char *query;
};

struct data_t {
    u64 pid;
    u64 timestamp;
    u64 duration;
    char query[256];
};

BPF_HASH(temp, u64, struct temp_t);
BPF_PERF_OUTPUT(events);

int probe_start(struct pt_regs *ctx) {
    struct temp_t tmp = {};
    tmp.timestamp = bpf_ktime_get_ns();
    bpf_usdt_readarg(1, ctx, &tmp.query);
    u64 pid = bpf_get_current_pid_tgid();
    temp.update(&pid, &tmp);
    return 0;
}

int probe_end(struct pt_regs *ctx) {
    struct temp_t *tempp;
    u64 pid = bpf_get_current_pid_tgid();
    tempp = temp.lookup(&pid);
    if (!tempp)
        return 0;

    u64 delta = bpf_ktime_get_ns() - tempp->timestamp;
    if (delta >= 1000000) {
        struct data_t data = {};
        data.pid = pid >> 32;   // only process id
        data.timestamp = tempp->timestamp;
        data.duration = delta;
        bpf_probe_read(&data.query, sizeof(data.query), tempp->query);
        events.perf_submit(ctx, &data, sizeof(data));
    }
    temp.delete(&pid);
    return 0;
}

bpf: Invalid argument

Traceback (most recent call last):
  File "./dbslower", line 113, in <module>
    bpf = BPF(text=program, usdt_contexts=usdts)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 296, in __init__
    usdt_context.attach_uprobes(self)
  File "/usr/lib/python2.7/site-packages/bcc/usdt.py", line 181, in attach_uprobes
    addr=addr, pid=pid)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 818, in attach_uprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 344, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program probe_start: Invalid argument
```

Note, that this includes the ```#include <uapi/linux/ptrace.h>``` change

**Comment by goldshtn** [comment]
Hmm. Can you load any BPF program at all? E.g. can you try some other tools like `biosnoop` or `cpudist` to see if this is specific to `dbslower`?

**Comment by goldshtn** [comment]
Could this be the same issue as #881 (assuming that you updated your kernel separately from the kernel headers)?

**Comment by jesperpedersen** [comment]
*Facepalm*

Precisely the issue, headers didn't match.

Sorry for wasting your time !

**Comment by jesperpedersen** [comment]
Actually, ```cpudist``` works now, but ```dbslower``` still fails... Need more coffee

**Comment by jesperpedersen** [comment]
```
[root@localhost tools]# ./dbslower -v postgres
#include <uapi/linux/ptrace.h>
static inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}
static inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}

#include <uapi/linux/ptrace.h>
static inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}
static inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}

#include <uapi/linux/ptrace.h>
static inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}
static inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}

#include <uapi/linux/ptrace.h>
static inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}
static inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}

#include <uapi/linux/ptrace.h>
static inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}
static inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}

#include <uapi/linux/ptrace.h>
static inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}
static inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}

#include <uapi/linux/ptrace.h>
static inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}
static inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}

#include <uapi/linux/ptrace.h>
static inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}
static inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  { u64 __addr = ctx->bp + (-248);uint64_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint64_t *)dest) = __res; }
  return 0;
}


#include <uapi/linux/ptrace.h>

struct temp_t {
    u64 timestamp;
    char *query;
};

struct data_t {
    u64 pid;
    u64 timestamp;
    u64 duration;
    char query[256];
};

BPF_HASH(temp, u64, struct temp_t);
BPF_PERF_OUTPUT(events);

int probe_start(struct pt_regs *ctx) {
    struct temp_t tmp = {};
    tmp.timestamp = bpf_ktime_get_ns();
    bpf_usdt_readarg(1, ctx, &tmp.query);
    u64 pid = bpf_get_current_pid_tgid();
    temp.update(&pid, &tmp);
    return 0;
}

int probe_end(struct pt_regs *ctx) {
    struct temp_t *tempp;
    u64 pid = bpf_get_current_pid_tgid();
    tempp = temp.lookup(&pid);
    if (!tempp)
        return 0;

    u64 delta = bpf_ktime_get_ns() - tempp->timestamp;
    if (delta >= 1000000) {
        struct data_t data = {};
        data.pid = pid >> 32;   // only process id
        data.timestamp = tempp->timestamp;
        data.duration = delta;
        bpf_probe_read(&data.query, sizeof(data.query), tempp->query);
        events.perf_submit(ctx, &data, sizeof(data));
    }
    temp.delete(&pid);
    return 0;
}

/virtual/main.c:13:19: error: redefinition of '_bpf_readarg_probe_start_1'
static inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
                  ^
/virtual/main.c:2:19: note: previous definition is here
static inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
                  ^
/virtual/main.c:18:19: error: redefinition of '_bpf_readarg_probe_end_1'
static inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
                  ^
/virtual/main.c:7:19: note: previous definition is here
static inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
                  ^
2 errors generated.
Traceback (most recent call last):
  File "./dbslower", line 113, in <module>
    bpf = BPF(text=program, usdt_contexts=usdts)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 293, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 
```

With the ```uapi``` change...

**Comment by jesperpedersen** [comment]
```dbslower postgres -p 1769``` works

**Comment by jesperpedersen** [comment]
Using latest master (2d82c8e) with Fedora 24 on Linux 4.10.10 I get
```
[root@localhost tools]# ./dbslower postgres -p 2848
Tracing database queries for pids 2848 slower than 1 ms...
TIME(s)        PID          MS QUERY
3.599168       2848   2003.210 
```
when doing
```
test=# SELECT 1 FROM pg_sleep(2);
```
in pid 2848. E.g. there is no query output.

I can send a pull request with my few changes (updated include, move of bpf variable and help text) if needed

**Comment by goldshtn** [comment]
Just to confirm, 2848 is the process id handling this particular client? Did you try tracing other Postgres processes? I recall when writing dbslower, that it wasn't always very clear which pid to trace 😞

**Comment by jesperpedersen** [comment]
Yes, as there were only one client attached to the instance. `dbslower` outputs the elapsed time, but never the query

**Comment by goldshtn** [comment]
That's odd. I just ran a query and got it in the output:

```
TIME(s)        PID          MS QUERY
7.110259       8186   1003.731 select 1 from pg_sleep(1);
```

What happens if you use `trace 'u::query__start' "%s", arg1' -p POSTGRESPID`? Does it show the query text?

**Comment by jesperpedersen** [comment]
Nope - if I have my `'`s correctly placed
```
[root@localhost tools]# ./trace 'u::query__start "%s", arg1' -p 31717
PID    TID    COMM         FUNC             -
31717  31717  postgres     query__start     
```

**Comment by goldshtn** [comment]
Well that's odd. How did you install postgres (I built from source)? I could try and reproduce this, or you could check in a debugger around the probe's location if the postgres version you have passes the string argument properly to the probe?

**Comment by jesperpedersen** [comment]
There is something general going on, since nothing gets passed
```
[root@localhost tools]# ./trace 'sys_execve "%s", arg1'
PID    TID    COMM         FUNC             -
1403   1403   bash         sys_execve       
```
e.g. no command here either. I'm investigating, since it shouldn't hijack this issue

**Comment by jesperpedersen** [comment]
Same thing applies for a single process with multiple attach on the same function, e.g.
```
u = USDT(pid=int(sys.argv[1]))
u.enable_probe_or_bail(probe="probe_name1", fn_name="myfunc")
u.enable_probe_or_bail(probe="probe_name2", fn_name="myfunc")
u.enable_probe_or_bail(probe="probe_name3", fn_name="myfunc")
...
```

**Comment by goldshtn** [comment]
@vmg 
Do you have any thoughts on a clean approach to handle this? Basically each `enable_probe` will be generating a set of readarg helpers with the function name embedded in the helper name, so if you call `enable_probe` multiple times with the same function handling all probes, you get multiple versions of the helpers defined with the same names. This happens when attaching to multiple processes or when attaching a single function to multiple probes in the same process. I'd like to find a surgical fix for this that doesn't have us changing the Python API ideally...

**Comment by yonghong-song** [comment]
On Fri, Jul 14, 2017 at 11:01 AM, Sasha Goldshtein
<notifications@github.com> wrote:
> @vmg
> Do you have any thoughts on a clean approach to handle this? Basically each
> enable_probe will be generating a set of readarg helpers with the function
> name embedded in the helper name, so if you call enable_probe multiple times
> with the same function handling all probes, you get multiple versions of the
> helpers defined with the same names. This happens when attaching to multiple
> processes or when attaching a single function to multiple probes in the same
> process. I'd like to find a surgical fix for this that doesn't have us
> changing the Python API ideally...
>

This is hard with static functions. Without bpf_usdt_readarg in static
functions,
you could encode both probe and func name in the helper function names based
on the input from:
    usdt.enable_probe("memory_mallopt", "probe")
the readarg helper could be:
    _bpf_readarg_memory_mallopt_probe_1(...)

An example with bpf_usdt_readarg in static functions:
static fn1(...) { bpf_usdt_readarg(1, ctx, &arg1); }
static fn2 (...) { bpf_usdt_readarg(1, ctx, &arg1); }
probe1() { ... fn2() ... }
probe2() { ... fn1() ... }

To do this properly in rewriter, you will need to traverse the AST twice.
First, you need to remember the callgraph and then you can try to
do the usdt_readarg transformation.

In current bcc infrastructure, we could use the TracePointFrontend
action to record call graph as well and BFrontend action can use the
call graph information to do the transformation.

One thing it won't work with this approach is:
static fn() { bpf_usdt_readarg() }
probe1() { ... fn() ... }
probe2() { ... fn() ... }

I would say that we could reject such a sharing of bpf_usdt_readarg
with two different probe functions. I do not know how practical it is.

Any comments?

**Comment by goldshtn** [comment]
It would be really nice to make it possible to share a static helper between two probe functions, because it's a fairly common scenario (e.g. probing MySQL and PostgreSQL query start and end probes -- they have identical signatures). There is always the workaround of generating multiple copies of the probe functions before compiling (which is what happens at the BPF program level anyway), but it's annoying, and will probably trip a lot of people going forward.

But the even more annoying scenario is where I want to attach the same probe function to the same probe, but in multiple processes, which is what this issue is originally about:

```python
usdt1 = USDT(pid=pid1)
usdt2 = USDT(pid=pid2)
usdt1.enable_probe("query__start", "probe")
usdt2.enable_probe("query__start", "probe")
bpf = BPF(text=text, usdt_contexts=[usdt1, usdt2])
```

This shouldn't cause any issues at all fundamentally, but the way bcc works right now, it generates the readarg helpers multiple times.

**Comment by yonghong-song** [comment]
Right, we can avoid generating duplicating functions after we prove pid1
and pid2 pointing to the same binary.

To solve different binary attaching to the same probe issue, pid may need
to be in generated code. Based on different pid, we can have different
codes (based on PC)
to read from registers.

Will do some prototype to start concrete discussion.
