### ISSUE TITLE
Failed to load BPF program trace_connect_v4_return: 

### ISSUE THREAD

**Issue by thnam91** [iovisor/bcc#1236]

**Comment by yonghong-song** [comment]
I tried latest net-next and did not find the issue. It is possible that 4.4.0 has some verifier limitation which is fixed later on. I did not check the kernel code, but you can try to use bpf_probe_read for 2 4-byte read instead of one 8-byte read. Better if you could try a later kernel.

**Comment by shehzadkhawar** [comment]
I just checked with 4.8.0-58-generic and it is working. I had the same problem with your version of the kernel. Now it is working with newer one.

**Comment by mukuntharajaa** [comment]
I am running LFS based on 4.4.104. Some of the tools works fine from tools/old. Some doesnt work. For example,

./biosnoop 
bpf: Failed to load program: Permission denied
0: (79) r1 = *(u64 *)(r1 +112)
1: (7b) *(u64 *)(r10 -8) = r1
2: (18) r1 = 0xffff880feb004700
4: (bf) r2 = r10
5: (07) r2 += -8
6: (85) call 1
7: (bf) r7 = r0
8: (15) if r0 == 0x0 goto pc+118
 R0=map_value(ks=8,vs=8) R7=map_value_or_null(ks=8,vs=8) R10=fp
9: (85) call 5
10: (bf) r6 = r0
11: (79) r9 = *(u64 *)(r7 +0)
R7 invalid mem access 'map_value_or_null'

HINT: The 'map_value_or_null' error can happen if you dereference a pointer value from a map lookup without first checking if that pointer is NULL.

Traceback (most recent call last):
  File "./biosnoop", line 102, in <module>
    fn_name="trace_req_completion")
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 519, in attach_kprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 349, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program trace_req_completion: Permission denied

Is it because of older kernel or am I missing something ?

**Comment by yonghong-song** [comment]
On Wed, Feb 7, 2018 at 11:01 PM, mukuntharajaa <notifications@github.com> wrote:
> I am running LFS based on 4.4.104. Some of the tools works fine from
> tools/old. Some doesnt work. For example,
>
> ./biosnoop
> bpf: Failed to load program: Permission denied
> 0: (79) r1 = *(u64 *)(r1 +112)
> 1: (7b) *(u64 *)(r10 -8) = r1
> 2: (18) r1 = 0xffff880feb004700
> 4: (bf) r2 = r10
> 5: (07) r2 += -8
> 6: (85) call 1
> 7: (bf) r7 = r0
> 8: (15) if r0 == 0x0 goto pc+118
> R0=map_value(ks=8,vs=8) R7=map_value_or_null(ks=8,vs=8) R10=fp
> 9: (85) call 5
> 10: (bf) r6 = r0
> 11: (79) r9 = *(u64 *)(r7 +0)
> R7 invalid mem access 'map_value_or_null'
>
> HINT: The 'map_value_or_null' error can happen if you dereference a pointer
> value from a map lookup without first checking if that pointer is NULL.

This mostly an old kernel issue. The newer kernel is able to handle
the above case,
i.e., right before insn #9, R7 will be map_value instead of map_value_or_null.
