### ISSUE TITLE
chdir(/lib/modules/4.8.3-x86_64-linode76/build): No such file or directory

### ISSUE THREAD

**Issue by kirantpatil** [iovisor/bcc#1238]
Hi,

On linode machine, I am having this issue.

I installed kernel headers but getting below error.

## fueb@localhost:/usr/share/bcc/tools$ ./opensnoop
chdir(/lib/modules/4.8.3-x86_64-linode76/build): No such file or directory
Traceback (most recent call last):
  File "./opensnoop", line 126, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 294, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 

Environment:
---

```
fueb@localhost:~$ uname -a
Linux localhost 4.8.3-x86_64-linode76 #1 SMP Thu Oct 20 19:05:39 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
fueb@localhost:~$ cat /etc/issue
Ubuntu 16.04.2 LTS \n \l
```

Edit: I referred this article, http://www.brendangregg.com/blog/2016-06-14/ubuntu-xenial-bcc-bpf.html

**Comment by kirantpatil** [comment]
Issue resolved by migrating to ubuntu default kernel which is 4.8.0-58-generic.
By following this guide, https://www.linode.com/docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel-with-kvm.
