### ISSUE TITLE
Why can't i use bpf_skb_store_bytes() in kprobe program?

### ISSUE THREAD

**Issue by JerryChenBupt** [iovisor/bcc#1245]
This is my first time to use `bpf_skb_store_bytes()`. I want to test it in a program attched to `dev_queue_xmit()` by kprobe.
```c
#include <uapi/linux/ptrace.h>
#include <uapi/linux/ip.h>
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wtautological-compare"
#include <linux/skbuff.h>
#pragma clang diagnostic pop

#define IPPROTO_TCP 6
#define IPPROTO_ICMP 1

#define IP_TOS_OFF offsetof(struct iphdr, tos)

int kprobe__dev_queue_xmit(struct pt_regs *ctx, struct sk_buff *skb)
{
        u16 protocol = bpf_ntohs(skb->protocol);
        u8 ip_p;
        u8 tos;
        if(protocol == ETH_P_IP)
        {
                struct iphdr *iph = (struct iphdr *)(skb->head + skb->network_header);
                bpf_probe_read(&ip_p, sizeof(ip_p), &(iph->protocol));
                bpf_probe_read(&tos, sizeof(tos), &(iph->tos));
                if(ip_p == IPPROTO_ICMP)
                {
                        bpf_trace_printk("ip_p: %u tos: %u\n", ip_p, tos);
                        bpf_skb_store_bytes(skb, IP_TOS_OFF, &tos, sizeof(tos), 0);
                }
        }
        return 0;
}
```
And i get this:
```
bpf: Invalid argument
0: (79) r6 = *(u64 *)(r1 +112)
1: (b7) r8 = 0
2: (6b) *(u16 *)(r10 -32) = r8
3: (bf) r3 = r6
4: (07) r3 += 192
5: (bf) r1 = r10
6: (07) r1 += -32
7: (b7) r2 = 2
8: (85) call 4
9: (69) r1 = *(u16 *)(r10 -32)
10: (55) if r1 != 0x8 goto pc+52
 R0=inv R1=inv48,min_value=8,max_value=8 R6=inv R8=imm0,min_value=0,max_value=0 R10=fp
11: (7b) *(u64 *)(r10 -32) = r8
12: (bf) r3 = r6
13: (07) r3 += 208
14: (bf) r1 = r10
15: (07) r1 += -32
16: (b7) r2 = 8
17: (85) call 4
18: (79) r7 = *(u64 *)(r10 -32)
19: (6b) *(u16 *)(r10 -32) = r8
20: (bf) r3 = r6
21: (07) r3 += 196
22: (bf) r1 = r10
23: (07) r1 += -32
24: (b7) r2 = 2
25: (85) call 4
26: (69) r1 = *(u16 *)(r10 -32)
27: (0f) r7 += r1
28: (bf) r1 = r10
29: (07) r1 += -1
30: (bf) r3 = r7
31: (07) r3 += 9
32: (b7) r2 = 1
33: (85) call 4
34: (07) r7 += 1
35: (bf) r1 = r10
36: (07) r1 += -2
37: (b7) r2 = 1
38: (bf) r3 = r7
39: (85) call 4
40: (71) r1 = *(u8 *)(r10 -1)
41: (55) if r1 != 0x1 goto pc+21
 R0=inv R1=inv56,min_value=1,max_value=1 R6=inv R7=inv R8=imm0,min_value=0,max_value=0 R10=fp
42: (b7) r1 = 10
43: (6b) *(u16 *)(r10 -16) = r1
44: (18) r1 = 0x736f7420
46: (7b) *(u64 *)(r10 -24) = r1
47: (18) r1 = 0x705f7069
49: (7b) *(u64 *)(r10 -32) = r1
50: (71) r4 = *(u8 *)(r10 -2)
51: (bf) r1 = r10
52: (07) r1 += -32
53: (b7) r2 = 18
54: (b7) r3 = 1
55: (85) call 6
56: (bf) r3 = r10
57: (07) r3 += -2
58: (bf) r1 = r6
59: (b7) r2 = 1
60: (b7) r4 = 1
61: (b7) r5 = 0
62: (85) call 9
unknown func 9
```
When i delete the line of `bpf_skb_store_bytes()`. It worked correctly. The output is:
```
Tracing... Hit Ctrl-C to end.
ip_p: 1 tos: 0
ip_p: 1 tos: 0
ip_p: 1 tos: 0
ip_p: 1 tos: 0
```
**Do i miss something when using `bpf_skb_store_bytes()`? Or it can't be used in some situation?**

**Comment by yonghong-song** [comment]
bpf_skb_store_bytes can only be used in a few networking related prog types, notably BPF_PROG_TYPE_SCHED_CLS, BPF_PROG_TYPE_SCHED_ACT and BPF_PROG_TYPE_LWT_XMIT.

**Comment by goldshtn** [comment]
I believe this is resolved; closing now, please feel free to reopen if necessary.

**Comment by JerryChenBupt** [comment]
I test the same code using `SCHED_CLS` . But it failed too.
My code:
```c
#include <uapi/linux/if_ether.h>
#include <uapi/linux/in.h>
#include <uapi/linux/ip.h>
#include <uapi/linux/pkt_cls.h>
#include <uapi/linux/bpf.h>

#define IP_CSUM_OFF (ETH_HLEN + offsetof(struct iphdr, check))
#define TOS_OFF (ETH_HLEN + offsetof(struct iphdr, tos))

int hello(struct __sk_buff *skb) {
        u16 eth_protocol = bpf_ntohl(skb->protocol)>>16;
        
        void *data = (void *)(long)skb->data;
        void *data_end = (void *)(long)skb->data_end;
        struct ethhdr *eth = data;
        struct iphdr *iph = data + sizeof(*eth);
        
        u8 ip_p;
        u8 ttl;
        u8 old_tos;
        u8 new_tos = 0x01;

        if (data + sizeof(*eth) + sizeof(*iph) > data_end)
                return TC_ACT_OK;

        //bpf_trace_printk("eth protocol = %x\\n", ntohs(eth->h_proto));

        if (eth->h_proto == htons(ETH_P_IP) &&
            iph->protocol == IPPROTO_ICMP)
        {
                bpf_trace_printk("protocol = %d ttl = %d tos = %x\\n", iph->protocol, iph->ttl, iph->tos);

                bpf_skb_load_bytes(skb, TOS_OFF, &old_tos, 1);
                bpf_l3_csum_replace(skb, IP_CSUM_OFF, bpf_htons(old_tos), bpf_htons(new_tos), 2);
                bpf_skb_store_bytes(skb, TOS_OFF, &new_tos, sizeof(new_tos), 0);

                bpf_trace_printk("tos = %x\\n", iph->tos);
        }

        return TC_ACT_OK;
}
```
```python
#!/usr/bin/python

from bcc import BPF
from pyroute2 import IPRoute

ipr = IPRoute()
text = """..."""
try:
    b = BPF(text=text, debug=0)
    fn = b.load_func("hello", BPF.SCHED_CLS)

    idx = ipr.link_lookup(ifname="eth0")[0]

    ipr.tc("add", "ingress", idx, "ffff:")
    ipr.tc("add-filter", "bpf", idx, ":1", fd=fn.fd,
           name=fn.name, parent="ffff:", action="ok", classid=1)
    # header
    print("Tracing... Hit Ctrl-C to end.")
    while 1:
        try:
            (task, pid, cpu, flags, ts, msg) = b.trace_fields()
        except KeyboardInterrupt:
            break
        print("%s" % (msg))

except KeyboardInterrupt:
    print("get int")

finally:
    if "idx" in locals():
        ipr.tc("del", "ingress", idx, "ffff:")
print("BPF tc functionality - SCHED_CLS: OK")
```

**The output:**
```
HINT: The invalid mem access 'inv' error can happen if you try to dereference memory without first using bpf_probe_read() to copy it to the BPF stack. Sometimes the bpf_probe_read is automatic by the bcc rewriter, other times you'll need to be explicit.

Traceback (most recent call last):
  File "./cyj.py", line 54, in <module>
    fn = b.load_func("hello", BPF.SCHED_CLS)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 345, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program hello: Permission denied
```

**Comment by JerryChenBupt** [comment]
I'm sorry that a new problem arise now. Can i reopen this issue? @goldshtn

**Comment by JerryChenBupt** [comment]
Well, I found that this error is because the the use of `bpf_trace_printk("tos = %x\\n", iph->tos)`. It works fine now!
