### ISSUE TITLE
tcp tools fail on CentOS 7 4.13.8

### ISSUE THREAD

**Issue by alexandrnikitin** [iovisor/bcc#1407]
```
[root@PRCAPISV0003L01 bcc]# tcptop
In file included from /virtual/main.c:3:
In file included from /lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/net/sock.h:58:
/lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/linux/memcontrol.h:580:31: warning: implicit conversion from enumeration type 'enum node_stat_item' to different enumeration type 'enum memcg_stat_item' [-Wenum-conversion]
        __mod_memcg_state(pn->memcg, idx, val);
        ~~~~~~~~~~~~~~~~~            ^~~
/lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/linux/memcontrol.h:593:29: warning: implicit conversion from enumeration type 'enum node_stat_item' to different enumeration type 'enum memcg_stat_item' [-Wenum-conversion]
        mod_memcg_state(pn->memcg, idx, val);
        ~~~~~~~~~~~~~~~            ^~~
/lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/linux/memcontrol.h:605:38: warning: implicit conversion from enumeration type 'enum node_stat_item' to different enumeration type 'enum memcg_stat_item' [-Wenum-conversion]
        __mod_memcg_state(page->mem_cgroup, idx, val);
        ~~~~~~~~~~~~~~~~~                   ^~~
/lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/linux/memcontrol.h:618:36: warning: implicit conversion from enumeration type 'enum node_stat_item' to different enumeration type 'enum memcg_stat_item' [-Wenum-conversion]
        mod_memcg_state(page->mem_cgroup, idx, val);
        ~~~~~~~~~~~~~~~                   ^~~
/lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/linux/memcontrol.h:639:40: warning: implicit conversion from enumeration type 'enum memcg_stat_item' to different enumeration type 'enum vm_event_item' [-Wenum-conversion]
                count_memcg_events(page->mem_cgroup, idx, 1);
                ~~~~~~~~~~~~~~~~~~                   ^~~
In file included from /virtual/main.c:3:
In file included from /lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/net/sock.h:64:
/lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/linux/filter.h:466:11: error: use of undeclared identifier 'BPF_TAG_SIZE'
        u8                      tag[BPF_TAG_SIZE];
                                    ^
5 warnings and 1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/tcptop", line 197, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 284, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module
```
```
[root@PRCAPISV0003L01 bcc]# tcpretrans
In file included from /virtual/main.c:3:
In file included from /lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/net/sock.h:58:
/lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/linux/memcontrol.h:580:31: warning: implicit conversion from enumeration type 'enum node_stat_item' to different enumeration type 'enum memcg_stat_item' [-Wenum-conversion]
        __mod_memcg_state(pn->memcg, idx, val);
        ~~~~~~~~~~~~~~~~~            ^~~
/lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/linux/memcontrol.h:593:29: warning: implicit conversion from enumeration type 'enum node_stat_item' to different enumeration type 'enum memcg_stat_item' [-Wenum-conversion]
        mod_memcg_state(pn->memcg, idx, val);
        ~~~~~~~~~~~~~~~            ^~~
/lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/linux/memcontrol.h:605:38: warning: implicit conversion from enumeration type 'enum node_stat_item' to different enumeration type 'enum memcg_stat_item' [-Wenum-conversion]
        __mod_memcg_state(page->mem_cgroup, idx, val);
        ~~~~~~~~~~~~~~~~~                   ^~~
/lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/linux/memcontrol.h:618:36: warning: implicit conversion from enumeration type 'enum node_stat_item' to different enumeration type 'enum memcg_stat_item' [-Wenum-conversion]
        mod_memcg_state(page->mem_cgroup, idx, val);
        ~~~~~~~~~~~~~~~                   ^~~
/lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/linux/memcontrol.h:639:40: warning: implicit conversion from enumeration type 'enum memcg_stat_item' to different enumeration type 'enum vm_event_item' [-Wenum-conversion]
                count_memcg_events(page->mem_cgroup, idx, 1);
                ~~~~~~~~~~~~~~~~~~                   ^~~
In file included from /virtual/main.c:3:
In file included from /lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/net/sock.h:64:
/lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/linux/filter.h:466:11: error: use of undeclared identifier 'BPF_TAG_SIZE'
        u8                      tag[BPF_TAG_SIZE];
                                    ^
5 warnings and 1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/tcpretrans", line 196, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 284, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module
```

```
[root@PRCAPISV0003L01 bcc]# uname -r
4.13.8-1.el7.elrepo.x86_64
```

**Comment by yonghong-song** [comment]
> /lib/modules/4.13.8-1.el7.elrepo.x86_64/build/include/linux/filter.h:466:11: error: use of undeclared identifier 'BPF_TAG_SIZE'
        u8                      tag[BPF_TAG_SIZE];

This should have been fixed with the latest bcc.

**Comment by alexandrnikitin** [comment]
@yonghong-song I've just checked the recent 0.4.0 version and can confirm that it works. Thank you!
