### ISSUE TITLE
In funcslower.py and other similar tools, functions called from same thread are not traced correctly

### ISSUE THREAD

**Issue by ggaurav10** [iovisor/bcc#1420]
In tools like:
https://github.com/iovisor/bcc/blob/master/tools/funcslower.py

If the function list provided has functions which will be called by the same thread such as:
`#./funcslower.py vfs_read __vfs_read`

then the latencies calculated will be wrong, because the tool is only filtering based on the tid/pid and not on the function name/id.
I made below changes to correct this. Basically after hash lookup for tid/pid in trace_return, proceed only if the function name/id also matches. 

```diff --git a/tools/funcslower.py b/tools/funcslower.py
index b8ef230..cc74a4b 100755
--- a/tools/funcslower.py
+++ b/tools/funcslower.py
@@ -115,13 +115,13 @@ static int trace_entry(struct pt_regs *ctx, int id)
     return 0;
 }
 
-int trace_return(struct pt_regs *ctx)
+int trace_return(struct pt_regs *ctx, int id)
 {
     struct entry_t *entryp;
     u64 tgid_pid = bpf_get_current_pid_tgid();
 
     entryp = entryinfo.lookup(&tgid_pid);
-    if (entryp == 0) {
+    if (entryp == 0 || entryp->id != id) {
         return 0;
     }
 
@@ -160,7 +160,10 @@ for i in range(len(args.functions)):
 int trace_%d(struct pt_regs *ctx) {
     return trace_entry(ctx, %d);
 }
-""" % (i, i)
+int rtrace_%d(struct pt_regs *ctx) {
+    return trace_return(ctx, %d);
+}
+""" % (i, i, i, i)
 
 if args.verbose:
     print(bpf_text)
@@ -171,10 +174,10 @@ for i, function in enumerate(args.functions):
     if ":" in function:
         library, func = function.split(":")
         b.attach_uprobe(name=library, sym=func, fn_name="trace_%d" % i)
-        b.attach_uretprobe(name=library, sym=func, fn_name="trace_return")
+        b.attach_uretprobe(name=library, sym=func, fn_name="rtrace_%d" % i)
     else:
         b.attach_kprobe(event=function, fn_name="trace_%d" % i)
-        b.attach_kretprobe(event=function, fn_name="trace_return")
+        b.attach_kretprobe(event=function, fn_name="rtrace_%d" % i)
 
 TASK_COMM_LEN = 16  # linux/sched.h
 
```

However, I am getting below error when I run: 

```
# ./funcslower.py __vfs_read vfs_write vfs_read
/virtual/main.c:93:30: error: too many arguments to function call, expected single argument 'ctx', have 2 arguments
    return trace_return(ctx, 0);
           ~~~~~~~~~~~~      ^
/virtual/main.c:55:1: note: 'trace_return' declared here
__attribute__((section(".bpf.fn.trace_return")))
^
/virtual/main.c:102:30: error: too many arguments to function call, expected single argument 'ctx', have 2 arguments
    return trace_return(ctx, 1);
           ~~~~~~~~~~~~      ^
/virtual/main.c:55:1: note: 'trace_return' declared here
__attribute__((section(".bpf.fn.trace_return")))
^
/virtual/main.c:111:30: error: too many arguments to function call, expected single argument 'ctx', have 2 arguments
    return trace_return(ctx, 2);
           ~~~~~~~~~~~~      ^
/virtual/main.c:55:1: note: 'trace_return' declared here
__attribute__((section(".bpf.fn.trace_return")))
^
3 errors generated.
Traceback (most recent call last):
  File "./funcslower.py", line 171, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 197, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 
```

I need some help in understanding this behaviour, or am I missing something here.

Thanks.

**Comment by pchaigno** [comment]
I think you need to make `trace_return` static. All functions not attached to [uk]probes must be static (and will be inlined).

**Comment by ggaurav10** [comment]
much thanks @pchaigno . That worked :)
