### ISSUE TITLE
f26 buildbot fails tests, 'arguments to BPF program definition must be named'

### ISSUE THREAD

**Issue by drzaeus77** [iovisor/bcc#1429]
Just went through and created a buildbot for fedora 26. The compile went through without much trouble but many tests fail with the below error, which comes from kernel headers. This will need to be fixed before the f26 buildbot can be enabled.

```
test 10
      Start 10: py_test_trace2

10: Test command: /home/fedora/jenkins/workspace/bcc-nightly-test/label/fc26/build/tests/wrapper.sh "py_trace2" "sudo" "/home/fedora/jenkins/workspace/bcc-nightly-test/label/fc26/tests/python/test_trace2.py"
10: Test timeout computed to be: 9.99988e+06
10: In file included from /virtual/main.c:2:
10: In file included from /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/ptrace.h:5:
10: In file included from /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/sched.h:13:
10: In file included from /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/pid.h:4:
10: In file included from /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/rculist.h:10:
10: In file included from /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/rcupdate.h:39:
10: In file included from /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/irqflags.h:15:
10: In file included from /lib/modules/4.13.9-200.fc26.x86_64/build/arch/x86/include/asm/irqflags.h:64:
10: In file included from /lib/modules/4.13.9-200.fc26.x86_64/build/arch/x86/include/asm/paravirt.h:15:
10: In file included from /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/cpumask.h:11:
10: In file included from /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/bitmap.h:8:
10: /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/string.h:21:27: error: arguments to BPF program definition must be named
10: extern char * strcpy(char *,const char *);
10:                           ^
10: /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/string.h:24:28: error: arguments to BPF program definition must be named
10: extern char * strncpy(char *,const char *, __kernel_size_t);
10:                            ^
10: /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/string.h:27:21: error: arguments to BPF program definition must be named
10: size_t strlcpy(char *, const char *, size_t);
10:                     ^
10: /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/string.h:33:27: error: arguments to BPF program definition must be named
10: extern char * strcat(char *, const char *);
10:                           ^
10: /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/string.h:36:28: error: arguments to BPF program definition must be named
10: extern char * strncat(char *, const char *, __kernel_size_t);
10:                            ^
10: /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/string.h:81:42: error: arguments to BPF program definition must be named
10: extern __kernel_size_t strlen(const char *);
10:                                          ^
10: /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/string.h:84:43: error: arguments to BPF program definition must be named
10: extern __kernel_size_t strnlen(const char *,__kernel_size_t);
10:                                           ^
10: /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/string.h:109:28: error: arguments to BPF program definition must be named
10: extern void * memscan(void *,int,__kernel_size_t);
10:                            ^
10: /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/string.h:112:30: error: arguments to BPF program definition must be named
10: extern int memcmp(const void *,const void *,__kernel_size_t);
10:                              ^
10: /lib/modules/4.13.9-200.fc26.x86_64/build/include/linux/string.h:115:33: error: arguments to BPF program definition must be named
10: extern void * memchr(const void *,int,__kernel_size_t);
10:                                 ^
10: 10 errors generated.
10: E
10: ======================================================================
10: ERROR: test_sched1 (__main__.TestTracingEvent)
10: ----------------------------------------------------------------------
10: Traceback (most recent call last):
10:   File "/home/fedora/jenkins/workspace/bcc-nightly-test/label/fc26/tests/python/test_trace2.py", line 27, in setUp
10:     b = BPF(text=text, debug=0)
10:   File "/home/fedora/jenkins/workspace/bcc-nightly-test/label/fc26/src/python/bcc/__init__.py", line 296, in __init__
10:     raise Exception("Failed to compile BPF module %s" % src_file)
10: Exception: Failed to compile BPF module 
10: 
10: ----------------------------------------------------------------------
10: Ran 1 test in 2.542s
10: 
10: FAILED (errors=1)
10: Failed
10/35 Test #10: py_test_trace2 ...................***Failed    2.61 sec
```

**Comment by yonghong-song** [comment]
Yes, I see this as well a while back with exactly the same signature plus two more:
   . verifier may complain invalid LD_imm insn, and
   . clang rewriter fails due to try to write with a "macro" for packet pointer, but actually it is not.

I debugged this for a couple of days and eventually adding some fprintf in some clang function makes the problem going away. After that, removing all these fprintf's, rebuild llvm/clang, and the tests start to pass.

Not exactly sure what is the problem.

**Comment by drzaeus77** [comment]
That won't really work here :( The clang/llvm libraries are coming from fedora repos. I'm a little bit confused too.

**Comment by chaoys** [comment]
I saw the problem too in ubuntu 17.10. My llvm-4.0 is from ubuntu repos.

**Comment by frioux** [comment]
This is happening on my 17.10 laptop, with llvm 3.8.  Here's an example:
```
$ sudo ./trace.py sys_execve "%s", arg1
In file included from /virtual/main.c:2:
In file included from include/linux/ptrace.h:5:
In file included from include/linux/sched.h:13:
In file included from include/linux/pid.h:4:
In file included from include/linux/rculist.h:10:
In file included from include/linux/rcupdate.h:39:
In file included from include/linux/irqflags.h:15:
In file included from ./arch/x86/include/asm/irqflags.h:64:
In file included from ./arch/x86/include/asm/paravirt.h:15:
In file included from include/linux/cpumask.h:11:
In file included from include/linux/bitmap.h:8:
include/linux/string.h:21:27: error: arguments to BPF program definition must be named
extern char * strcpy(char *,const char *);
                          ^
include/linux/string.h:24:28: error: arguments to BPF program definition must be named
extern char * strncpy(char *,const char *, __kernel_size_t);
                           ^
include/linux/string.h:27:21: error: arguments to BPF program definition must be named
size_t strlcpy(char *, const char *, size_t);
                    ^
include/linux/string.h:33:27: error: arguments to BPF program definition must be named
extern char * strcat(char *, const char *);
                          ^
include/linux/string.h:36:28: error: arguments to BPF program definition must be named
extern char * strncat(char *, const char *, __kernel_size_t);
                           ^
include/linux/string.h:81:42: error: arguments to BPF program definition must be named
extern __kernel_size_t strlen(const char *);
                                         ^
include/linux/string.h:84:43: error: arguments to BPF program definition must be named
extern __kernel_size_t strnlen(const char *,__kernel_size_t);
                                          ^
include/linux/string.h:109:28: error: arguments to BPF program definition must be named
extern void * memscan(void *,int,__kernel_size_t);
                           ^
include/linux/string.h:112:30: error: arguments to BPF program definition must be named
extern int memcmp(const void *,const void *,__kernel_size_t);
                             ^
include/linux/string.h:115:33: error: arguments to BPF program definition must be named
extern void * memchr(const void *,int,__kernel_size_t);
                                ^
10 errors generated.
Failed to compile BPF module 
```

**Comment by drzaeus77** [comment]
Seems the problem is spreading. I haven't seen the issue on any llvm 5.0+ based machine (i.e. my local setup). Wondering aloud here...Is it llvm that changed to expose this or the kernel headers? In either case, why the heck is a declaration like `extern char * strcpy(char *,const char *);` passing the `D->hasBody()` check in `BTypeVisitor::VisitFunctionDecl`?

**Comment by frioux** [comment]
btw I upgraded to llvm 5.0 and still got the error.  I recompiled bcc etc.

**Comment by yonghong-song** [comment]
I will have a patch in a few minutes.

**Comment by yonghong-song** [comment]
Just submitted a pull request. Please take a look and test.
