### ISSUE TITLE
ext4slower: UnicodeDecodeError in python3 with Cyrillic alphabet

### ISSUE THREAD

**Issue by r4f4** [iovisor/bcc#1459]
As reported in the Fedora bugzilla [1]:
Run /usr/share/bcc/tools/ext4slower 1 in gnome terminal, open nautilus. It seems to be related with russian letters in some file names in home dir.

Version-Release number of selected component:
bcc-tools-0.4.0-1.fc27

Additional info:
reporter:       libreport-2.9.3
cmdline:        /usr/bin/python3 /usr/share/bcc/tools/ext4slower 1
crash_function: print_event
exception_type: UnicodeDecodeError
executable:     /usr/share/bcc/tools/ext4slower
kernel:         4.13.15-300.fc27.x86_64
runlevel:       N 5
type:           Python3
uid:            0

Truncated backtrace:
ext4slower:313:print_event:UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 31: unexpected end of data

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "/usr/share/bcc/tools/ext4slower", line 313, in print_event
    float(event.delta_us) / 1000, event.file.decode()))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 31: unexpected end of data

Local variables in innermost frame:
type: 'R'
event: <__main__.Data object at 0x7f11a50f2598>
size: 100
data: 139713759059340
cpu: 3

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1516678

**Comment by jeromemarchand** [comment]
Several other tools have the same issue when encountering unexpected character. While maybe not a proper solution, using a more permissive error handler in the decode method ('ignore' or 'replace') than the default 'strict' would be a simple workaround.

**Comment by yonghong-song** [comment]
Do you mind to submit a pull request for this?

**Comment by jeromemarchand** [comment]
I was hoping that someone more proficient in python would come up with a better solution with that all python2/3 string encoding trouble.  But looking at the several related issues still open, for quite a while for some of them, it seems that not much progress has been made so far. I'll look into it: I don't want to just do a blind search and replace script.

**Comment by yonghong-song** [comment]
Thanks!

**Comment by jeromemarchand** [comment]
I got side tracked, but I finally submitted a pull request (#2004)
