### ISSUE TITLE
bcc tools's nfs* do not work

### ISSUE THREAD

**Issue by kenshin33** [iovisor/bcc#1509]
host ~ #/usr/share/bcc/tools/nfsslower 
    Traceback (most recent call last):
    File "/usr/share/bcc/tools/nfsslower", line 294, in <module>
    b.attach_kprobe(event="nfs4_file_open", fn_name="trace_file_open_entry")
    File "/usr/lib64/python3.5/site-packages/bcc/__init__.py", line 526, in attach_kprobe
    raise Exception("Failed to attach BPF to kprobe")
    Exception: Failed to attach BPF to kprobe

the above is from my gentoo system but I got the same from a debian stretch and a debian jessie one!
bcc v0.5.0

**Comment by kenshin33** [comment]
the problem seams taht the modules nfsv4.ko wasn't loaded  for some reason!
