### ISSUE TITLE
Opensnoop issue on Fedora 27 hosts

### ISSUE THREAD

**Issue by Matty9191** [iovisor/bcc#1572]
Hey Brendan,

I was doing some Kubernetes investigative work this morning on a Fedora 27 host and bumped into an issue. When i run execsnoop with Python 3.6 the program bombs with the stack trace listed below [1]:

$ ./execsnoop -n nsenter
PCOMM            PID    PPID   RET ARGS
Traceback (most recent call last):
....

Based on what I read here:

https://github.com/iovisor/bcc/blob/master/INSTALL.md

It looks like the tools require python2 and python2-bcc (I may be wrong on this though). Newer Fedora releases no longer ship with python2-bcc. python3-bcc is the only package available. I google'ed the following message:

TypeError: cannot use a string pattern on a bytes-like object

And the flask documentation mentions that the default argument type for add_argument is a unicode string for Python 2 and a str class for Python 3:

http://flask-restful.readthedocs.io/en/0.3.5/reqparse.html

"The default argument type is a unicode string. This will be str in python3 and unicode in python2."

If I'm reading the re documentation correctly re.search in Python 3 takes a unicode string or a byte string as its first argument. Passing a class str seems to make it angry. As a quick test I changed line 182 to call encode('utf-8)':

if args.name and not re.search(args.name.encode('utf-8'), event.comm):

This appears to have fixed my issue:

$ execsnoop -n nsenter
PCOMM            PID    PPID   RET ARGS
nsenter          25898  976      0 /usr/bin/nsenter -t 4947 -n /usr/bin/socat - TCP4:localhost:8080

I'm sure you are already aware of this and it looks like I may be trying to run the tools on an unsupported version of Python. On the off change that you haven't seen this I thought I would send in an issue. Thanks again for the amazing tools! They make debugging a whole lot easier!

Have the best day of your life!
- Ryan

[1] stack trace
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in <lambda>
    fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
  File "./execsnoop", line 182, in print_event
    if args.name and not re.search(args.name, event.comm):
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by yonghong-song** [comment]
Maybe use `encode('ascii')` also work? Do you want to send a pull request?

**Comment by Matty9191** [comment]
encode('ascii') works as well. I'll be glad to send in a PR if you think this is the right way to solve this.

**Comment by yonghong-song** [comment]
Yes, please send a PR with `encode('ascii')` fix. Thanks!

**Comment by brendangregg** [comment]
Why do we suddenly need this? Do all tools now need an explicit encode
ascii?? That would be pretty awful. Matty, is your LANG environment
variable set to something?

Brendan

**Comment by yonghong-song** [comment]
@brendangregg I can reproduce this issue on my fc27 as well. In fact, I tried to run `opensnoop` as well. I has the same issue.
```
$ sudo ./opensnoop.py -n 'ls'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in raw_cb_
    callback(cpu, data, size)
  File "./opensnoop.py", line 179, in print_event
    if args.name and args.name not in event.comm:
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in raw_cb_
    callback(cpu, data, size)
  File "./opensnoop.py", line 179, in print_event
    if args.name and args.name not in event.comm:
TypeError: a bytes-like object is required, not 'str'
```

I have this LANG environment variable, which should be the default one:
```
[yhs@localhost tools]$ env | grep LANG
LANG=en_US.UTF-8
```

Did error have anything related to LANG, or python3 compatibility? Maybe this is just a python3 compatibility issue and get undetected due to inadequate testing?

**Comment by Matty9191** [comment]
Hey Brendan,

LANG is set to en_US.UTF-8 on my laptop:

[matty@dingo][RC:0][~/projects/bcc-debugging]$ echo $LANG
en_US.UTF-8

I played around with a couple of other LANGs and execsnoop still exits with the stack trace listed above. Just out of curiosity is Python 3 officially supported? I couldn't find an answer to that in the documentation

Hope both of you are having an awesome day!
- Ryan

**Comment by yonghong-song** [comment]
File issue #1579 to specifically track this byte/str encoding issue.
