### ISSUE TITLE
python2/3 compatibility issue in tools regarding byte/str encoding

### ISSUE THREAD

**Issue by yonghong-song** [iovisor/bcc#1579]
The original discussion is in issue #1572. File this issue to track this issue separately as we may need a better overall solution.

In issue #1572, opensnoop/execsnoop is discovered to have python3 failure due to byte encoding. The failure signature looks like:
```
$ sudo ./opensnoop.py -n 'ls'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/bcc/table.py", line 526, in raw_cb_
    callback(cpu, data, size)
  File "./opensnoop.py", line 179, in print_event
    if args.name and args.name not in event.comm:
TypeError: a bytes-like object is required, not 'str'
```

Adding `.encoding('ascii')` everywhere is kind of ugly. Do we have better way to do this?

**Comment by palmtenor** [comment]
Some discussion about this topic in #1073

**Comment by brendangregg** [comment]
I just hit this too: the bcc-tools package on Amazon Linux hits this, eg:

```
/usr/share/bcc/tools/funccount 't:block:*'
cannot use a bytes pattern on a string-like object
```

**Comment by palao** [comment]
Is there a solution for this problem?

**Comment by yonghong-song** [comment]
@palao This is not fixed yet. Could you help submit a pull request to fix this problem?

**Comment by palao** [comment]
yonghong-song,
I'd be glad to do that, but my story is: I was curious about this eBPF thing and started to read a post written by Gregg. I wanted to test the software to simply see what it does... but the first thing I notice is that it does not even work.

Without even knowing what bcc is for, I doubt I can fix a problem (although I'm a Python programmer and I could be interested in this...).

Is there no one working to fix this? How can I use the tool to learn about it before trying to fix the problem?

**Comment by lcp** [comment]
I also encountered the problem with funccount. This https://github.com/iovisor/bcc/pull/2318/commits/d2a4626dacc33d3dca9a7e6ea2ef4bdaa6ef3c74 works for me.

**Comment by palao** [comment]
Ok, so I finally submitted a pull request [#2319](https://github.com/iovisor/bcc/pull/2319). It works for me, but no idea if it works in other environments. Need proper testing. 
I don't like changing a code without tests. I'd like to know more about the development strategy of bcc...
I know there are some tests, but they are incomplete. For instance, is there any test for the PerfEventArray class in table.py?

**Comment by vahid83** [comment]
@brendangregg what kernel and bcc-tools version did you use for BPF Performance Tools? It apparently worked for you, back then.
