### ISSUE TITLE
support u32's and others in perf_submit()

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#1642]
Many programs use u64's instead of u32's in the perf data struct because the u32s weren't working. And still aren't? Here is a test program (from bashreadline):

```Python
#!/usr/bin/python
# [...]

from __future__ import print_function
from bcc import BPF
from time import strftime
import ctypes as ct

# load BPF program
bpf_text = """
#include <uapi/linux/ptrace.h>

struct str_t {
    u32 pid;
    char str[80];
};

BPF_PERF_OUTPUT(events);

int printret(struct pt_regs *ctx) {
    struct str_t data  = {};
    u32 pid;
    if (!PT_REGS_RC(ctx))
        return 0;
    pid = bpf_get_current_pid_tgid();
    data.pid = pid;
    bpf_probe_read(&data.str, sizeof(data.str), (void *)PT_REGS_RC(ctx));
    events.perf_submit(ctx,&data,sizeof(data));

    return 0;
};
"""
STR_DATA = 80

class Data(ct.Structure):
    _fields_ = [
        ("pid", ct.c_ulong),
        ("str", ct.c_char * STR_DATA)
    ]

b = BPF(text=bpf_text)
b.attach_uretprobe(name="/bin/bash", sym="readline", fn_name="printret")

# header
print("%-9s %-6s %s" % ("TIME", "PID", "COMMAND"))

def print_event(cpu, data, size):
    event = ct.cast(data, ct.POINTER(Data)).contents
    print("%-9s %-6d %s" % (strftime("%H:%M:%S"), event.pid,
                            event.str.decode()))

b["events"].open_perf_buffer(print_event)
while 1:
    b.perf_buffer_poll()
```

I've changed pid in the struct to u32, instead of u64, and it doesn't work:

```
# ./bashreadline.py
TIME      PID    COMMAND
22:06:29  3251725838655177905 l
22:06:34  8027775621230773425  I am messed up
22:06:54  8027775621230773425  this pid one sick pup
```

**Comment by brendangregg** [comment]
Adding another u32 to make it u64 aligned doesn't fix it either...

```Python
#!/usr/bin/python
# [...]

from __future__ import print_function
from bcc import BPF
from time import strftime
import ctypes as ct

# load BPF program
bpf_text = """
#include <uapi/linux/ptrace.h>

struct str_t {
    u32 pid;
    u32 foo;
    char str[80];
};

BPF_PERF_OUTPUT(events);

int printret(struct pt_regs *ctx) {
    struct str_t data  = {};
    u32 pid;
    if (!PT_REGS_RC(ctx))
        return 0;
    pid = bpf_get_current_pid_tgid();
    data.pid = pid;
    data.foo = 42;
    bpf_probe_read(&data.str, sizeof(data.str), (void *)PT_REGS_RC(ctx));
    events.perf_submit(ctx,&data,sizeof(data));

    return 0;
};
"""
STR_DATA = 80

class Data(ct.Structure):
    _fields_ = [
        ("pid", ct.c_ulong),
        ("foo", ct.c_ulong),
        ("str", ct.c_char * STR_DATA)
    ]

b = BPF(text=bpf_text)
b.attach_uretprobe(name="/bin/bash", sym="readline", fn_name="printret")

# header
print("%-9s %-6s %s" % ("TIME", "PID", "COMMAND"))

def print_event(cpu, data, size):
    event = ct.cast(data, ct.POINTER(Data)).contents
    print("%-9s %-6d %s" % (strftime("%H:%M:%S"), event.pid,
                            event.str.decode()))

b["events"].open_perf_buffer(print_event)
while 1:
    b.perf_buffer_poll()
```

```
TIME      PID    COMMAND
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/bcc/table.py", line 526, in raw_cb_
    callback(cpu, data, size)
  File "./bashreadline.py", line 63, in print_event
    event.str.decode()))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf7 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/bcc/table.py", line 526, in raw_cb_
    callback(cpu, data, size)
  File "./bashreadline.py", line 63, in print_event
    event.str.decode()))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf7 in position 0: ordinal not in range(128)
```

**Comment by brendangregg** [comment]
Oh, grumble, so if I change this:

```
class Data(ct.Structure):
    _fields_ = [
        ("pid", ct.c_ulong),
        ("str", ct.c_char * STR_DATA)
    ]
```

to this:

```
class Data(ct.Structure):
    _fields_ = [
        ("pid", ct.c_int),
        ("str", ct.c_char * STR_DATA)
    ]
```

It works. So c_ulong is not u32? I'm guessing it's getting change to a u64.
