### ISSUE TITLE
test py_test_tools_memleak failed with python3

### ISSUE THREAD

**Issue by yonghong-song** [iovisor/bcc#1685]
The test py_test_tools_memleak failed with python3. python2 works fine as expected.
With your bcc installation with python3, the failure can be easily reproduced with
```
[yhs@localhost python]$ pwd
/home/yhs/work/bcc/tests/python
[yhs@localhost python]$ sudo ./test_tools_memleak.py
E/usr/lib64/python3.6/subprocess.py:766: ResourceWarning: subprocess 14520 is still running
  ResourceWarning, source=self)
E/usr/lib64/python3.6/subprocess.py:766: ResourceWarning: subprocess 14523 is still running
  ResourceWarning, source=self)
/usr/lib64/python3.6/subprocess.py:204: ResourceWarning: unclosed file <_io.BufferedWriter name=4>
  for inst in _active[:]:
/usr/lib64/python3.6/subprocess.py:204: ResourceWarning: unclosed file <_io.BufferedReader name=5>
  for inst in _active[:]:
...
======================================================================
ERROR: test_aligned_alloc (__main__.MemleakToolTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_tools_memleak.py", line 117, in test_aligned_alloc
    self.assertEqual(cfg.leaking_amount, self.run_leaker("aligned_alloc"))
  File "./test_tools_memleak.py", line 71, in run_leaker
    if "with outstanding allocations" in line:
TypeError: a bytes-like object is required, not 'str'
...
```

After fixing the above byte-object vs. str errors, the failure seems due to
the following piece of code
```
        # At this point, memleak.py have already launched application and set
        # probes. Sending command to the leaking application to make its
        # allocations.
        out = p.communicate(input="\n")[0]
```
In python2, you will get `out` as
```
leaking via valloc, 0x604000
[18:12:20] Top 1 stacks with outstanding allocations:
        30000 bytes in 1 allocations from stack
                [unknown]
                [unknown]
                [unknown]
```
But in python3, you only get
```
leaking via valloc, 0x604000
```

As a result, python3 failed the test. Is this because subprocess communication change or
what kind of things could trigger such a change. In python3 environment, you will see these
```
[18:12:20] Top 1 stacks with outstanding allocations:
        30000 bytes in 1 allocations from stack
                [unknown]
                [unknown]
                [unknown]
```
if you run the standalone process which is associated with subprocess above.

Maybe some python expert could help debug this a little bit more? Thanks!

**Comment by yonghong-song** [comment]
I have found a workaround for python3 as below:
```
diff --git a/tests/python/test_tools_memleak.py b/tests/python/test_tools_memleak.py
index acdc6f6..d8afe61 100755
--- a/tests/python/test_tools_memleak.py
+++ b/tests/python/test_tools_memleak.py
@@ -4,7 +4,7 @@ from unittest import main, skipUnless, TestCase
 import distutils.version
 import os
 import subprocess
-import sys
+import time, sys
 import tempfile
 
 TOOLS_DIR = "../../tools/"
@@ -50,7 +50,7 @@ def setUpModule():
     # time, and to disable buffering.
     cfg.cmd_format = (
         'stdbuf -o 0 -i 0 timeout -s KILL 10s ' + TOOLS_DIR +
-        'memleak.py -c "{} {{}} {}" -T 1 1 2'.format(exec_dst,
+        'memleak.py -c "{} {{}} {}" -T 1 1 3'.format(exec_dst,
                                                      cfg.leaking_amount))
 
 
@@ -63,23 +63,27 @@ class MemleakToolTests(TestCase):
                              shell=True)
 
         # Waiting for the first report.
-        while True:
-            p.poll()
-            if p.returncode is not None:
-                break
-            line = p.stdout.readline()
-            if "with outstanding allocations" in line:
-                break
+        # while True:
+        #     p.poll()
+        #     if p.returncode is not None:
+        #         break
+        #     line = p.stdout.readline()
+        #     print(line)
+        #     if b"with outstanding allocations" in line:
+        #         break
 
         # At this point, memleak.py have already launched application and set
         # probes. Sending command to the leaking application to make its
         # allocations.
-        out = p.communicate(input="\n")[0]
+
+        # wait one second for memleak to launch the application
+        time.sleep(1)
+        out = p.communicate(input=b"\n")[0]
 
         # If there were memory leaks, they are in the output. Filter the lines
         # containing "byte" substring. Every interesting line is expected to
         # start with "N bytes from"
-        x = [x for x in out.split('\n') if 'byte' in x]
+        x = [x for x in out.split(b'\n') if b'byte' in x]
 
         self.assertTrue(len(x) >= 1,
                         msg="At least one line should have 'byte' substring.")
```

Basically do not do `poll` on subprocess stdout stream and instead just
wait a while until the process stabilized, sent the input in and wait for the result.

Some of above changes is due to python3 byte requirement. Why the original
polling works for python2 but not python3, I have no idea.
