### ISSUE TITLE
tools/wakeuptime.py says "UnicodeDecodeError: 'ascii' codec can't decode byte 0x95 in position 2"

### ISSUE THREAD

**Issue by luohao-brian** [iovisor/bcc#1730]
[root@ecs-blog2 tools]# ./wakeuptime.py
Tracing blocked time (us) by kernel stack... Hit Ctrl-C to end.
^C
    target:
    ffffffff81a00205 ret_from_fork
    ffffffff810a6a15 kthread
    ffffffff810a1821 worker_thread
    ffffffff8109f700 create_worker
    waker:           kworker/0:1
        5

Traceback (most recent call last):
  File "./wakeuptime.py", line 216, in <module>
    print("    %-16s %s" % ("target:", k.target.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0x95 in position 2: ordinal not in range(128)

it seems bpf_probe_read(&key.target, sizeof(key.target), p->comm) gets corrupted string，so decode() reports an error.

My enviornment:

CentOS 7.4 + elrepo kernel-ml 4.16 +  bcc(cf44278)

**Comment by yonghong-song** [comment]
Could you print the byte sequence so that we may get some clue whether this is just a strange process name set by somebody or it is a kernel bug or it is a memory corruption somewhere?

**Comment by luohao-brian** [comment]
Thanks for your respond.

I tried to print out the byte code as well as the string,  and below is my code change and part of the output. I'm pretty sure there is no process with a strange name.


214         else:
215             # print default multi-line stack output
216             #print("    %-16s %s" % ("target:", k.target.decode()))
217             print("    %-16s %s (%s)" % ("target:", k.target, ":".join("{:02x}".format(ord(c)) for c in k.    target)))
218             #for addr in waker_kernel_stack:
219             #    print("    %-16x %s" % (addr, b.ksym(addr)))
220             print("    %-16s %s" % ("waker:", k.waker.decode()))
221             print("        %d\n" % v.value)

    target:          �q�q���kworker/ (80:71:e2:71:04:88:ff:ff:6b:77:6f:72:6b:65:72:2f)
    waker:           swapper/5
        575986

    target:           ()
    waker:           swapper/7
        704986

    target:          ��/����pool (c0:d6:2f:a6:04:88:ff:ff:70:6f:6f:6c)
    waker:           swapper/2
        800744

    target:          @�<����pcscd (40:c5:3c:94:04:88:ff:ff:70:63:73:63:64)
    waker:           pool
        801235

    target:          @�֫���kworker/ (40:ab:d6:ab:04:88:ff:ff:6b:77:6f:72:6b:65:72:2f)
    waker:           swapper/7
        822076

    target:          �����kworker/ (80:04:19:a6:04:88:ff:ff:6b:77:6f:72:6b:65:72:2f)
    waker:           kworker/u16:0
        832222

    target:          @������sshd (40:a8:82:aa:04:88:ff:ff:73:73:68:64)
    waker:           swapper/5
        1053945

    target:           ()
    waker:           kworker/u16:1
        1054252

    target:           ()
    waker:           docker-containe
        1463600

    target:          �������dockerd- (80:9d:fe:a4:04:88:ff:ff:64:6f:63:6b:65:72:64:2d)
    waker:           dockerd-latest
        1499708

    target:          @����mysqld (40:02:e1:a5:04:88:ff:ff:6d:79:73:71:6c:64)
    waker:           swapper/2
        1500287

    target:          @����mysqld (40:02:e1:a5:04:88:ff:ff:6d:79:73:71:6c:64)
    waker:           swapper/4
        1500294

**Comment by yonghong-song** [comment]
Looks like the first 8 bytes are garbage. The following is the way to help debug this issue as I cannot reproduce this behavior in my setup:

1. in the bpf program, call bpf_trace_printk to check what is exactly written to the target buffer in the bpf program.
2. It looks like the offset to the correct name is 8 bytes. Maybe bcc messed it up?
```
struct key_t {
    int  w_k_stack_id;
    char waker[TASK_COMM_LEN];
    char target[TASK_COMM_LEN];
};
```
Maybe you could experiment with the above data structure to see whether a particular alignment
will fix the issue? For example, change the above w_k_stack_id to long long?  In kernel 
```
linux/sched.h:#define TASK_COMM_LEN                     16
```
Anyway, the issue is not obvious to me.

**Comment by luohao-brian** [comment]
Weird.

Even though I tried to keep the code as simple as possible,  I still got the corrupted data.

```
#!/usr/bin/env python
from bcc import BPF

bpf_text = """
#include <uapi/linux/ptrace.h>
#include <linux/sched.h>

int waker(struct pt_regs *ctx, struct task_struct *p) {
    bpf_trace_printk("%s\\n", p->comm);
    return 0;
}
"""


b = BPF(text=bpf_text)
b.attach_kprobe(event="try_to_wake_up", fn_name="waker")

b.trace_print()
```

```
 gnome-terminal--2918  [005] d...  2285.156944: 0:
   kworker/u16:3-5427  [001] d...  2285.156944: 0: �
                                                    �l���gnome-te������
   kworker/u16:3-5427  [001] d...  2285.156946: 0: �
                                                    �l���gnome-te������
   kworker/u16:3-5427  [001] d...  2285.156948: 0: �
                                                    �l���gnome-te������
   kworker/u16:3-5427  [001] d...  2285.156949: 0: �
                                                    �l���gnome-te{�
   kworker/u16:3-5427  [001] d...  2285.156951: 0: �
                                                    �l���gnome-te������
 gnome-terminal--2918  [005] d...  2285.156955: 0:
   kworker/u16:3-5427  [001] d...  2285.156957: 0: �
                                                    �l���gnome-te
   kworker/u16:3-5427  [001] d...  2285.156958: 0: �
                                                    �l���gnome-te
   kworker/u16:3-5427  [001] d...  2285.156959: 0: �
                                                    �l���gnome-te
   kworker/u16:3-5427  [001] d...  2285.156961: 0: �
                                                    �l���gnome-te_#���H{�%s

   kworker/u16:3-5427  [001] d...  2285.156963: 0: �
                                                    �l���gnome-te
 gnome-terminal--2918  [005] d...  2285.156966: 0:
   kworker/u16:3-5427  [001] d...  2285.156968: 0: �
                                                    �l���gnome-te
   kworker/u16:3-5427  [001] d...  2285.156969: 0: �
                                                    �l���gnome-te
   kworker/u16:3-5427  [001] d...  2285.156970: 0:
   kworker/u16:3-5427  [001] d...  2285.156971: 0: �
                                                    �l���gnome-te

```

**Comment by luohao-brian** [comment]
Sorry for being so late. 

I tried it on 4.16.7 and 4.16.11, and got the same result as below:

Without bpf_get_current_task workaround, same thing as previous.
```
[root@hluo bcc]# tools/wakeuptime.py
Tracing blocked time (us) by kernel stack... Hit Ctrl-C to end.
^C
Traceback (most recent call last):
  File "tools/wakeuptime.py", line 218, in <module>
    print("    %-16s %s" % ("target:", k.target.decode()))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x98 in position 1: ordinal not in range(128)
 ```

With bpf_get_current_task workaround, got warnings and nothing displayed.

```
[root@hluo bcc]# tools/wakeuptime.py
/virtual/main.c:2:9: warning: 'randomized_struct_fields_start' macro redefined [-Wmacro-redefined]
#define randomized_struct_fields_start  struct {
        ^
/lib/modules/4.16.11-1.el7.elrepo.x86_64/build/include/linux/compiler_types.h:230:10: note: previous definition is here
# define randomized_struct_fields_start
         ^
/virtual/main.c:3:9: warning: 'randomized_struct_fields_end' macro redefined [-Wmacro-redefined]
#define randomized_struct_fields_end    };
        ^
/lib/modules/4.16.11-1.el7.elrepo.x86_64/build/include/linux/compiler_types.h:231:10: note: previous definition is here
# define randomized_struct_fields_end
         ^
2 warnings generated.
Tracing blocked time (us) by kernel stack... Hit Ctrl-C to end.

^C
Detaching...

```

However, it worked fine with 4.14.40.
```
[root@ecs-blog2 bcc]# tools/wakeuptime.py
Tracing blocked time (us) by kernel stack... Hit Ctrl-C to end.
^C
    target:          sshd
    ffffffff81800205 ret_from_fork
    ffffffff810a2355 kthread
    ffffffff8109be55 worker_thread
    ffffffff8109bc1a process_one_work
    ffffffff814abfee flush_to_ldisc
    ffffffff814ac899 tty_port_default_receive_buf
    ffffffff814abe72 tty_ldisc_receive_buf
    ffffffff814a9474 n_tty_receive_buf2
    ffffffff814a8d4f n_tty_receive_buf_common
    ffffffff810c7d73 __wake_up
    ffffffff810c7d20 __wake_up_common_lock
    ffffffff810c7bb2 __wake_up_common
    ffffffff812682c3 pollwake
    waker:           kworker/u256:1
        48

    target:          sshd
    ffffffff81800205 ret_from_fork
    ffffffff810a2355 kthread
    ffffffff8109be55 worker_thread
    ffffffff8109bc1a process_one_work
    ffffffff814abfee flush_to_ldisc
    ffffffff814ac899 tty_port_default_receive_buf
    ffffffff814abe72 tty_ldisc_receive_buf
    ffffffff814a9474 n_tty_receive_buf2
    ffffffff814a8d4f n_tty_receive_buf_common
    ffffffff810c7d73 __wake_up
    ffffffff810c7d20 __wake_up_common_lock
    ffffffff810c7bb2 __wake_up_common
    ffffffff812682c3 pollwake
    waker:           kworker/u256:2
        51

    target:          kworker/u256:2
    ffffffff81800081 entry_SYSCALL_64_after_hwframe
    ffffffff81003b24 do_syscall_64
    ffffffff81251745 sys_write
    ffffffff812514f1 vfs_write
    ffffffff81251237 __vfs_write
    ffffffff814a31c2 tty_write
    ffffffff814a705c n_tty_write
    ffffffff814a678c do_output_char
    ffffffff814aead3 pty_write
    ffffffff814abf0b tty_flip_buffer_push
    ffffffff8109a6a8 queue_work_on
    ffffffff81099aa9 __queue_work
    ffffffff81099972 insert_work
    waker:           wakeuptime.py
        95

    target:          rcu_sched
    ffffffff810000d5 secondary_startup_64
    ffffffff81051982 start_secondary
    ffffffff810c8a23 cpu_startup_entry
    ffffffff810c87d7 do_idle
    ffffffff817e2273 default_idle_call
    ffffffff81036d6f arch_cpu_idle
    ffffffff817e1de0 default_idle
    ffffffff817e20f6 native_safe_halt
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c70 xen_evtchn_do_upcall
    ffffffff81087bed irq_exit
    ffffffff81a000da __softirqentry_text_start
    ffffffff810f38bb rcu_process_callbacks
    ffffffff810f0459 rcu_report_qs_rnp
    ffffffff810f010b rcu_gp_kthread_wake
    ffffffff810c812c swake_up
    ffffffff810c80b7 swake_up_locked.part.0
    waker:           swapper/1
        1004

    target:          rcu_sched
    ffffffff810000d5 secondary_startup_64
    ffffffff8226a4f8 x86_64_start_kernel
    ffffffff8226a484 x86_64_start_reservations
    ffffffff8226affa start_kernel
    ffffffff817d479e rest_init
    ffffffff810c8a23 cpu_startup_entry
    ffffffff810c87d7 do_idle
    ffffffff817e2273 default_idle_call
    ffffffff81036d6f arch_cpu_idle
    ffffffff817e1de0 default_idle
    ffffffff817e20f6 native_safe_halt
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c70 xen_evtchn_do_upcall
    ffffffff81087bed irq_exit
    ffffffff81a000da __softirqentry_text_start
    ffffffff810fa07d run_timer_softirq
    ffffffff810f9a13 call_timer_fn
    ffffffff810f9b1e process_timeout
    waker:           swapper/0
        7898

    target:          rcu_sched
    ffffffff810000d5 secondary_startup_64
    ffffffff81051982 start_secondary
    ffffffff810c8a23 cpu_startup_entry
    ffffffff810c87d7 do_idle
    ffffffff817e2273 default_idle_call
    ffffffff81036d6f arch_cpu_idle
    ffffffff817e1de0 default_idle
    ffffffff817e20f6 native_safe_halt
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c70 xen_evtchn_do_upcall
    ffffffff81087bed irq_exit
    ffffffff81a000da __softirqentry_text_start
    ffffffff810fa07d run_timer_softirq
    ffffffff810f9a13 call_timer_fn
    ffffffff810f9b1e process_timeout
    waker:           swapper/1
        7968

    target:          kworker/0:1
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c70 xen_evtchn_do_upcall
    ffffffff81087bed irq_exit
    ffffffff81a000da __softirqentry_text_start
    ffffffff810f9e23 run_timer_softirq
    ffffffff810f9a13 call_timer_fn
    ffffffff81099db8 delayed_work_timer_fn
    ffffffff81099aa9 __queue_work
    ffffffff81099972 insert_work
    waker:           wakeuptime.py
        160960

    target:          kworker/0:1
    ffffffff810000d5 secondary_startup_64
    ffffffff8226a4f8 x86_64_start_kernel
    ffffffff8226a484 x86_64_start_reservations
    ffffffff8226affa start_kernel
    ffffffff817d479e rest_init
    ffffffff810c8a23 cpu_startup_entry
    ffffffff810c87d7 do_idle
    ffffffff817e2273 default_idle_call
    ffffffff81036d6f arch_cpu_idle
    ffffffff817e1de0 default_idle
    ffffffff817e20f6 native_safe_halt
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c70 xen_evtchn_do_upcall
    ffffffff81087bed irq_exit
    ffffffff81a000da __softirqentry_text_start
    ffffffff810f9e23 run_timer_softirq
    ffffffff810f9a13 call_timer_fn
    ffffffff81099db8 delayed_work_timer_fn
    ffffffff81099aa9 __queue_work
    ffffffff81099972 insert_work
    waker:           swapper/0
        428886

    target:          mysqld
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c6b xen_evtchn_do_upcall
    ffffffff81480bb3 __xen_evtchn_do_upcall
    ffffffff81483572 evtchn_2l_handle_events
    ffffffff810e2b62 generic_handle_irq
    ffffffff810e7b7a handle_percpu_irq
    ffffffff810e3a02 handle_irq_event_percpu
    ffffffff810e387f __handle_irq_event_percpu
    ffffffff8101b58d xen_timer_interrupt
    ffffffff810fc7a0 hrtimer_interrupt
    ffffffff810fc0bd __hrtimer_run_queues
    ffffffff810fbde2 hrtimer_wakeup
    waker:           tuned
        500157

    target:          rcu_sched
    ffffffff810000d5 secondary_startup_64
    ffffffff81051982 start_secondary
    ffffffff810c8a23 cpu_startup_entry
    ffffffff810c87d7 do_idle
    ffffffff817e2273 default_idle_call
    ffffffff81036d6f arch_cpu_idle
    ffffffff817e1de0 default_idle
    ffffffff817e20f6 native_safe_halt
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c70 xen_evtchn_do_upcall
    ffffffff81087bed irq_exit
    ffffffff81a000da __softirqentry_text_start
    ffffffff810f3588 rcu_process_callbacks
    ffffffff810f010b rcu_gp_kthread_wake
    ffffffff810c812c swake_up
    ffffffff810c80b7 swake_up_locked.part.0
    waker:           swapper/1
        808005

    target:          kworker/u256:1
    ffffffff81800081 entry_SYSCALL_64_after_hwframe
    ffffffff81003b24 do_syscall_64
    ffffffff81251745 sys_write
    ffffffff812514f1 vfs_write
    ffffffff81251237 __vfs_write
    ffffffff814a31c2 tty_write
    ffffffff814a71c8 n_tty_write
    ffffffff814aead3 pty_write
    ffffffff814abf0b tty_flip_buffer_push
    ffffffff8109a6a8 queue_work_on
    ffffffff81099aa9 __queue_work
    ffffffff81099972 insert_work
    waker:           sshd
        888757

    target:          kworker/u256:1
    ffffffff810000d5 secondary_startup_64
    ffffffff8226a4f8 x86_64_start_kernel
    ffffffff8226a484 x86_64_start_reservations
    ffffffff8226affa start_kernel
    ffffffff817d479e rest_init
    ffffffff810c8a23 cpu_startup_entry
    ffffffff810c87d7 do_idle
    ffffffff817e2273 default_idle_call
    ffffffff81036d6f arch_cpu_idle
    ffffffff817e1de0 default_idle
    ffffffff817e20f6 native_safe_halt
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c70 xen_evtchn_do_upcall
    ffffffff81087bed irq_exit
    ffffffff81a000da __softirqentry_text_start
    ffffffff810fa011 run_timer_softirq
    ffffffff810f9a13 call_timer_fn
    ffffffff81099db8 delayed_work_timer_fn
    ffffffff81099aa9 __queue_work
    ffffffff81099972 insert_work
    waker:           swapper/0
        959322

    target:          tuned
    ffffffff810000d5 secondary_startup_64
    ffffffff8226a4f8 x86_64_start_kernel
    ffffffff8226a484 x86_64_start_reservations
    ffffffff8226affa start_kernel
    ffffffff817d479e rest_init
    ffffffff810c8a23 cpu_startup_entry
    ffffffff810c87d7 do_idle
    ffffffff817e2273 default_idle_call
    ffffffff81036d6f arch_cpu_idle
    ffffffff817e1de0 default_idle
    ffffffff817e20f6 native_safe_halt
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c6b xen_evtchn_do_upcall
    ffffffff81480bb3 __xen_evtchn_do_upcall
    ffffffff81483572 evtchn_2l_handle_events
    ffffffff810e2b62 generic_handle_irq
    ffffffff810e7b7a handle_percpu_irq
    ffffffff810e3a02 handle_irq_event_percpu
    ffffffff810e387f __handle_irq_event_percpu
    ffffffff8101b58d xen_timer_interrupt
    ffffffff810fc7a0 hrtimer_interrupt
    ffffffff810fc0bd __hrtimer_run_queues
    ffffffff810fbde2 hrtimer_wakeup
    waker:           swapper/0
        1000258

    target:          in:imjournal
    ffffffff810000d5 secondary_startup_64
    ffffffff8226a4f8 x86_64_start_kernel
    ffffffff8226a484 x86_64_start_reservations
    ffffffff8226affa start_kernel
    ffffffff817d479e rest_init
    ffffffff810c8a23 cpu_startup_entry
    ffffffff810c87d7 do_idle
    ffffffff817e2273 default_idle_call
    ffffffff81036d6f arch_cpu_idle
    ffffffff817e1de0 default_idle
    ffffffff817e20f6 native_safe_halt
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c6b xen_evtchn_do_upcall
    ffffffff81480bb3 __xen_evtchn_do_upcall
    ffffffff81483572 evtchn_2l_handle_events
    ffffffff810e2b62 generic_handle_irq
    ffffffff810e7b7a handle_percpu_irq
    ffffffff810e3a02 handle_irq_event_percpu
    ffffffff810e387f __handle_irq_event_percpu
    ffffffff8101b58d xen_timer_interrupt
    ffffffff810fc7a0 hrtimer_interrupt
    ffffffff810fc0bd __hrtimer_run_queues
    ffffffff810fbde2 hrtimer_wakeup
    waker:           swapper/0
        1001094

    target:          kworker/0:1
    ffffffff810000d5 secondary_startup_64
    ffffffff8226a4f8 x86_64_start_kernel
    ffffffff8226a484 x86_64_start_reservations
    ffffffff8226affa start_kernel
    ffffffff817d479e rest_init
    ffffffff810c8a23 cpu_startup_entry
    ffffffff810c87d7 do_idle
    ffffffff817e2273 default_idle_call
    ffffffff81036d6f arch_cpu_idle
    ffffffff817e1de0 default_idle
    ffffffff817e20f6 native_safe_halt
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c70 xen_evtchn_do_upcall
    ffffffff81087bed irq_exit
    ffffffff81a000da __softirqentry_text_start
    ffffffff810fa07d run_timer_softirq
    ffffffff810f9a13 call_timer_fn
    ffffffff81412ab9 cursor_timer_handler
    ffffffff8109a6a8 queue_work_on
    ffffffff81099aa9 __queue_work
    ffffffff81099972 insert_work
    waker:           swapper/0
        1234783

    target:          sshd
    ffffffff810000d5 secondary_startup_64
    ffffffff8226a4f8 x86_64_start_kernel
    ffffffff8226a484 x86_64_start_reservations
    ffffffff8226affa start_kernel
    ffffffff817d479e rest_init
    ffffffff810c8a23 cpu_startup_entry
    ffffffff810c87d7 do_idle
    ffffffff817e2273 default_idle_call
    ffffffff81036d6f arch_cpu_idle
    ffffffff817e1de0 default_idle
    ffffffff817e20f6 native_safe_halt
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c70 xen_evtchn_do_upcall
    ffffffff81087bed irq_exit
    ffffffff81a000da __softirqentry_text_start
    ffffffff81688d54 net_rx_action
    ffffffffa015e0ec xennet_poll
    ffffffff81689522 napi_gro_receive
    ffffffff81688905 netif_receive_skb_internal
    ffffffff81686678 __netif_receive_skb
    ffffffff81685f57 __netif_receive_skb_core
    ffffffff816d370c ip_rcv
    ffffffff816d2d6f ip_rcv_finish
    ffffffff816d340f ip_local_deliver
    ffffffff816d30ac ip_local_deliver_finish
    ffffffff816fb4f9 tcp_v4_rcv
    ffffffff816f9e0d tcp_v4_do_rcv
    ffffffff816ee408 tcp_rcv_established
    ffffffff816ed8b8 tcp_data_queue
    ffffffff81669e3d sock_def_readable
    ffffffff810c7d9e __wake_up_sync_key
    ffffffff810c7d20 __wake_up_common_lock
    ffffffff810c7bb2 __wake_up_common
    ffffffff812682c3 pollwake
    waker:           swapper/0
        1847935

    target:          wakeuptime.py
    ffffffff81800205 ret_from_fork
    ffffffff810a2355 kthread
    ffffffff8109be55 worker_thread
    ffffffff8109bc1a process_one_work
    ffffffff814abfee flush_to_ldisc
    ffffffff814ac899 tty_port_default_receive_buf
    ffffffff814abe72 tty_ldisc_receive_buf
    ffffffff814a9474 n_tty_receive_buf2
    ffffffff814a9119 n_tty_receive_buf_common
    ffffffff814a8292 n_tty_receive_char_special
    ffffffff814a788c n_tty_receive_signal_char
    ffffffff814a7553 isig
    ffffffff814a661f __isig
    ffffffff81091405 kill_pgrp
    ffffffff81091386 __kill_pgrp_info
    ffffffff81091335 group_send_sig_info
    ffffffff81090df2 do_send_sig_info
    ffffffff810903fe send_signal
    ffffffff81090206 __send_signal
    ffffffff8108f677 complete_signal
    ffffffff8108f549 signal_wake_up_state
    waker:           kworker/u256:1
        1848168

    target:          mysqld
    ffffffff810000d5 secondary_startup_64
    ffffffff81051982 start_secondary
    ffffffff810c8a23 cpu_startup_entry
    ffffffff810c87d7 do_idle
    ffffffff817e2273 default_idle_call
    ffffffff81036d6f arch_cpu_idle
    ffffffff817e1de0 default_idle
    ffffffff817e20f6 native_safe_halt
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c6b xen_evtchn_do_upcall
    ffffffff81480bb3 __xen_evtchn_do_upcall
    ffffffff81483572 evtchn_2l_handle_events
    ffffffff810e2b62 generic_handle_irq
    ffffffff810e7b7a handle_percpu_irq
    ffffffff810e3a02 handle_irq_event_percpu
    ffffffff810e387f __handle_irq_event_percpu
    ffffffff8101b58d xen_timer_interrupt
    ffffffff810fc7a0 hrtimer_interrupt
    ffffffff810fc0bd __hrtimer_run_queues
    ffffffff810fbde2 hrtimer_wakeup
    waker:           swapper/1
        5000940

    target:          mysqld
    ffffffff810000d5 secondary_startup_64
    ffffffff8226a4f8 x86_64_start_kernel
    ffffffff8226a484 x86_64_start_reservations
    ffffffff8226affa start_kernel
    ffffffff817d479e rest_init
    ffffffff810c8a23 cpu_startup_entry
    ffffffff810c87d7 do_idle
    ffffffff817e2273 default_idle_call
    ffffffff81036d6f arch_cpu_idle
    ffffffff817e1de0 default_idle
    ffffffff817e20f6 native_safe_halt
    ffffffff8180143e xen_hvm_callback_vector
    ffffffff81482c6b xen_evtchn_do_upcall
    ffffffff81480bb3 __xen_evtchn_do_upcall
    ffffffff81483572 evtchn_2l_handle_events
    ffffffff810e2b62 generic_handle_irq
    ffffffff810e7b7a handle_percpu_irq
    ffffffff810e3a02 handle_irq_event_percpu
    ffffffff810e387f __handle_irq_event_percpu
    ffffffff8101b58d xen_timer_interrupt
    ffffffff810fc7a0 hrtimer_interrupt
    ffffffff810fc0bd __hrtimer_run_queues
    ffffffff810fbde2 hrtimer_wakeup
    waker:           swapper/0
        9501815

Detaching...

```

**Comment by yonghong-song** [comment]
Could you send me your 4.16 config file to me? I suspect some config options changed the `struct task_struct` layout by 8 bytes which is not visible if directly compiled from bcc.

**Comment by luohao-brian** [comment]
The kernel was from centos elrepo-kernel: http://elrepo.org/linux/kernel/el7/; I uploaded the config to http://114.115.144.21/static/tmp/config-4.16.11-x86_64.txt

**Comment by yonghong-song** [comment]
The following diff fixed the issue,
```
[yhs@localhost tools]$ git diff
diff --git a/tools/wakeuptime.py b/tools/wakeuptime.py
index cf0ca7d..0af4cc0 100755
--- a/tools/wakeuptime.py
+++ b/tools/wakeuptime.py
@@ -86,6 +86,11 @@ def signal_ignore(signal, frame):
 
 # define BPF program
 bpf_text = """
+#if !defined(CONFIG_CC_STACKPROTECTOR)
+#if defined(CONFIG_CC_STACKPROTECTOR_AUTO) \
+    || defined(CONFIG_CC_STACKPROTECTOR_REGULAR) \
+    || defined(CONFIG_CC_STACKPROTECTOR_STRONG)
+#define CONFIG_CC_STACKPROTECTOR
+#endif
+#endif
 #include <uapi/linux/ptrace.h>
 #include <linux/sched.h>
 
[yhs@localhost tools]$
```

The config file defined `CONFIG_CC_STACKPROTECTOR_STRONG=y`. In top linux Makefile,
this will add `-DCONFIG_CC_STACKPROTECTOR` to the kernel compilation flag.

Unfortunately, the native clang bpf program compilation won't see `-DCONFIG_CC_STACKPROTECTOR`, so this caused kernel and bpf program disagrees with the following part of task_struct:
```
struct task_struct {
 ...
        pid_t                           pid;
        pid_t                           tgid;

#ifdef CONFIG_CC_STACKPROTECTOR
        /* Canary value for the -fstack-protector GCC feature: */
        unsigned long                   stack_canary;
#endif
        /*
         * Pointers to the (original) parent process, youngest child, younger sibling,
         * older sibling, respectively.  (p->father can be replaced with
         * p->real_parent->pid)
         */

        /* Real parent process: */
        struct task_struct __rcu        *real_parent;
...
}
```

I think rewriter should be able to handle this transparently.

**Comment by yonghong-song** [comment]
The hack below in bcc clang frontend should do it,
```
[yhs@localhost tools]$ git diff
diff --git a/src/cc/frontends/clang/loader.cc b/src/cc/frontends/clang/loader.cc
index eb6a307..46837bc 100644
--- a/src/cc/frontends/clang/loader.cc
+++ b/src/cc/frontends/clang/loader.cc
@@ -353,6 +353,16 @@ int ClangLoader::do_compile(unique_ptr<llvm::Module> *mod, TableStorage &ts,
   BFrontendAction bact(os1, flags_, ts, id, main_path, func_src, mod_src);
   if (!compiler1.ExecuteAction(bact))
     return -1;
+
+  out_str1 = "#if !defined(CONFIG_CC_STACKPROTECTOR)\n"
+             "#if defined(CONFIG_CC_STACKPROTECTOR_AUTO) \\\n"
+             "    || defined(CONFIG_CC_STACKPROTECTOR_REGULAR) \\\n"
+             "    || defined(CONFIG_CC_STACKPROTECTOR_STRONG)\n"
+             "#define CONFIG_CC_STACKPROTECTOR\n"
+             "#endif\n"
+             "#endif\n"
+             + out_str1;
+
   unique_ptr<llvm::MemoryBuffer> out_buf1 = llvm::MemoryBuffer::getMemBuffer(out_str1);
 
   // second pass, clear input and take rewrite buffer
[yhs@localhost tools]$
```
Of course, need to nail down proper implementation.
