### ISSUE TITLE
Can't trace multiple USDT locations in a shared object

### ISSUE THREAD

**Issue by myllynen** [iovisor/bcc#1774]
The following example currently fails, I wonder would it be feasible to support this scenario?

```
# cat ~/utest.py
#!/usr/bin/python

import time
from bcc import BPF, USDT

bpf_text = """
struct usdt_t {
    char usdt[128];
};

BPF_HASH(stats, struct usdt_t, u64, 2);

static char *key1 = "thread__sleep__begin";
int do_trace1(void *ctx) {
    struct usdt_t key = {};
    __builtin_memcpy(&key.usdt, key1, sizeof(key.usdt));
    u64 zero = 0, *val;
    val = stats.lookup_or_init(&key, &zero);
    (*val)++;
    return 0;
}

static char *key2 = "thread__sleep__end";
int do_trace2(void *ctx) {
    struct usdt_t key = {};
    __builtin_memcpy(&key.usdt, key2, sizeof(key.usdt));
    u64 zero = 0, *val;
    val = stats.lookup_or_init(&key, &zero);
    (*val)++;
    return 0;
}
"""

contexts = []
u1 = USDT(path="/usr/lib/jvm/java-9-openjdk-9.0.4.11-6.fc28.x86_64/lib/server/libjvm.so")
u1.enable_probe("thread__sleep__begin", "do_trace1")
contexts.append(u1)
u2 = USDT(path="/usr/lib/jvm/java-9-openjdk-9.0.4.11-6.fc28.x86_64/lib/server/libjvm.so")
u2.enable_probe("thread__sleep__end", "do_trace2")
contexts.append(u2)
b = BPF(text=bpf_text, usdt_contexts=contexts)
while True:
  time.sleep(1)
  s = b["stats"]
  for k, v in s.items():
    print(k.usdt.decode("ASCII") + " = " + str(v.value))
# python2 ~/utest.py
Traceback (most recent call last):
  File "/root/utest.py", line 41, in <module>
    b = BPF(text=bpf_text, usdt_contexts=contexts)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 302, in __init__
    "locations")
Exception: can't generate USDT probe arguments; possible cause is missing pid
    when a probe in a shared object has multiple locations
```

Thanks.

**Comment by myllynen** [comment]
Thanks for your detailed answer!

FWIW, the background for this was that we're adding support for kernel tracepoint / uprobe / USDT probes in the PCP BCC PMDA plugin to produce hit counts available as PCP metrics with hopefully pretty simple configuration mechanism (=list the wanted to tracepoints/uprobes/USDTs to corresponding configuration text files). For anyone tracing something with a standalone tool it's of course pretty simple to provide a PID but with a system service running in the background having to specify a PID at startup might require a bit of additional effort to get right.

The patches implementing the above are being merged as we speak but this post should give you a concrete idea how they will work:

https://groups.io/g/pcp/message/18875

Hopefully these will be part of PCP 4.1.0, currently scheduled around mid-June.

Thanks.
