### ISSUE TITLE
tools/argdist.py can not work with -v option. It business with BPF object.

### ISSUE THREAD

**Issue by kernel-z** [iovisor/bcc#1845]
I have tested it at 4.17.2 and 4.13.0.
`./argdist.py -v -C 'p:c:fork()#fork calls'
struct __string_t { char s[80]; };

#include <uapi/linux/ptrace.h>
                
struct fork_hash0_key_t {
u64 v0;
};
BPF_HASH(fork_hash0, struct fork_hash0_key_t, u64);

                int fork_probe0(struct pt_regs *ctx )
{
        u64 __pid_tgid = bpf_get_current_pid_tgid();
        u32 __pid      = __pid_tgid;        // lower 32 bits
        u32 __tgid     = __pid_tgid >> 32;  // upper 32 bits
        
        
        if (!(1)) return 0;
        struct fork_hash0_key_t __key = {};
        __key.v0 = 1;

        fork_hash0.increment(__key);
        return 0;
}

Traceback (most recent call last):
  File "./argdist.py", line 711, in run
    self._attach()
  File "./argdist.py", line 684, in _attach
    print("open uprobes: %s" % self.bpf.open_uprobes)
AttributeError: 'BPF' object has no attribute 'open_uprobes'`

Is the BPF delete the attribute ?

**Comment by kernel-z** [comment]
fixed by #1846  ,Thanks @yonghong-song
