### ISSUE TITLE
bcc tools inside a docker container?

### ISSUE THREAD

**Issue by saobao913** [iovisor/bcc#1875]
Trying to run 'tcplife' inside a docker container with latest stable release v0.6.0
bcc tools built from sources.

Ubuntu bionic 
4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Docker version 17.12.1-ce, build 7390fc6
```
# python3 ./tcplife -w
```
1) It *SUCCEEDS* if I add --privileged
But this is excessive

2) It *FAILS* if I add only CAP_SYS_ADMIN with the following error:
```
**open(/sys/kernel/debug/tracing/kprobe_events): Permission denied**
Traceback (most recent call last):
  File "./tcplife", line 479, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 329, in __init__
    self._trace_autoload()
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1010, in _trace_autoload
    self.attach_kprobe(event=fn.name[8:], fn_name=fn.name)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 575, in attach_kprobe
    raise Exception("Failed to attach BPF to kprobe")
Exception: Failed to attach BPF to kprobe
```

Thoughts?

**Comment by Julio-Guerra** [comment]
Useful to build and start a "debugging container" with all the tools inside. But so far I couldn't receive anything form a "sibling container". But it works with "non containerized" processes.

I wonder if I should use the process id `docker top` gives. Any idea?

For now, I simply mount into the "debugging container the required" `/lib/modules/<version>` folders to be able to compile BPF programs,  `/sys/kernel/debug` for debugfs and `/proc` for procfs. What else should I do?

**Comment by yzhao1012** [comment]
Hi All, sorry to post on an old issue.

Was this resolved? I tried to mount the various directory, and still the kprobe attach failed:
docker run -it --rm --name=test -v /sys:/sys:rw -v $PWD/bazel-bin/src/stirling/:/pl/src/pixielabs.ai/pixielabs -v /lib/modules:/lib/modules -v /usr/src:/usr/src --cap-add=SYS_PTRACE --cap-add=SYS_ADMIN test:latest bash
// Code
BPF bpf;
bpf.attach_kprobe(...);
// This still failed with
// open(/sys/kernel/debug/tracing/kprobe_events): Permission denied
root@bda878f536a4:/pl/src/pixielabs.ai/pixielabs# ls -ld /sys/kernel/debug/tracing/kprobe_events-rw-r--r-- 1 root root 0 May  1 15:46 /sys/kernel/debug/tracing/kprobe_events
// I am running as root:
root@bda878f536a4:/pl/src/pixielabs.ai/pixielabs# whoami
root

Any idea?

**Comment by yzhao1012** [comment]
Yeah! --privileged works for me, after I added it to my command line.
Thanks!

**Comment by yzhao1012** [comment]
A brief summary:
I tried --cap_add ALL, without --previleged, and still runs into the same issue. According to https://docs.docker.com/v17.09/engine/reference/commandline/run/:

"""
The --privileged flag gives all capabilities to the container, and it also lifts all the limitations enforced by the device cgroup controller. In other words, the container can then do almost everything that the host can do. This flag exists to allow special use-cases, like running Docker within Docker.
"""

So it seems the limitation is from "the device cgroup controller", as ALL capabilities do not enable the access.

**Comment by alban** [comment]
> So it seems the limitation is from "the device cgroup controller", as ALL capabilities do not enable the access.

I suspect it might be a LSM (AppArmor or SELinux?) instead of the device cgroup controller: `--privileged` also affects LSMs.

**Comment by elesiuta** [comment]
Has anyone been able to use uflow inside of a docker container?  

I start my container using the same commands as mentioned above
```
sudo docker run -it -v /sys/kernel/debug:/sys/kernel/debug -v /sys/fs/cgroup:/sys/fs/cgroup -v /sys/fs/bpf:/sys/fs/bpf --privileged ubuntu:focal
```
Then install all the dependencies and build python with dtrace enabled (I am able to get this working successfully outside of docker, and am doing the exact same thing inside of the container)  

However when I run the following command inside the container, I get this error
```
root@7d015a3801dd:/# /Python-3.9.1/python /test.py > /dev/null & pythonflow-bpfcc $!
[2] 100096
Error attaching USDT probes: the specified pid might not contain the
given language's runtime, or the runtime was not built with the required
USDT probes. Look for a configure flag similar to --with-dtrace or
--enable-dtrace. To check which probes are present in the process, use the
tplist tool.
[1]   Done                    /Python-3.9.1/python /test.py > /dev/null
```
<details>
<summary>But when I check the probes present in the process, they appear to be there</summary>

```
root@7d015a3801dd:/# /Python-3.9.1/python /test.py > /dev/null & tplist-bpfcc -p $!
[1] 100083
b'/proc/100083/root/Python-3.9.1/python' b'python':b'line'
b'/proc/100083/root/Python-3.9.1/python' b'python':b'function__entry'
b'/proc/100083/root/Python-3.9.1/python' b'python':b'function__return'
b'/proc/100083/root/Python-3.9.1/python' b'python':b'import__find__load__start'
b'/proc/100083/root/Python-3.9.1/python' b'python':b'import__find__load__done'
b'/proc/100083/root/Python-3.9.1/python' b'python':b'audit'
b'/proc/100083/root/Python-3.9.1/python' b'python':b'gc__start'
b'/proc/100083/root/Python-3.9.1/python' b'python':b'gc__done'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'setjmp'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'longjmp'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'longjmp_target'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'lll_lock_wait_private'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_mallopt_arena_max'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_mallopt_arena_test'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_tunable_tcache_max_bytes'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_tunable_tcache_count'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_tunable_tcache_unsorted_limit'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_mallopt_trim_threshold'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_mallopt_top_pad'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_mallopt_mmap_threshold'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_mallopt_mmap_max'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_mallopt_perturb'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_mallopt_mxfast'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_heap_new'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_arena_reuse_free_list'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_arena_reuse'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_arena_reuse_wait'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_arena_new'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_arena_retry'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_sbrk_less'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_heap_free'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_heap_less'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_tcache_double_free'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_heap_more'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_sbrk_more'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_malloc_retry'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_memalign_retry'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_mallopt_free_dyn_thresholds'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_realloc_retry'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_calloc_retry'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libc-2.31.so' b'libc':b'memory_mallopt'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libm-2.31.so' b'libm':b'slowatan2_inexact'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libm-2.31.so' b'libm':b'slowatan2'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libm-2.31.so' b'libm':b'slowatan_inexact'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libm-2.31.so' b'libm':b'slowatan'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libm-2.31.so' b'libm':b'slowtan'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libm-2.31.so' b'libm':b'slowasin'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libm-2.31.so' b'libm':b'slowacos'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libm-2.31.so' b'libm':b'slowsin'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libm-2.31.so' b'libm':b'slowcos'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'pthread_start'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'pthread_create'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'pthread_join'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'pthread_join_ret'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'mutex_init'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'mutex_destroy'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'mutex_acquired'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'mutex_entry'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'mutex_timedlock_acquired'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'mutex_clocklock_entry'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'mutex_timedlock_entry'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'mutex_release'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'rwlock_destroy'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'rdlock_entry'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'rdlock_acquire_read'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'wrlock_entry'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'wrlock_acquire_write'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'rwlock_unlock'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'cond_init'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'cond_destroy'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'cond_wait'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'cond_signal'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'cond_broadcast'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'lll_lock_wait_private'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so' b'libpthread':b'lll_lock_wait'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/ld-2.31.so' b'rtld':b'init_start'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/ld-2.31.so' b'rtld':b'init_complete'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/ld-2.31.so' b'rtld':b'map_failed'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/ld-2.31.so' b'rtld':b'map_start'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/ld-2.31.so' b'rtld':b'map_complete'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/ld-2.31.so' b'rtld':b'reloc_start'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/ld-2.31.so' b'rtld':b'reloc_complete'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/ld-2.31.so' b'rtld':b'unmap_start'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/ld-2.31.so' b'rtld':b'unmap_complete'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/ld-2.31.so' b'rtld':b'setjmp'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/ld-2.31.so' b'rtld':b'longjmp'
b'/proc/100083/root/usr/lib/x86_64-linux-gnu/ld-2.31.so' b'rtld':b'longjmp_target'
```
</details>

I also tried running pythonflow outside of the container on the python process for test.py inside the container but get the same error, and use tplist to confirm the probes are present and still see them in the output (I also run the container with --pid host)
```
sudo tplist-bpfcc -p  $(sudo docker exec <container_name> sh -c /start.sh)
b'/proc/100806/root/Python-3.9.1/python' b'python':b'line'
b'/proc/100806/root/Python-3.9.1/python' b'python':b'function__entry'
b'/proc/100806/root/Python-3.9.1/python' b'python':b'function__return'
b'/proc/100806/root/Python-3.9.1/python' b'python':b'import__find__load__start'
b'/proc/100806/root/Python-3.9.1/python' b'python':b'import__find__load__done'
b'/proc/100806/root/Python-3.9.1/python' b'python':b'audit'
b'/proc/100806/root/Python-3.9.1/python' b'python':b'gc__start'
b'/proc/100806/root/Python-3.9.1/python' b'python':b'gc__done'
...
```
where start.sh is
```
/Python-3.9.1/python /test.py > /dev/null & echo $!
```
