### ISSUE TITLE
fatal error: 'uapi/linux/bpf_perf_event.h' file not found

### ISSUE THREAD

**Issue by tekumara** [iovisor/bcc#1876]
```
$ /usr/share/bcc/tools/profile
Sampling at 49 Hertz of all threads by user + kernel stack... Hit Ctrl-C to end.
/virtual/main.c:3:10: fatal error: 'uapi/linux/bpf_perf_event.h' file not found
#include <uapi/linux/bpf_perf_event.h>
         ^
1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/profile", line 246, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 310, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text
```

```
$ uname -r
4.4.0-1062-aws
```

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

**Comment by tekumara** [comment]
Looks like the master version of profile requires Linux 4.9+, older versions may support Linux 4.6 - 4.8 see https://github.com/iovisor/bcc/blob/master/tools/profile.py#L12

**Comment by pchaigno** [comment]
The version in `tools/old/` should work with older kernels too.
