### ISSUE TITLE
chdir(/lib/modules/4.14.47-56.37.amzn1.x86_64/build): No such file or directory

### ISSUE THREAD

**Issue by tekumara** [iovisor/bcc#1877]
```
$ sudo /usr/share/bcc/tools/execsnoop
chdir(/lib/modules/4.14.47-56.37.amzn1.x86_64/build): No such file or directory
Traceback (most recent call last):
  File "/usr/share/bcc/tools/execsnoop", line 147, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 311, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text
```

**Comment by tekumara** [comment]
The kernel sources were missing. Resolved with:
```
sudo yum install kernel-devel-$(uname -r)
```
