### ISSUE TITLE
Failed to attach BPF to kprobe

### ISSUE THREAD

**Issue by tekumara** [iovisor/bcc#1878]
Regardless of which tool I run (eg: 'cpudist', 'opensnoop', 'execsnoop') I get:
```
$ sudo /usr/share/bcc/tools/opensnoop
open(/sys/kernel/debug/tracing/kprobe_events): No such file or directory
Traceback (most recent call last):
  File "/usr/share/bcc/tools/opensnoop", line 138, in <module>
    b.attach_kprobe(event="do_sys_open", fn_name="trace_entry")
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 576, in attach_kprobe
    raise Exception("Failed to attach BPF to kprobe")
Exception: Failed to attach BPF to kprobe
```

**Comment by palmtenor** [comment]
If you run on newer Kernel (>=4.17), BCC will automatically use the Perf Event based kprobe / uprobe and does not require a `debugfs` mount

**Comment by tekumara** [comment]
To avoid this when running `bcc` inside a container I needed to add a `rw` volume mount for `/sys/kernel/debug`, eg:
```
docker run -it --rm \
  --privileged \
  -v /sys/kernel/debug:/sys/kernel/debug:rw \
  -v /lib/modules:/lib/modules:ro \
  -v /usr/src:/usr/src:ro \
  -v /etc/localtime:/etc/localtime:ro \
  --workdir /usr/share/bcc/tools \
  --pid=host \
  bcc
```
