### ISSUE TITLE
Fedora 28 "ttysnoop" fails with "startswith first arg must be bytes or a tuple of bytes, not str"

### ISSUE THREAD

**Issue by aborniak** [iovisor/bcc#1910]
`[root@aborniakFC tools]# uname -a
Linux aborniakFC.localdomain 4.17.9-200.fc28.x86_64 #1 SMP Mon Jul 23 21:41:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

`[root@aborniakFC tools]# rpm -qa | grep python`
`python3-dnf-plugins-core-2.1.5-4.fc28.noarch`
`python3-setuptools-39.2.0-6.fc28.noarch`
`python3-gobject-base-3.28.3-1.fc28.x86_64`
`python3-rpm-4.14.1-9.fc28.x86_64`
`python3-dbus-1.2.4-13.fc28.x86_64`
`python3-libcomps-0.1.8-11.fc28.x86_64`
`python3-slip-dbus-0.6.4-10.fc28.noarch`
`python3-gpg-1.10.0-4.fc28.x86_64`
`python3-librepo-1.8.1-7.fc28.x86_64`
`python3-bcc-0.6.1-2.git.492a2bf.x86_64`
`python3-decorator-4.2.1-1.fc28.noarch`
`python3-iniparse-0.4-30.fc28.noarch`
`python3-smartcols-0.3.0-2.fc28.x86_64`
`python3-slip-0.6.4-10.fc28.noarch`
`python3-pip-9.0.3-2.fc28.noarch`
`python3-3.6.6-1.fc28.x86_64`
`python3-firewall-0.5.3-2.fc28.noarch`
`python3-libselinux-2.8-1.fc28.x86_64`
`python3-hawkey-0.11.1-3.fc28.x86_64`
`python3-dnf-2.7.5-12.fc28.noarch`
`python3-libs-3.6.6-1.fc28.x86_64`
`python3-six-1.11.0-3.fc28.noarch`
[root@aborniakFC tools]#`

`[root@aborniakFC tools]#  ps -p $$`
  `PID TTY          TIME CMD`
  `902 pts/1    00:00:00 bash`

`[root@aborniakFC tools]# ./ttysnoop 1`
`Traceback (most recent call last):`
  `File "./ttysnoop", line 102, in <module>`
  `  b = BPF(text=bpf_text)`
  `File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 337, in __init__`
   ` self._trace_autoload()`
  `File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 1030, in _trace_autoload`
 `   event=self.fix_syscall_fnname(func_name[8:]),`
 ` File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 569, in fix_syscall_fnname`
 `   if name.startswith(prefix):`
`TypeError: startswith first arg must be bytes or a tuple of bytes, not str`
`[root@aborniakFC tools]#`

The same error appears for 0 & 2 & /dev/console

**Comment by aborniak** [comment]
Thank you for quick response. You made my day.
