### ISSUE TITLE
example of BPF_HASH without key_t

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#192]
In a few cases, the struct key_t for a BPF_HASH only contains one pointer. Eg, disksnoop.c:

```C
struct key_t {
	struct request *req;
};
BPF_HASH(start, struct key_t);
```

It seems redundant. But I can't seem to use a pointer directly. Eg, changing disksnoop.c to become:

```C
#include <uapi/linux/ptrace.h>
#include <linux/blkdev.h>

BPF_HASH(start, struct request *);

int do_request(struct pt_regs *ctx, struct request *req) {
	u64 ts;

	// stash start timestamp by request ptr
	ts = bpf_ktime_get_ns();
	start.update(req, &ts);

	return 0;
}

int do_completion(struct pt_regs *ctx, struct request *req) {
	u64 *tsp, delta;

	tsp = start.lookup(req);

	if (tsp != 0) {
		delta = bpf_ktime_get_ns() - *tsp;
		bpf_trace_printk("%d %x %d\n", req->__data_len,
		    req->cmd_flags, delta / 1000);
		start.delete(req);
	}

	return 0;
}
```

output:

```Shell
# ./disksnoop.py 
/home/bgregg-buildtest/bcc/examples/disksnoop.c:23:15: warning: incompatible pointer types passing 'struct request *' to parameter of type 'struct request **'; take the
      address with & [-Wincompatible-pointer-types]
        start.update(req, &ts);
                     ^~~
                     &
/home/bgregg-buildtest/bcc/examples/disksnoop.c:31:21: warning: incompatible pointer types passing 'struct request *' to parameter of type 'struct request **'; take the
      address with & [-Wincompatible-pointer-types]
        tsp = start.lookup(req);
                           ^~~
                           &
/home/bgregg-buildtest/bcc/examples/disksnoop.c:37:16: warning: incompatible pointer types passing 'struct request *' to parameter of type 'struct request **'; take the
      address with & [-Wincompatible-pointer-types]
                start.delete(req);
                             ^~~
                             &
3 warnings generated.
<bcc-memory-buffer>:33:59: error: use of undeclared identifier 'u'
        tsp = bpf_map_lookup_elem((void *)bpf_pseudo_fd(1, 3), ((u);
                                                                 ^
<bcc-memory-buffer>:43:2: error: expected '}'
}
 ^
<bcc-memory-buffer>:30:61: note: to match this '{'
int do_completion(struct pt_regs *ctx, struct request *req) {
                                                            ^
2 errors generated.
Traceback (most recent call last):
  File "./disksnoop.py", line 19, in <module>
    b = BPF(src_file="disksnoop.c")
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 345, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module disksnoop.c
```

**Comment by drzaeus77** [comment]
The pending fix addresses the buggy rewrite pass that was mangling the sample you included. However, you will still need to pass `&req`, since the prototype for lookup/delete/etc. is a pointer to a key, which therefore should be `struct request **`

**Comment by brendangregg** [comment]
ok, sounds good, thanks.

**Comment by brendangregg** [comment]
I really want to use this, but got a build error:

```Shell
[...]
/mnt/src/bcc/src/cc/frontends/clang/b_frontend_action.cc: At global scope:
/mnt/src/bcc/src/cc/frontends/clang/b_frontend_action.cc:437:1: error: prototype for ‘ebpf::BFrontendAction::BFrontendAction(llvm::raw_ostream&, unsigned int)’ does not match any in class ‘ebpf::BFrontendAction’
 BFrontendAction::BFrontendAction(llvm::raw_ostream &os, unsigned flags)
 ^
In file included from /mnt/src/bcc/src/cc/frontends/clang/b_frontend_action.cc:26:0:
/mnt/src/bcc/src/cc/frontends/clang/b_frontend_action.h:95:7: error: candidates are: ebpf::BFrontendAction::BFrontendAction(ebpf::BFrontendAction&&)
 class BFrontendAction : public clang::ASTFrontendAction {
       ^
/mnt/src/bcc/src/cc/frontends/clang/b_frontend_action.h:95:7: error:                 ebpf::BFrontendAction::BFrontendAction(const ebpf::BFrontendAction&)
/mnt/src/bcc/src/cc/frontends/clang/b_frontend_action.h:99:12: error:                 ebpf::BFrontendAction::BFrontendAction(llvm::raw_ostream&)
   explicit BFrontendAction(llvm::raw_ostream &os);
            ^
/mnt/src/bcc/src/cc/frontends/clang/b_frontend_action.cc: In member function ‘virtual void ebpf::BFrontendAction::EndSourceFileAction()’:
/mnt/src/bcc/src/cc/frontends/clang/b_frontend_action.cc:443:7: error: ‘flags_’ was not declared in this scope
   if (flags_ & 0x4)
       ^
make[2]: *** [src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/b_frontend_action.cc.o] Error 1
make[1]: *** [src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by drzaeus77** [comment]
There must be some stale code hanging around somewhere. Did you try the usual suspects, like cleaning the build directory?

**Comment by brendangregg** [comment]
Yes, both make clean, and deleting the build directory...

```Shell
# cksum src/cc/frontends/clang/b_frontend_action.cc tests/cc/test_clang.py 
2865925912 18014 src/cc/frontends/clang/b_frontend_action.cc
4147208165 3547 tests/cc/test_clang.py
```

**Comment by drzaeus77** [comment]
That's indeed very odd. Nothing comes to mind...let me know how I might help. The build passed on both buildbots, with gcc4.8+ubuntu14.04 and clang+fedora22 variants, as well as my arch linux gcc 5.2 box.

**Comment by brendangregg** [comment]
Might have been an older clang (rebuilding). I get further on a newer built system:

```Shell
# ./disksnoop.py 
<bcc-memory-buffer>:24:51: error: cannot take the address of an rvalue of type 'u64' (aka 'unsigned long long')
        bpf_map_update_elem((void *)bpf_pseudo_fd(1, 3), &((u64)ctx->di), &ts, BPF_ANY);
                                                         ^ ~~~~~~~~~~~~
<bcc-memory-buffer>:33:60: error: use of undeclared identifier 'u'
        tsp = bpf_map_lookup_elem((void *)bpf_pseudo_fd(1, 3), &((u);
                                                                  ^
<bcc-memory-buffer>:43:2: error: expected '}'
}
 ^
<bcc-memory-buffer>:30:74: note: to match this '{'
int kprobe__blk_update_request(struct pt_regs *ctx, struct request *req) {
                                                                         ^
3 errors generated.
Traceback (most recent call last):
  File "./disksnoop.py", line 19, in <module>
    b = BPF(src_file="disksnoop.c")
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 349, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module disksnoop.c
```

Running:

```C
#include <uapi/linux/ptrace.h>
#include <linux/blkdev.h>

BPF_HASH(start, struct request *);

int kprobe__blk_start_request(struct pt_regs *ctx, struct request *req) {
	u64 ts;

	// stash start timestamp by request ptr
	ts = bpf_ktime_get_ns();
	start.update(&req, &ts);

	return 0;
}

int kprobe__blk_update_request(struct pt_regs *ctx, struct request *req) {
	u64 *tsp, delta;

	tsp = start.lookup(&req);

	if (tsp != 0) {
		delta = bpf_ktime_get_ns() - *tsp;
		bpf_trace_printk("%d %x %d\n", req->__data_len,
		    req->cmd_flags, delta / 1000);
		start.delete(&req);
	}

	return 0;
}
```

**Comment by drzaeus77** [comment]
This should have been fixed by this very commit. Have you done make install?

A new parameter with the recent changeset is BPF(..., debug=0x4) which will print the clang-rewritten source. If you see no output when providing that flag, then the old library is still being loaded.

**Comment by brendangregg** [comment]
debug=0x4 prints nothing new. I've done a fresh bcc build with https://raw.githubusercontent.com/iovisor/bcc/3c4a29ced84bea80b957d21256d529afb02eb634/src/cc/frontends/clang/b_frontend_action.cc ...

**Comment by drzaeus77** [comment]
Can you try from HEAD? There is a further fix that went in at 0ac26e8b65ffa7b2ca487796e97e686ffa2198be, as well the debug=0x4 flag requires a bunch of extra file changes to pass the flag to BFrontendAction.

**Comment by brendangregg** [comment]
I still can't see any debug code...

```Shell
# clang --version
clang version 3.8.0 (http://llvm.org/git/clang.git 93885ee97cd4a65cc773a654cb2d15b2890c81a2) (http://llvm.org/git/llvm.git 2354b37ae030104dd424149804946722fce72872)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /mnt/src/llvm/build/install/bin
```

**Comment by brendangregg** [comment]
Ok, back to the system I rebuilt clang on... that now works with disksnoop.c as listed previously. This works, thanks!

**Comment by drzaeus77** [comment]
Ok, closing then :)
