### ISSUE TITLE
Can't attach multiple functions to a kretprobe from the same process

### ISSUE THREAD

**Issue by myllynen** [iovisor/bcc#1921]
In issue #1631 it was reported that can't attach multiple functions to a kprobe from the same process. That issue has since then been fixed. However, it seems that this still does not work for kretprobe:

```
# cat ./test.py
#!/usr/bin/python3

from bcc import BPF

b1t = "int trace1(struct pt_regs *ctx) {return 0;}"
b2t = "int trace2(struct pt_regs *ctx) {return 0;}"

b1 = BPF(text=b1t)
execve_fnname = b1.get_syscall_fnname("execve")
b1.attach_kprobe(event=execve_fnname, fn_name="trace1")
b1.attach_kretprobe(event=execve_fnname, fn_name="trace1")
b2 = BPF(text=b2t)
execve_fnname = b2.get_syscall_fnname("execve")
b2.attach_kprobe(event=execve_fnname, fn_name="trace2")
b2.attach_kretprobe(event=execve_fnname, fn_name="trace2")

# python3 ./test.py
cannot attach kprobe, Device or resource busy
Traceback (most recent call last):
  File "./test.py", line 15, in <module>
    b2.attach_kretprobe(event=execve_fnname, fn_name="trace2")
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 598, in attach_kretprobe
    raise Exception("Failed to attach BPF to kretprobe")
Exception: Failed to attach BPF to kretprobe
```

This is on Fedora 28 with kernel 4.17 and bcc-0.6.0.

**Comment by yonghong-song** [comment]
It is a bcc issue. Just submitted a patch to fix. Please help take a look! Thanks!

**Comment by myllynen** [comment]
Confirmed, the fix works here, thanks a lot!
