### ISSUE TITLE
counts.increment(key, delta): too many arguments to function call

### ISSUE THREAD

**Issue by Lakshmipathi** [iovisor/bcc#1942]
I'm running on `4.19.0-0.rc0.git4.2.fc30.x86_64`  offcputime scripts errors out like:
So far other scripts seem to be working fine. Any thoughts whats wrong with this script?

```
 python tools/offcputime.py 
/virtual/main.c:55:27: error: too many arguments to function call, expected 1, have 2
    counts.increment(key, delta);
    ~~~~~~~~~~~~~~~~      ^~~~~
1 error generated.
Traceback (most recent call last):
  File "tools/offcputime.py", line 235, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 318, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text
```

**Comment by Lakshmipathi** [comment]
Yes, `./tools/wakeuptime.py` also  produces same error message.

**Comment by yonghong-song** [comment]
Could you post the complete steps about how to reproduce the issue? I would like to get this issue resolved soon as we can tag a release for bcc.

**Comment by Lakshmipathi** [comment]
Sorry for the delay. Here is the steps I used on Fedora-27. 

```
dnf config-manager --add-repo=http://alt.fedoraproject.org/pub/alt/rawhide-kernel-nodebug/fedora-rawhide-kernel-nodebug.repo
dnf update
reboot
echo -e '[iovisor]\nbaseurl=https://repo.iovisor.org/yum/main/f27/$basearch\nenabled=1\ngpgcheck=0' | sudo tee /etc/yum.repos.d/iovisor.repo
dnf update
dnf --enablerepo=iovisor install bcc-tools kernel-devel kernel-headers



```
Now clone bcc tools then run '/tools/wakeuptime.py'

**Comment by Lakshmipathi** [comment]
thanks for the details. I think this can be closed.
