### ISSUE TITLE
error matching many kprobes (eg, "tcp*")

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#199]
I can can attach kprobes to "vfs_.\*" successfully, but not "tcp_.\*".

```Shell
# ./funccount 'vfs_*'
Tracing... Ctrl-C to end.
^C
ADDR             FUNC                          COUNT
ffffffff811e8d71 vfs_fstat                        22
ffffffff811e8dd1 vfs_fstatat                      42
ffffffff811e4381 vfs_write                        58
ffffffff811e8c71 vfs_getattr_nosec                63
ffffffff811e8d41 vfs_getattr                      63
ffffffff811e4251 vfs_read                         91
ffffffff811e3221 vfs_open                        108

# ./funccount 'tcp_*'
write(kprobe_events): Invalid argument
Traceback (most recent call last):
  File "./funccount", line 84, in <module>
    b.attach_kprobe(event_re=pattern, fn_name="trace_count")
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 485, in attach_kprobe
    cpu=cpu, group_fd=group_fd)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 494, in attach_kprobe
    raise Exception("Failed to attach BPF to kprobe")
Exception: Failed to attach BPF to kprobe
```

This is using funccount, which is a port of my simple but useful ftrace function profiling tool of the same name. That original tool had some limitations, eg, it could not match a PID (set_ftrace_pid was ignored, likely due to a bug). This bcc/eBPF tool can fix that issue and more.

funcount:

```Python
#!/usr/bin/python
#
# funccount	Count kernel function calls.
#		For Linux, uses BCC, eBPF. See .c file.
#
# USAGE: funccount [-h] [-p PID] [-i INTERVAL] [-t TOP] [-T] [-r] pattern
#
# The pattern is a string with optional '*' wildcards, similar to file globbing.
# If you'd prefer to use regular expressions, use the -r option.
#
# Copyright (c) 2015 Brendan Gregg.
# Licensed under the Apache License, Version 2.0 (the "License")
#
# 09-Sep-2015	Brendan Gregg	Created this.

from __future__ import print_function
from bcc import BPF
from time import sleep, strftime
import argparse
import re

# arguments
examples = """examples:
    ./funccount 'tcp_*'         # count kernel functions starting with "tcp"
    ./funccount 'vfs_*'         # count kernel functions starting with "vfs"
    ./funccount -r '^vfs.*'     # same as above, using regular expressions
    ./funccount -Ti 5 'vfs_*'   # output every 5 seconds, with timestamps
    ./funccount -p 185 'vfs_*'  # count vfs calls for PID 181 only
"""
parser = argparse.ArgumentParser(
	description="Count kernel function calls",
	formatter_class=argparse.RawDescriptionHelpFormatter,
	epilog=examples)
parser.add_argument("-p", "--pid",
	help="Trace this PID only")
parser.add_argument("-i", "--interval", default=99999999,
	help="Summary interval, seconds")
parser.add_argument("-t", "--top",
	help="Show top number, count")
parser.add_argument("-T", "--timestamp", action="store_true",
	help="Include timestamp on output")
parser.add_argument("-r", "--regexp", action="store_true",
	help="Use regular expressions. Default is \"*\" wildcards only.")
parser.add_argument("pattern",
	help="search expression for kernel functions")
args = parser.parse_args()
pattern = args.pattern
if not args.regexp:
	pattern = pattern.replace('*', '.*')
	pattern = '^' + pattern + '$'
debug = 1

# load BPF program
bpf_text = """
#include <uapi/linux/ptrace.h>

struct key_t {
	u64 ip;
};
BPF_HASH(counts, struct key_t);

int trace_count(struct pt_regs *ctx) {
	FILTER_START
	struct key_t key = {};
	u64 zero = 0, *val;
	key.ip = ctx->ip;
	val = counts.lookup_or_init(&key, &zero);
	(*val)++;
	FILTER_DONE
	return 0;
}
"""
if args.pid:
	bpf_text = bpf_text.replace('FILTER_START',
	    ('u32 pid; pid = bpf_get_current_pid_tgid(); ' +
	    'if (pid == %s) {') % (args.pid))
	bpf_text = bpf_text.replace('FILTER_DONE', '}')
else:
	bpf_text = bpf_text.replace('FILTER_START', '')
	bpf_text = bpf_text.replace('FILTER_DONE', '')
if debug:
	print(bpf_text)
b = BPF(text=bpf_text)
b.attach_kprobe(event_re=pattern, fn_name="trace_count")

# header
print("Tracing... Ctrl-C to end.")

# output
exiting = 0 if args.interval else 1
while (1):
	try:
		sleep(int(args.interval))
	except KeyboardInterrupt:
		exiting=1

	print()
	if args.timestamp:
		print("%-8s\n" % strftime("%H:%M:%S"), end="")

	print("%-16s %-26s %8s" % ("ADDR", "FUNC", "COUNT"))
	counts = b.get_table("counts")
	for k, v in sorted(counts.items(), key=lambda counts: counts[1].value):
		print("%-16x %-26s %8d" % (k.ip, b.ksym(k.ip), v.value))
	counts.clear()

	if exiting:
		exit()
```

USAGE:

```Shell
# ./funccount -h
usage: funccount [-h] [-p PID] [-i INTERVAL] [-t TOP] [-T] [-r] pattern

Count kernel function calls

positional arguments:
  pattern               search expression for kernel functions

optional arguments:
  -h, --help            show this help message and exit
  -p PID, --pid PID     Trace this PID only
  -i INTERVAL, --interval INTERVAL
                        Summary interval, seconds
  -t TOP, --top TOP     Show top number, count
  -T, --timestamp       Include timestamp on output
  -r, --regexp          Use regular expressions. Default is "*" wildcards
                        only.

examples:
    ./funccount 'tcp_*'         # count kernel functions starting with "tcp"
    ./funccount 'vfs_*'         # count kernel functions starting with "vfs"
    ./funccount -r '^vfs.*'     # same as above, using regular expressions
    ./funccount -Ti 5 'vfs_*'   # output every 5 seconds, with timestamps
    ./funccount -p 185 'vfs_*'  # count vfs calls for PID 181 only
```

Now to get it to work on more than just vfs*. :)

The ftrace function profiling version does do this ok, eg:

```Shell
# /apps/perf-tools/bin/funccount 'tcp*'
Tracing "tcp*"... Ctrl-C to end.
^C
FUNC                              COUNT
tcp_tasklet_func                      1
tcp_tsq_handler.part.31               1
tcp_write_timer                       2
tcp_write_timer_handler               2
tcp_delack_timer                      5
tcp_delack_timer_handler              5
tcp_cleanup_rbuf                      6
tcp_event_data_recv                   6
tcp_queue_rcv                         6
tcp_rcv_space_adjust                  6
tcp_recvmsg                           6
tcp_send_delayed_ack                  6
tcp_event_new_data_sent              11
tcp_init_tso_segs                    11
tcp_nagle_check                      11
tcp_options_write                    11
tcp_push                             11
tcp_sendmsg                          11
tcp_send_mss                         11
tcp_transmit_skb                     11
tcp_v4_send_check                    11
tcp_wfree                            11
tcp_write_xmit                       11
tcp_current_mss                      12
tcp_data_queue                       14
tcp_urg                              14
tcp_validate_incoming                14
tcp_ack                              15
tcp_check_space                      15
tcp4_gro_receive                     16
tcp_gro_receive                      16
tcp_parse_aligned_timestamp.pa       16
tcp_parse_md5sig_option              16
tcp_prequeue                         16
tcp_rcv_established                  16
tcp_schedule_loss_probe              16
tcp_v4_do_rcv                        16
tcp_v4_early_demux                   16
tcp_v4_rcv                           16
tcp_release_cb                       17
tcp_established_options              23
tcp_v4_md5_lookup                    23
tcp_rearm_rto                        31
tcp_md5_do_lookup                    39
tcp_poll                             49

Ending tracing...
```

**Comment by brendangregg** [comment]
I think it doesn't like matching functions like "tcp_kmemdup_sysctl_table.isra.9.part.10".

Just matching alphabet and underscores (bcc version):

```Shell
# ./funccount -r '^tcp_[a-z_]*$'
Tracing... Ctrl-C to end.
^C
ADDR             FUNC                          COUNT
ffffffff816c01f1 tcp_validate_incoming             6
ffffffff816d08b1 tcp_gro_receive                   6
ffffffff816c8001 tcp_write_timer                  10
ffffffff816c7e31 tcp_write_timer_handler          10
ffffffff816c5921 tcp_send_ack                     10
ffffffff816c7641 tcp_delack_timer                 12
ffffffff816c7471 tcp_delack_timer_handler         12
ffffffff816bb5e1 tcp_queue_rcv                    23
ffffffff816b44f1 tcp_prequeue_process             24
ffffffff816ba321 tcp_urg                          26
ffffffff816bdb91 tcp_data_queue                   26
ffffffff816c6c81 tcp_send_delayed_ack             38
ffffffff816cafc1 tcp_prequeue                     42
ffffffff816bda61 tcp_rcv_space_adjust             43
ffffffff816bb2a1 tcp_event_data_recv              43
ffffffff816c3f11 tcp_write_xmit                   44
ffffffff816c3061 tcp_current_mss                  44
ffffffff816c3251 tcp_schedule_loss_probe          44
ffffffff816c1db1 tcp_init_tso_segs                44
ffffffff816b76c1 tcp_sendmsg                      44
ffffffff816c2341 tcp_event_new_data_sent          44
ffffffff816c1d61 tcp_nagle_check                  44
ffffffff816c2871 tcp_wfree                        44
ffffffff816bb721 tcp_check_space                  46
ffffffff816bee61 tcp_ack                          46
ffffffff816b54e1 tcp_recvmsg                      51
ffffffff816b3ee1 tcp_send_mss                     52
ffffffff816b3dc1 tcp_push                         52
ffffffff816c2111 tcp_options_write                54
ffffffff816c3581 tcp_transmit_skb                 54
ffffffff816c04a1 tcp_rcv_established              56
ffffffff816b64a1 tcp_poll                         61
ffffffff816b3fb1 tcp_cleanup_rbuf                 75
ffffffff816c1f01 tcp_established_options          98
ffffffff816c4e11 tcp_release_cb                  107
ffffffff816bec01 tcp_rearm_rto                   130
```

**Comment by brendangregg** [comment]
... as a test case, this should work: ./funccount '*'

**Comment by drzaeus77** [comment]
Made some progress on this, but the ./funccount '*' case is going to be super slow from what I can tell. Many minutes to attach all of the events. What would be a useful benchmark in your mind for how long it should take to attach all 36000 events.

**Comment by brendangregg** [comment]
15 seconds would be bearable. It's not a common case; usually it's a subset like vfs, tcp, blk, bio, etc.

**Comment by brendangregg** [comment]
Oh, you said many minutes... Well, if vfs, tcp, blk, bio, sys, SyS, and ext4, can be matched in the order of seconds, then this tool will work for almost all use cases.

If I'm counting everything, I'm pretty desperate, and can wait a while. Or use the ftrace function profiler.

**Comment by drzaeus77** [comment]
As a for instance, '^tcp_*' took 2 seconds to startup and 15 seconds to tear down, and '*' took a couple minutes to reach to 6k probes (out of ~37k available) before I killed it, and then it took even longer to clean up (and spent some time [defunct] just to entertain itself). I'm briefly exploring if there is a way to batch it before sending out the code that I have so far.

**Comment by brendangregg** [comment]
works, thanks!

**Comment by brendangregg** [comment]
PS. I'm going to catch ctrl-C on funccount to prevent people quitting during cleanup, which otherwise leaves kprobes attached...
