### ISSUE TITLE
cannot attach kprobe in kernel 4.19

### ISSUE THREAD

**Issue by egggHang** [iovisor/bcc#2071]
HI  BCC,
I got this error when run execsnoop and killsnoop in Centos 7 and Debian 9 with kernel 4.19, but everything is fine with the 4.18 one: 
```
cannot attach kprobe, probe entry may not exist
Traceback (most recent call last):
  File "./execsnoop", line 168, in <module>
    b.attach_kprobe(event=execve_fnname, fn_name="syscall__execve")
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 606, in attach_kprobe
    (fn_name, event))
Exception: Failed to attach BPF program syscall__execve to kprobe sys_execve
```
I found this function called by _bpf_try_perf_event_open_with_probe_ in src/cc/libbpf.c failed, and the errer number is 2:
 _syscall(__NR_perf_event_open, &attr, pid, cpu, -1 /* group_fd */, PERF_FLAG_FD_CLOEXEC);_

Any idea why this might happen?

Thank you

**Comment by yonghong-song** [comment]
The error number 2 is ENOENT.
```
#define ENOENT           2      /* No such file or directory */
```
Even if `bpf_try_perf_event_open_with_probe` failed, libbpf should still try to use debugfs based approach, do you know why it does not work?
Could you check whether there exists any kernel message for the error (dmesg output)?
Could you attach you config file here so in case further debug is needed?

**Comment by yonghong-song** [comment]
On Tue, Dec 11, 2018 at 3:25 AM egggHang <notifications@github.com> wrote:

> Sorry for my late reply.
>
>    1.
>
>    I find when bpf_try_perf_event_open_with_probe failed as stated above,
>    the code tries to open the file /sys/kernel/debug/tracing/kprobe_events
>    using the function kfd = open(buf, O_WRONLY | O_APPEND, 0), which
>    succeeds , and the *fd* is 5. But code failed to write p:kprobes/p_sys_execve_bcc_19099
>    sys_execve into the same file using write(kfd, buf, strlen(buf), the
>    errno is ENOENT, so the whole bpf_attach_kprobe returns -1. The
>    problem is why it failed to write.
>
>
For 4.19, the function name `sys_execve` is wrong.  The execsnoop.py or
killsnoop.py should find the syscall func name
__x64_sys_execve instead. Did you use an old bcc installation? Could you
check whether your execsnoop.py has the
following code?

```
b = BPF(text=bpf_text)
execve_fnname = b.get_syscall_fnname("execve")
b.attach_kprobe(event=execve_fnname, fn_name="syscall__execve")
b.attach_kretprobe(event=execve_fnname, fn_name="do_ret_sys_execve")
```

If the problem still exists, could you check why get_syscall_fnname() did
not return correct function name __x64_sys_execve?

**Comment by egggHang** [comment]
> For 4.19, the function name `sys_execve` is wrong.  The execsnoop.py or
> killsnoop.py should find the syscall func name
> __x64_sys_execve instead. Did you use an old bcc installation? Could you
> check whether your execsnoop.py has the
> following code?
> 
> ```
> b = BPF(text=bpf_text)
> execve_fnname = b.get_syscall_fnname("execve")
> b.attach_kprobe(event=execve_fnname, fn_name="syscall__execve")
> b.attach_kretprobe(event=execve_fnname, fn_name="do_ret_sys_execve")
> ```
The version of bcc I am using is 0.7.0  released on  5 Sep, which does have the code above.
And I run bcc on an aarch64 device. In fact, in CentOS/Debian with 4.18 kernel, The execsnoop.py or
 killsnoop.py also find the syscal func name sys_execve, and everything goes well, does it use __x64_sys_execve  from kernel 4.19?  BTW, even if I fix the variable `execve_fnname` to `__x64_sys_execve`, the program ends up the same error in kernel 4.19, am I doing the right way?

**Comment by yonghong-song** [comment]
> In fact, in CentOS/Debian with 4.18 kernel, the execsnoop.py or killsnoop.py also find the syscall func name sys_execve, and everything goes well, does it use __x64_sys_execve from kernel 4.19?

Right in 4.18, it should be sys_execve and in 4.19, it will be __x64_sys_execve.

> BTW, even if I fix the variable execve_fnname to __x64_sys_execve, the program ends up the same error in kernel 4.19, am I doing the right way?

I did not spot any issues. May need to reproduce first to see what is the reason.
Do you have issues with other kprobe functions other than sys_*?

**Comment by egggHang** [comment]
> Do you have issues with other kprobe functions other than sys_*?
Other kprobe functions like  `mark_buffer_dirty (cachestat)、do_sys_open（opensnoop）、blk_account_io_start(biosnoop)` work well, but functions like `sys_sync 、sys_execve、 sys_kill ` fails.

And I am using an Arm64 device , will it matter?

**Comment by egggHang** [comment]
Ohh,  the right kprobe functions of `__arm64_sys_`*, when I modify this, the tool works well. 
And I wonder why the functions `get_syscall_fnname` get the wrong one.

**Comment by palmtenor** [comment]
Because the prefix is hard-coded https://github.com/iovisor/bcc/blob/master/src/python/bcc/__init__.py#L170

**Comment by egggHang** [comment]
> Because the prefix is hard-coded https://github.com/iovisor/bcc/blob/master/src/python/bcc/__init__.py#L170

That's it.  Adding an arm64 prefix like `b"__arm64_sys_"` in  `_syscall_prefixes` in __init__.py  solved this.

Thank you for all your help ~ @yonghong-song  @palmtenor

**Comment by egggHang** [comment]
@yonghong-song  I‘d like to, but need some try to do this. Just not familiar how to do it.

**Comment by yonghong-song** [comment]
The link below has some information about how to create a pull request
https://help.github.com/articles/creating-a-pull-request/
Maybe you can follow the guide there?
