### ISSUE TITLE
softirqs fails to print histogram of distributions

### ISSUE THREAD

**Issue by boat0** [iovisor/bcc#2154]
I encountered the following err with bcc v0.8.0:

    root@debian:~/bcc/tools# ./softirqs.py -d
    Tracing soft irq event time... Hit Ctrl-C to end.
    ^C
    Traceback (most recent call last):
      File "./softirqs.py", line 144, in <module>
        dist.print_log2_hist(label, "softirq", section_print_fn=vec_to_name)
      File "/usr/local/lib/python2.7/dist-packages/bcc/table.py", line 326, in print_log2_hist
        vals[slot] = v.value
    TypeError: list indices must be integers, not str

I looked through softirqs.py and found no obvious bug. Maybe a bug in table.py?

**Comment by boat0** [comment]
Turns out when a struct S is used as key to a BPF_HISTOGRAM, table.py expects the second member of S is holding the slot. But when S is converted to python from bpf C, a padding may be inserted as a second member of S. table.py doesn't check the possible padding and print_log2_hist() is broken.

**Comment by boat0** [comment]
A quick fix is skipping the possible padding member in tables.py.
I am just wondering if we could remove the padding from the start.

**Comment by boat0** [comment]
#2155
