### ISSUE TITLE
kprobe function wrapping error

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#217]
Having issues wrapping a static function in a kprobe'd function. test.py:

```Python
#!/usr/bin/python

from bcc import BPF

b = BPF(text = '''
#include <uapi/linux/ptrace.h>
#include <linux/blkdev.h>
#include <linux/mount.h>

BPF_HASH(start, u32);
BPF_HASH(filebypid, u32, struct dentry *);

static int trace_process(struct pt_regs *ctx, struct file *file)
{
    u64 ts;
    u32 pid;

    pid = bpf_get_current_pid_tgid();

    // map pid to dentry pointer, for later filename lookups
    if (file != NULL && file->f_path.dentry != NULL){
        struct dentry *dent = file->f_path.dentry;
        filebypid.update(&pid, &dent);
    } else {
        // cleanup now (see return)
        filebypid.delete(&pid);
    }

    // save start timestamp
    ts = bpf_ktime_get_ns();
    start.update(&pid, &ts);
    return 0;
}

int trace_readpages_entry(struct pt_regs *ctx, struct file *file)
{
    return trace_process(ctx, file);
}
''')
b.attach_kprobe(event="ext4_readpages", fn_name="trace_readpages_entry")
```

output:

```Shell
bpf: Permission denied
0: (79) r6 = *(u64 *)(r1 +112)
1: (85) call 14
2: (63) *(u32 *)(r10 -12) = r0
3: (15) if r6 == 0x0 goto pc+12
 R0=inv R6=inv R10=fp
4: (79) r1 = *(u64 *)(r6 +24)
R6 invalid mem access 'inv'

Traceback (most recent call last):
  File "./ext4slower", line 193, in <module>
    b.attach_kprobe(event="ext4_readpages", fn_name="trace_readpages_entry")
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 498, in attach_kprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 388, in load_func
    raise Exception("Failed to load BPF program %s" % func_name)
Exception: Failed to load BPF program trace_readpages_entry
```

Note the exception is for trace_readpages_entry(), which is pretty simple.

**Comment by brendangregg** [comment]
Oh, if I remove static from trace_process() it works...

**Comment by drzaeus77** [comment]
Hmmm, that's definitely weird. How about static inline?

**Comment by brendangregg** [comment]
static inline didn't work.

**Comment by drzaeus77** [comment]
Ah, I get it. Keeping the static keyword there is tricking the rewriter to work for now. Will try to clean this up, but let me know if this is blocking you and I will prioritize.

**Comment by brendangregg** [comment]
Ok, thanks, this is not blocking me.

**Comment by drzaeus77** [comment]
I believe this is fixed, closing.
