### ISSUE TITLE
bcc tools sslsniff fails

### ISSUE THREAD

**Issue by sereysethy** [iovisor/bcc#2193]
Hi,

I am new to bcc, I tested various tools provided by bcc tools, I could only run `opensnoop` without any errors. My goal is to do something similar to`sslsniff`, to capture activities during an ssl session, but `sslsniff` did not work. Can anyone tell me what might be the problems?

- OS: `Linux ubuntu1604 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- I installed bcc by following the INSTALL page, using `apt-get`.
- Command: `sslsniff`

Output
```bash
$ sudo python /usr/share/bcc/tools/sslsniff
Traceback (most recent call last):
  File "/usr/share/bcc/tools/sslsniff", line 157, in <module>
    pid=args.pid or -1)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 982, in attach_uprobe
    (path, addr) = BPF._check_path_symbol(name, sym, addr, pid)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 727, in _check_path_symbol
    raise Exception("could not determine address of symbol %s" % symname)
Exception: could not determine address of symbol PR_Write
```

**Comment by yonghong-song** [comment]
```
156     b.attach_uprobe(name="nspr4", sym="PR_Write", fn_name="probe_SSL_write",
157                     pid=args.pid or -1)
```
It cannot find library `libnspr4.{a,so}`. You can add `--no-nss` which will prevent attaching those nspr4 library symbols.

**Comment by stafot** [comment]
Getting similar error with `gethostlatency` on Amazon Linux/2 on php processes, works on some other.

**Comment by xxradar** [comment]
Hi, similar error

sudo ./sslsniff -p 2792
Traceback (most recent call last):
  File "./sslsniff", line 140, in <module>
    pid=args.pid or -1)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1005, in attach_uprobe
    (path, addr) = BPF._check_path_symbol(name, sym, addr, pid)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 745, in _check_path_symbol
    raise Exception("could not determine address of symbol %s" % symname)
Exception: could not determine address of symbol SSL_write
