### ISSUE TITLE
softirqs fails to run under Ubuntu 18.04

### ISSUE THREAD

**Issue by otherjason** [iovisor/bcc#2201]
With the latest nightly build for Ubuntu 18.04, running `softirqs` fails with the following error:

```
[user@host:~/git/bcc]$ /usr/share/bcc/tools/softirqs
/virtual/main.c:18:1: warning: declaration of 'struct tracepoint__irq__softirq_entry' will not be visible outside of this function [-Wvisibility]
TRACEPOINT_PROBE(irq, softirq_entry)
^
/virtual/include/bcc/helpers.h:805:46: note: expanded from macro 'TRACEPOINT_PROBE'
int tracepoint__##category##__##event(struct tracepoint__##category##__##event *args)
                                             ^
<scratch space>:207:1: note: expanded from here
tracepoint__irq__softirq_entry
^
/virtual/main.c:23:19: error: incomplete definition of type 'struct tracepoint__irq__softirq_entry'
    val.vec = args->vec;
              ~~~~^
/virtual/main.c:18:1: note: forward declaration of 'struct tracepoint__irq__softirq_entry'
TRACEPOINT_PROBE(irq, softirq_entry)
^
/virtual/include/bcc/helpers.h:805:46: note: expanded from macro 'TRACEPOINT_PROBE'
int tracepoint__##category##__##event(struct tracepoint__##category##__##event *args)
                                             ^
<scratch space>:207:1: note: expanded from here
tracepoint__irq__softirq_entry
^
/virtual/main.c:28:1: warning: declaration of 'struct tracepoint__irq__softirq_exit' will not be visible outside of this function [-Wvisibility]
TRACEPOINT_PROBE(irq, softirq_exit)
^
/virtual/include/bcc/helpers.h:805:46: note: expanded from macro 'TRACEPOINT_PROBE'
int tracepoint__##category##__##event(struct tracepoint__##category##__##event *args)
                                             ^
<scratch space>:213:1: note: expanded from here
tracepoint__irq__softirq_exit
^
2 warnings and 1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/softirqs", line 120, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 323, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text
```

**Comment by yonghong-song** [comment]
Typically, this means the tracepoint path `/sys/kernel/debug/tracing/events/irq/softirq_entry` does not exist. That is, the bcc cannot find the tracepoint `irq:softirq_entry`. could you check whether this is the case?

**Comment by otherjason** [comment]
You're right, this was the issue. I'm embarrassed to report that I had just failed to run the script as `root`, so I didn't have permissions to read `/sys/kernel/debug/` and below. When executing `softirqs` as root, it runs fine. Thanks for your help.
