### ISSUE TITLE
undefined symbol: bpf_perf_event_fields

### ISSUE THREAD

**Issue by weixingsun** [iovisor/bcc#2222]
Hi me again, just compiled latest git, but failed to run a test now
perf is working properly, what else packages needed for my ubuntu 18.04 ?

------
sudo /usr/local/share/bcc/tools/syscount
Traceback (most recent call last):
  File "/usr/local/share/bcc/tools/syscount", line 18, in <module>
    from bcc import BPF
  File "/usr/local/lib/python2.7/dist-packages/bcc/__init__.py", line 27, in <module>
    from .libbcc import lib, bcc_symbol, bcc_symbol_option, bcc_stacktrace_build_id, _SYM_CB_TYPE
  File "/usr/local/lib/python2.7/dist-packages/bcc/libbcc.py", line 68, in <module>
    lib.bpf_perf_event_fields.restype = ct.c_ulonglong
  File "/usr/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_perf_event_fields

**Comment by yonghong-song** [comment]
`bpf_perf_event_fields` was introduced to bcc just last week. Most likely this is due to mismatch between source based installation and package based installation, different versions of source installation, etc. Maybe you want to do a clean up and then a clean install?

**Comment by weixingsun** [comment]
Thanks, I update and rebuild fix it.
