### ISSUE TITLE
fileslower 0 cause error info loop

### ISSUE THREAD

**Issue by justlooks** [iovisor/bcc#2235]
this can not be stop until I type "kill -9"

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/lib/python2.7/site-packages/bcc/table.py", line 650, in raw_cb_
    callback(cpu, data, size)
  File "./fileslower", line 229, in print_event
    if event.name_len > DNAME_INLINE_LEN:
NameError: global name 'DNAME_INLINE_LEN' is not defined
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/lib/python2.7/site-packages/bcc/table.py", line 650, in raw_cb_
    callback(cpu, data, size)
  File "./fileslower", line 229, in print_event
    if event.name_len > DNAME_INLINE_LEN:
NameError: global name 'DNAME_INLINE_LEN' is not defined
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/lib/python2.7/site-packages/bcc/table.py", line 650, in raw_cb_
    callback(cpu, data, size)
  File "./fileslower", line 229, in print_event
    if event.name_len > DNAME_INLINE_LEN:
NameError: global name 'DNAME_INLINE_LEN' is not defined

**Comment by mcaleavya** [comment]
Hey

What kernel and OS are you running?  and version of bcc?

Al

**Comment by mcaleavya** [comment]
ok I can see this with the latest version of bcc

root@henky:~/bcc/tools# ./fileslower.py 1
Tracing sync read/writes slower than 1 ms
TIME(s)  COMM           TID    D BYTES   LAT(ms) FILENAME
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/bcc/table.py", line 650, in raw_cb_
    callback(cpu, data, size)
  File "./fileslower.py", line 229, in print_event
    if event.name_len > DNAME_INLINE_LEN:
NameError: global name 'DNAME_INLINE_LEN' is not defined

I am not sure as to why this is failing now as compared to previously -
but declaring DNAME_INLINE_LEN to be say 32 as a python variable resolves
the issue - happy to do a pull request but would like to understand the
failure more as this was showing as working on previous versions where I
had a file > 32 chars it was limited and appended with dots.


root@henky:~/bcc/tools# ./fileslower.py 1
Tracing sync read/writes slower than 1 ms
TIME(s)  COMM           TID    D BYTES   LAT(ms) FILENAME
3.268    prometheus     1285   W 3123       1.96 45030fed915769.db
13.267   prometheus     1285   W 3123       1.73 47f09950ff0807.db
23.274   prometheus     1351   W 3123       7.73 47fc9950ff014b.db
33.268   prometheus     1351   W 3123       1.93 5a665c3eabcb2c.db

Al

**Comment by arighi** [comment]
I think 51d62d36bd072530a238ac147a61b631fdc44659 broke it.

**Comment by mcaleavya** [comment]
Thanks I was wondering this morning where the ctype structures went but didn’t have a lot of time to investigate further 

Al

**Comment by boat0** [comment]
Fixed by #2236 . 
Thanks!

**Comment by boat0** [comment]
> Thanks I was wondering this morning where the ctype structures went but didn’t have a lot of time to investigate further Al

https://github.com/iovisor/bcc/commit/3156303439960602667b2e1dc05aebfe43ad0066
