### ISSUE TITLE
Using get_pid_task in general.

### ISSUE THREAD

**Issue by BenSimsCitrix** [iovisor/bcc#2348]
I have extracted a pid from a file and would like to find the task associated with it by calling something akin to get_pid_task.

I know that bpf calls get_pid_task in a restricted way in bpf_task_fd_query, but I can't find a more generalized method.

What's the most bcc like way of doing this?

If it does not exist id be happy to add the functionality.

**Comment by yonghong-song** [comment]
What is your use case? I mean what do you do with the task structure for that pid? It would be a little bit tricky to get/maintain task structure for the pid as pid may be gone, pid may be reused , or the task associated with pid may be in a weird state (e.g., to be deleted and some field may not be even valid), or you will have race with somebody to read/write to that pid/task's fields.

**Comment by BenSimsCitrix** [comment]
I would like to make a generalized tool to find the owners of block devices. Fuser can work for some pathologies but not for example if there is an lvm volume on the device.

blkdev_open will return EBUSY if there is a device holder

inode->i_bdev->bd_holder

I can get the "struct pid" of holder and would like to convert it to the task. I think we can avoid some of the problems you mention above because this is the "struct pid"

https://elixir.bootlin.com/linux/v2.6.21.5/source/include/linux/pid.h

Unless im miss understanding the comments at the top of this header file :)

**Comment by yonghong-song** [comment]
I guess you may not need a helper. Just tracing pointers may get the task structure based on a pid structure
```
struct task_struct *pid_task(struct pid *pid, enum pid_type type)
{
        struct task_struct *result = NULL;
        if (pid) {
                struct hlist_node *first;
                first = rcu_dereference_check(hlist_first_rcu(&pid->tasks[type]),
                                              lockdep_tasklist_lock_is_held());
                if (first)
                        result = hlist_entry(first, struct task_struct, pid_links[(type)]);
        }
        return result;
}
```
Here, the pid_type should be PIDTYPE_PID.

**Comment by BenSimsCitrix** [comment]
Great, that will work for the problem I'm trying to debug.

Long term, I think this should be hidden under a helper API. I can work on making a PR for this, just wanted to check I'm not violating any of the tenants of bcc philosophy :)

**Comment by yonghong-song** [comment]
It does not violate bcc philosophy. I think use case is not strong enough for upstream, esp. when we have a way to do that.

**Comment by chelei97** [comment]
i tried function pid_task in bcc/tools/bashreadline.py, modified it like this
`#include <uapi/linux/ptrace.h>
#include <linux/sched.h>
#include <linux/pid.h>

struct str_t {
    u32 pid;
    char str[80];
};

BPF_PERF_OUTPUT(events);

int printret(struct pt_regs *ctx) {
    struct str_t data  = {};
    char comm[TASK_COMM_LEN] = {};
    if (!PT_REGS_RC(ctx))
        return 0;
    data.pid = bpf_get_current_pid_tgid() >> 32;
    bpf_probe_read_user(&data.str, sizeof(data.str), (void *)PT_REGS_RC(ctx));

    struct pid *pid_struct = find_vpid(data.pid);
    if (!pid_struct) {
        return 0;
    }
    struct task_struct *task = pid_task(find_vpid(data.pid), PIDTYPE_PID);

    bpf_get_current_comm(&comm, sizeof(comm));
    if (comm[0] == 'b' && comm[1] == 'a' && comm[2] == 's' && comm[3] == 'h' && comm[4] == 0 ) {
        events.perf_submit(ctx,&data,sizeof(data));
    }


    return 0;
};`
Then i run it, but failed, it shows that:
`bpf: Failed to load program: Invalid argument
jump out of range from insn 16 to 53
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

Traceback (most recent call last):
  File "/root/bcc/tools/bashreadline.py", line 73, in <module>
    b.attach_uretprobe(name=name, sym="readline", fn_name="printret")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1179, in attach_uretprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 411, in load_func
    raise Exception("Failed to load BPF program %s: %s" %
Exception: Failed to load BPF program b'printret': Invalid argument`
Is it not supported now?
