### ISSUE TITLE
libbpf.so not installed on Ubuntu 19.04

### ISSUE THREAD

**Issue by DoctorSher** [iovisor/bcc#2381]
On a clean install of Ubuntu 19.04, I installed the linux headers for the running kernel (5.0.0-15-generic) and `bpfcc-tools` using apt. Installing `bpfcc-tools` brings in a number of other packages, most importantly `libbpfcc`. 

Walking through the python developer's tutorial, the example `hello_perf_output.py` fails with the following error:
```
adam@xdp-vm:~/bpf/bcc/examples/tracing$ sudo ./hello_perf_output.py 
TIME(s)            COMM             PID    MESSAGE
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/bcc/table.py", line 572, in raw_cb_
    callback(cpu, data, size)
  File "./hello_perf_output.py", line 44, in print_event
    event = b["events"].event(data)
AttributeError: 'PerfEventArray' object has no attribute 'event'
```
However, this should not be related to issue #2227 because there is no mismatched versioning / mixing of source and distro packages.

This error happens because the Ubuntu packages `bpfcc-tools` and `libbpfcc` do not install `libbpf.so`, which is necessary to run this example. I have attached a list of the installed files for each of these packages using `dpkg-query`, and we can see the only installed library is `/usr/lib/x86_64-linux-gnu/libbcc.so.0`.

If I purge the apt packages and install v0.9.0 of bcc from source, it correctly installs `libbpf.so` along with `libbcc.so`, and the example runs as expected.

Attached documents:
[dpkg_bpfcc.log](https://github.com/iovisor/bcc/files/3228448/dpkg_bpfcc.log)
[dpkg_libpfcc.log](https://github.com/iovisor/bcc/files/3228449/dpkg_libpfcc.log)

**Comment by DoctorSher** [comment]
On second thought, there was a version mismatch like Issue #2227. I was running compiled examples from source, against the installed packages. This is almost certainly the problem so I am closing the issue.
