### ISSUE TITLE
failures in a VM

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#239]
Just tried bcc in a VBox VM. Some scripts work (hello_world, syncsnoop), others fail. Eg:

```
root@ubuntu:~/bcc/examples> ./disksnoop.py 
<bcc-memory-buffer>:23:51: error: cannot take the address of an rvalue of type 'u64' (aka 'unsigned long long')
        bpf_map_update_elem((void *)bpf_pseudo_fd(1, 3), &((u64)ctx->di), &ts, BPF_ANY);
                                                         ^ ~~~~~~~~~~~~
<bcc-memory-buffer>:30:60: error: use of undeclared identifier 'u'
        tsp = bpf_map_lookup_elem((void *)bpf_pseudo_fd(1, 3), &((u);
                                                                  ^
<bcc-memory-buffer>:37:2: error: expected '}'
}
 ^
<bcc-memory-buffer>:27:65: note: to match this '{'
void trace_completion(struct pt_regs *ctx, struct request *req) {
                                                                ^
3 errors generated.
Traceback (most recent call last):
  File "./disksnoop.py", line 19, in <module>
    b = BPF(src_file="disksnoop.c")
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 349, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module disksnoop.c
root@ubuntu:~/bcc/examples> uname -a
Linux ubuntu 4.3.0-999-generic #201509202159 SMP Mon Sep 21 02:01:24 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
root@ubuntu:~/bcc/tools> ./opensnoop 
<bcc-memory-buffer>:12:64: error: use of undeclared identifier 'ct'
        bpf_map_update_elem((void *)bpf_pseudo_fd(1, 3), &pid, &((u64)ct, BPF_ANY);
                                                                      ^
<bcc-memory-buffer>:19:1: error: function definition is not allowed here
{
^
<bcc-memory-buffer>:34:2: error: expected '}'
}
 ^
<bcc-memory-buffer>:8:1: note: to match this '{'
{
^
3 errors generated.
Traceback (most recent call last):
  File "./opensnoop", line 80, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 349, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 
```

**Comment by drzaeus77** [comment]
Is this BCC built from source or .deb package?

**Comment by brendangregg** [comment]
I did a git clone of bcc, then a build of it.

**Comment by drzaeus77** [comment]
Something about the code being generated is not up to date. It should not be rewriting &req anymore. This is what I see when I add debug=0x4 to disksnoop.py:

```c
#include <uapi/linux/ptrace.h>
#include <linux/blkdev.h>

BPF_HASH(start, struct request *);

__attribute__((section(".bpf.fn.trace_start")))
void trace_start(struct pt_regs *ctx, struct request *req) {req = ctx->di;
        // stash start timestamp by request ptr
        u64 ts = bpf_ktime_get_ns();

        bpf_map_update_elem((void *)bpf_pseudo_fd(1, 3), &req, &ts, BPF_ANY);
}

__attribute__((section(".bpf.fn.trace_completion")))
void trace_completion(struct pt_regs *ctx, struct request *req) {req = ctx->di;
        u64 *tsp, delta;

        tsp = bpf_map_lookup_elem((void *)bpf_pseudo_fd(1, 3), &req);
        if (tsp != 0) {
                delta = bpf_ktime_get_ns() - *tsp;
                ({ char _fmt[] = "%d %x %d\n"; bpf_trace_printk_(_fmt, sizeof(_fmt), ({ typeof(unsigned int) _val; memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)req + offsetof(struct request, __data_len)); _val; }),
                    ({ typeof(u64) _val; memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)req + offsetof(struct request, cmd_flags)); _val; }), delta / 1000); });
                bpf_map_delete_elem((void *)bpf_pseudo_fd(1, 3), &req);
        }
}
```

Can you check for duplicate libbcc.so.* in /usr/lib

**Comment by brendangregg** [comment]
Ah, I'd checked /usr/lib but forget to check /usr/lib/x86...:

```Shell
root@ubuntu:~/bcc/examples> find /usr/lib -ls | grep libbcc
 51791    0 lrwxrwxrwx   1 root     root           11 Sep 21 12:32 /usr/lib/libbcc.so -> libbcc.so.0
 51822    4 -rw-r--r--   1 root     root          297 Sep 21 12:16 /usr/lib/pkgconfig/libbcc.pc
 85363    0 lrwxrwxrwx   1 root     root           11 Sep  2 22:07 /usr/lib/x86_64-linux-gnu/libbcc.so -> libbcc.so.0
 85364    0 lrwxrwxrwx   1 root     root           15 Sep  2 22:07 /usr/lib/x86_64-linux-gnu/libbcc.so.0 -> libbcc.so.0.1.6
 85355 32964 -rw-r--r--   1 root     root     33753656 Sep  2 22:07 /usr/lib/x86_64-linux-gnu/libbcc.so.0.1.6
 51790    0 lrwxrwxrwx   1 root     root           15 Sep 21 12:32 /usr/lib/libbcc.so.0 -> libbcc.so.0.1.6
 51789 43472 -rw-r--r--   1 root     root     44510611 Sep 21 12:31 /usr/lib/libbcc.so.0.1.6
```

Deleting the /usr/lib/x86... ones fixed it, thanks!

**Comment by brendangregg** [comment]
Oh, and:

```Shell
root@ubuntu:~/bcc/examples> history | grep libbcc
  462  sudo apt-get install libbcc libbcc-examples python-bcc
```

**Comment by drzaeus77** [comment]
Yeah, I haven't updated those packages in about a week, so they are out of
date and incompatible with the examples that are checked into github HEAD.
