### ISSUE TITLE
biosnoop,biolatency,xfsslower run failed at centos7.6.1810

### ISSUE THREAD

**Issue by fredchenbj** [iovisor/bcc#2413]
kernel: 3.10.0-957.21.2.el7.x86_64
centos: CentOS Linux release 7.6.1810

$ sudo ./biosnoop
```
Traceback (most recent call last):
  File "./biosnoop", line 159, in <module>
    if BPF.get_kprobe_functions(b'blk_start_request'):
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 528, in get_kprobe_functions
    with open("%s/../kprobes/blacklist" % TRACEFS, "rb") as blacklist_f:
IOError: [Errno 2] No such file or directory: '/sys/kernel/debug/tracing/../kprobes/blacklist'
```

$ sudo ./biolatency
```
Traceback (most recent call last):
  File "./biolatency", line 138, in <module>
    if BPF.get_kprobe_functions(b'blk_start_request'):
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 528, in get_kprobe_functions
    with open("%s/../kprobes/blacklist" % TRACEFS, "rb") as blacklist_f:
IOError: [Errno 2] No such file or directory: '/sys/kernel/debug/tracing/../kprobes/blacklist'
```

$ sudo ./xfsslower
```
/virtual/main.c:50:18: error: incomplete definition of type 'struct kiocb'
    val.fp = iocb->ki_filp;
             ~~~~^
/lib/modules/3.10.0-957.21.2.el7.x86_64/build/include/linux/fs.h:43:8: note: forward declaration of 'struct kiocb'
struct kiocb;
       ^
/virtual/main.c:51:22: error: incomplete definition of type 'struct kiocb'
    val.offset = iocb->ki_pos;
                 ~~~~^
/lib/modules/3.10.0-957.21.2.el7.x86_64/build/include/linux/fs.h:43:8: note: forward declaration of 'struct kiocb'
struct kiocb;
       ^
2 errors generated.
Traceback (most recent call last):
  File "./xfsslower", line 264, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 325, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text
```

**Comment by pchaigno** [comment]
Linux 4.1 is required to attach BPF programs to kprobes (see [`kernel-versions.md`](https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md#main-features)), so even if these issues were fixed, you wouldn't be able to run these three scripts. Unless you've backported the necessary patches to 3.10?

**Comment by fredchenbj** [comment]
@pchaigno Thanks for your reply. I wonder for centos 7.6 which kind of command is not supported ?

**Comment by fredchenbj** [comment]
I have run `opensnoop/execsnoop` etc, those works.

**Comment by pchaigno** [comment]
My bad. Looks like support for BPF kprobes was actually backported. Most likely, you're missing the backports for `/sys/kernel/debug/kprobes/blacklist`.

**Comment by fredchenbj** [comment]
the kernel 3.10.0-957.21.2.el7.x86_64 I used is mostly updated at May 28 2019, and no related patches is founded in  changelog of SPEC/kernel.spec. So maybe it is forgot by centos or redhat to backport this.

**Comment by mcaleavya** [comment]
[root@ut012109 local]# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)

[root]# /usr/share/bcc/tools/biosnoop
#TIME(s)        COMM           PID    DISK    T  SECTOR    BYTES   LAT(ms)
0.000000000    jbd2/dm-0-8    3953   sda     W  51239312  380928     3.08
0.000738000    jbd2/dm-0-8    3953   sda     W  51238288  524288     3.93
0.001339000    jbd2/dm-0-8    3953   sda     W  51240056  4096       0.40
0.124690000    ?              0              R  -1        8          0.18
2.172677000    ?              0              R  -1        8          0.15
4.220680000    ?              0              R  -1        8          0.15
6.268670000    ?              0              R  -1        8          0.14
8.316681000    ?              0              R  -1        8          0.17

[root]# /usr/share/bcc/tools/biolatency
Tracing block device I/O... Hit Ctrl-C to end.
^C
     usecs               : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 0        |                                        |
         4 -> 7          : 0        |                                        |
         8 -> 15         : 0        |                                        |
        16 -> 31         : 0        |                                        |
        32 -> 63         : 0        |                                        |
        64 -> 127        : 0        |                                        |
       128 -> 255        : 1        |****************************************|

biotop looks ok also.
13:42:20 loadavg: 0.00 0.01 0.05 2/169 41362

PID    COMM             D MAJ MIN DISK       I/O  Kbytes  AVGms

[root]# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
[rootl]# uname -a
Linux henky 3.10.0-957.12.1.el7.x86_64 #1 SMP Mon Apr 29 14:59:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

so looks ok from my side on a slightly earlier kernel , I have no xfs on this VM so cant check xfsslower.

**Comment by pchaigno** [comment]
@fredchenbj Looks like the [blacklist creation may fail in some cases](https://github.com/torvalds/linux/blob/2f4c53349961c8ca480193e47da4d44fdb8335a8/kernel/kprobes.c#L2240). Have you checked your system logs?

**Comment by fredchenbj** [comment]
@pchaigno When run those failed commands, this is no related system log. But there is an old log: "TECH PREVIEW: eBPF syscall may not be fully supported. Please review provided documentation for limitations" .

**Comment by palmtenor** [comment]
The BPF support in RHEL 7.6's back-ported Kernel is limited and not guaranteed. The `biosnoop/biolatency/biotop` failures are due to missing back-port of `blacklist` feature. You can manually remove the line from https://github.com/iovisor/bcc/blob/c36f5bf297e36e96fa5ce6899d9ba579ef782501/src/python/bcc/__init__.py#L528 and the tools should run. The `xfsslower` issue is due to Kernel struct missing / mismatched definition. I do not know what exactly is the state of XFS in the RHEL's back-ported 3.10 Kernel. You can look into the source code yourself~

**Comment by fredchenbj** [comment]
@palmtenor Thanks very much. Following your advice, `biosnoop/biolatency/biotop` works now.

**Comment by balasu** [comment]
@palmtenor, have the same error on centos7.6, pl suggest

[root@server1 ~]# biolatency 
Traceback (most recent call last):
  File "/usr/share/bcc/tools/biolatency", line 138, in <module>
    if BPF.get_kprobe_functions(b'blk_start_request'):
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 539, in get_kprobe_functions
    with open("%s/../kprobes/blacklist" % TRACEFS, "rb") as blacklist_f:
IOError: [Errno 2] No such file or directory: '/sys/kernel/debug/tracing/../kprobes/blacklist'

**Comment by palmtenor** [comment]
@balasu Have you tried aforementioned resolution then?

**Comment by balasu** [comment]
Hi have tried it by commenting below line, result is same error
with open("%s/../kprobes/blacklist" % TRACEFS, "rb") as blacklist_f:
