### ISSUE TITLE
BPF_PERF_OUTPUT in SOCKET_FILTER type 

### ISSUE THREAD

**Issue by phantooom** [iovisor/bcc#2423]
i want put all ip package info to user space use  BPF_PERF_OUTPUT. 
but my program doesn't work 

```
bpf: Failed to load program: Invalid argument
0: (bf) r6 = r1
1: (18) r7 = 0xffffffff
3: (28) r0 = *(u16 *)skb[12]
4: (55) if r0 != 0x800 goto pc+20
 R0=inv2048 R6=ctx(id=0,off=0,imm=0) R7=inv4294967295 R10=fp0
5: (30) r0 = *(u8 *)skb[23]
6: (55) if r0 != 0x6 goto pc+18
 R0=inv6 R6=ctx(id=0,off=0,imm=0) R7=inv4294967295 R10=fp0
7: (20) r0 = *(u32 *)skb[30]
8: (63) *(u32 *)(r10 -12) = r0
9: (20) r0 = *(u32 *)skb[26]
10: (63) *(u32 *)(r10 -16) = r0
11: (28) r0 = *(u16 *)skb[36]
12: (6b) *(u16 *)(r10 -6) = r0
13: (28) r0 = *(u16 *)skb[34]
14: (6b) *(u16 *)(r10 -8) = r0
15: (18) r2 = 0xffff9a343a8f3200
17: (bf) r4 = r10
18: (07) r4 += -16
19: (bf) r1 = r6
20: (18) r3 = 0xffffffff
22: (b7) r5 = 12
23: (85) call bpf_perf_event_output#25
unknown func bpf_perf_event_output#25

Traceback (most recent call last):
  File "tcpflow-test.py", line 60, in <module>
    function = bpf.load_func("tcp_monitor", BPF.SOCKET_FILTER)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 384, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program tcp_monitor: Invalid argument

```

os version:

`Linux ubuntu-bionic 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`

my code

```
# coding: utf-8
#! /usr/bin/python

from bcc import BPF
interface="enp0s3"
prog = """
#include <uapi/linux/ptrace.h>
#include <uapi/linux/if_packet.h>
#include <net/sock.h>
#include <bcc/proto.h>

#define IP_TCP 	6
#define ETH_HLEN 14

struct Key {
	u32 src_ip;               // source ip
	u32 dst_ip;               // destination ip
	unsigned short src_port;  // source port
	unsigned short dst_port;  // destination port
};


BPF_PERF_OUTPUT(events);

int tcp_monitor(struct pt_regs *ctx, struct __sk_buff *skb) {
	u8 *cursor = 0;

	struct ethernet_t *ethernet = cursor_advance(cursor, sizeof(*ethernet));
	// Only process IP packets (ethernet type = 0x0800)
	if (!(ethernet->type == 0x0800)) {
		return -1;
	}
	struct ip_t *ip = cursor_advance(cursor, sizeof(*ip));
	// Only process TCP packets (ip next protocol = 0x06)
	if (ip->nextp != IP_TCP) {
		return -1;
	}
	struct tcp_t *tcp = cursor_advance(cursor, sizeof(*tcp));

	struct Key key;
	key.dst_ip = ip->dst;
	key.src_ip = ip->src;
	key.dst_port = tcp->dst_port;
	key.src_port = tcp->src_port;
	events.perf_submit(ctx, &key, sizeof(key));

	return 0;
}
"""

bpf = BPF(text=prog, debug = 0)
function = bpf.load_func("tcp_monitor", BPF.SOCKET_FILTER)
BPF.attach_raw_socket(function, interface)
while 1:
    print ("---------------")


```

in doc: https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#3-perf_submit

`For SCHED_CLS or SOCKET_FILTER programs, the struct __sk_buff *skb must be used instead.
`
i try to use instead 

`	events.perf_submit(ctx, &key, sizeof(key));
`
a new error

```
bpf: Failed to load program: Permission denied
0: (bf) r6 = r1
1: (18) r8 = 0xffffffff
3: (79) r7 = *(u64 *)(r6 +112)
invalid bpf_context access off=112 size=8

Traceback (most recent call last):
  File "tcpflow-test.py", line 60, in <module>
    function = bpf.load_func("tcp_monitor", BPF.SOCKET_FILTER)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 384, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program tcp_monitor: Permission denied


```

**Comment by phantooom** [comment]
i can't find my mistake

**Comment by yonghong-song** [comment]
The `SOCKET_FILTER` program cannot access `bpf_perf_event_output` helper. It can only be used for tracing program types.

The following
```
int tcp_monitor(struct pt_regs *ctx, struct __sk_buff *skb) {
```
obviously not correct.

Could you take a look at some examples under `bcc/examples/networking`?
