### ISSUE TITLE
funccount: Operation not permitted: '/sys/kernel/debug/tracing/../kprobes/blacklist'

### ISSUE THREAD

**Issue by SPYFF** [iovisor/bcc#2436]
With `funccount` I got the following error:

```
sudo /usr/share/bcc/tools/funccount -D kfree_skb

Traceback (most recent call last):
  File "/usr/share/bcc/tools/funccount", line 299, in <module>
    Tool().run()
  File "/usr/share/bcc/tools/funccount", line 261, in run
    self.probe.load()
  File "/usr/share/bcc/tools/funccount", line 191, in load
    bpf_text += self._generate_functions(trace_count_text)
  File "/usr/share/bcc/tools/funccount", line 121, in _generate_functions
    functions = BPF.get_kprobe_functions(self.pattern)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 528, in get_kprobe_functions
    with open("%s/../kprobes/blacklist" % TRACEFS, "rb") as blacklist_f:
IOError: [Errno 1] Operation not permitted: '/sys/kernel/debug/tracing/../kprobes/blacklist'
```
I tried it with kernel 4.18 and 5.0 (Ubuntu 18.04 HWE and HWE edge), none of them works. BCC installed from the stable repository.

**Comment by SPYFF** [comment]
Update: sorry, this is not related to `funccount` becauser `hello_world.py` also fail:
```
sudo ./hello_world.py 
bpf: Failed to load program: Operation not permitted

Traceback (most recent call last):
  File "./hello_world.py", line 12, in <module>
    BPF(text='int kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 351, in __init__
    self._trace_autoload()
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1097, in _trace_autoload
    fn = self.load_func(func_name, BPF.KPROBE)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 387, in load_func
    raise Exception("Need super-user privileges to run")
Exception: Need super-user privileges to run

```

What is interesting, it fails with `sudo` too

**Comment by SPYFF** [comment]
```
cat /boot/config-5.0.0-20-generic | grep BPF
CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_IPV6_SEG6_BPF=y
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_BPFILTER=y
CONFIG_BPFILTER_UMH=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_LWTUNNEL_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_BPF_EVENTS=y
CONFIG_BPF_KPROBE_OVERRIDE=y
CONFIG_TEST_BPF=m

```

**Comment by SPYFF** [comment]
On 4.15 the `hello_world.py` and other tools are working but I still get the first error in `funccount`

**Comment by yonghong-song** [comment]
Maybe this file `/sys/kernel/debug/tracing/blacklist` is missing?
Do you have the following:
  CONFIG_KPROBES=y
 CONFIG_KPROBES_ON_FTRACE=y

**Comment by SPYFF** [comment]
Thanks for the answer!
```
cat /boot/config-5.0.0-20-generic | grep KPROBE
CONFIG_KPROBES=y
CONFIG_KPROBES_ON_FTRACE=y
CONFIG_HAVE_KPROBES=y
CONFIG_HAVE_KPROBES_ON_FTRACE=y
CONFIG_KPROBE_EVENTS=y
CONFIG_BPF_KPROBE_OVERRIDE=y
```
Yes, `/sys/kernel/debug/tracing/blacklist` indeed missing

**Comment by jgehrcke** [comment]
What was the conclusion here? What does it mean when `/sys/kernel/debug/tracing/blacklist` is missing? @SPYFF I would appreciate if you could summarize a bit how you proceeded ... I think I have the same or a very similar challenge.

**Comment by SPYFF** [comment]
Hi! I will take a look into that soon.

**Comment by palmtenor** [comment]
@jgehrcke It means your Kernel is missing this feature. This is an optional feature and you can just do this: https://github.com/iovisor/bcc/issues/2413#issuecomment-503339169

**Comment by SPYFF** [comment]
In my case, installing Ubuntu 19.10 with 5.3 kernel, and installing BCC from source solved the issue.
Probably a missing kernel feature is the root of the problem.
