### ISSUE TITLE
funccount  error: Can't mix strings and bytes in path components

### ISSUE THREAD

**Issue by mwesolowski** [iovisor/bcc#2512]
Hi, I try to trace function calls to go library and unfortunately get an error:
```
$ sudo /usr/share/bcc/tools/funccount -D 'go:os.*'
Can't mix strings and bytes in path components 
```
It looks like python type mismatch error. More detailed output:
```
$ sudo /usr/share/bcc/tools/funccount -D 'go:os.*'
Traceback (most recent call last):
  File "/usr/share/bcc/tools/funccount", line 299, in <module>
    Tool().run()
  File "/usr/share/bcc/tools/funccount", line 250, in __init__
    self.probe = Probe(self.args.pattern, self.args.regexp, self.args.pid)
  File "/usr/share/bcc/tools/funccount", line 76, in __init__
    libpath = BPF.find_exe(self.library)
  File "/usr/lib/python3.7/site-packages/bcc/__init__.py", line 269, in find_exe
    exe_file = os.path.join(path, bin_path)
  File "/usr/lib64/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.7/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by mwesolowski** [comment]
Actually the problem is more general. For example when I try to generate flame graph:
```
$ sudo ./stackcount -f -D 1 --debug ktime_get
```
there is another type mismatch error:
```
Traceback (most recent call last):
  File "./stackcount", line 374, in <module>
    Tool().run()
  File "./stackcount", line 353, in run
    print("%s %d" % (";".join(line), v.value))
TypeError: sequence item 1: expected str instance, bytes found
```

**Comment by martinvonwittich** [comment]
I'm having the same problem with `trace.py`, while using the Debian buster-backports packaged downloaded from https://packages.debian.org/buster-backports/bpfcc-tools:

```
host ~ # trace-bpfcc -v 'r:bash:readline "%s", retval'
[...]
Traceback (most recent call last):
  File "/usr/sbin/trace-bpfcc", line 886, in run
    self._attach_probes()
  File "/usr/sbin/trace-bpfcc", line 862, in _attach_probes
    probe.attach(self.bpf, self.args.verbose)
  File "/usr/sbin/trace-bpfcc", line 637, in attach
    self._attach_u(bpf)
  File "/usr/sbin/trace-bpfcc", line 657, in _attach_u
    libpath = BPF.find_exe(self.library)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 286, in find_exe
    exe_file = os.path.join(path.encode(), bin_path)
  File "/usr/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.7/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

As this also happens in `libpath = BPF.find_exe(self.library)`, I believe it is the same bug.

I got it working with the following change (which is probably wrong because I have no idea what I'm doing):

``` diff
host ~ # diff -u __init__.py /usr/lib/python3/dist-packages/bcc/__init__.py             
--- __init__.py 2020-11-24 21:07:01.447980649 +0100
+++ /usr/lib/python3/dist-packages/bcc/__init__.py      2020-11-24 21:10:39.698384053 +0100
@@ -283,7 +283,7 @@
         else:
             for path in os.environ["PATH"].split(os.pathsep):
                 path = path.strip('"')
-                exe_file = os.path.join(path.encode(), bin_path)
+                exe_file = os.path.join(path, bin_path)
                 if is_exe(exe_file):
                     return exe_file
         return None
```

The output still contains `b''`, but I guess this is a different problem:

```
PID     TID     COMM            FUNC             -
16801   16801   bash            readline         b'ls'
16801   16801   bash            readline         b''
```

Both issues seem to be caused by an incomplete Python2->Python3 migration.

**Comment by ianwoolf** [comment]
> 

it works for me

**Comment by ianwoolf** [comment]
> I'm having the same problem with `trace.py`, while using the Debian buster-backports packaged downloaded from https://packages.debian.org/buster-backports/bpfcc-tools:
> 
> ```
> host ~ # trace-bpfcc -v 'r:bash:readline "%s", retval'
> [...]
> Traceback (most recent call last):
>   File "/usr/sbin/trace-bpfcc", line 886, in run
>     self._attach_probes()
>   File "/usr/sbin/trace-bpfcc", line 862, in _attach_probes
>     probe.attach(self.bpf, self.args.verbose)
>   File "/usr/sbin/trace-bpfcc", line 637, in attach
>     self._attach_u(bpf)
>   File "/usr/sbin/trace-bpfcc", line 657, in _attach_u
>     libpath = BPF.find_exe(self.library)
>   File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 286, in find_exe
>     exe_file = os.path.join(path.encode(), bin_path)
>   File "/usr/lib/python3.7/posixpath.py", line 94, in join
>     genericpath._check_arg_types('join', a, *p)
>   File "/usr/lib/python3.7/genericpath.py", line 151, in _check_arg_types
>     raise TypeError("Can't mix strings and bytes in path components") from None
> TypeError: Can't mix strings and bytes in path components
> ```
> 
> As this also happens in `libpath = BPF.find_exe(self.library)`, I believe it is the same bug.
> 
> I got it working with the following change (which is probably wrong because I have no idea what I'm doing):
> 
> ```diff
> host ~ # diff -u __init__.py /usr/lib/python3/dist-packages/bcc/__init__.py             
> --- __init__.py 2020-11-24 21:07:01.447980649 +0100
> +++ /usr/lib/python3/dist-packages/bcc/__init__.py      2020-11-24 21:10:39.698384053 +0100
> @@ -283,7 +283,7 @@
>          else:
>              for path in os.environ["PATH"].split(os.pathsep):
>                  path = path.strip('"')
> -                exe_file = os.path.join(path.encode(), bin_path)
> +                exe_file = os.path.join(path, bin_path)
>                  if is_exe(exe_file):
>                      return exe_file
>          return None
> ```
> 
> The output still contains `b''`, but I guess this is a different problem:
> 
> ```
> PID     TID     COMM            FUNC             -
> 16801   16801   bash            readline         b'ls'
> 16801   16801   bash            readline         b''
> ```
> 
> Both issues seem to be caused by an incomplete Python2->Python3 migration.

it works for me
