### ISSUE TITLE
Invalid intermediate source on qemu-system-ppc64 (w/o kvm)

### ISSUE THREAD

**Issue by vt-alt** [iovisor/bcc#2771]
When I run `/usr/share/bcc/tools/cpudist 1 1` on `qemu-system-ppc64` (without KVM) I get such result:

```
# /usr/share/bcc/tools/cpudist 1 1
/virtual/main.c:30:55: error: expected expression
    bpf_map_update_elem((void *)bpf_pseudo_fd(1, -1), , BPF_ANY) start.update(&pid, &ts);
                                                      ^
/virtual/main.c:39:66: error: expected expression
    u64 *tsp = bpf_map_lookup_elem((void *)bpf_pseudo_fd(1, -1), ) start.lookup(&pid);
                                                                 ^
/virtual/main.c:50:32: error: expected expression
    ({ typeof(dist.key) _key = ; typeof(dist.leaf) *_leaf = bpf_map_lookup_elem_(bpf_pseudo_fd(1, -2), &_key); if (_leaf) (*_leaf) += 1;}) dist.increment(bpf_log2l(delta));
                               ^
/virtual/main.c:50:139: error: expected ';' after expression
    ({ typeof(dist.key) _key = ; typeof(dist.leaf) *_leaf = bpf_map_lookup_elem_(bpf_pseudo_fd(1, -2), &_key); if (_leaf) (*_leaf) += 1;}) dist.increment(bpf_log2l(delta));
                                                                                                                                          ^
/virtual/main.c:54:37: error: expected ')'
int sched_switch(struct pt_regs *ctx*ctx, struct task_struct *prev)
                                    ^
/virtual/main.c:54:17: note: to match this '('
int sched_switch(struct pt_regs *ctx*ctx, struct task_struct *prev)
                ^
/virtual/main.c:56:3: error: expected expression
  = ctx->gpr[3];
  ^
/virtual/main.c:62:130: error: expected identifier
    if (({ typeof(volatile long) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&prev->); _val; })>state == TASK_RUNNING) {
                                                                                                                                 ^
/virtual/main.c:62:124: error: use of undeclared identifier 'prev'
    if (({ typeof(volatile long) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&prev->); _val; })>state == TASK_RUNNING) {
                                                                                                                           ^
/virtual/main.c:62:142: error: use of undeclared identifier 'state'; did you mean 'start'?
    if (({ typeof(volatile long) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&prev->); _val; })>state == TASK_RUNNING) {
                                                                                                                                             ^~~~~
                                                                                                                                             start
/virtual/main.c:21:10: note: 'start' declared here
BPF_HASH(start, u32, u64, MAX_PID);
         ^
/virtual/main.c:62:141: error: invalid operands to binary expression ('long' and 'struct start_table_t')
    if (({ typeof(volatile long) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&prev->); _val; })>state == TASK_RUNNING) {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/virtual/main.c:66:137: error: expected identifier
        u32 prev_pid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&prev->); _val; })>pid;
                                                                                                                                        ^
/virtual/main.c:66:131: error: use of undeclared identifier 'prev'
        u32 prev_pid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&prev->); _val; })>pid;
                                                                                                                                  ^
/virtual/main.c:67:138: error: expected identifier
        u32 prev_tgid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&prev->); _val; })>tgid;
                                                                                                                                         ^
/virtual/main.c:67:132: error: use of undeclared identifier 'prev'
        u32 prev_tgid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&prev->); _val; })>tgid;
                                                                                                                                   ^
14 errors generated.
Traceback (most recent call last):
  File "/usr/src/tmp/bcc-buildroot/usr/share/bcc/tools/cpudist", line 161, in <module>
    b = BPF(text=bpf_text, cflags=["-DMAX_PID=%d" % max_pid], debug=0xf)
  File "/usr/src/tmp/bcc-buildroot/usr/lib64/python3/site-packages/bcc/__init__.py", line 349, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

When I add `debug = 0xf` to `BPF()` I see such output:

```
Running from kernel directory at: /lib/modules/5.5.5-un-def-alt1/build
clang -cc1 -triple powerpc64le-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu ppc64le -mfloat-abi hard -target-abi elfv2 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /usr/src/linux-5.5.5-un-def-alt1/main.gcno -nostdsysteminc -nobuiltininc -resource-dir lib64/clang/9.0.1 -isystem /virtual/lib/clang/include -include ./include/linux/kconfig.h -include /virtual/include/bcc/bpf.h -include /virtual/include/bcc/helpers.h -isystem /virtual/include -I /.in -D __BPF_TRACING__ -I ./arch/powerpc/include -I arch/powerpc/include/generated/uapi -I arch/powerpc/include/generated -I include -I ./arch/powerpc/include/uapi -I arch/powerpc/include/generated/uapi -I ./include/uapi -I include/generated/uapi -D __KERNEL__ -D __HAVE_BUILTIN_BSWAP16__ -D __HAVE_BUILTIN_BSWAP32__ -D __HAVE_BUILTIN_BSWAP64__ -D MAX_PID=32768 -O2 -Wno-deprecated-declarations -Wno-gnu-variable-sized-type-not-at-end -Wno-pragma-once-outside-header -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-unused-value -Wno-pointer-sign -fdebug-compilation-dir /usr/src/linux-5.5.5-un-def-alt1 -ferror-limit 19 -fmessage-length 0 -fno-signed-char -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-loops -vectorize-slp -faddrsig -o main.bc -x c /virtual/main.c

#if defined(BPF_LICENSE)
#error BPF_LICENSE cannot be specified through cflags
#endif
#if !defined(CONFIG_CC_STACKPROTECTOR)
#if defined(CONFIG_CC_STACKPROTECTOR_AUTO) \
    || defined(CONFIG_CC_STACKPROTECTOR_REGULAR) \
    || defined(CONFIG_CC_STACKPROTECTOR_STRONG)
#define CONFIG_CC_STACKPROTECTOR
#endif
#endif
#include <uapi/linux/ptrace.h>
#include <linux/sched.h>
#define ONCPU

typedef struct pid_key {
    u64 id;
    u64 slot;
} pid_key_t;


BPF_HASH(start, u32, u64, MAX_PID);
BPF_HISTOGRAM(dist);

__attribute__((always_inline))
static inline void store_start(u32 tgid, u32 pid, u64 ts)
{
    if (0)
        return;

    bpf_map_update_elem((void *)bpf_pseudo_fd(1, -1), , BPF_ANY) start.update(&pid, &ts);
}

__attribute__((always_inline))
static inline void update_hist(u32 tgid, u32 pid, u64 ts)
{
    if (0)
        return;

    u64 *tsp = bpf_map_lookup_elem((void *)bpf_pseudo_fd(1, -1), ) start.lookup(&pid);
    if (tsp == 0)
        return;

    if (ts < *tsp) {
        // Probably a clock issue where the recorded on-CPU event had a
        // timestamp later than the recorded off-CPU event, or vice versa.
        return;
    }
    u64 delta = ts - *tsp;
    delta /= 1000;
    ({ typeof(dist.key) _key = ; typeof(dist.leaf) *_leaf = bpf_map_lookup_elem_(bpf_pseudo_fd(1, -2), &_key); if (_leaf) (*_leaf) += 1;}) dist.increment(bpf_log2l(delta));
}

__attribute__((section(".bpf.fn.sched_switch")))
int sched_switch(struct pt_regs *ctx*ctx, struct task_struct *prev)
{
  = ctx->gpr[3];
    u64 ts = bpf_ktime_get_ns();
    u64 pid_tgid = bpf_get_current_pid_tgid();
    u32 tgid = pid_tgid >> 32, pid = pid_tgid;

#ifdef ONCPU
    if (({ typeof(volatile long) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&prev->); _val; })>state == TASK_RUNNING) {
#else
    if (1) {
#endif
        u32 prev_pid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&prev->); _val; })>pid;
        u32 prev_tgid = ({ typeof(pid_t) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&prev->); _val; })>tgid;
#ifdef ONCPU
        update_hist(prev_tgid, prev_pid, ts);
#else
        store_start(prev_tgid, prev_pid, ts);
#endif
    }

BAIL:
#ifdef ONCPU
    store_start(tgid, pid, ts);
#else
    update_hist(tgid, pid, ts);
#endif

    return 0;
}

#include <bcc/footer.h>
```

When I run on `qemu-system-ppc64` with KVM enabled there is no such errors.

(These tests was performed on real POWER8E hardware, qemu is used just to make test environment contained.)

**Comment by yonghong-song** [comment]
This looks a bug in bcc rewriter. Do you have a reproducible test case?

**Comment by vt-alt** [comment]
Hm. I did not try, but maybe emulated `qemu-system-ppc64` on x86 would reproduce this? Is there any additional debug I could do on the target box?

**Comment by yonghong-song** [comment]
It would be good if you could try `qemu-system-x86_64` without KVM enabled to see whether the problem there or not. This may be easier to debug.

**Comment by vt-alt** [comment]
@yonghong-song I tried `qemu-system-x86_64` w/o KVM and it does not produce a error.

I may apply any patch (debug lines?) to the source and test on the ppc.

**Comment by yonghong-song** [comment]
Not 100% sure what is the best way to debug this since it only happens to `qemu-system-ppc64` without kvm. You could add some debug statements and print out rewriter buffers (see some examples in the `b_frontend_action.cc`) to see what is the issue. The translated C source is just so broken so probably some big issue in clang side exists.

**Comment by vt-alt** [comment]
This seems to be a bug in Qemu's ppc64 emulator. One op (`rlwinm`) is emulated incorrectly for some input values. https://lists.nongnu.org/archive/html/qemu-ppc/2020-03/msg00196.html So, I close this issue.

**Comment by vt-alt** [comment]
FYI, fix to the ppc64 platform is accepted in qemu upstream. https://github.com/qemu/qemu/commit/94f040aaecf4e41cc68991b80204b1b6886bbdd0
