### ISSUE TITLE
Can't create BPF_LPM_TRIE (1 EINVAL)

### ISSUE THREAD

**Issue by 01000101** [iovisor/bcc#2860]
### System Info
**Distro**: Fedora 31 server
**Linux kernel**: 5.6.2
**LLVM**: 9.0.1 (Fedora 9.0.1-2.fc31)
**Python**: 3.7.6
**BCC**:  0.13.0-495a4a34 (from master, but same issue from Fedora 31 package)

Everything is run as root, SELinux is disabled, and ulimits (soft/hard) are set to unlimited. 

### Problem
I cannot create a `BPF_MAP_TYPE_LPM_TRIE` map using BCC, but I can create it fine in-tree. 

None of the following work with BCC.
```
BPF_LPM_TRIE(lpm_map);
BPF_F_TABLE("lpm_trie", long, long, lpm_map, 10240, BPF_F_NO_PREALLOC);
BPF_F_TABLE("lpm_trie", long, long, lpm_map, 8, BPF_F_NO_PREALLOC);
```

This works fine without BCC.
```
struct bpf_map_def SEC("maps") trie = {
    .type        = BPF_MAP_TYPE_LPM_TRIE,
    .key_size    = sizeof(long),
    .value_size  = sizeof(long),
    .max_entries = 10000,
    .map_flags   = BPF_F_NO_PREALLOC
};
```

### Error output
This shows 2 successful (BPF_ARRAY) maps being created before failing (twice?) at creating a BPF_LPM_TRIE map. 

```
Using BCC version  0.13.0-495a4a34
bpf(BPF_BTF_LOAD, {btf="\237\353\1\0\30\0\0\0\0\0\0\0\260\10\0\0\260\10\0\0j\f\0\0\1\0\0\0\2\0\0\4"..., btf_log_buf=NULL, btf_size=5426, btf_log_size=0, btf_log_level=0}, 120) = 3
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_ARRAY, key_size=4, value_size=4, max_entries=8, map_flags=0, inner_map_fd=0, map_name="test_map", map_ifindex=0, btf_fd=3, btf_key_type_id=7, btf_value_type_id=7}, 120) = 4
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_ARRAY, key_size=4, value_size=8, max_entries=256, map_flags=0, inner_map_fd=0, map_name="xdp_stats_map", map_ifindex=0, btf_fd=3, btf_key_type_id=7, btf_value_type_id=8}, 120) = 5
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_LPM_TRIE, key_size=8, value_size=8, max_entries=10240, map_flags=BPF_F_NO_PREALLOC, inner_map_fd=0, map_name="lpm_map", map_ifindex=0, btf_fd=3, btf_key_type_id=2, btf_value_type_id=2}, 120) = -1 EINVAL (Invalid argument)
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_LPM_TRIE, key_size=8, value_size=8, max_entries=10240, map_flags=BPF_F_NO_PREALLOC, inner_map_fd=0, map_name="", map_ifindex=0, btf_fd=3, btf_key_type_id=2, btf_value_type_id=2}, 120) = -1 EINVAL (Invalid argument)
could not open bpf map: lpm_map, error: Invalid argument
Traceback (most recent call last):
  File "./src/examples/drop-icmp/user.py", line 110, in <module>
    main()
  File "./src/examples/drop-icmp/user.py", line 73, in main
    debug=args.debug)
  File "./src/examples/drop-icmp/user.py", line 22, in load_xdp_program
    debug=debug)
  File "/usr/lib/python3.7/site-packages/bcc/__init__.py", line 356, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module b'/root/ebpf/src/examples/drop-icmp/kern.c'
+++ exited with 1 +++
```

Compared to a successful map create from in-tree BPF, I'm not seeing much difference in the syscall itself... Here's the working syscall without BCC. 

```
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_LPM_TRIE, key_size=8, value_size=8, max_entries=10000, map_flags=BPF_F_NO_PREALLOC, inner_map_fd=0, map_name="trie", map_ifindex=0, btf_fd=0, btf_key_type_id=0, btf_value_type_id=0}, 120) = 5
```

The in-tree sanity checks are being passed, but I'm not sure what BCC is doing differently. The in-tree checks are found here - https://elixir.bootlin.com/linux/v5.6.2/source/kernel/bpf/lpm_trie.c#L549 . Can someone point me to where the sanity checks for this map type happen in BCC source?

**Comment by 01000101** [comment]
So, if I go a little deeper I can get it to work. 

```
#define _key_type long
#define _leaf_type long
#define _name "lpm_map"
#define _table_type "lpm_trie"

#define __BPF_F_TABLE(_table_type, _key_type, _leaf_type, _name, _max_entries, _flags) \
struct _name##_table_t { \
  _key_type key; \
  _leaf_type leaf; \
  _leaf_type * (*lookup) (_key_type *); \
  _leaf_type * (*lookup_or_init) (_key_type *, _leaf_type *); \
  _leaf_type * (*lookup_or_try_init) (_key_type *, _leaf_type *); \
  int (*update) (_key_type *, _leaf_type *); \
  int (*insert) (_key_type *, _leaf_type *); \
  int (*delete) (_key_type *); \
  void (*call) (void *, int index); \
  void (*increment) (_key_type, ...); \
  int (*get_stackid) (void *, u64); \
  u32 max_entries; \
  int flags; \
}; \
__attribute__((section("maps/" _table_type))) \
struct _name##_table_t _name = { .flags = (_flags), .max_entries = (_max_entries) }; \
BPF_ANNOTATE_KV_PAIR(my_new, _key_type, _leaf_type)

__BPF_F_TABLE("lpm_trie", long, int, my_new_map, 10000, 1);
```

My guess is that `BPF_ANNOTATE_KV_PAIR(_name, _key_type, _leaf_type)` is wrong in that `_name` (being `lpm_map`) actually needs to be without the `_map` part to work. If I change the value from "lpm_trie" to "lpm_trie_map" (like the _name is), then it fails with the original error.

**Comment by yonghong-song** [comment]
This is due to a kernel requirement with BTF support for lpm_trie map.
https://github.com/torvalds/linux/blob/master/kernel/bpf/lpm_trie.c#L728-L736

I have added a unit test case to illustrate the issue:
https://github.com/iovisor/bcc/pull/2862

In the above, you can use any name like "my_new", "my", etc. it all can work around the issue. But change your key type to be a structure like in the above pull request probably is the most sensible way to fix.
