### ISSUE TITLE
Not able to attach profile.py to a process id (pid)

### ISSUE THREAD

**Issue by sattishv** [iovisor/bcc#2916]
Hi Team,

We aren't able to attach the tool profile.py to a process which resides in another container using -p option. Started the docker with the below listed command options 
docker run -it --rm   --privileged  --pid host --net host  -v /lib/modules:/lib/modules:ro   -v /usr/src:/usr/src:ro  -v /etc/localtime:/etc/localtime:ro   --workdir /usr/share/bcc/tools   zlim/bcc

bcc started successfully but while trying to attach to a process which resides in another container we get empty profile means no stack trace

/usr/share/bcc/tools# ./profile -F 99 -p 174674
Sampling at 99 Hertz of PID 174674 by user + kernel stack... Hit Ctrl-C to end.
^C
root@gpma10-0:/usr/share/bcc/tools# no stack traces were displayed.

It works well without specifying pid option -p 

Thanks
Sattish.

**Comment by yonghong-song** [comment]
In this case, you need to find *host-level* pid for the pid you want filter. The pid inside the container won't work yet.

**Comment by sattishv** [comment]
Hi yong,

Thanks for the response. We tried with the host-level pid not the container level. With the host level pid we couldn't attach to the process.

Sattish.

**Comment by yonghong-song** [comment]
Could you provide more information on how do you find the host pid and how the command line looks like? The following command `./profile -F 99 -p <host_pid>` should work...

**Comment by sattishv** [comment]
Hi 
Have listed the steps we followed
We executed the docker run command listed below
docker run -it --rm --privileged --pid host --net host -v /lib/modules:/lib/modules:ro -v /usr/src:/usr/src:ro -v /etc/localtime:/etc/localtime:ro --workdir /usr/share/bcc/tools zlim/bcc

we got access to /usr/share/bcc/tools# from here 
Issued ps -ef | grep process inside the container and got the pid of the process.
from the same folder /usr/share/bcc/tools# invoked ./profile -F 99 -p 174674 

Response:
Sampling at 99 Hertz of PID 769998 by user + kernel stack... Hit Ctrl-C to end.
^C
root@host:/usr/share/bcc/tools# nothing been displayed

Sattish.

**Comment by JackyWoo** [comment]
Is there any progress in this issue?

**Comment by bveldhoen** [comment]
Seeing this with other tools as well:

Running the docker container with --privileged, using mounts:
-v /lib/modules:/lib/modules -v /usr/src:/usr/src -v /etc/localtime:/etc/localtime -v /sys/kernel:/sys/kernel

```
root@container:/usr/share/bcc/tools# funclatency -p 1 -r /usr/local/lib/libmylib.so:.*MyClass.*Exec.*
Tracing 31 functions for "/usr/local/lib/libmylib.so:.*MyClass.*Exec.*"... Hit Ctrl-C to end.
^C
Detaching...
root@container:/usr/share/bcc/tools#
```

Conclusion: Attaching the probes works, but no output is printed.

Perhaps related:

The /sys/kernel folder was required to avoid errors w.r.t. bpf_trace_printk:

```
root@2e6394a6bbaf:/usr/share/bcc/tools# ../examples/hello_world.py
Traceback (most recent call last):
  File "/usr/share/bcc/tools/../examples/hello_world.py", line 12, in <module>
    BPF(text='int kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1568, in trace_print
    line = self.trace_readline(nonblocking=False)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1544, in trace_readline
    trace = self.trace_open(nonblocking)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1495, in trace_open
    self.tracefile = open("%s/trace_pipe" % TRACEFS, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/tracing/trace_pipe'
open(/sys/kernel/tracing/kprobe_events): No such file or directory
Exception ignored in atexit callback: <bound method BPF.cleanup of <bcc.BPF object at 0x7f4531093c10>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1774, in cleanup
    self.detach_kprobe_event(k)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 899, in detach_kprobe_event
    self.detach_kprobe_event_by_fn(ev_name, fn_name)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 913, in detach_kprobe_event_by_fn
    raise Exception("Failed to detach BPF from kprobe")
Exception: Failed to detach BPF from kprobe

```
