### ISSUE TITLE
error: field has incomplete type 'struct memcg_cache_params'

### ISSUE THREAD

**Issue by Daniel15** [iovisor/bcc#2955]
I installed this on Debian Bullseye using:
```
apt install bpfcc-tools
```

but when I run `slabratetop-bpfcc`, I get this error:
```
In file included from /virtual/main.c:6:
include/linux/slub_def.h:112:28: error: field has incomplete type 'struct memcg_cache_params'
        struct memcg_cache_params memcg_params;
                                  ^
include/linux/slub_def.h:112:9: note: forward declaration of 'struct memcg_cache_params'
        struct memcg_cache_params memcg_params;
               ^
1 error generated.
Traceback (most recent call last):
  File "/usr/sbin/slabratetop-bpfcc", line 109, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 347, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

Any ideas?

```
root@lux01:~# cat /etc/debian_version
bullseye/sid

root@lux01:~# uname -a
Linux lux01 5.6.0-2-cloud-amd64 #1 SMP Debian 5.6.14-1 (2020-05-23) x86_64 GNU/Linux
```

**Comment by yonghong-song** [comment]
Yes, this is a problem with 5.6 kernel where `struct memcg_cache_params` is defined in `linux/mm/slab.h`.  This can be fixed by copying related structures to the bpf program, e.g., `runqlen.py`. If you are interested, please go ahead to try and submit a pull request. Otherwise, I will find some time later to fix it.
