### ISSUE TITLE
Confused about LSM_PROBE behavior

### ISSUE THREAD

**Issue by willfindlay** [iovisor/bcc#2961]
I'm trying to get a simple example of LSM_PROBE working.
Here is my code (edit: added a line to attach as a kfunc, still not working):
```python
import os
import sys
import time

from bcc import BPF, libbcc

src = """
#include <linux/fs.h>
#include <uapi/asm-generic/errno-base.h>

LSM_PROBE(inode_permission, struct inode *inode, int mask) {
    bpf_trace_printk("hello lsm world\\n");

    u32 pid = bpf_get_current_pid_tgid();
    if (pid == %d) {
        return -EPERM;
    }

    return 0;
}
""" % (
    os.getpid()
)

b = BPF(text=src)
fn = b.load_func("lsm__inode_permission", BPF.LSM)
res = libbcc.lib.bpf_attach_kfunc(fn.fd)

try:
    while 1:
        time.sleep(0.5)
        # Print when bpf_trace_printk is called
        f = b.trace_fields(nonblocking=True)
        if f[-1]:
            print(f[-1])
        try:
            # Try to open own source file
            print('Opening %s' % (__file__))
            f = open(__file__, 'r')
            f.close()
        except PermissionError:
            print('No permissions!')
except KeyboardInterrupt:
    sys.exit()
```
~Here are my relevant kernel configs:~ (see comment below)
```
CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_INFO_BTF=y
....
CONFIG_BPF_LSM=y
```
I am running `5.7.1-arch1-1` kernel and latest bcc master built from source.

According to my understanding, the above code should print "hello lsm world" every time a file is opened and should cause the call to `f = open(__file__, 'r')` to fail with EPERM. However, I am not seeing the hook being triggered at all.

Am I missing something?

**Comment by willfindlay** [comment]
Update: Turns out I was missing `CONFIG_LSM="bpf"` in my kernel configs. I have booted into a custom kernel with the new configs and now I am seeing the log message. However, returning -EPERM is still **not causing a permission error as expected**.

**Comment by willfindlay** [comment]
I have found the problem. See #2976

**Comment by bitvijays** [comment]
Hi @willfindlay Hope you are doing well. Thank you for your support. I tried running the example you have mentioned above and got the below error
```  File "bcclsm.py", line 25, in <module>
    b = BPF(text=src)
  File "/usr/lib/python3.8/site-packages/bcc/__init__.py", line 366, in __init__
    self._trace_autoload()
  File "/usr/lib/python3.8/site-packages/bcc/__init__.py", line 1241, in _trace_autoload
    self.attach_lsm(fn_name=func_name)
  File "/usr/lib/python3.8/site-packages/bcc/__init__.py", line 974, in attach_lsm
    fn = self.load_func(fn_name, BPF.LSM)
  File "/usr/lib/python3.8/site-packages/bcc/__init__.py", line 405, in load_func
    raise Exception("Failed to load BPF program %s: %s" %
Exception: Failed to load BPF program b'lsm__inode_permission': Invalid argument
```

Just for reference purposes here's the code which I am trying to run

```
import os
import sys
import time

from bcc import BPF, libbcc

src = """
#include <linux/fs.h>
#include <uapi/asm-generic/errno-base.h>

LSM_PROBE(inode_permission, struct inode *inode, int mask) {
    bpf_trace_printk("hello lsm world\\n");

    u32 pid = bpf_get_current_pid_tgid();
    if (pid == %d) {
        return -EPERM;
    }

    return 0;
}
""" % (
    os.getpid()
)

b = BPF(text=src)
fn = b.load_func("lsm__inode_permission", BPF.LSM)
res = libbcc.lib.bpf_attach_kfunc(fn.fd)

try:
    while 1:
        time.sleep(0.5)
        # Print when bpf_trace_printk is called
        f = b.trace_fields(nonblocking=True)
        if f[-1]:
            print(f[-1])
        try:
            # Try to open own source file
            print('Opening %s' % (__file__))
            f = open(__file__, 'r')
            f.close()
        except PermissionError:
            print('No permissions!')
except KeyboardInterrupt:
    sys.exit()
```

Also, I am trying to run on Fedora 32, Kernel 5.7.10 build using the stable version and have set `CONFIG_LSM="bpf"`  which was verified by 
```
cat /sys/kernel/security/lsm
lockdown,capability,yama,selinux,bpf
```

Built using
```
CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_LSM=y
CONFIG_BPF_SYSCALL=y
CONFIG_ARCH_WANT_DEFAULT_BPF_JIT=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_BPF_JIT_DEFAULT_ON=y
CONFIG_IPV6_SEG6_BPF=y
CONFIG_NETFILTER_XT_MATCH_BPF=m
# CONFIG_BPFILTER is not set
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_LWTUNNEL_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_BPF_LIRC_MODE2=y
CONFIG_BPF_EVENTS=y
# CONFIG_BPF_KPROBE_OVERRIDE is not set
# CONFIG_TEST_BPF is not set
CONFIG_IIO_ST_LSM6DSX=m
CONFIG_IIO_ST_LSM6DSX_I2C=m
CONFIG_IIO_ST_LSM6DSX_SPI=m
CONFIG_LSM_MMAP_MIN_ADDR=65536
CONFIG_SECURITY_LOCKDOWN_LSM=y
CONFIG_SECURITY_LOCKDOWN_LSM_EARLY=y
CONFIG_IMA_LSM_RULES=y
CONFIG_LSM="yama,loadpin,safesetid,integrity,selinux,smack,tomoyo,apparmor,bpf"
```
Any suggestions, what I might be doing wrong?

**Comment by willfindlay** [comment]
@bitvijays You need BTF support in your kernel to use BPF LSM.

**Comment by willfindlay** [comment]
Also note the example here is obsolete. Refer to the documentation for an up to date example. You don't need to call attach_kfunc or load_func on your own anymore. bcc is smart enough to do that for you.

**Comment by bitvijays** [comment]
@willfindlay Thank you for your continuous support. CONFIG_DEBUG_INFO, CONFIG_DEBUG_INFO_BTF is yes. Also pahole is > 0.16. 
```
[vagrant@localhost linux-5.7.10]$ cat .config | grep CONFIG_DEBUG_INFO
CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_INFO_BTF=y
[vagrant@localhost linux-5.7.10]$ pahole --version
v1.17
```

However, still getting the same error. 

I have reduced my program to 
```
import os
import sys
import time

from bcc import BPF, libbcc

if not BPF.support_lsm():
        print("LSM not supported")

src1 = """
#include <linux/fs.h>
#include <uapi/asm-generic/errno-base.h>
LSM_PROBE(bpf, int cmd, union bpf_attr *attr, unsigned int size)
{
    return -EPERM;
}
"""

b = BPF(text=src1)
```

However, still got

```
bpf: Failed to load program: Invalid argument

Traceback (most recent call last):
  File "bccvk.py", line 19, in <module>
    b = BPF(text=src1)
  File "/usr/lib/python3.8/site-packages/bcc/__init__.py", line 366, in __init__
    self._trace_autoload()
  File "/usr/lib/python3.8/site-packages/bcc/__init__.py", line 1241, in _trace_autoload
    self.attach_lsm(fn_name=func_name)
  File "/usr/lib/python3.8/site-packages/bcc/__init__.py", line 974, in attach_lsm
    fn = self.load_func(fn_name, BPF.LSM)
  File "/usr/lib/python3.8/site-packages/bcc/__init__.py", line 405, in load_func
    raise Exception("Failed to load BPF program %s: %s" %
Exception: Failed to load BPF program b'lsm__bpf': Invalid argument
```

By any chance do you have a working program for this? or suggestions, how this can be debugged? or any vagrant file? on which this has been tested already? 

Thank you :)

**Comment by willfindlay** [comment]
@bitvijays I'm stumped. Your example is working fine on my system. Consider filing this as a separate issue, maybe it can get more exposure. Something must somehow be misconfigured, but I'm not sure what it could be.
