### ISSUE TITLE
filesslower crashes on kernel 5.8.0: cannot attach kprobe, probe entry may not exist

### ISSUE THREAD

**Issue by cmurf** [iovisor/bcc#3045]
Somewhat similar to #3023

kernel-5.8.0-1.fc33.x86_64
bcc-tools-0.15.0-6.fc33.x86_64

```
# /usr/share/bcc/tools/fileslower
cannot attach kprobe, probe entry may not exist
Traceback (most recent call last):
  File "/usr/share/bcc/tools/fileslower", line 202, in <module>
    b.attach_kprobe(event="__vfs_read", fn_name="trace_read_entry")
  File "/usr/lib/python3.9/site-packages/bcc/__init__.py", line 676, in attach_kprobe
    raise Exception("Failed to attach BPF program %s to kprobe %s" %
Exception: Failed to attach BPF program b'trace_read_entry' to kprobe b'__vfs_read'

# grep vfs_read /proc/kallsyms
ffffffff83323770 T vfs_read
ffffffff83324580 T vfs_readv
ffffffff83336e60 T vfs_readlink
ffffffff844caf40 r __ksymtab_vfs_readlink
ffffffff844e3462 r __kstrtabns_vfs_readlink
ffffffff844e65f7 r __kstrtab_vfs_readlink
```

**Comment by realhezhe** [comment]
https://github.com/iovisor/bcc/pull/3047
This change can fix the error.

**Comment by kong62** [comment]
work for me
```
# egrep __vfs_read fileslower      
# This works by tracing __vfs_read() and __vfs_write(), and filtering for
    // skip non-sync I/O; see kernel code for __vfs_read()
b.attach_kprobe(event="__vfs_read", fn_name="trace_read_entry")
b.attach_kretprobe(event="__vfs_read", fn_name="trace_read_return")
```
```
# sed -i 's/__vfs_read/vfs_read/g' fileslower
```
```
# fileslower 1
cannot attach kprobe, probe entry may not exist
Tracing sync read/writes slower than 1 ms
TIME(s)  COMM           TID    D BYTES   LAT(ms) FILENAME
0.006    dockerd        1954   R 371        5.79 87b18c556c22f187bbabb15065394...
0.741    filebeat       3109   W 101150     3.48 data.json.new
0.796    filebeat       31326  W 1396       2.46 data.json.new
1.500    auditd         963    W 320        1.72 audit.log
1.501    filebeat       3443   W 101151     4.19 data.json.new
1.799    filebeat       4088   W 1397       2.44 data.json.new
2.391    filebeat       3107   W 101152     3.77 data.json.new
```

**Comment by yang-wei** [comment]
Getting similar error when running `runqslower` 
```bash
cannot attach kprobe, probe entry may not exist
Traceback (most recent call last):
  File "/usr/share/bcc/tools/runqslower", line 256, in <module>
    b.attach_kprobe(event="ttwu_do_wakeup", fn_name="trace_ttwu_do_wakeup")
  File "/usr/lib/python3.7/site-packages/bcc/__init__.py", line 684, in attach_kprobe
    (fn_name, event))
Exception: Failed to attach BPF program b'trace_ttwu_do_wakeup' to kprobe b'ttwu_do_wakeup'
```

```bash
sh-4.2$ uname -p
aarch64
sh-4.2$ uname -r
4.14.238-182.422.amzn2.aarch64

sh-4.2$ yum info bcc
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
200 packages excluded due to repository priority protections
Installed Packages
Name        : bcc
Arch        : aarch64
Version     : 0.18.0
Release     : 1.amzn2.0.3
Size        : 78 M
Repo        : installed
From repo   : amzn2-core
Summary     : BPF Compiler Collection (BCC)

sh-4.2$ cat /proc/kallsyms | grep ttwu_do_wakeup
0000000000000000 t ttwu_do_wakeup.isra.19
```

### workaround

```diff
-    b.attach_kprobe(event="ttwu_do_wakeup", fn_name="trace_ttwu_do_wakeup")
+    b.attach_kprobe(event="ttwu_do_wakeup.isra.19", fn_name="trace_ttwu_do_wakeup")

```
