### ISSUE TITLE
Exception: Failed to attach BPF program do_ret_sys_kill to kretprobe sys_kill

### ISSUE THREAD

**Issue by glbjiiii** [iovisor/bcc#3070]
i try this command，not working

root@localhost:/usr/share# killsnoop
cannot attach kprobe, Function not implemented
Traceback (most recent call last):
  File "/usr/share/bcc/tools/killsnoop", line 125, in <module>
    b.attach_kretprobe(event=kill_fnname, fn_name="do_ret_sys_kill")
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 709, in attach_kretprobe
    (fn_name, event))
Exception: Failed to attach BPF program do_ret_sys_kill to kretprobe sys_kill

i using [adeb](https://github.com/joelagnel/adeb) running on android pixel4xl
kernel versiong 4.14 (4.14.170-g551313822-dirty_audio-g199e9bf)
bcc version latest

kernel config 

CONFIG_BPF=y
CONFIG_BPF_JIT=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_KPROBE_EVENTS=y
CONFIG_UPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y
CONFIG_DEBUG_PREEMPT=y
CONFIG_PREEMPTIRQ_EVENTS=y
CONFIG_FTRACE_SYSCALLS=y

I don't know what to do

**Comment by netedwardwu** [comment]
Could you check the content of kill_fnname variable is exist in Android /proc/kallsyms or not?
https://github.com/iovisor/bcc/blob/master/tools/killsnoop.py#L123

**Comment by glbjiiii** [comment]
@netedwardwu Thank you for your reply
coral:/ # cat /proc/kallsyms |grep sys_kill
ffffff80754c77e0 T sys_kill
coral:/ #
is right?

**Comment by netedwardwu** [comment]
Could you also print kill_fnname in killsnoop for me?
https://github.com/iovisor/bcc/blob/master/tools/killsnoop.py#L123

**Comment by glbjiiii** [comment]
@netedwardwu yes
root@localhost:/# killsnoop
fnname sys_kill
cannot attach kprobe, Function not implemented
Traceback (most recent call last):
  File "/usr/share/bcc/tools/killsnoop", line 126, in <module>
    b.attach_kretprobe(event=kill_fnname, fn_name="do_ret_sys_kill")
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 709, in attach_kretprobe
    (fn_name, event))
Exception: Failed to attach BPF program do_ret_sys_kill to kretprobe sys_kill
root@localhost:/#

i add print('fnname',kill_fnname)

**Comment by netedwardwu** [comment]
So weird, why kprobe is acceptable but not kretprobe...
You can check if ketprobe event is created. If not, you should trace kretprobe kernel code
```
/sys/kernel/debug # cat kprobes/list
c0333190  r  sys_kill+0x0
c0333190  k  sys_kill+0x0
```
r is retprobe
If not created, use ftrace to check register_kretprobe() is called or not.
```
/sys/kernel/debug/tracing # echo register_kretprobe > set_ftrace_filter
/sys/kernel/debug/tracing # echo function > current_tracer
/sys/kernel/debug/tracing # cat trace_pipe
            14264.456148: register_kretprobe <-__register_trace_kprobe.part.1
```
Or check returned error value

**Comment by netedwardwu** [comment]
Did you enable CONFIG_KRETPROBES?

**Comment by glbjiiii** [comment]
Nothing
```bash
coral:/sys/kernel/debug # cat kprobes/list                                     
coral:/sys/kernel/debug # 
```
nothing and Permission denied
```bash
coral:/sys/kernel/debug/tracing # echo register_kretprobe > set_ftrace_filter
/system/bin/sh: can't create set_ftrace_filter: Permission denied
1|coral:/sys/kernel/debug/tracing # echo function > current_tracer
1|coral:/sys/kernel/debug/tracing # cat trace_pipe


```
/proc/config.gz can't find CONFIG_KRETPROBES

my phone pixel4xl(arm64) system is userdebug , should i use eng version?
or i should rebuild kernel add CONFIG_KRETPROBES.
@netedwardwu thank you help

**Comment by netedwardwu** [comment]
rebuild kernel add CONFIG_KRETPROBES is enough
Because you can use kprobe but not kretprobe

**Comment by glbjiiii** [comment]
@netedwardwu thank you very much for your help,I will try, then report

**Comment by Youlor** [comment]
> @netedwardwu 

I also encountered this problem, have you solved it?

**Comment by Youlor** [comment]
I also encountered this problem, have you solved it?

**Comment by Youlor** [comment]
> @netedwardwu 

I also encountered this problem, have you solved it?

**Comment by Youlor** [comment]
I solved it by add config and rebuild:
```
CONFIG_KRETPROBES=y
CONFIG_HAVE_KRETPROBES=y
CONFIG_ROP_PROTECTION_NONE=y
```
reference private/msm-google/arch/Kconfig file:
```
config KRETPROBES
	def_bool y
	depends on KPROBES && HAVE_KRETPROBES && ROP_PROTECTION_NONE
```

**Comment by glbjiiii** [comment]
> I solved it by add config and rebuild:
> 
> ```
> CONFIG_KRETPROBES=y
> CONFIG_HAVE_KRETPROBES=y
> CONFIG_ROP_PROTECTION_NONE=y
> ```
> 
> reference private/msm-google/arch/Kconfig file:
> 
> ```
> config KRETPROBES
> 	def_bool y
> 	depends on KPROBES && HAVE_KRETPROBES && ROP_PROTECTION_NONE
> ```

Thank you
I did not test
I want to use bcc tool to get the user stack,  bcc tool can do it?
@Youlor

**Comment by Youlor** [comment]
> > I solved it by add config and rebuild:
> > ```
> > CONFIG_KRETPROBES=y
> > CONFIG_HAVE_KRETPROBES=y
> > CONFIG_ROP_PROTECTION_NONE=y
> > ```
> > 
> > 
> > reference private/msm-google/arch/Kconfig file:
> > ```
> > config KRETPROBES
> > 	def_bool y
> > 	depends on KPROBES && HAVE_KRETPROBES && ROP_PROTECTION_NONE
> > ```
> 
> Thank you
> I did not test
> I want to use bcc tool to get the user stack, bcc tool can do it?
> @Youlor

yes, you can.
```
python3 trace 'compat_sys_openat "%s", arg2@user' -U -a
```
reference: https://github.com/iovisor/bcc/blob/master/tools/trace_example.txt

**Comment by glbjiiii** [comment]
> > > I solved it by add config and rebuild:
> > > ```
> > > CONFIG_KRETPROBES=y
> > > CONFIG_HAVE_KRETPROBES=y
> > > CONFIG_ROP_PROTECTION_NONE=y
> > > ```
> > > 
> > > 
> > > reference private/msm-google/arch/Kconfig file:
> > > ```
> > > config KRETPROBES
> > > 	def_bool y
> > > 	depends on KPROBES && HAVE_KRETPROBES && ROP_PROTECTION_NONE
> > > ```
> > 
> > 
> > Thank you
> > I did not test
> > I want to use bcc tool to get the user stack, bcc tool can do it?
> > @Youlor
> 
> yes, you can.
> 
> ```
> python3 trace 'compat_sys_openat "%s", arg2@user' -U -a
> ```
> 
> reference: https://github.com/iovisor/bcc/blob/master/tools/trace_example.txt

thank you
