### ISSUE TITLE
XDP unit tests with bcc

### ISSUE THREAD

**Issue by sbernard31** [iovisor/bcc#3091]
I'm currently using bcc to develop an UDP loadbalancer : https://github.com/AirVantage/sbulb

I would like to write some tests. I discover recently `BPF_PROG_TEST_RUN` and so plan to use it : https://github.com/AirVantage/sbulb/issues/29

But trying to run this sample https://gist.github.com/yunazuno/14eb1b7fc5eb6bb23f36d1d01ed00367 on my debian buster 10 (Debian 4.19.118-2+deb10u1) with [bcc 0.8](https://packages.debian.org/buster/python3-bpfcc),  I get this error : 
```
Traceback (most recent call last):
  File "tests.py", line 40, in test_ipv4_tcp_80
    self._run_test(packet_in, None, BPF.XDP_DROP)
  File "tests.py", line 22, in _run_test
    ret = libbcc.lib.bpf_prog_test_run(self.func.fd, repeat,
  File "/usr/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_prog_test_run
```

Should it work with this version of bcc ? or maybe I did something wrong ?

I see there is a more recent version of bcc in backport repository : [0.14](https://packages.debian.org/buster-backports/python3-bpfcc). I should maybe give it a try :thinking:

**Comment by sbernard31** [comment]
I should have test with 0.14 before to open a ticket as it seems to work as expected with this version ... :sweat_smile: 

This ticket will maybe be useful for some else which faces this issue too.

**Comment by sbernard31** [comment]
Just in case our unit test are available at : https://github.com/AirVantage/sbulb/tree/master/sbulb/tests
This is an example about how to automatic testing bcc/XDP with scapy.
