### ISSUE TITLE
TypeError: glob() got an unexpected keyword argument 'recursive'

### ISSUE THREAD

**Issue by kong62** [iovisor/bcc#3137]
```
# uname -r
5.4.25-200.el7.x86_64
```

```
# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```

```
# dirtop  -d /root
Traceback (most recent call last):
  File "/usr/share/bcc/tools/dirtop", line 182, in <module>
    inodes, inodes_to_path = get_searched_ids(args.rootdirs)
  File "/usr/share/bcc/tools/dirtop", line 151, in get_searched_ids
    searched_dirs = glob(root_directory, recursive=True)
TypeError: glob() got an unexpected keyword argument 'recursive'
```

when I change  python3:

```
# vi dirtop
#!/usr/bin/python3
##!/usr/bin/python

# dirtop -d '/etc' 1 2
Traceback (most recent call last):
  File "/usr/share/bcc/tools/dirtop", line 18, in <module>
    from bcc import BPF
ModuleNotFoundError: No module named 'bcc'
```

**Comment by willfindlay** [comment]
Did you build and install bcc manually? If so, make sure to supply `-DPYTHON_CMD=python3` to cmake to install it as a python3 module.

**Comment by willfindlay** [comment]
Could also catch the TypeError and fall back to glob(pathname) to fix Python2.7 support

**Comment by willfindlay** [comment]
@kong62 I've create a PR to fix python2 support. Feel free to check it out now or wait for it to be merged upstream.

**Comment by kong62** [comment]
@willfindlay thks
