### ISSUE TITLE
klockstat, netqtop tools in bcc-tools

### ISSUE THREAD

**Issue by shubhtrivedi** [iovisor/bcc#3180]
Hi,

I am running bcc-tools inside a container. some tools are working fine but some are giving errors.

klockstat

> [root@9318756deac1 tools]# ./klockstat
Traceback (most recent call last):
  File "./klockstat", line 304, in <module>
    is_support_kfunc = BPF.support_kfunc()
AttributeError: type object 'BPF' has no attribute 'support_kfunc'

Netqtop

> [root@9318756deac1 tools]# ./netqtop -n lo
/virtual/main.c:76:1: warning: declaration of 'struct tracepoint__net__net_dev_start_xmit' will not be visible outside of this function
      [-Wvisibility]
TRACEPOINT_PROBE(net, net_dev_start_xmit){
^
/virtual/include/bcc/helpers.h:837:46: note: expanded from macro 'TRACEPOINT_PROBE'
int tracepoint__##category##__##event(struct tracepoint__##category##__##event *args)
                                             ^
<scratch space>:110:1: note: expanded from here
tracepoint__net__net_dev_start_xmit
^
/virtual/main.c:78:48: error: incomplete definition of type 'struct tracepoint__net__net_dev_start_xmit'
    struct sk_buff* skb = (struct sk_buff*)args->skbaddr;
                                           ~~~~^
/virtual/main.c:76:1: note: forward declaration of 'struct tracepoint__net__net_dev_start_xmit'
TRACEPOINT_PROBE(net, net_dev_start_xmit){
^
/virtual/include/bcc/helpers.h:837:46: note: expanded from macro 'TRACEPOINT_PROBE'
int tracepoint__##category##__##event(struct tracepoint__##category##__##event *args)
                                             ^
<scratch space>:110:1: note: expanded from here
tracepoint__net__net_dev_start_xmit
^
/virtual/main.c:87:36: error: no member named 'lookup_or_try_init' in 'struct tx_q_table_t'; did you mean 'lookup_or_init'?
    struct queue_data *data = tx_q.lookup_or_try_init(&qid, &newdata);
                                   ^~~~~~~~~~~~~~~~~~
                                   lookup_or_init
/virtual/main.c:34:1: note: 'lookup_or_init' declared here
BPF_HASH(tx_q, u16, struct queue_data, MAX_QUEUE_NUM);
^
/virtual/include/bcc/helpers.h:164:26: note: expanded from macro 'BPF_HASH'
  BPF_HASHX(__VA_ARGS__, BPF_HASH4, BPF_HASH3, BPF_HASH2, BPF_HASH1)(__VA_ARGS__)
                         ^
/virtual/main.c:87:54: error: called object type '<dependent type>' is not a function or function pointer
    struct queue_data *data = tx_q.lookup_or_try_init(&qid, &newdata);
                                                     ^
/virtual/main.c:111:36: error: no member named 'lookup_or_try_init' in 'struct rx_q_table_t'; did you mean 'lookup_or_init'?
    struct queue_data *data = rx_q.lookup_or_try_init(&qid, &newdata);
                                   ^~~~~~~~~~~~~~~~~~
                                   lookup_or_init
/virtual/main.c:35:1: note: 'lookup_or_init' declared here
BPF_HASH(rx_q, u16, struct queue_data, MAX_QUEUE_NUM);
^
/virtual/include/bcc/helpers.h:164:26: note: expanded from macro 'BPF_HASH'
  BPF_HASHX(__VA_ARGS__, BPF_HASH4, BPF_HASH3, BPF_HASH2, BPF_HASH1)(__VA_ARGS__)
                         ^
/virtual/main.c:111:54: error: called object type '<dependent type>' is not a function or function pointer
    struct queue_data *data = rx_q.lookup_or_try_init(&qid, &newdata);
                                                     ^
1 warning and 5 errors generated.
Traceback (most recent call last):
  File "./netqtop", line 207, in <module>
    b = BPF(src_file = EBPF_FILE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 336, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module netqtop.c

Can anyone suggest the correct way to run these tools or the problem in the above way??

Thanks.

**Comment by jiangxiaobin96** [comment]
check if `/usr/lib/python3/dist-packages/bcc/__init__.py` has support_kfunc, maybe need to update bcc version.
