### ISSUE TITLE
nf_nat_l4proto_unique_tuple: cannot attach kprobe, probe entry may not exist

### ISSUE THREAD

**Issue by boulevarder** [iovisor/bcc#3185]
```cannot attach kprobe, probe entry may not exist
Traceback (most recent call last):
  File "overtime_connection.py", line 51, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 372, in __init__
    self._trace_autoload()
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1232, in _trace_autoload
    fn_name=fn.name)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 684, in attach_kprobe
    (fn_name, event))
Exception: Failed to attach BPF program b'kprobe__nf_nat_l4proto_unique_tuple' to kprobe b'nf_nat_l4proto_unique_tuple'
```

kernel : 5.4.0.bsk.1-amd64

but works ok with 4.14.81.bm.15-amd64

Thanks

**Comment by willfindlay** [comment]
The problem is that this function was made static in later versions of the kernel, meaning that it is no longer exported to kallsyms. You would need to somehow find the address manually and instrument that or else instrument another function.

**Comment by boulevarder** [comment]
thx!!!
