### ISSUE TITLE
uprobe attached to functions defined in self-compiled binary doesn't fire

### ISSUE THREAD

**Issue by nalzok** [iovisor/bcc#3215]
Consider the following program. It goes into `/tmp/bin.c` and the corresponding executable is built with `gcc -o bin bin.c`.

```c
#include <stdio.h>

void foo();

int main(int argc, char **argv) {
    foo();
}

void foo() {
    puts("hello");
}
```

The bcc script `do_main.py` contains the following

```python
#!/usr/bin/python

from __future__ import print_function
import bcc


b = bcc.BPF(text="""
int do_libc_main(void *ctx) {
    bpf_trace_printk("libc main\\n");
    return 0;
};

int do_binary_main(void *ctx) {
    bpf_trace_printk("binary main\\n");
    return 0;
};
""")

b.attach_uprobe(name="/usr/lib64/libc.so.6",
                sym="__libc_start_main",
                fn_name="do_libc_main")
b.attach_uprobe(name="/tmp/bin",
                sym="main",
                fn_name="do_binary_main")

while True:
    print(b.trace_fields())
```

Then I execute `sudo python do_main.py` and run `/tmp/bin` from another terminal. As you can see below, only the probe attached to the library function `__libc_start_main` fires.

```
$ sudo python do_main.py
('bin', 8103, 2, '....', 607583.867852, 'libc main')
```

The issue can be reproduced with `bpftrace`.

```
$ sudo bpftrace -e 'uprobe:/usr/lib64/libc.so.6:__libc_start_main { printf("main called\n"); }' -c /tmp/bin
Attaching 1 probe...
hello
main called


$ sudo bpftrace -e 'uprobe:/tmp/bin:main { printf("main called\n"); }' -c /tmp/bin
Attaching 1 probe...
hello


```

To make things more complicated, the probe attached to certain binaries shipped with the system does fire!

```
$ sudo bpftrace -e 'uprobe:/bin/bash:main { printf("main called\n"); }' -c /bin/bash
Attaching 1 probe...
main called
main called

```

------

System information:

```
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: n/a
Description:    NAME="Red Hat Enterprise Linux Server"
Release:        n/a
Codename:       n/a

$ uname -a
Linux mwfsh 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ sudo python -c 'import bcc; print(bcc.__version__)'
0.18.0-b1ab8690

$ bpftrace --version
bpftrace v0.11.0-118-gf543-dirty
```

**Comment by yonghong-song** [comment]
I cannot reproduce this issue with centos with 5.6 kernel.

```
[yhs@devvm1886.ftw0 ~/tmp]$ sudo ./do_main.py
(b'<...>', 364762, 12, b'd...', 2005797.032185, b'binary main')
(b'<...>', 366001, 8, b'd...', 2005808.113191, b'binary main')
^CTraceback (most recent call last):
  File "./do_main.py", line 26, in <module>
    print(b.trace_fields())
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 1274, in trace_fields
    line = self.trace_readline(nonblocking)
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 1312, in trace_readline
    line = trace.readline(1024).rstrip()
KeyboardInterrupt
[yhs@devvm1886.ftw0 ~/tmp]$
```

I changed the python code to
```
#b.attach_uprobe(name="/usr/lib64/libc.so.6",
                #sym="__libc_start_main",
                #fn_name="do_libc_main")
b.attach_uprobe(name="/home/yhs/tmp/bin",
                sym="main",
                fn_name="do_binary_main")
```
The /home/yhs/tmp/bin is run on a different terminal,
```
[yhs@devvm1886.ftw0 ~/tmp]$ /home/yhs/tmp/bin
hello
[yhs@devvm1886.ftw0 ~/tmp]$ /home/yhs/tmp/bin
hello
[yhs@devvm1886.ftw0 ~/tmp]$
[yhs@devvm1886.ftw0 ~/tmp]$ nm bin | grep main
                 U __libc_start_main@@GLIBC_2.2.5
0000000000400626 T main
[yhs@devvm1886.ftw0 ~/tmp]$
```
With `sudo bpftool perf` should see something like below
```
pid 377904  fd 5: prog_id 521965  uprobe  filename /home/yhs/tmp/bin  offset 1574
```
basically there is uprobe for /home/yhs/tmp/bin. You can verify file offset against elf file.

**Comment by nalzok** [comment]
> You can verify file offset against elf file.

Surprisingly, the offset is actually right. Somehow `watchpoint` fires but `uprobe` doesn't.

```
$ nm bin | grep main
                 U __libc_start_main@@GLIBC_2.2.5
0000000000400507 T main

$ sudo bpftrace -e 'uprobe:/tmp/bin:0x400507 { printf("main called\n"); }' -c /tmp/bin
Attaching 1 probe...
hello

$ sudo bpftrace -e 'watchpoint::0x400507:8:x { printf("main called\n"); }' -c /tmp/bin
Attaching 1 probe...
main called
hello
```

Given this

```
$ sudo bpftool perf
Error: perf_query_support: Invalid argument
HINT: non root or kernel doesn't support TASK_FD_QUERY
```

and your experience

> I cannot reproduce this issue with centos with 5.6 kernel.

I thought the issue is due to the hopelessly outdated kernel. However, attaching to `/bin/bash:main` does work, so there must be some kernel support.
