### ISSUE TITLE
cpudist on i586: error: no member named 'ds' in 'pt_regs'

### ISSUE THREAD

**Issue by vt-alt** [iovisor/bcc#3241]
`cpudist` run fails on i586 (linux 5.10.10 in qemu-system-i386 v5.2.0):
```
builder@i586:~/RPM/BUILD/bcc-0.18.0# /usr/src/tmp/bcc-buildroot/usr/share/bcc/tools/cpudist 1 1
In file included from /virtual/main.c:1:
In file included from include/uapi/linux/ptrace.h:143:
arch/x86/include/asm/ptrace.h:240:16: error: no member named 'ds' in 'pt_regs'
            offset == offsetof(struct pt_regs, ds) ||
                      ^                        ~~
include/linux/stddef.h:17:32: note: expanded from macro 'offsetof'
#define offsetof(TYPE, MEMBER)  __compiler_offsetof(TYPE, MEMBER)
                                ^                         ~~~~~~
include/linux/compiler_types.h:135:35: note: expanded from macro '__compiler_offsetof'
#define __compiler_offsetof(a, b)       __builtin_offsetof(a, b)
                                        ^                     ~
In file included from /virtual/main.c:1:
In file included from include/uapi/linux/ptrace.h:143:
arch/x86/include/asm/ptrace.h:241:16: error: no member named 'es' in 'pt_regs'
            offset == offsetof(struct pt_regs, es) ||
                      ^                        ~~
include/linux/stddef.h:17:32: note: expanded from macro 'offsetof'
#define offsetof(TYPE, MEMBER)  __compiler_offsetof(TYPE, MEMBER)
                                ^                         ~~~~~~
include/linux/compiler_types.h:135:35: note: expanded from macro '__compiler_offsetof'
#define __compiler_offsetof(a, b)       __builtin_offsetof(a, b)
                                        ^                     ~
In file included from /virtual/main.c:1:
In file included from include/uapi/linux/ptrace.h:143:
arch/x86/include/asm/ptrace.h:242:16: error: no member named 'fs' in 'pt_regs'
            offset == offsetof(struct pt_regs, fs) ||
                      ^                        ~~
include/linux/stddef.h:17:32: note: expanded from macro 'offsetof'
#define offsetof(TYPE, MEMBER)  __compiler_offsetof(TYPE, MEMBER)
                                ^                         ~~~~~~
include/linux/compiler_types.h:135:35: note: expanded from macro '__compiler_offsetof'
#define __compiler_offsetof(a, b)       __builtin_offsetof(a, b)
                                        ^                     ~
In file included from /virtual/main.c:1:
In file included from include/uapi/linux/ptrace.h:143:
arch/x86/include/asm/ptrace.h:243:16: error: no member named 'gs' in 'pt_regs'
            offset == offsetof(struct pt_regs, gs)) {
                      ^                        ~~
include/linux/stddef.h:17:32: note: expanded from macro 'offsetof'
#define offsetof(TYPE, MEMBER)  __compiler_offsetof(TYPE, MEMBER)
                                ^                         ~~~~~~
include/linux/compiler_types.h:135:35: note: expanded from macro '__compiler_offsetof'
#define __compiler_offsetof(a, b)       __builtin_offsetof(a, b)
                                        ^                     ~
4 errors generated.
Traceback (most recent call last):
  File "/usr/src/tmp/bcc-buildroot/usr/share/bcc/tools/cpudist", line 161, in <module>
    b = BPF(text=bpf_text, cflags=["-DMAX_PID=%d" % max_pid])
  File "/usr/src/tmp/bcc-buildroot/usr/lib/python3/site-packages/bcc/__init__.py", line 364, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```
Same run succeeds on x86_64.

**Comment by vt-alt** [comment]
For context - we have simple run test in qemu after building `bcc` on all supported arches. There is [transient] build log for i586: http://git.altlinux.org/tasks/265190/build/100/i586/log (quoted above).

But, it seems, failure goes on all 32-bit arches (i586 and ARM), however error output on ARM is quite different: http://git.altlinux.org/tasks/265190/build/100/armh/log (Maybe this should be different issue.)

**Comment by yonghong-song** [comment]
@vt-alt  Right, unfortunately bcc does not really support 32bit architectures as there is no effort to make it work. Most of people does not use 32bit systems either. If you are interested, maybe you can help debug the issues and propose fixes? Thanks!
