### ISSUE TITLE
asm __inline usage on newer kernels (5.10.x)

### ISSUE THREAD

**Issue by rostamn739** [iovisor/bcc#3244]

**Comment by yonghong-song** [comment]
I have not tried to reproduce the issue yet, could you paste the details of the error?
Also, could you try the following patch to see whether it works for your or not?
```
diff --git a/src/cc/export/helpers.h b/src/cc/export/helpers.h
index 0447a956..a0388729 100644
--- a/src/cc/export/helpers.h
+++ b/src/cc/export/helpers.h
@@ -25,6 +25,11 @@ R"********(
 #define asm_inline asm
 #endif
 
+#ifdef __inline
+#undef __inline
+#define __inline
+#endif
+
 /* Before bpf_helpers.h is included, uapi bpf.h has been
  * included, which references linux/types.h. This may bring
  * in asm_volatile_goto definition if permitted based on
```

**Comment by frukto** [comment]
I think I see the same problem on Debian Buster (`Linux 5.10.0-0.bpo.3-amd64`), also may be related: https://gitlab.com/gitlab-com/gl-infra/infrastructure/-/issues/12052

```
/usr/sbin/cachestat-bpfcc

In file included from /virtual/main.c:2:
In file included from include/uapi/linux/ptrace.h:143:
In file included from ./arch/x86/include/asm/ptrace.h:5:
./arch/x86/include/asm/segment.h:262:2: error: expected '(' after 'asm'
        alternative_io ("lsl %[seg],%[p]",
        ^
./arch/x86/include/asm/alternative.h:240:2: note: expanded from macro 'alternative_io'
        asm_inline volatile (ALTERNATIVE(oldinstr, newinstr, feature)   \
        ^
include/linux/compiler_types.h:245:24: note: expanded from macro 'asm_inline'
#define asm_inline asm __inline
                       ^
1 error generated.
Traceback (most recent call last):
  File "/usr/sbin/cachestat-bpfcc", line 95, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 320, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text
```

**Comment by yonghong-song** [comment]
Does latest bcc (bcc trunk) still have the issue? It should have been fixed with the following patch
```
commit 2d1497cde1cc9835f759a707b42dea83bee378b8
Author: Ivan Babrou <ibobrik@gmail.com>
Date:   Thu Oct 10 20:24:21 2019 -0700

    Redefine asm_inline for Linux 5.4+, Fixes #2546 (#2547)
    
    Here's the upstream commit that introduced `asm_inline`:
    
    * https://github.com/torvalds/linux/commit/eb111869301e15b737315a46c913ae82bd19eb9d
    
    Without this patch BCC fails with the following:
    
    ```
    $ sudo /usr/share/bcc/tools/opensnoop
    In file included from /virtual/main.c:2:
    In file included from include/uapi/linux/ptrace.h:142:
    In file included from ./arch/x86/include/asm/ptrace.h:5:
    ./arch/x86/include/asm/segment.h:254:2: error: expected '(' after 'asm'
            alternative_io ("lsl %[seg],%[p]",
            ^
    ./arch/x86/include/asm/alternative.h:240:2: note: expanded from macro 'alternative_io'
            asm_inline volatile (ALTERNATIVE(oldinstr, newinstr, feature)   \
            ^
    include/linux/compiler_types.h:210:24: note: expanded from macro 'asm_inline'
                           ^
```

**Comment by dilfish** [comment]
I fixed this issue by undefined asm_inline

/usr/src/linux-headers-5.10.5-051005-generic/include/linux/compiler_types.h +245

244 #ifdef CONFIG_CC_HAS_ASM_INLINE
245 #define asm_inline asm
246 #else
247 #define asm_inline asm
248 #endif

**Comment by ESWZY** [comment]
There is a workround in [`samples/bpf/asm_goto_workaround.h`](https://github.com/torvalds/linux/blob/f443e374ae131c168a065ea1748feac6b2e76613/samples/bpf/asm_goto_workaround.h#L17).

```
/*
 * asm_inline is defined as asm __inline in "include/linux/compiler_types.h"
 * if supported by the kernel's CC (i.e CONFIG_CC_HAS_ASM_INLINE) which is not
 * supported by CLANG.
 */
#ifdef asm_inline
#undef asm_inline
#define asm_inline asm
#endif
```
