### ISSUE TITLE
Error running samples

### ISSUE THREAD

**Issue by namespaceXP** [iovisor/bcc#3329]
Below is the output.

# sudo /usr/share/bcc/tools/execsnoop
In file included from <built-in>:2:
/virtual/include/bcc/bpf.h:67:2: error: unknown type name '__u8'
        __u8    code;           /* opcode */
        ^
/virtual/include/bcc/bpf.h:68:2: error: unknown type name '__u8'
        __u8    dst_reg:4;      /* dest register */
        ^
/virtual/include/bcc/bpf.h:69:2: error: unknown type name '__u8'
        __u8    src_reg:4;      /* source register */
        ^
/virtual/include/bcc/bpf.h:70:2: error: unknown type name '__s16'
        __s16   off;            /* signed offset */
        ^
/virtual/include/bcc/bpf.h:71:2: error: unknown type name '__s32'
        __s32   imm;            /* signed immediate constant */
        ^
/virtual/include/bcc/bpf.h:76:2: error: unknown type name '__u32'
        __u32   prefixlen;      /* up to 32 for AF_INET, 128 for AF_INET6 */
        ^
/virtual/include/bcc/bpf.h:77:2: error: unknown type name '__u8'
        __u8    data[0];        /* Arbitrary size */
        ^
/virtual/include/bcc/bpf.h:81:2: error: unknown type name '__u64'
        __u64   cgroup_inode_id;        /* cgroup inode id */
        ^
/virtual/include/bcc/bpf.h:82:2: error: unknown type name '__u32'
        __u32   attach_type;            /* program attach type */
        ^
/virtual/include/bcc/bpf.h:87:3: error: unknown type name '__u32'
                __u32   map_fd;
                ^
/virtual/include/bcc/bpf.h:435:2: error: unknown type name '__s32'
        __s32           status;
        ^
/virtual/include/bcc/bpf.h:438:3: error: unknown type name '__u64'
                __u64   offset;
                ^
/virtual/include/bcc/bpf.h:439:3: error: unknown type name '__u64'
                __u64   ip;
                ^
/virtual/include/bcc/bpf.h:447:3: error: unknown type name '__u32'
                __u32   map_type;       /* one of enum bpf_map_type */
                ^
/virtual/include/bcc/bpf.h:448:3: error: unknown type name '__u32'
                __u32   key_size;       /* size of key in bytes */
                ^
/virtual/include/bcc/bpf.h:449:3: error: unknown type name '__u32'
                __u32   value_size;     /* size of value in bytes */
                ^
/virtual/include/bcc/bpf.h:450:3: error: unknown type name '__u32'
                __u32   max_entries;    /* max number of entries in a map */
                ^
/virtual/include/bcc/bpf.h:451:3: error: unknown type name '__u32'
                __u32   map_flags;      /* BPF_MAP_CREATE related
                ^
/virtual/include/bcc/bpf.h:454:3: error: unknown type name '__u32'
                __u32   inner_map_fd;   /* fd pointing to the inner map */
                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/execsnoop", line 227, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 364, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

**Comment by xiaobo55x** [comment]
Got same error! Any one have a solution on this?
