### ISSUE TITLE
Is it possible to create a new map and pin it to bpffs as FILE.

### ISSUE THREAD

**Issue by chenyuezhou** [iovisor/bcc#3373]

**Comment by yonghong-song** [comment]
You can try to use BPF_TABLE_PINNED.
```
$ egrep -r BPF_TABLE_PINNED                                                               
docs/reference_guide.md:Maps that were pinned to the BPF filesystem can be accessed through an extended syntax: ```BPF_TA
BLE_PINNED(_table_type, _key_type, _leaf_type, _name, _max_entries, "/sys/fs/bpf/xyz")```                                
docs/reference_guide.md:BPF_TABLE_PINNED("hash", u64, u64, ids, 1024, "/sys/fs/bpf/ids");                                
src/python/bcc/containers.py:    BPF_TABLE_PINNED("hash", u64, u64, cgroupset, 1024, "CGROUP_PATH");                     
src/python/bcc/containers.py:    BPF_TABLE_PINNED("hash", u64, u32, mount_ns_set, 1024, "MOUNT_NS_PATH");
src/cc/export/helpers.h:#define BPF_TABLE_PINNED(_table_type, _key_type, _leaf_type, _name, _max_entries, _pinned) \
tests/cc/test_pinned_table.cc:      BPF_TABLE_PINNED("hash", u64, u64, ids, 1024, "/sys/fs/bpf/test_pinned_table");
tests/cc/test_pinned_table.cc:      BPF_TABLE_PINNED("hash", u64, u64, ids, 1024, "/sys/fs/bpf/test_pinned_table");
```

**Comment by chenyuezhou** [comment]
> You can try to use BPF_TABLE_PINNED.
> 
> ```
> $ egrep -r BPF_TABLE_PINNED                                                               
> docs/reference_guide.md:Maps that were pinned to the BPF filesystem can be accessed through an extended syntax: ```BPF_TA
> BLE_PINNED(_table_type, _key_type, _leaf_type, _name, _max_entries, "/sys/fs/bpf/xyz")```                                
> docs/reference_guide.md:BPF_TABLE_PINNED("hash", u64, u64, ids, 1024, "/sys/fs/bpf/ids");                                
> src/python/bcc/containers.py:    BPF_TABLE_PINNED("hash", u64, u64, cgroupset, 1024, "CGROUP_PATH");                     
> src/python/bcc/containers.py:    BPF_TABLE_PINNED("hash", u64, u32, mount_ns_set, 1024, "MOUNT_NS_PATH");
> src/cc/export/helpers.h:#define BPF_TABLE_PINNED(_table_type, _key_type, _leaf_type, _name, _max_entries, _pinned) \
> tests/cc/test_pinned_table.cc:      BPF_TABLE_PINNED("hash", u64, u64, ids, 1024, "/sys/fs/bpf/test_pinned_table");
> tests/cc/test_pinned_table.cc:      BPF_TABLE_PINNED("hash", u64, u64, ids, 1024, "/sys/fs/bpf/test_pinned_table");
> ```

Thanks.  @yonghong-song But what i really want is to create a new map if it doesn't exist and pin it to the bpffs as a FILE, otherwise use the map that is pinned to the bpffs. 

```
$ll /sys/fs/bpf
total 0
```

```
$python -c "import bcc; bcc.BPF(text='BPF_TABLE_PINNED(\"hash\", u64, u64, test, 1024, \"/sys/fs/bpf/test\");')"
/virtual/main.c:1:1: error: map not found: /sys/fs/bpf/test
BPF_TABLE_PINNED("hash", u64, u64, test, 1024, "/sys/fs/bpf/test");
^
/virtual/include/bcc/helpers.h:160:92: note: expanded from macro 'BPF_TABLE_PINNED'
#define BPF_TABLE_PINNED(_table_type, _key_type, _leaf_type, _name, _max_entries, _pinned) \
                                                                                           ^
/virtual/include/bcc/helpers.h:157:76: note: expanded from macro '\
BPF_TABLE'
#define BPF_TABLE(_table_type, _key_type, _leaf_type, _name, _max_entries) \
                                                                           ^
/virtual/include/bcc/helpers.h:107:4: note: expanded from macro '\
BPF_F_TABLE'
}; \
   ^
1 error generated.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 364, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

I want it to look like this

```
$bpftool map create /sys/fs/bpf/test type hash key 8 value 8 entries 1024 name test
```

```
$ll /sys/fs/bpf
total 0
-rw-------. 1 root root 0 Apr 25 20:55 test
```

```
bpftool map -p
[{
        "id": 1479,
        "type": "hash",
        "name": "test",
        "flags": 0,
        "bytes_key": 8,
        "bytes_value": 8,
        "max_entries": 1024,
        "bytes_memlock": 86016,
        "frozen": 0
    }
]
```

```
$python -c "import bcc; bcc.BPF(text='BPF_TABLE_PINNED(\"hash\", u64, u64, test, 1024, \"/sys/fs/bpf/test\");')"
```

**If the map does not exist, create a new map and pin it to bpffs as FILE, else  use the maps that were pinned to the bpffs.**

**Comment by yonghong-song** [comment]
This can be improved in rewriter.
Currently, we have
```
    if (pinned_path_pos != std::string::npos) {
      std::string pinned = section_attr.substr(pinned_path_pos + 1);
      section_attr = section_attr.substr(0, pinned_path_pos);
      int fd = bpf_obj_get(pinned.c_str());
      struct bpf_map_info info = {};
      unsigned int info_len = sizeof(info);
      
      if (bpf_obj_get_info_by_fd(fd, &info, &info_len)) {
        error(GET_BEGINLOC(Decl), "map not found: %0") << pinned;
        return false;
      } 
      
      close(fd);
      pinned_id = info.id;
    }
```
We assume bpf_obj_get() returns a valid fd. I think we can check whether the fd is valid or not. If it is not valid, you can create a map here. You may need to reorganize the code a little to get all map attributes in order to create a map though. Do you want to investigate and submit a pull request to support this feature?

**Comment by chenyuezhou** [comment]
Of course. I'll give it a try.
