### ISSUE TITLE
After installing bcc, run the command and report an error

### ISSUE THREAD

**Issue by jony-one** [iovisor/bcc#3386]
environment：
```bash
$ cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

$ uname -r
4.11.1-1.el7.elrepo.x86_64

$ tcpconnect
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module) or installing the kernel development package for your running kernel version.
chdir(/lib/modules/4.11.1-1.el7.elrepo.x86_64/build): No such file or directory
Traceback (most recent call last):  File "/usr/share/bcc/tools/tcpconnect", line 301, in <module>    b = BPF(text=bpf_text)  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 358, in __init__    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))Exception: Failed to compile BPF module <text>

$ ls -l /usr/src/kernels/
drwxr-xr-x 22 root root 4096 Apr 28 23:22 3.10.0-1127.18.2.el7.x86_64
drwxr-xr-x 23 root root 4096 Apr 27 18:18 4.11.1-1.el7.elrepo.x86_64

$ ls /lib/modules
```

i cannot found  `4.11.1-1.el7.elrepo.x86_64` source 

Any suggestions

**Comment by chenhengqi** [comment]
try install kernel headers:

```
yum install kernel-headers
```

**Comment by jony-one** [comment]
> try install kernel headers:
> 
> ```
> yum install kernel-headers
> ```

i do it,but install kernel-headers don't  solve this ask

**Comment by michaelgugino** [comment]
The error message is confusing.  You actually need to `yum install kernel-devel-$(uname)`

The headers message is about newer kernels that provide a module called kheaders which is loaded if the kernel source (from kernel-devel package) is not found.  I'm not sure why bcc-tools can use headers only with newer distros, seems like a bug.
