### ISSUE TITLE
AttributeError: 'BPF' object has no attribute 'perf_buffer_poll'

### ISSUE THREAD

**Issue by waectr** [iovisor/bcc#3397]
Today I encountered this problem in the waiting time block while writing the sql slow query.
this is Error.
`Traceback (most recent call last): 
  File "slowquery.py", line 115, in <module> 
    bpf.perf_buffer_poll() 
AttributeError: 'BPF' object has no attribute 'perf_buffer_poll' 
`

**Comment by waectr** [comment]
Traceback (most recent call last):
  File "slowquery1.py", line 115, in <module>
    bpf.perf_buffer_poll()
AttributeError: 'BPF' object has no attribute 'perf_buffer_poll'

**Comment by waectr** [comment]
Traceback (most recent call last):
   File "slowquery1.py", line 115, in <module>
     bpf.perf_buffer_poll()
AttributeError: 'BPF' object has no attribute 'perf_buffer_poll'

**Comment by yonghong-song** [comment]
Maybe this is an installation issue? Mixing pre-installed or built-from-source ones? Maybe you can double check where the bcc python codes are installed and whether it is aligned with your python version?
