### ISSUE TITLE
memleak: could not determine address of symbol malloc

### ISSUE THREAD

**Issue by martinvonwittich** [iovisor/bcc#3432]
I recently discovered a memory leak issue in `php7.3-fpm` on our production servers due to an outdated [Ioncube loader](https://www.ioncube.com/loaders.php). I wanted to see if I could discover the known issue using `memleak`, but I can't get it to work:

```
server ~ # memleak-bpfcc -p 9268
Attaching to pid 9268, Ctrl+C to quit.
Traceback (most recent call last):
  File "/usr/sbin/memleak-bpfcc", line 416, in <module>
    attach_probes("malloc")
  File "/usr/sbin/memleak-bpfcc", line 406, in attach_probes
    pid=pid)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 982, in attach_uprobe
    (path, addr) = BPF._check_path_symbol(name, sym, addr, pid)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 727, in _check_path_symbol
    raise Exception("could not determine address of symbol %s" % symname)
Exception: could not determine address of symbol malloc
```

I thought that installing the `libc6-dbg` package should enable it to locate `malloc`, but apparently it doesn't.

Normal tracing works fine though:

```
server ~ # trace-bpfcc -p 9268 'c:malloc' | head
PID     TID     COMM            FUNC             
9268    9268    php-fpm7.3      malloc           
9268    9268    php-fpm7.3      malloc           
9268    9268    php-fpm7.3      malloc           
9268    9268    php-fpm7.3      malloc           
9268    9268    php-fpm7.3      malloc           
9268    9268    php-fpm7.3      malloc           
9268    9268    php-fpm7.3      malloc           
9268    9268    php-fpm7.3      malloc           
9268    9268    php-fpm7.3      malloc           
```

```
server ~ # lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

server ~ # apt-cache policy php7.3-fpm
php7.3-fpm:
  Installiert:           7.3.27-1~deb10u1
  Installationskandidat: 7.3.27-1~deb10u1
  Versionstabelle:
 *** 7.3.27-1~deb10u1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        500 http://deb.debian.org/debian-security buster/updates/main amd64 Packages
        100 /var/lib/dpkg/status

server ~ # apt-cache policy libc6-dbg  
libc6-dbg:
  Installiert:           2.28-10
  Installationskandidat: 2.28-10
  Versionstabelle:
 *** 2.28-10 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by yonghong-song** [comment]
This needs to be debugged. I am not sure why either. But from the clue from trace.py, maybe you can specify the object path (libc library) with
```
parser.add_argument("-O", "--obj", type=str, default="c",
        help="attach to allocator functions in the specified object")
```
Maybe somehow default "c" won't work any more? In trace.py, we do try to find the library path `libpath = BPF.find_library(self.library)`.

**Comment by martinvonwittich** [comment]
Yep, this worked:

```
memleak-bpfcc -p <pid> -O /lib/x86_64-linux-gnu/libc-2.28.so
```

No idea why it was necessary though, and I also can't reproduce the issue on my test server.

**Comment by jessequinn** [comment]
I am also having this issue. `memleak-bpfcc -p <pid> -O <static linked object> did not work.`
