### ISSUE TITLE
attach_tracepoint seems to be not work

### ISSUE THREAD

**Issue by masibw** [iovisor/bcc#3521]
Hi, When I using the `TRACEPOINT_PROBE` macro the bpf program works. But When I using `b.attach_tracepoint()` the bpf program doesn't work.

This program works.
```#!/usr/bin/python
from bcc import BPF
from bcc.utils import printb

# define BPF program
bpf_text= """
TRACEPOINT_PROBE(syscalls, sys_enter_socket){
bpf_trace_printk("%d",args->protocol);
return 0;
}
"""

b = BPF(text=bpf_text)
b.trace_print()
```

This program doesn't work.
```
#!/usr/bin/python
from bcc import BPF
from bcc.utils import printb

# define BPF program
bpf_text= """
#include <linux/sched.h>
int trace_socket(struct pt_regs *ctx, int family, int type, int protocol) {
bpf_trace_printk("%d",protocol);
return 0;
}
"""

b = BPF(text=bpf_text)
b.attach_tracepoint("syscalls:sys_enter_socket", "trace_socket")
b.trace_print()

```

My environment is `Ubuntu 20.04, 5.10.0-1016-oem`

Any errors don't print. But I wrote this program by gobpf, the output is 
```
ioctl(PERF_EVENT_IOC_SET_BPF): Permission denied
```

**Comment by chenhengqi** [comment]
`attach_tracepoint` has named arguments, not positional arguments. So you need to have this instead:

```python
b.attach_tracepoint(tp="syscalls:sys_enter_socket", fn_name="trace_socket")
```

**Comment by masibw** [comment]
thanks to reply @chenhengqi 
Now I'm  using following code, but I got same error.
```Python
#!/usr/bin/python
from bcc import BPF
from bcc.utils import printb

# define BPF program
bpf_text= """
#include <linux/sched.h>
int trace_socket(struct pt_regs *ctx, int family, int type, int protocol) {
bpf_trace_printk("%d",protocol);
return 0;
}
"""

b = BPF(text=bpf_text)
b.attach_tracepoint(tp="syscalls:sys_enter_socket", fn_name="trace_socket")
b.trace_print()

```
ioctl(PERF_EVENT_IOC_SET_BPF): Permission denied
Traceback (most recent call last):
  File "./trace_clone.py", line 15, in <module>
    b.attach_tracepoint(tp="syscalls:sys_enter_socket", fn_name="trace_socket")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 978, in attach_tracepoint
    raise Exception("Failed to attach BPF program %s to tracepoint %s" %
Exception: Failed to attach BPF program b'trace_socket' to tracepoint b'syscalls:sys_enter_socket'
```

**Comment by chenhengqi** [comment]
Try this:
```c
struct args {
        __u64 x;
        int __syscall_nr;
        int family;
        int type;
        int protocol;
};

int trace_socket(struct args *args) {
        bpf_trace_printk("socket: %d\\n", args->family);
        return 0;
}
```

**Comment by chenhengqi** [comment]
You need to define an argument struct which match the expected format.

```shell
$ cat /sys/kernel/debug/tracing/events/syscalls/sys_enter_socket/format
```

BCC does that for you.

**Comment by masibw** [comment]
>Try this:

It works, thank you!

>BCC does that for you.

It seems counter-intuitive that Tracepoint needs to be defined while kprobe and others do not need to be predefined. Is this a specification? Is it a bug?

**Comment by chenhengqi** [comment]
Tracepoint follows the convention defined by kernel, while kprobe just follows the system ABI (struct pt_regs *ctx).

**Comment by masibw** [comment]
I see. How about writing that in https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#3-tracepoints?
