### ISSUE TITLE
error: incomplete definition of type 'struct tracepoint__raw_syscalls__sys_exit'

### ISSUE THREAD

**Issue by seehearfeel** [iovisor/bcc#3526]
```
# /usr/share/bcc/tools/syscount 
/virtual/main.c:29:1: warning: declaration of 'struct tracepoint__raw_syscalls__sys_exit' will not be visible outside of this function [-Wvisibility]
TRACEPOINT_PROBE(raw_syscalls, sys_exit) {
^
/virtual/include/bcc/helpers.h:1263:46: note: expanded from macro 'TRACEPOINT_PROBE'
int tracepoint__##category##__##event(struct tracepoint__##category##__##event *args)
                                             ^
<scratch space>:142:1: note: expanded from here
tracepoint__raw_syscalls__sys_exit
^
/virtual/main.c:50:19: error: incomplete definition of type 'struct tracepoint__raw_syscalls__sys_exit'
    u32 key = args->id;
              ~~~~^
/virtual/main.c:29:1: note: forward declaration of 'struct tracepoint__raw_syscalls__sys_exit'
TRACEPOINT_PROBE(raw_syscalls, sys_exit) {
^
/virtual/include/bcc/helpers.h:1263:46: note: expanded from macro 'TRACEPOINT_PROBE'
int tracepoint__##category##__##event(struct tracepoint__##category##__##event *args)
                                             ^
<scratch space>:142:1: note: expanded from here
tracepoint__raw_syscalls__sys_exit
^
1 warning and 1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/syscount", line 165, in <module>
    bpf = BPF(text=text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 452, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

# cat /sys/kernel/debug/tracing/events/raw_syscalls/sys_exit/format 
name: sys_exit
ID: 21
format:
	field:unsigned short common_type;	offset:0;	size:2;	signed:0;
	field:unsigned char common_flags;	offset:2;	size:1;	signed:0;
	field:unsigned char common_preempt_count;	offset:3;	size:1;	signed:0;
	field:int common_pid;	offset:4;	size:4;	signed:1;

	field:long id;	offset:8;	size:8;	signed:1;
	field:long ret;	offset:16;	size:8;	signed:1;

print fmt: "NR %ld = %ld", REC->id, REC->ret
```

Any comment is appreciated, thank you.

**Comment by yonghong-song** [comment]
Could you make the following change to the tool so the amended source code can be printed out?
```
--- a/tools/syscount.py
+++ b/tools/syscount.py
@@ -162,7 +162,7 @@ if args.ebpf:
     print(text)
     exit()
 
-bpf = BPF(text=text)
+bpf = BPF(text=text, debug=4)
 
 def print_stats():
     if args.latency:
```

Which bcc version you are using? Maybe you want to check whether latest source-built bcc to see whether it works?

**Comment by seehearfeel** [comment]
Thank you yonghong.

I use the latest bcc and modify architecture related code for a new unsupported architecture loongarch64, examples/hello_world.py, tools/execsnoop, tools/opensnoop work well, tools/syscount has the above issue. 
I add "#include <trace/events/syscalls.h>" referenced with the issue 374,  but it has no effect.
https://github.com/iovisor/bcc/issues/374,

The output with debug=4:

`root@linux:/home/loongson# /usr/share/bcc/tools/syscount 
Running from kernel directory at: /lib/modules/4.19.190+/source
clang -cc1 -triple loongarch64-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model pic -pic-level 1 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu gs464v -target-feature -noabicalls -target-abi lp64 -mfloat-abi hard -dwarf-column-info -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /home/loongson/linux419.git/main.gcno -nostdsysteminc -nobuiltininc -resource-dir lib/clang/8.0.1 -isystem /virtual/lib/clang/include -include ./include/linux/kconfig.h -include /virtual/include/bcc/bpf.h -include /virtual/include/bcc/bpf_workaround.h -include /virtual/include/bcc/helpers.h -isystem /virtual/include -I /home/loongson -D __BPF_TRACING__ -I arch/loongarch/include/ -I /lib/modules/4.19.190+/build/arch/loongarch/include/generated -I include -I /lib/modules/4.19.190+/build/include -I arch/loongarch/include/uapi -I /lib/modules/4.19.190+/build/arch/loongarch/include/generated/uapi -I include/uapi -I /lib/modules/4.19.190+/build/include/generated/uapi -I arch/loongarch/include/asm/mach-la64 -I arch/loongarch/include/asm/mach-generic -D __KERNEL__ -D KBUILD_MODNAME="bcc" -O2 -Wno-deprecated-declarations -Wno-gnu-variable-sized-type-not-at-end -Wno-pragma-once-outside-header -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-unused-value -Wno-pointer-sign -fdebug-compilation-dir /home/loongson/linux419.git -ferror-limit 19 -fmessage-length 190 -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o main.bc -x c /virtual/main.c -faddrsig
/virtual/main.c:31:1: warning: declaration of 'struct tracepoint__raw_syscalls__sys_exit' will not be visible outside of this function [-Wvisibility]
TRACEPOINT_PROBE(raw_syscalls, sys_exit) {
^
/virtual/include/bcc/helpers.h:1263:46: note: expanded from macro 'TRACEPOINT_PROBE'
int tracepoint__##category##__##event(struct tracepoint__##category##__##event *args)
                                             ^
<scratch space>:148:1: note: expanded from here
tracepoint__raw_syscalls__sys_exit
^
/virtual/main.c:52:19: error: incomplete definition of type 'struct tracepoint__raw_syscalls__sys_exit'
    u32 key = args->id;
              ~~~~^
/virtual/main.c:31:1: note: forward declaration of 'struct tracepoint__raw_syscalls__sys_exit'
TRACEPOINT_PROBE(raw_syscalls, sys_exit) {
^
/virtual/include/bcc/helpers.h:1263:46: note: expanded from macro 'TRACEPOINT_PROBE'
int tracepoint__##category##__##event(struct tracepoint__##category##__##event *args)
                                             ^
<scratch space>:148:1: note: expanded from here
tracepoint__raw_syscalls__sys_exit
^
#if defined(BPF_LICENSE)
#error BPF_LICENSE cannot be specified through cflags
#endif
#if !defined(CONFIG_CC_STACKPROTECTOR)
#if defined(CONFIG_CC_STACKPROTECTOR_AUTO) \
    || defined(CONFIG_CC_STACKPROTECTOR_REGULAR) \
    || defined(CONFIG_CC_STACKPROTECTOR_STRONG)
#define CONFIG_CC_STACKPROTECTOR
#endif
#endif
#define bpf_probe_read_kernel bpf_probe_read
#define bpf_probe_read_kernel_str bpf_probe_read_str
#define bpf_probe_read_user bpf_probe_read
#define bpf_probe_read_user_str bpf_probe_read_str

#include <trace/events/syscalls.h>

#ifdef LATENCY
struct data_t {
    u64 count;
    u64 total_ns;
};

BPF_HASH(start, u64, u64);
BPF_HASH(data, u32, struct data_t);
#else
BPF_HASH(data, u32, u64);
#endif

#ifdef LATENCY
TRACEPOINT_PROBE(raw_syscalls, sys_enter) {
    u64 pid_tgid = bpf_get_current_pid_tgid();

#ifdef FILTER_PID
    if (pid_tgid >> 32 != FILTER_PID)
        return 0;
#endif

    u64 t = bpf_ktime_get_ns();
    start.update(&pid_tgid, &t);
    return 0;
}
#endif

TRACEPOINT_PROBE(raw_syscalls, sys_exit) {

    u64 pid_tgid = bpf_get_current_pid_tgid();

#ifdef FILTER_PID
    if (pid_tgid >> 32 != FILTER_PID)
        return 0;
#endif

#ifdef FILTER_FAILED
    if (args->ret >= 0)
        return 0;
#endif

#ifdef FILTER_ERRNO
    if (args->ret != -FILTER_ERRNO)
        return 0;
#endif

#ifdef BY_PROCESS
    u32 key = pid_tgid >> 32;
#else
    u32 key = args->id;
#endif

#ifdef LATENCY
    struct data_t *val, zero = {};
    u64 *start_ns = start.lookup(&pid_tgid);
    if (!start_ns)
        return 0;

    val = data.lookup_or_try_init(&key, &zero);
    if (val) {
        val->count++;
        val->total_ns += bpf_ktime_get_ns() - *start_ns;
    }
#else
    u64 *val, zero = 0;
    val = ({typeof(data.leaf) *leaf = bpf_map_lookup_elem_(bpf_pseudo_fd(1, -1), &key); if (!leaf) { bpf_map_update_elem_(bpf_pseudo_fd(1, -1), &key, &zero, BPF_NOEXIST); leaf = bpf_map_lookup_elem_(bpf_pseudo_fd(1, -1), &key);}leaf;});
    if (val) {
        ++(*val);
    }
#endif
    return 0;
}

#include <bcc/footer.h>
1 warning and 1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/syscount", line 167, in <module>
    bpf = BPF(text=text, debug=4)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 452, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>`

This issue is caused by bcc, clang, or kernel?

**Comment by seehearfeel** [comment]
@yonghong-song, I find out the similar issue https://github.com/iovisor/bcc/issues/2201,
you said the bcc cannot find the tracepoint, but in my case it seems the tracepoint exists.
```
root@linux:/home/loongson# cat /sys/kernel/debug/tracing/events/raw_syscalls/sys_exit/format 
name: sys_exit
ID: 21
format:
	field:unsigned short common_type;	offset:0;	size:2;	signed:0;
	field:unsigned char common_flags;	offset:2;	size:1;	signed:0;
	field:unsigned char common_preempt_count;	offset:3;	size:1;	signed:0;
	field:int common_pid;	offset:4;	size:4;	signed:1;

	field:long id;	offset:8;	size:8;	signed:1;
	field:long ret;	offset:16;	size:8;	signed:1;

print fmt: "NR %ld = %ld", REC->id, REC->ret
```

**Comment by seehearfeel** [comment]
The following output is correct on mips:
```
root@linux:/home/loongson# /usr/share/bcc/tools/syscount 
Running from kernel directory at: /lib/modules/4.19.190+/source
clang -cc1 -triple mips64el-unknown-linux-gnuabi64 -emit-llvm-bc -emit-llvm-uselists -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model pic -pic-level 1 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu mips64r2 -target-feature -noabicalls -target-abi n64 -mfloat-abi hard -dwarf-column-info -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /home/loongson/linux419.git/main.gcno -nostdsysteminc -nobuiltininc -resource-dir lib/clang/8.0.1 -isystem /virtual/lib/clang/include -include ./include/linux/kconfig.h -include /virtual/include/bcc/bpf.h -include /virtual/include/bcc/bpf_workaround.h -include /virtual/include/bcc/helpers.h -isystem /virtual/include -I /home/loongson -D __BPF_TRACING__ -D __MIPSEL__ -D _MIPS_SZLONG=64 -I arch/mips/include/ -I /lib/modules/4.19.190+/build/arch/mips/include/generated -I include -I /lib/modules/4.19.190+/build/include -I arch/mips/include/uapi -I /lib/modules/4.19.190+/build/arch/mips/include/generated/uapi -I include/uapi -I /lib/modules/4.19.190+/build/include/generated/uapi -I arch/mips/include/asm/mach-loongson64 -I arch/mips/include/asm/mach-generic -D __KERNEL__ -D KBUILD_MODNAME="bcc" -O2 -Wno-deprecated-declarations -Wno-gnu-variable-sized-type-not-at-end -Wno-pragma-once-outside-header -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-unused-value -Wno-pointer-sign -fdebug-compilation-dir /home/loongson/linux419.git -ferror-limit 19 -fmessage-length 190 -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o main.bc -x c /virtual/main.c -faddrsig
#if defined(BPF_LICENSE)
#error BPF_LICENSE cannot be specified through cflags
#endif
#if !defined(CONFIG_CC_STACKPROTECTOR)
#if defined(CONFIG_CC_STACKPROTECTOR_AUTO) \
    || defined(CONFIG_CC_STACKPROTECTOR_REGULAR) \
    || defined(CONFIG_CC_STACKPROTECTOR_STRONG)
#define CONFIG_CC_STACKPROTECTOR
#endif
#endif
#define bpf_probe_read_kernel bpf_probe_read
#define bpf_probe_read_kernel_str bpf_probe_read_str
#define bpf_probe_read_user bpf_probe_read
#define bpf_probe_read_user_str bpf_probe_read_str

#ifdef LATENCY
struct data_t {
    u64 count;
    u64 total_ns;
};

BPF_HASH(start, u64, u64);
BPF_HASH(data, u32, struct data_t);
#else
BPF_HASH(data, u32, u64);
#endif

#ifdef LATENCY
TRACEPOINT_PROBE(raw_syscalls, sys_enter) {
    u64 pid_tgid = bpf_get_current_pid_tgid();

#ifdef FILTER_PID
    if (pid_tgid >> 32 != FILTER_PID)
        return 0;
#endif

    u64 t = bpf_ktime_get_ns();
    start.update(&pid_tgid, &t);
    return 0;
}
#endif

struct tracepoint__raw_syscalls__sys_exit {
	u64 __do_not_use__;
	long id;
	long ret;
};
__attribute__((section(".bpf.fn.tracepoint__raw_syscalls__sys_exit")))
TRACEPOINT_PROBE(raw_syscalls, sys_exit) {

    u64 pid_tgid = bpf_get_current_pid_tgid();

#ifdef FILTER_PID
    if (pid_tgid >> 32 != FILTER_PID)
        return 0;
#endif

#ifdef FILTER_FAILED
    if (args->ret >= 0)
        return 0;
#endif

#ifdef FILTER_ERRNO
    if (args->ret != -FILTER_ERRNO)
        return 0;
#endif

#ifdef BY_PROCESS
    u32 key = pid_tgid >> 32;
#else
    u32 key = args->id;
#endif

#ifdef LATENCY
    struct data_t *val, zero = {};
    u64 *start_ns = start.lookup(&pid_tgid);
    if (!start_ns)
        return 0;

    val = data.lookup_or_try_init(&key, &zero);
    if (val) {
        val->count++;
        val->total_ns += bpf_ktime_get_ns() - *start_ns;
    }
#else
    u64 *val, zero = 0;
    val = ({typeof(data.leaf) *leaf = bpf_map_lookup_elem_(bpf_pseudo_fd(1, -1), &key); if (!leaf) { bpf_map_update_elem_(bpf_pseudo_fd(1, -1), &key, &zero, BPF_NOEXIST); leaf = bpf_map_lookup_elem_(bpf_pseudo_fd(1, -1), &key);}leaf;});
    if (val) {
        ++(*val);
    }
#endif
    return 0;
}

#include <bcc/footer.h>
Tracing syscalls, printing top 10... Ctrl+C to quit.
```
The difference is:
```
struct tracepoint__raw_syscalls__sys_exit {
	u64 __do_not_use__;
	long id;
	long ret;
};
__attribute__((section(".bpf.fn.tracepoint__raw_syscalls__sys_exit")))
```

**Comment by yonghong-song** [comment]
I don't know why mips works and loongson doesn't work. IIUC, loongson is a mips chip and they should behave the same in bcc.

In any case, I guess you probably need to debug by yourself. bcc/src/cc/frontends/clang/tp_frontend_action.cc is the file to generate the above tracepoint structure. The following code
in loader.cc,
```
  string out_str;
  llvm::raw_string_ostream os(out_str);
  TracepointFrontendAction tpact(os);
  compiler0.ExecuteAction(tpact); // ignore errors, they will be reported later
  unique_ptr<llvm::MemoryBuffer> out_buf = llvm::MemoryBuffer::getMemBuffer(out_str);
```
calls tracepoint structure generation.

**Comment by xen0n** [comment]
> I don't know why mips works and loongson doesn't work. IIUC, loongson is a mips chip and they should behave the same in bcc.

[LoongArch is not MIPS](https://github.com/loongson/LoongArch-Documentation) but a new RISC architecture. I think @seehearfeel should post their PR first so people at least have a clue what changes are there for the new port so to help debugging.

**Comment by yonghong-song** [comment]
@xen0n the following is the supported architecture,
```
typedef enum {
  BCC_ARCH_PPC,
  BCC_ARCH_PPC_LE,
  BCC_ARCH_S390X,
  BCC_ARCH_ARM64,
  BCC_ARCH_MIPS,
  BCC_ARCH_X86
} bcc_arch_t;
```
Some other places also need changes to support this new architecture. Mostly in src/cc/frontends/clang directory and helpers.h.

**Comment by xen0n** [comment]
> @xen0n the following is the supported architecture,
> ```
> typedef enum {
>   BCC_ARCH_PPC,
>   BCC_ARCH_PPC_LE,
>   BCC_ARCH_S390X,
>   BCC_ARCH_ARM64,
>   BCC_ARCH_MIPS,
>   BCC_ARCH_X86
> } bcc_arch_t;
> ```
> Some other places also need changes to support this new architecture. Mostly in src/cc/frontends/clang directory and helpers.h.

Yeah sure, Loongson people are porting many packages right now and I'm reviewing their work (at my free time; I'm not Loongson employee). I suppose they're able to see this helpful reply and I'll help reviewing the incoming PR as well.

**Comment by seehearfeel** [comment]
Hi Yonghong and xen0n,

Thank you for your discussions and suggestions.
With the following changes, tools/syscount works well.
```
diff --git a/tools/syscount.py b/tools/syscount.py
index 7ba08dd3..5f20a4a5 100755
--- a/tools/syscount.py
+++ b/tools/syscount.py
@@ -88,7 +88,7 @@ BPF_HASH(data, u32, u64);
 #endif
 
 #ifdef LATENCY
-TRACEPOINT_PROBE(raw_syscalls, sys_enter) {
+int tracepoint__raw_syscalls__sys_enter (struct tracepoint__raw_syscalls__sys_enter *args) {
     u64 pid_tgid = bpf_get_current_pid_tgid();
 
 #ifdef FILTER_PID
@@ -102,7 +102,7 @@ TRACEPOINT_PROBE(raw_syscalls, sys_enter) {
 }
 #endif
 
-TRACEPOINT_PROBE(raw_syscalls, sys_exit) {
+int tracepoint__raw_syscalls__sys_exit (struct tracepoint__raw_syscalls__sys_exit *args) {
     u64 pid_tgid = bpf_get_current_pid_tgid();
 
 #ifdef FILTER_PID
```

It seems that there exists some problems when expand TRACEPOINT_PROBE, I will look a bit deeper.

**Comment by xen0n** [comment]
@seehearfeel Without your in-progress draft PR we cannot make any sense out of your reports, could you please share a branch for preliminary reviews?

**Comment by seehearfeel** [comment]
https://github.com/iovisor/bcc/pull/3536
