### ISSUE TITLE
cpudist-bpfcc: 'asm goto' constructs are not supported yet

### ISSUE THREAD

**Issue by turingScholar** [iovisor/bcc#3535]
On arm64 ubuntu 18.04, I install the bpfcc-tools

Running cpudist-bpfcc, here is the error:

In file included from /virtual/main.c:1:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/uapi/linux/ptrace.h:107:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/arch/arm64/include/asm/ptrace.h:91:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/linux/bug.h:5:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/arch/arm64/include/asm/bug.h:37:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/asm-generic/bug.h:18:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/linux/kernel.h:14:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/linux/printk.h:336:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/linux/dynamic_debug.h:6:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/linux/jump_label.h:117:
/lib/modules/4.19.115-g0cfccb73c/build/arch/arm64/include/asm/jump_label.h:31:2: error: 'asm goto' constructs
      are not supported yet
        asm_volatile_goto("1: nop\n\t"
        ^
/lib/modules/4.19.115-g0cfccb73c/build/include/linux/compiler_types.h:155:37: note: expanded from macro
      'asm_volatile_goto'
#define asm_volatile_goto(x...) asm goto(x)
                                    ^
In file included from /virtual/main.c:1:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/uapi/linux/ptrace.h:107:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/arch/arm64/include/asm/ptrace.h:91:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/linux/bug.h:5:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/arch/arm64/include/asm/bug.h:37:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/asm-generic/bug.h:18:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/linux/kernel.h:14:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/linux/printk.h:336:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/linux/dynamic_debug.h:6:
In file included from /lib/modules/4.19.115-g0cfccb73c/build/include/linux/jump_label.h:117:
/lib/modules/4.19.115-g0cfccb73c/build/arch/arm64/include/asm/jump_label.h:45:2: error: 'asm goto' constructs
      are not supported yet
        asm_volatile_goto("1: b %l[l_yes]\n\t"
        ^
/lib/modules/4.19.115-g0cfccb73c/build/include/linux/compiler_types.h:155:37: note: expanded from macro
      'asm_volatile_goto'
#define asm_volatile_goto(x...) asm goto(x)
                                    ^
2 errors generated.
Traceback (most recent call last):
  File "/usr/sbin/cpudist-bpfcc", line 155, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 301, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 

who knows what happend?

**Comment by jony-one** [comment]
These two questions are somewhat similar：
https://github.com/iovisor/bcc/issues/2119
https://github.com/iovisor/bcc/issues/2329
