### ISSUE TITLE
BPF: Failed to attach BPF to device eth0: Cannot allocate memory

### ISSUE THREAD

**Issue by sudhii1991** [iovisor/bcc#3617]
Hi, 
i am getting below error when running a bpf program(socket filtering) in GKE 1.20 cluster.
BPF program is running in a Centos8 docker container, The container is running in the GKE

Host Info:
  OS: Container-Optimized OS(COS)
  BUILD_ID=16108.470.1
  Kernel: 5.4.120+
  BCC Version: 0.16.0-3.el8
  
Error:
`Traceback (most recent call last):
  File "bpf-parser-l7flowmap.py", line 354, in <module>
    attach_interfaces_to_sock(iface)
  File "bpf-parser-l7flowmap.py", line 251, in attach_interfaces_to_sock
    BPF.attach_raw_socket(function_flow_bpf_filter, iface)
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 552, in attach_raw_socket
    % (dev, errstr))
Exception: Failed to attach BPF to device b'eth0': Cannot allocate memory`

Can someone help me why throwing "Cannot Allocate memory". There is lots of memory available in the host.
Facing this issue only in GKE cluster

**Comment by wyEumenides** [comment]
I solved this error here because the number of queues is too small.
If you are executing in a virtual machine, please set the number of virtual machine queues
For example <driver name='vhost' queues='16'/>
You can view the current number of queues through ethtool -l <interface-name>
