### ISSUE TITLE
Many tools don't work on aarch64 when kasan is enabled

### ISSUE THREAD

**Issue by jeromemarchand** [iovisor/bcc#3648]
On aarch64, when kasan is enabled, many tools failed with the following error:
```
# /usr/share/bcc/tools/bashreadline 
In file included from <built-in>:3:
In file included from /virtual/include/bcc/helpers.h:54:
In file included from arch/arm64/include/asm/page.h:44:
arch/arm64/include/asm/memory.h:204:24: error: use of undeclared identifier 'KASAN_SHADOW_SCALE_SHIFT'
        return kimage_vaddr - KIMAGE_VADDR;
                              ^
arch/arm64/include/asm/memory.h:64:24: note: expanded from macro 'KIMAGE_VADDR'
#define KIMAGE_VADDR            (MODULES_END)
                                 ^
arch/arm64/include/asm/memory.h:68:23: note: expanded from macro 'MODULES_END'
#define MODULES_END             (MODULES_VADDR + MODULES_VSIZE)
                                 ^
arch/arm64/include/asm/memory.h:69:25: note: expanded from macro 'MODULES_VADDR'
#define MODULES_VADDR           (BPF_JIT_REGION_END)
                                 ^
arch/arm64/include/asm/memory.h:67:29: note: expanded from macro 'BPF_JIT_REGION_END'
#define BPF_JIT_REGION_END      (BPF_JIT_REGION_START + BPF_JIT_REGION_SIZE)
                                 ^
arch/arm64/include/asm/memory.h:65:42: note: expanded from macro 'BPF_JIT_REGION_START'
#define BPF_JIT_REGION_START    (VA_START + KASAN_SHADOW_SIZE)
                                            ^
arch/arm64/include/asm/memory.h:91:48: note: expanded from macro 'KASAN_SHADOW_SIZE'
#define KASAN_SHADOW_SIZE       (UL(1) << (VA_BITS - KASAN_SHADOW_SCALE_SHIFT))
                                                     ^
1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/bashreadline", line 67, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 365, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

The reason behind this, is that on arm64 KASAN_SHADOW_SCALE_SHIFT isn't defined in arch/arm64/include/asm/memory.h as ii is for the other arches, but in the arch/arm64/Makefile where it's not visible to bcc.

**Comment by bitcoffeeiux** [comment]
Any new developments on this issue?

**Comment by yonghong-song** [comment]
I don't have aarch64 environment. Since you are using bcc tools in your aarch64 environment, maybe you could craft a fix?

**Comment by bitcoffeeiux** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，你的邮件我已经收到，谢谢~
