### ISSUE TITLE
BCC failed to recognize static function ?

### ISSUE THREAD

**Issue by chenhengqi** [iovisor/bcc#3690]
I was testing the new [kernel patch](https://patchwork.kernel.org/project/netdevbpf/patch/20211104213138.2779620-2-songliubraving@fb.com/) with BCC with the following code:
```python
#!/usr/bin/python

from bcc import BPF

bpf_text = '''
#include <linux/ptrace.h>
#include <linux/sched.h>

struct callback_ctx {
        int dummy;
};

static long (*bpf_find_vma)(struct task_struct *task, u64 addr, void *callback_fn, void *callback_ctx, u64 flags) = (void *)180;

static __u64
write_task(struct task_struct *task, struct vm_area_struct *vma,
           struct callback_ctx *data)
{
        /* writing to task, which is illegal */
        /* task->mm = NULL; */

        return 0;
}

KFUNC_PROBE(vfs_read)
{
    struct task_struct *task = bpf_get_current_task_btf();
    struct callback_ctx data = {};

    bpf_find_vma(task, 0, write_task, &data, 0);
    return 0;
}
'''

b = BPF(text=bpf_text)
print("BPF programs loaded")
b.trace_print()
```

But it failed with:
```
bpf: Failed to load program: Permission denied
; struct task_struct *task = bpf_get_current_task_btf();
0: (85) call bpf_get_current_task_btf#158
1: (b7) r1 = 0
; struct callback_ctx data = {};
2: (63) *(u32 *)(r10 -8) = r1
last_idx 2 first_idx 0
regs=2 stack=0 before 1: (b7) r1 = 0
3: (bf) r4 = r10
; 
4: (07) r4 += -8
; bpf_find_vma(task, 0, write_task, &data, 0);
5: (bf) r1 = r0
6: (b7) r2 = 0
7: (18) r3 = 0x0
9: (b7) r5 = 0
10: (85) call bpf_find_vma#180
R3 type=inv expected=func
processed 10 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

Traceback (most recent call last):
  File "./s.py", line 35, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 487, in __init__
    self._trace_autoload()
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1456, in _trace_autoload
    self.attach_kfunc(fn_name=func_name)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1118, in attach_kfunc
    fn = self.load_func(fn_name, BPF.TRACING)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 527, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program kfunc__vfs_read: Permission denied
```

But with libbpf, this new helper works fine.

cc @yonghong-song

**Comment by davemarchevsky** [comment]
This is sort of expected since BCC doesn't currently load a "bpf object", but rather just one function. When the in-progress refactor I'm working on is complete we should get this for free / easy.

**Comment by yonghong-song** [comment]
Ya, @davemarchevsky is right. Current bcc infrastructure doesn't support callback function. @davemarchevsky is working on to enbrace libbpf more so bcc users can use such features easily.
