### ISSUE TITLE
Segfault when running tools/profile on RHEL 8.4

### ISSUE THREAD

**Issue by eyakimov-bbg** [iovisor/bcc#3693]
Hello,

I'm getting a segfault when trying to run `profile`, details:

Invocation:
```
[root@dev-10-34-19-186 ~]# /usr/share/bcc/tools/profile -p $(pidof a.out)
Sampling at 49 Hertz of PID 5342 by user + kernel stack... Hit Ctrl-C to end.
Segmentation fault (core dumped)
```

(`a.out` is running and is a simple main() with some large iterative loops of basic maths and sleep for testing, can copy if needed)

System Info:
```
[root@dev-10-34-19-186 ~]# yum info bcc-tools
Last metadata expiration check: 0:17:32 ago on Tue Nov  9 06:46:57 2021.
Installed Packages
Name         : bcc-tools
Version      : 0.16.0
Release      : 3.el8
Architecture : x86_64
Size         : 1.8 M
Source       : bcc-0.16.0-3.el8.src.rpm
Repository   : @System
From repo    : rhel-8-for-x86_64-appstream-rpms
Summary      : Command line tools for BPF Compiler Collection (BCC)
URL          : https://github.com/iovisor/bcc
License      : ASL 2.0
Description  : Command line tools for BPF Compiler Collection (BCC)

[root@dev-10-34-19-186 ~]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterprise
Description:    Red Hat Enterprise Linux release 8.4 (Ootpa)
Release:        8.4
Codename:       Ootpa
[root@dev-10-34-19-186 ~]# uname -a
Linux dev-10-34-19-186 4.18.0-305.25.1.el8_4.x86_64 #1 SMP Mon Oct 18 14:34:11 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
[root@dev-10-34-19-186 ~]#
```

Stack
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f03daa07442 in clang::RecursiveASTVisitor<ebpf::TracepointTypeVisitor>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) () from /lib64/libbcc.so.0
Missing separate debuginfos, use: yum debuginfo-install platform-python-3.6.8-39.el8_4.x86_64
(gdb) bt
#0  0x00007f03daa07442 in clang::RecursiveASTVisitor<ebpf::TracepointTypeVisitor>::dataTraverseNode(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) () from /lib64/libbcc.so.0
#1  0x00007f03daa09d80 in clang::RecursiveASTVisitor<ebpf::TracepointTypeVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) () from /lib64/libbcc.so.0
#2  0x00007f03daa0658b in clang::RecursiveASTVisitor<ebpf::TracepointTypeVisitor>::TraverseDecl(clang::Decl*) () from /lib64/libbcc.so.0
#3  0x00007f03daa05d8f in ebpf::TracepointTypeConsumer::HandleTopLevelDecl(clang::DeclGroupRef) () from /lib64/libbcc.so.0
#4  0x00007f03d7c2bb54 in clang::ParseAST(clang::Sema&, bool, bool) () from /lib64/libclang-cpp.so.11
#5  0x00007f03d944bc79 in clang::FrontendAction::Execute() () from /lib64/libclang-cpp.so.11
#6  0x00007f03d9404243 in clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) () from /lib64/libclang-cpp.so.11
#7  0x00007f03da96da65 in ebpf::ClangLoader::do_compile(std::unique_ptr<llvm::Module, std::default_delete<llvm::Module> >*, ebpf::TableStorage&, bool, std::vector<char const*, std::allocator<char const*> > const&, std::vector<char const*, std::allocator<char const*> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ebpf::FuncSource&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<int, std::tuple<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::less<int>, std::allocator<std::pair<int const, std::tuple<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&) () from /lib64/libbcc.so.0
#8  0x00007f03da97000f in ebpf::ClangLoader::parse(std::unique_ptr<llvm::Module, std::default_delete<llvm::Module> >*, ebpf::TableStorage&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, char const**, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ebpf::FuncSource&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<int, std::tuple<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::less<int>, std::allocator<std::pair<int const, std::tuple<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&) () from /lib64/libbcc.so.0
#9  0x00007f03da8f0f5d in ebpf::BPFModule::load_cfile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, char const**, int) () from /lib64/libbcc.so.0
#10 0x00007f03da8f70a2 in ebpf::BPFModule::load_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const**, int) () from /lib64/libbcc.so.0
#11 0x00007f03da8f09c8 in bpf_module_create_c_from_string () from /lib64/libbcc.so.0
#12 0x00007f03dbc8709e in ffi_call_unix64 () from /lib64/libffi.so.6
#13 0x00007f03dbc86a4f in ffi_call () from /lib64/libffi.so.6
#14 0x00007f03dbe9961c in _ctypes_callproc.cold.53 () from /usr/lib64/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so
#15 0x00007f03dbe9dfd9 in PyCFuncPtr_call () from /usr/lib64/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so
#16 0x00007f03ea8e2c8b in _PyObject_FastCallKeywords () from /lib64/libpython3.6m.so.1.0
#17 0x00007f03ea8e3656 in call_function () from /lib64/libpython3.6m.so.1.0
#18 0x00007f03ea8e4158 in _PyEval_EvalFrameDefault () from /lib64/libpython3.6m.so.1.0
#19 0x00007f03ea83fbc4 in _PyEval_EvalCodeWithName () from /lib64/libpython3.6m.so.1.0
#20 0x00007f03ea841504 in _PyFunction_FastCallDict () from /lib64/libpython3.6m.so.1.0
#21 0x00007f03ea841eae in _PyObject_FastCallDict () from /lib64/libpython3.6m.so.1.0
#22 0x00007f03ea853d90 in method_call () from /lib64/libpython3.6m.so.1.0
#23 0x00007f03ea8ce9e1 in slot_tp_init () from /lib64/libpython3.6m.so.1.0
#24 0x00007f03ea8e2b22 in _PyObject_FastCallKeywords () from /lib64/libpython3.6m.so.1.0
#25 0x00007f03ea8e3656 in call_function () from /lib64/libpython3.6m.so.1.0
#26 0x00007f03ea8e4d98 in _PyEval_EvalFrameDefault () from /lib64/libpython3.6m.so.1.0
#27 0x00007f03ea83fbc4 in _PyEval_EvalCodeWithName () from /lib64/libpython3.6m.so.1.0
#28 0x00007f03ea840f63 in PyEval_EvalCode () from /lib64/libpython3.6m.so.1.0
#29 0x00007f03ea94f962 in run_mod () from /lib64/libpython3.6m.so.1.0
#30 0x00007f03ea8204cb in PyRun_FileExFlags () from /lib64/libpython3.6m.so.1.0
#31 0x00007f03ea8255c4 in PyRun_SimpleFileExFlags () from /lib64/libpython3.6m.so.1.0
#32 0x00007f03ea825f13 in Py_Main.cold.3364 () from /lib64/libpython3.6m.so.1.0
#33 0x000055cc15166b96 in main ()
```

**Comment by yonghong-song** [comment]
which llvm version in your system? Old bcc version for example 0.16.0 may not work with newer llvm. Could you try to build from source to see whether the problem still exists or not?

**Comment by eyjohn** [comment]
Sorry for the delay, it does seem that I'm getting this error with:

```
Installed Packages
Name         : bcc-tools
Version      : 0.16.0
Release      : 3.el8
Architecture : x86_64
Size         : 1.8 M
Source       : bcc-0.16.0-3.el8.src.rpm
Repository   : @System
From repo    : rhel-8-for-x86_64-appstream-rpms
Summary      : Command line tools for BPF Compiler Collection (BCC)
URL          : https://github.com/iovisor/bcc
License      : ASL 2.0
Description  : Command line tools for BPF Compiler Collection (BCC)

Name         : llvm-libs
Version      : 11.0.1
Release      : 2.module+el8.4.0+12666+0fb5828f
Architecture : x86_64
Size         : 78 M
Source       : llvm-11.0.1-2.module+el8.4.0+12666+0fb5828f.src.rpm
Repository   : @System
From repo    : rhel-8-for-x86_64-appstream-rpms
Summary      : LLVM shared libraries
URL          : http://llvm.org
License      : NCSA
Description  : Shared libraries for the LLVM compiler infrastructure.
```

I'll try to "upgrade" all the packages to see if my results differ
