### ISSUE TITLE
cannot attach uprobe, probe entry may not exist  error for ustat running inside container.

### ISSUE THREAD

**Issue by pr2340** [iovisor/bcc#3754]
cannot attach uprobe, probe entry may not exist
Traceback (most recent call last):
  File "/usr/share/bcc/tools/lib/ustat", line 307, in <module>
    Tool().run()
  File "/usr/share/bcc/tools/lib/ustat", line 299, in run
    self._loop_iter()
  File "/usr/share/bcc/tools/lib/ustat", line 248, in _loop_iter
    self._attach_probes()
  File "/usr/share/bcc/tools/lib/ustat", line 239, in _attach_probes
    self.bpf.attach_uprobe(name=path, fn_name=func, addr=addr, pid=-1)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1019, in attach_uprobe
    raise Exception("Failed to attach BPF to uprobe")
Exception: Failed to attach BPF to uprobe

no issues running ustat on vm.  anything missing for container to work ?

**Comment by chenhengqi** [comment]
Do you mean the tool is failing inside container ?

**Comment by pr2340** [comment]
@chenhengqi  it is failing due to old lookup_or_init() . I replaced with lookup_or_try_init() . getting some complication error with old bcc tool version (0.10.0).  is this function added after this version ? how can I make it work with this version of bcc.

**Comment by pr2340** [comment]
@chenhengqi I hv identified the issue.  it was attaching to libjvm.so in vm instead of container libjvm.so .  Do you know how to map it to container libjvm.so.

**Comment by chenhengqi** [comment]
Please refer to:

* https://github.com/iovisor/bcc/issues/3487
* https://github.com/iovisor/bcc/pull/3498

cc @davemarchevsky

**Comment by pr2340** [comment]
@chenhengqi @davemarchevsky  my issue is little different.  bcc tool is running inside container which is from ubuntu image with bcc-tool version 0.10.0-34 which is nightly build.  when I run inside container, it returns path as /root/.sdkman/candidates/java/11.0.11.hs-adpt/lib/server/libjvm.so  when does not exist inside container.  if I map this relative path to container, I can see result for the given pid. I can not update bcc tool version inside container to use the fix suggested in threads above.  Do you hv any solutions to try for ?

**Comment by davemarchevsky** [comment]
@pr2340 Sorry for the delayed response.

> bcc tool is running inside container which is from ubuntu image with bcc-tool version 0.10.0-34 which is nightly build

This is `bcc-tool` from repo.iovisor.org?
