### ISSUE TITLE
u32s in BPF_PERF_OUTPUT data_t

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#382]
I've used the new BPF_PERF_OUTPUT successfully for u64's and char *'s. But u32's are hit or miss. Sometimes they work, sometimes I get the error that follows, and sometimes I get the wrong data (fields look shifted).

To reproduce, edit ext4slower.py and change the pid in data_t to a u32, and the corresponding field in Data to a ct.c_ulong. Doing this, I get:

``` Shell
# ./ext4slower.py
bpf: Permission denied
0: (7b) *(u64 *)(r10 -120) = r1
1: (85) call 14
2: (63) *(u32 *)(r10 -4) = r0
3: (18) r1 = 0xa2a3cc80
5: (bf) r2 = r10
6: (07) r2 += -4
7: (85) call 1
8: (bf) r7 = r0
9: (15) if r7 == 0x0 goto pc+67
 R0=map_value_or_null(ks=4,vs=24) R7=map_value(ks=4,vs=24) R10=fp fp-120=ctx
10: (85) call 5
11: (bf) r6 = r0
12: (79) r9 = *(u64 *)(r7 +0)
13: (18) r1 = 0xa2a3cc80
15: (bf) r2 = r10
16: (07) r2 += -4
17: (85) call 3
18: (bf) r8 = r6
19: (1f) r8 -= r9
20: (b7) r1 = 10001000
21: (2d) if r1 > r8 goto pc+55
 R0=inv R1=imm10001000 R6=inv R7=map_value(ks=4,vs=24) R8=inv R9=inv R10=fp fp-120=ctx
22: (b7) r9 = 0
23: (7b) *(u64 *)(r10 -16) = r9
24: (79) r3 = *(u64 *)(r7 +16)
25: (07) r3 += 24
26: (bf) r1 = r10
27: (07) r1 += -16
28: (b7) r2 = 8
29: (85) call 4
30: (79) r1 = *(u64 *)(r10 -120)
31: (7b) *(u64 *)(r10 -120) = r1
32: (61) r1 = *(u32 *)(r1 +80)
33: (7b) *(u64 *)(r10 -104) = r9
34: (7b) *(u64 *)(r10 -112) = r9
35: (7b) *(u64 *)(r10 -96) = r1
36: (37) r8 /= 1000
37: (7b) *(u64 *)(r10 -88) = r9
38: (7b) *(u64 *)(r10 -80) = r8
39: (61) r1 = *(u32 *)(r10 -4)
40: (63) *(u32 *)(r10 -72) = r1
41: (63) *(u32 *)(r10 -24) = r9
42: (63) *(u32 *)(r10 -28) = r9
43: (63) *(u32 *)(r10 -32) = r9
44: (63) *(u32 *)(r10 -36) = r9
45: (63) *(u32 *)(r10 -40) = r9
46: (63) *(u32 *)(r10 -44) = r9
47: (63) *(u32 *)(r10 -48) = r9
48: (63) *(u32 *)(r10 -52) = r9
49: (63) *(u32 *)(r10 -56) = r9
50: (63) *(u32 *)(r10 -60) = r9
51: (63) *(u32 *)(r10 -64) = r9
52: (63) *(u32 *)(r10 -68) = r9
53: (37) r6 /= 1000
54: (7b) *(u64 *)(r10 -112) = r6
55: (79) r1 = *(u64 *)(r7 +8)
56: (7b) *(u64 *)(r10 -88) = r1
57: (79) r3 = *(u64 *)(r10 -16)
58: (07) r3 += 56
59: (bf) r1 = r10
60: (07) r1 += -52
61: (b7) r2 = 32
62: (85) call 4
63: (bf) r1 = r10
64: (07) r1 += -68
65: (b7) r2 = 16
66: (85) call 16
67: (18) r7 = 0x7a8fe900
69: (85) call 8
70: (bf) r4 = r10
71: (07) r4 += -112
72: (79) r1 = *(u64 *)(r10 -120)
73: (bf) r2 = r7
74: (bf) r3 = r0
75: (b7) r5 = 96
76: (85) call 25
invalid indirect read from stack off -112+92 size 96

Traceback (most recent call last):
  File "./ext4slower.py", line 311, in <module>
    b.attach_kretprobe(event="generic_file_read_iter", fn_name="trace_read_return")
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 695, in attach_kretprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 522, in load_func
    raise Exception("Failed to load BPF program %s" % func_name)
Exception: Failed to load BPF program trace_read_return
```

**Comment by 4ast** [comment]
-112+92 == r10 -20 and it's not inited by the code above.
Likely the struct in C code has gaps between u32 and other fields.
I think we have another rfe filed to warn about such things at compile time.
bcc is probably a better place to warn. Hacking clang for that is unnecessary.

**Comment by pchaigno** [comment]
Duplicate of #269 (with slightly more info.).

**Comment by brendangregg** [comment]
Thanks @pchaigno, closing see #269.
