### ISSUE TITLE
bpf: Failed to load program: Operation not permitted, and Exception: Need super-user privileges to run. 

### ISSUE THREAD

**Issue by arayu05** [iovisor/bcc#3826]
ubuntu 18.04 lts , 
Kernel version : 5.4.0-91-generic

Hi Team,
I am building a docker image of my ebpf program(python and c file). 
Dockerfile:

```
`FROM ubuntu:20.04 as build
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
apt -y install linux-headers-$(uname -r)

RUN CONFIG_NET_CLS_BPF=m &&\
CONFIG_NET_ACT_BPF=m &&\
CONFIG_BPF_JIT=y &&\
CONFIG_BPF_STREAM_PARSER=y &&\
CONFIG_LWTUNNEL_BPF=y &&\
CONFIG_HAVE_EBPF_JIT=y &&\
CONFIG_BPF_EVENTS=y 

RUN apt-get update && \
apt-get -y install bison build-essential cmake flex git libedit-dev \
  libllvm6.0 llvm-6.0-dev libclang-6.0-dev python zlib1g-dev libelf-dev libfl-dev python3-distutils

RUN git clone https://github.com/iovisor/bcc.git
RUN mkdir bcc/build
WORKDIR /bcc/build
RUN cmake ..
RUN make
RUN make install
RUN cmake -DPYTHON_CMD=python3 .. # build python3 binding

WORKDIR /usr/sbin/

RUN apt-get update && \
      apt-get -y install sudo

// RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo

// USER docker

COPY . .
CMD ["python3", "./iplist.py"]`
```

But while Running the container it is giving below error:

```
`/virtual/main.c:1:9: warning: 'KBUILD_MODNAME' macro redefined [-Wmacro-redefined]
#define KBUILD_MODNAME "filter"
        ^
<command line>:3:9: note: previous definition is here
#define KBUILD_MODNAME "bcc"
        ^
1 warning generated.
bpf: Failed to load program: Operation not permitted

Traceback (most recent call last):
  File "./iplist.py", line 15, in <module>
    fn = b.load_func("udpfilter", BPF.XDP)   #% (3)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 519, in load_func
    raise Exception("Need super-user privileges to run")
Exception: Need super-user privileges to run`
```

But docker runs with super user privileges only. Can anyone suggest what changes I should to run the ebpf program inside container?

**Comment by arayu05** [comment]
solved after using '--privileged' flag in docker run

**Comment by arayu05** [comment]
solved.
