### ISSUE TITLE
memleak: could not determine address of symbol malloc

### ISSUE THREAD

**Issue by hidva** [iovisor/bcc#3834]
```
/usr/bin/python ../tools/memleak.py  -c "/root/hidva.com/rustplay2/target/debug/rustplay2" -O /lib64/libc-2.33.so
Executing '/root/project/rustplay2/target/debug/rustplay2' and tracing the resulting process.
Attaching to pid 964501, Ctrl+C to quit.
Traceback (most recent call last):
  File "/root/project/bcc/build/../tools/memleak.py", line 449, in <module>
    attach_probes("malloc")
  File "/root/project/bcc/build/../tools/memleak.py", line 437, in attach_probes
    bpf.attach_uprobe(name=obj, sym=sym,
  File "/root/project/bcc/build/src/python/bcc-python3/bcc/__init__.py", line 1361, in attach_uprobe
    (path, addr) = BPF._check_path_symbol(name, sym, addr, pid, sym_off)
  File "/root/project/bcc/build/src/python/bcc-python3/bcc/__init__.py", line 960, in _check_path_symbol
    raise Exception("could not determine address of symbol %s" % symname)
Exception: could not determine address of symbol b'malloc'
```

# Root Cause

rustplay2 only runs for 50ms, When `openelf(path="/proc/964798/root/lib64/libc-2.33.so")` executes, the process 964798 is terminated, so `/proc/964798/root` is cleared.

```
$ ls /proc/964798/root
ls: cannot read symbolic link '/proc/964798/root': No such file or directory
/proc/964798/root
$ ps -o pid,cmd 964798
    PID CMD
 964798 [rustplay2] <defunct>
```

**Comment by hidva** [comment]
Should we suspend the process until all initialization is completed?

**Comment by bacher09** [comment]
It's a behaviour you would get with any short running process, it's probably more reliable to attach uprobe before launching an application, but there is an issue with this approach, since application might load library from another path (that's why BCC is checking `/proc/$pid/maps`).
