### ISSUE TITLE
perf_event_open(/sys/kernel/debug/tracing/events/uprobes/p__proc_32829_root_opt_java_openjdk_lib_server_libjvm_so_0xd45575_bcc_35680/id): Invalid argument error

### ISSUE THREAD

**Issue by pr2340** [iovisor/bcc#3835]
Hi I am getting below error while running bcc tool inside container for a process running inside container.  perf_event_open(/sys/kernel/debug/tracing/events/uprobes/p__proc_32829_root_opt_java_openjdk_lib_server_libjvm_so_0xd45575_bcc_35680/id): Invalid argument
Traceback (most recent call last):
  File "/usr/share/bcc/tools/lib/ustat", line 305, in <module>
    Tool().run()
  File "/usr/share/bcc/tools/lib/ustat", line 297, in run
    self._loop_iter()
  File "/usr/share/bcc/tools/lib/ustat", line 246, in _loop_iter
    self._attach_probes()
  File "/usr/share/bcc/tools/lib/ustat", line 237, in _attach_probes
    self.bpf.attach_uprobe(name=path, fn_name=func, addr=addr, pid=-1)
  File "/usr/lib/python3.9/site-packages/bcc/__init__.py", line 1158, in attach_uprobe
    raise Exception("Failed to attach BPF to uprobe")
Exception: Failed to attach BPF to probe.    it refers correct libjvm.so path inside container  (/proc/32829/root/opt/java/../server/libjvm.so) . any suggestion how to fix this issue ?

**Comment by JonBruchim** [comment]
Name of your hook `/sys/kernel/debug/tracing/events/uprobes/p__proc_32829_root_opt_java_openjdk_lib_server_libjvm_so_0xd45575_bcc_35680/id`
might be too long, Is there an option you could shorten the path name and check it out?
