### ISSUE TITLE
Exception: Failed to load BPF program b'tracepoint__sock__inet_sock_set_state': Permission denied

### ISSUE THREAD

**Issue by Kim-SangMin3341** [iovisor/bcc#3841]
Hi, I am getting an error running tcpstates

Traceback (most recent call last):
  File "tcpstates", line 422, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 483, in __init__
    self._trace_autoload()
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1456, in _trace_autoload
    fn = self.load_func(func_name, BPF.TRACEPOINT)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 522, in load_func
    raise Exception("Failed to load BPF program %s: %s" %
Exception: Failed to load BPF program b'tracepoint__sock__inet_sock_set_state': Permission denied

**Comment by jackpgao** [comment]
it's already be root, sudo doesn't help.

**Comment by yonghong-song** [comment]
Only this bcc tool has issue, or other bcc tool also has the issue? If they all have the issues, maybe this is due to some other factors, like some kind of security system on the host.

**Comment by htliu6** [comment]
So, does anyone solve this problem?

**Comment by davemarchevsky** [comment]
I was able to run `tcpstates.py` on a few of my test environments. We'll need more information to be able to help you investigate, something like: 
 * kernel version (`uname -a`)
 * what distro you're using
 * whether other bcc python tools work for you
 * any other steps you've tried to resolve the issue
