### ISSUE TITLE
ext4slower does not work

### ISSUE THREAD

**Issue by ismail** [iovisor/bcc#400]
This is on Linux x86-64, LLVM 3.7, kernel 4.4.0:

```
seferogullari /usr/local/share/bcc/tools > sudo ./ext4slower
bpf: Permission denied
0: (7b) *(u64 *)(r10 -120) = r1
1: (85) call 14
2: (63) *(u32 *)(r10 -4) = r0
3: (18) r1 = 0x91e931c0
5: (bf) r2 = r10
6: (07) r2 += -4
7: (85) call 1
8: (bf) r7 = r0
9: (15) if r7 == 0x0 goto pc+62
 R0=map_value_or_null(ks=4,vs=24) R7=map_value(ks=4,vs=24) R10=fp fp-120=ctx
10: (85) call 5
11: (bf) r6 = r0
12: (79) r9 = *(u64 *)(r7 +0)
13: (18) r1 = 0x91e931c0
15: (bf) r2 = r10
16: (07) r2 += -4
17: (85) call 3
18: (bf) r8 = r6
19: (1f) r8 -= r9
20: (b7) r1 = 10001000
21: (2d) if r1 > r8 goto pc+50
 R0=inv R1=imm10001000 R6=inv R7=map_value(ks=4,vs=24) R8=inv R9=inv R10=fp fp-120=ctx
22: (b7) r9 = 0
23: (7b) *(u64 *)(r10 -16) = r9
24: (79) r3 = *(u64 *)(r7 +16)
25: (07) r3 += 24
26: (bf) r1 = r10
27: (07) r1 += -16
28: (b7) r2 = 8
29: (85) call 4
30: (79) r1 = *(u64 *)(r10 -120)
31: (7b) *(u64 *)(r10 -120) = r1
32: (61) r1 = *(u32 *)(r1 +80)
33: (7b) *(u64 *)(r10 -104) = r9
34: (7b) *(u64 *)(r10 -112) = r9
35: (7b) *(u64 *)(r10 -96) = r1
36: (37) r8 /= 1000
37: (7b) *(u64 *)(r10 -88) = r9
38: (7b) *(u64 *)(r10 -80) = r8
39: (61) r1 = *(u32 *)(r10 -4)
40: (7b) *(u64 *)(r10 -72) = r1
41: (7b) *(u64 *)(r10 -24) = r9
42: (7b) *(u64 *)(r10 -32) = r9
43: (7b) *(u64 *)(r10 -40) = r9
44: (7b) *(u64 *)(r10 -48) = r9
45: (7b) *(u64 *)(r10 -56) = r9
46: (7b) *(u64 *)(r10 -64) = r9
47: (37) r6 /= 1000
48: (7b) *(u64 *)(r10 -112) = r6
49: (79) r1 = *(u64 *)(r7 +8)
50: (7b) *(u64 *)(r10 -88) = r1
51: (79) r3 = *(u64 *)(r10 -16)
52: (07) r3 += 56
53: (bf) r7 = r10
54: (07) r7 += -112
55: (bf) r1 = r7
56: (07) r1 += 64
57: (b7) r2 = 32
58: (85) call 4
R1 type=inv expected=fp

Traceback (most recent call last):
  File "./ext4slower", line 311, in <module>
    b.attach_kretprobe(event="generic_file_read_iter", fn_name="trace_read_return")
  File "/usr/local/lib/python2.7/site-packages/bcc/__init__.py", line 343, in attach_kretprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/local/lib/python2.7/site-packages/bcc/__init__.py", line 165, in load_func
    raise Exception("Failed to load BPF program %s" % func_name)
Exception: Failed to load BPF program trace_read_return
```

**Comment by drzaeus77** [comment]
llvm 3.7.0 or 3.7.1? This looks like a bug that is fixed in 3.7.1.

**Comment by ismail** [comment]
3.7.0, will re-try with llvm 3.8.0 when its released. Thanks for the prompt reply!

**Comment by ismail** [comment]
Works with llvm 3.8.0, closing.
