### ISSUE TITLE
List of Kfunc/kretfunc supported?

### ISSUE THREAD

**Issue by josebeo2016** [iovisor/bcc#4001]
Hi, I'm trying to play with kfunc to write some tracing code in kernel function but I wonder how could I get the full list of supported kfunc or kretfunc of eBPF?

**Comment by yonghong-song** [comment]
You can find the list of functions at /sys/kernel/debug/tracing/available_filter_functions

**Comment by josebeo2016** [comment]
Thank you for your kindness

**Comment by josebeo2016** [comment]
When I run the example tools tcpcong.py, I saw the error:
```
python3 bcc/tools/tcpcong.py 1 10
libbpf: tcp_fastretrans_alert is not found in vmlinux BTF
bpf: tcp_fastretrans_alert is not found in vmlinux BTF
Traceback (most recent call last):
  File "../bcc/tools/tcpcong.py", line 456, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 488, in __init__
    self._trace_autoload()
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1454, in _trace_autoload
    self.attach_kfunc(fn_name=func_name)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1122, in attach_kfunc
    fn = self.load_func(fn_name, BPF.TRACING)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 527, in load_func
    raise Exception("Failed to load BPF program %s: %s" %
Exception: Failed to load BPF program b'kfunc__tcp_fastretrans_alert': No such file or directory
```

I confirmed my environment supporting kfunc using: `BPF.support_kfunc()`

Is there anything that I missed?

**Comment by yonghong-song** [comment]
Maybe the function tcp_fastretrans_alert call has been all inlined and gone?
```
ipv4/tcp_input.c:static void tcp_fastretrans_alert(struct sock *sk, const u32 prior_snd_una,
```
it is a static function. You can check /proc/kallsyms to check whether it is there or not. If it is still there, maybe you kernel doesn't support btf? check /sys/kernel/btf/vmlinux to see whether the file exists or not.

**Comment by josebeo2016** [comment]
The function is still there:
```
$ cat /proc/kallsyms|grep tcp_fastretrans_alert
ffffffff88045300 t tcp_fastretrans_alert
```

And I built the kernel 5.12.11 with `CONFIG_DEBUG_INFO_BTF=y`
```
$ ll /sys/kernel/btf/vmlinux 
-r--r--r-- 1 root root 3.7M  5월 24 16:54 /sys/kernel/btf/vmlinux
```

**Comment by josebeo2016** [comment]
I'm not so sure but as far as my experiences, the functions which are globally visible marked as T in /proc/kalllsyms 
```
$ cat /proc/kallsyms |grep tcp_enter_cwr
ffffffffb12403d0 T tcp_enter_cwr
```

Besides, the small "t" cannot be used.
```
$ cat /proc/kallsyms |grep tcp_fastretrans_alert
ffffffffb1245300 t tcp_fastretrans_alert
```
These "t" might not be called I think.
Do I need to include any further libraries in my bpf code (in C language)?
