### ISSUE TITLE
Use tools/deadlock.py to watch process in container

### ISSUE THREAD

**Issue by Akiya95** [iovisor/bcc#4082]
### Step:
1. Run app in a container.
2. Run `python3 deadlock.py --binary /lib/x86_64-linux-gnu/libpthread.so.0 <app PID>` in host .

### Expect:
```bash
Tracing... Hit Ctrl-C to end.	
----------------	
Potential Deadlock Detected!	
	
Cycle in lock order graph: Mutex M0 (0x000055f8c4b39160) => Mutex M1 (0x000055f8c4b390c0) => Mutex M2 (0x000055f8c4b390e8) => Mutex M3 (0x000055f8c4b39110) => Mutex M4 (0x000055f8c4b39138) => Mutex M0 (0x000055f8c4b39160)	
	
Mutex M1 (0x000055f8c4b390c0) acquired here while holding Mutex M0 (0x000055f8c4b39160) in Thread 22146 (b.out):	
@ 00007fb16e4fcfd0 b'pthread_mutex_lock'	
@ 000055f8c4937b12 b'philosopher'	
@ 00007fb16e4fa6db b'start_thread'	

Mutex M0 (0x000055f8c4b39160) previously acquired by the same Thread 22146 (b.out) here:	
@ 00007fb16e4fcfd0 b'pthread_mutex_lock'	
@ 000055f8c4937afc b'philosopher'	
@ 00007fb16e4fa6db b'start_thread'	
......
	
Thread 22144 created by Thread 20188 (b'b.out') here:	
@ 00007fb16e223611 b'clone'	
@ 000055f8c4937a2d b'main'	
@ 00007fb16e123c87 b'__libc_start_main'	
@ 109e258d4c544155 b'[unknown]'	
	
Thread 22145 created by Thread 20188 (b'b.out') here:	
@ 00007fb16e223611 b'clone'	
@ 000055f8c4937a2d b'main'	
@ 00007fb16e123c87 b'__libc_start_main'	
@ 109e258d4c544155 b'[unknown]'	
......
```

### Result: 
```bash
Tracing... Hit Ctrl-C to end.	
----------------	
Potential Deadlock Detected!	
	
Cycle in lock order graph: Mutex M0 (0x000055f8c4b39160) => Mutex M1 (0x000055f8c4b390c0) => Mutex M2 (0x000055f8c4b390e8) => Mutex M3 (0x000055f8c4b39110) => Mutex M4 (0x000055f8c4b39138) => Mutex M0 (0x000055f8c4b39160)	
	
Mutex M1 (0x000055f8c4b390c0) acquired here while holding Mutex M0 (0x000055f8c4b39160) in Thread 22146 (b.out):	
@ 00007fb16e4fcfd0 b'pthread_mutex_lock'	
@ 000055f8c4937b12 b'philosopher'	
@ 00007fb16e4fa6db b'start_thread'	
	
Mutex M0 (0x000055f8c4b39160) previously acquired by the same Thread 22146 (b.out) here:	
@ 00007fb16e4fcfd0 b'pthread_mutex_lock'	
@ 000055f8c4937afc b'philosopher'	
@ 00007fb16e4fa6db b'start_thread'	
......
Could not find stack trace where Thread 22146 was created

Could not find stack trace where Thread 22147 was created

Could not find stack trace where Thread 22148 was created
......
```
Could not find stack trace.

### Analyse
In deadlock.c
```c
int trace_clone(struct pt_regs *ctx, unsigned long flags, void *child_stack,
                void *ptid, void *ctid, struct pt_regs *regs) {
  // Now child_pid is Container PID.
  u32 child_pid = PT_REGS_RC(ctx);
  ...
  // Now parent_pid is Host PID.
  thread_created_leaf.parent_pid = bpf_get_current_pid_tgid();
  // Save  child_pid and parent_pid as a map.
  thread_to_parent.lookup_or_try_init(&child_pid, &thread_created_leaf);
  ...
```
When a thread is created in a container, the pid returned is the pid of the container and not the pid of the host.
```c
int trace_mutex_acquire(struct pt_regs *ctx, void *mutex_addr) {
  // Now child_pid is Host PID.
  u32 pid = bpf_get_current_pid_tgid();
...
int trace_mutex_release(struct pt_regs *ctx, void *mutex_addr) {
  // Now child_pid is Host PID.
  u32 pid = bpf_get_current_pid_tgid();
...
```
Because the host pid of the child process is obtained here, and the pid in the container is recorded when the child process is created, the two do not match, so the information of the parent process cannot be queried.

### Ask for help
How can I use tools/deadlock.py to watch a process in container and get the completly message?

**Comment by chenhengqi** [comment]
You need this helper `bpf_get_ns_current_pid_tgid`.

**Comment by Akiya95** [comment]
> You need this helper `bpf_get_ns_current_pid_tgid`.

Thanks, but this method requires linux 5.6 or above to support, my current kernel version is 5.0.

**Comment by chenhengqi** [comment]
Maybe you can do the filtering with task comm ?

**Comment by Akiya95** [comment]
I try to get the `struct pid` of `child_pid`, but there is an error.   
This error appears after calling `find_pid_ns(child_pid, ns)`.  
```c
int trace_clone(struct pt_regs *ctx, unsigned long flags, void *child_stack,
                void *ptid, void *ctid, struct pt_regs *regs) {
  u32 child_pid = PT_REGS_RC(ctx);
  if (child_pid <= 0) {
    return 1;
  }

  // add the following lines to get the child_pid in host.
  struct task_struct* task = (struct task_struct*)bpf_get_current_task();
  struct pid_namespace* ns = task->nsproxy->pid_ns_for_children;
  struct pid* pid = find_pid_ns(child_pid, ns);
  // struct pid* pid = find_vpid(child_pid);
  u32 child_pid_in_host = pid->numbers[0].nr;
  .....
```
```bash
# python3 deadlock.py --binary /lib/x86_64-linux-gnu/libpthread.so.0 21191
bpf: Failed to load program: Invalid argument
jump out of range from insn 6 to 78

Traceback (most recent call last):
  File "deadlock.py", line 570, in <module>
    main()
  File "deadlock.py", line 485, in main
    bpf.attach_kretprobe(event=bpf.get_syscall_fnname('clone'), fn_name='trace_clone')
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 868, in attach_kretprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 523, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program b'trace_clone': Invalid argument
```

**Comment by Akiya95** [comment]
In addition, here is my environment.  
```bash
# uname -r
5.0.0-23-generic

# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by Akiya95** [comment]
> 

ebpf programs cannot call external functions. please ignore.

**Comment by Akiya95** [comment]
During `mutex_acquire`, get the pid of the current thread in the container and store it in `edge_leaf`.  
When looking for parent messages, match by the pid in the container.
```c
int trace_mutex_acquire(struct pt_regs *ctx, void *mutex_addr) {
  // Higher 32 bits is process ID, Lower 32 bits is thread ID
  u32 pid = bpf_get_current_pid_tgid();
  u64 mutex = (u64)mutex_addr;

  struct task_struct* task = (struct task_struct*)bpf_get_current_task();
  struct pid *pid_p;
  unsigned int level;
  struct upid upid;
  
  bpf_probe_read_kernel(&pid_p, sizeof(pid_p), &task->thread_pid);
  bpf_probe_read_kernel(&level, sizeof(level), &pid_p->level);
  bpf_probe_read_kernel(&upid, sizeof(upid), &pid_p->numbers[level]);
  
  u32 pid_last_ns = upid.nr;
  ......
  struct edges_leaf_t edge_leaf = {};
    edge_leaf.mutex1_stack_id = leaf->held_mutexes[i].stack_id;
    edge_leaf.mutex2_stack_id = stack_id;
    edge_leaf.thread_pid = pid;
    edge_leaf.thread_pid_last_ns = pid_last_ns;
    bpf_get_current_comm(&edge_leaf.comm, sizeof(edge_leaf.comm));
  ......
```
```python
    # Set of threads involved in the lock inversion
    thread_pids = list()
    thread_pids_last_ns = list()

    # For each edge in the cycle, print where the two mutexes were held
    for (m, n) in edges:
        thread_pid = graph.attributes(m, n)['thread_pid']
        thread_pid_last_ns = graph.attributes(m, n)['thread_pid_last_ns']
        thread_comm = graph.attributes(m, n)['thread_comm']
        first_mutex_stack_id = graph.attributes(m, n)['first_mutex_stack_id']
        second_mutex_stack_id = graph.attributes(m, n)['second_mutex_stack_id']
        thread_pids.append(thread_pid)
        thread_pids_last_ns.append(thread_pid_last_ns)
        print(
            '%s acquired here while holding %s in Thread %d (%s):' % (
                node_addr_to_name[n], node_addr_to_name[m], thread_pid,
                thread_comm
            )
        )
        print_stack_trace_fn(second_mutex_stack_id)
        print('')
        print(
            '%s previously acquired by the same Thread %d (%s) here:' %
            (node_addr_to_name[m], thread_pid, thread_comm)
        )
        print_stack_trace_fn(first_mutex_stack_id)
        print('')

    # Print where the threads were created, if available
    for i in range(len(thread_pids_last_ns)):
        parent_pid, stack_id, parent_comm = thread_info.get(
            thread_pids_last_ns[i], (None, None, None)
        )
        if parent_pid:
            print(
                'Thread %d created by Thread %d (%s) here: ' %
                (thread_pids[i], parent_pid, parent_comm)
            )
            print_stack_trace_fn(stack_id)
        else:
            print(
                'Could not find stack trace where Thread %d was created' %
                thread_pids[i]
            )
        print('')
......
             for key, leaf in bpf.get_table('edges').items():
                graph.add_edge(
                    key.mutex1,
                    key.mutex2,
                    thread_pid=leaf.thread_pid,
                    thread_pid_last_ns=leaf.thread_pid_last_ns,
                    thread_comm=leaf.comm.decode('utf-8'),
                    first_mutex_stack_id=leaf.mutex1_stack_id,
                    second_mutex_stack_id=leaf.mutex2_stack_id,
                )
```
