### ISSUE TITLE
memleak: could not determine address of symbol b'malloc' with -p option 

### ISSUE THREAD

**Issue by richzw** [iovisor/bcc#4210]
We try to run `memleak` on AWS ec2 with system info `5.4.196-108.356.amzn2.x86_64`

When we run `sudo /usr/share/bcc/tools/memleak `, it works well.

However, we try to run memleak with `-p` option like

```
sudo /usr/share/bcc/tools/memleak -p $(pidof process)
```

We got the errors

```
Traceback (most recent call last):
  File "/usr/share/bcc/tools/memleak", line 449, in <module>
    attach_probes("malloc")
  File "/usr/share/bcc/tools/memleak", line 439, in attach_probes
    pid=pid)
  File "/usr/lib/python3.7/site-packages/bcc/__init__.py", line 1144, in attach_uprobe
    (path, addr) = BPF._check_path_symbol(name, sym, addr, pid, sym_off)
  File "/usr/lib/python3.7/site-packages/bcc/__init__.py", line 781, in _check_path_symbol
    raise Exception("could not determine address of symbol %s" % symname)
Exception: could not determine address of symbol b'malloc'
```

We also try to add ` -O /lib64/libc-2.26.so` option like

```
sudo /usr/share/bcc/tools/memleak -p $(pidof process)  -O /lib64/libc-2.26.so
```

The same error comes up again.

Is there anything am I missing?

**Comment by chenhengqi** [comment]
It is likely because the symbols has been stripped from `/lib64/libc-2.26.so`.

What's the result of `nm /lib64/libc-2.26.so | grep malloc` ?

**Comment by richzw** [comment]
@chenhengqi 

Here is the result of  `nm /lib64/libc-2.26.so | grep malloc`

```
00000000003a8a20 b cache_malloced
00000000003a9908 b disallow_malloc_check
000000000007e5b0 t __GI___libc_malloc
000000000007c7b0 t _int_malloc
000000000007e5b0 T __libc_malloc
00000000003a7264 d __libc_malloc_initialized
000000000007e5b0 T malloc
000000000007e5b0 t __malloc
0000000000079da0 t __malloc_assert
000000000007d6d0 t malloc_check
000000000007e530 t __malloc_check_init
000000000007a310 t malloc_consolidate
000000000007e360 t __malloc_fork_lock_parent
000000000007e490 t __malloc_fork_unlock_child
000000000007e400 t __malloc_fork_unlock_parent
0000000000128560 T malloc_get_state@GLIBC_2.2.5
00000000000800c0 t mallochook
00000000003a7c30 V __malloc_hook
000000000007e8a0 t malloc_hook_ini
000000000007fdd0 t __malloc_info
000000000007fdd0 W malloc_info
000000000007ae70 t __malloc_info.part.10
00000000003a98f0 V __malloc_initialize_hook@GLIBC_2.2.5
0000000000079c40 t malloc_init_state
0000000000079c90 t malloc_printerr
0000000000128580 T malloc_set_state@GLIBC_2.2.5
000000000007f9d0 t __malloc_stats
000000000007f9d0 W malloc_stats
000000000007f560 t __malloc_trim
000000000007f560 W malloc_trim
000000000007f7f0 t __malloc_usable_size
000000000007f7f0 W malloc_usable_size
00000000003a9970 b old_malloc_hook
000000000007a8b0 t ptmalloc_init
000000000007a690 t ptmalloc_init.part.1
000000000007bf40 t sysmalloc
0000000000080950 t tr_mallochook
00000000003a9998 b tr_old_malloc_hook
00000000003a990c b using_malloc_checking
```

**Comment by chenhengqi** [comment]
Please make sure your target process is linked against /lib64/libc-2.26.s.

**Comment by richzw** [comment]
@chenhengqi Thank you very much for your help.

After checking the files under `/proc/$(pidof process)/root/lib`,  I found the `libc.musl-x86_64.so.1`

```
sudo /usr/share/bcc/tools/memleak -p $(pidof process) -O /lib/libc.musl-x86_64.so.1
```

It works well now.

**Comment by galderz** [comment]
I was encountering the same issue and @richzw's comment gave me the clue on how to address this. The issue though is that there's a few libc*so files around in my system. After trying a few of them, the one that worked on my system (Fedora 37, x86) was `-O /lib64/libc.so.6`.

**Comment by galv** [comment]
I have the same error and found that my problem is that my libc.so.6 is apparently stripped.

```
$ nm /lib/x86_64-linux-gnu/libc-2.31.so 
nm: /lib/x86_64-linux-gnu/libc-2.31.so: no symbols```

But how would I get a non-stripped version of it? Speaking frankly, I'm surprised that a vanilla ubuntu 20.04 install has its symbols from libc stripped anyway.
