### ISSUE TITLE
vlan_learning.py: TypeError: expected bytes, int found

### ISSUE THREAD

**Issue by ruicao93** [iovisor/bcc#4243]
sudo ./examples/vlan_learning/vlan_learning.py

```
Traceback (most recent call last):
  File "/root/workspace/bcc/examples/networking/vlan_learning/vlan_learning.py", line 80, in <module>
    sim.start()
  File "/root/workspace/bcc/examples/networking/vlan_learning/vlan_learning.py", line 66, in start
    ingress[ingress.Key(mac)] = ingress.Leaf(idx, 0, 0, 0, 0)
TypeError: expected bytes, int found

```

**Comment by ruicao93** [comment]
Set breakpoint at `ingress = b.get_table("ingress")`

![ingress](https://user-images.githubusercontent.com/4922662/191015886-547d7581-9884-4cf8-a585-3e836eed8223.png)

```
_fields_ = {list: 6} [('out_ifindex', <class 'ctypes.c_int'>), ('vlan_tci', <class 'ctypes.c_int'>), ('vlan_proto', <class 'ctypes.c_int'>), ('__pad_3', <class 'bcc.c_char_Array_4'>), ('tx_pkts', <class 'ctypes.c_ulong'>), ('tx_bytes', <class 'ctypes.c_ulong'>)]
 0 = {tuple: 2} ('out_ifindex', <class 'ctypes.c_int'>)
 1 = {tuple: 2} ('vlan_tci', <class 'ctypes.c_int'>)
 2 = {tuple: 2} ('vlan_proto', <class 'ctypes.c_int'>)
 3 = {tuple: 2} ('__pad_3', <class 'bcc.c_char_Array_4'>)
 4 = {tuple: 2} ('tx_pkts', <class 'ctypes.c_ulong'>)
 5 = {tuple: 2} ('tx_bytes', <class 'ctypes.c_ulong'>)
 __len__ = {int} 6
```
There's an additional field: ` 3 = {tuple: 2} ('__pad_3', <class 'bcc.c_char_Array_4'>)`
