### ISSUE TITLE
arm64: 'asm/types.h' file not found

### ISSUE THREAD

**Issue by NirGeller18** [iovisor/bcc#4253]
Hi there,

I'm trying to use bcc tools 0.17.0-ad5b82a5 on a arm64. Python version is 3.9,
Kernel version is 5.10.109, and I have the kernel headers installed on the file system.

When trying to use any tool, I'm getting the following error:

# ./tcptop
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
include/uapi/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
         ^~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/./tcptop", line 225, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3.9/site-packages/bcc/__init__.py", line 364, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

Referring to issue #3731 I tried setting the environment variable BCC_KERNEL_SOURCE, but the result is the same.
Anyway, this issue is relevant to x86-64, my case is arm64.

Can you advise?

Thanks,

Nir.

**Comment by NirGeller18** [comment]
Hi,

any comment would be appreciated.

**Comment by chenhengqi** [comment]
Have you tried all advices in #3731 ? I don't have a arm64 device to reproduce this.

**Comment by NirGeller18** [comment]
Hi,

I tried all kinds of symbolic links like
/usr/include/aarch64-linux-gnu/asm -> /usr/include/asm

I also tried setting the environment variable BCC_KERNEL_SOURCE pointing it to the kernel headers on my file system,
/lib/modules/5.10.109-tq+g7545a39531f6-tq/build/

the result is always the same.

If possible, I'm looking for an elegant solution that doesn't involve editing the linux kernel headers or copying files from one directory to another.

Thanks,

Nir.

**Comment by NirGeller18** [comment]
Does anybody have experience with using bcc tools on arm64?

**Comment by woodpenker** [comment]
> 

I had met the same error before, but link `/usr/include/asm` to `/usr/include$(uname -m)-linux-gnu/asm` solved this. Maybe you need to check if `asm/types.h` exists or search on the system to find one. Just FYI.

**Comment by Vibgitcode27** [comment]
Hey! I encountered this error as well...

```
fatal error: 'asm/types.h' file not found
    5 | #include <asm/types.h>
      |          ^~~~~~~~~~~~~
1 error generated.
Error: compile: exit status 1
exit status 1
gen.go:3: running "go": exit status 1
```

It turns out the issue was caused by a bad symbolic link for `/usr/include/asm`. Even If you dont have one already you can skip 1st step. Here's how I fixed it:

1. **Check the current link**
   I ran:
   ```bash
   ls -l /usr/include/asm
   ```
   This showed that the link was pointing to `aarch64-linux-gnu/asm`, which is for ARM architectures. My system is `x86_64`, so this was wrong.

2. **Find the correct `asm/types.h`**
   I searched for `types.h` files in the `asm` directories:
   ```bash
   find /usr/include -name "types.h" | grep asm
   ```
   This pointed me to `/usr/include/x86_64-linux-gnu/asm/types.h`.

3. **Fix the symbolic link**
   I removed the incorrect link and created a new one pointing to the correct directory:
   ```bash
   sudo rm /usr/include/asm
   sudo ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/asm
   ```

4. **Verify the fix**
   I ran:
   ```bash
   ls -l /usr/include/asm
   ```
   Now the link points to `/usr/include/x86_64-linux-gnu/asm`.
