### ISSUE TITLE
Failing items_update_batch() call when updating BPF_HASH_OF_MAPS

### ISSUE THREAD

**Issue by buraks78** [iovisor/bcc#4314]
I have been unable to resolve this issue when I try to update a BPF_HASH_OF_MAPS type from python.

Relevant BPF maps from the code:

```
BPF_HASH(partitions, u32, u32, 256); // part dev id -> owner dev id
BPF_ARRAY(devs, u32, 256); // dev id
BPF_HASH_OF_MAPS(holders, u32, "devs", 256); // dev id -> hash of holder dev ids
```

This section works:

```
partitions = dict()

for device in block_stack.devices.values():
    if device.is_partition:
        partitions[device.id] = device.owner

partition_array_t = ctypes.c_uint * len(partitions)

b["partitions"].items_update_batch(partition_array_t(*partitions.keys()), partition_array_t(*partitions.values()))
```

This fails:

```
holders = dict()

holders_dev_array_t = ctypes.c_uint * 256

for device in block_stack.devices.values():
    if len(device.holders) > 0:
        holders[device.id] = holders_dev_array_t(*device.holders)

holders_key_array_t = ctypes.c_uint * len(holders)
holders_value_array_t = holders_dev_array_t * len(holders)

b["holders"].items_update_batch(holders_key_array_t(*holders.keys()), holders_value_array_t(*holders.values()))
```

```
 Traceback (most recent call last):
  File "/home/buraks78/workspace/sysbpf/tools/block-stack.py", line 45, in <module>
    b["holders"].items_update_batch(holders_key_array_t(*holders.keys()), holders_value_array_t(*holders.values()))
  File "/usr/lib/python3.10/site-packages/bcc/table.py", line 533, in items_update_batch
    raise Exception("BPF_MAP_UPDATE_BATCH has failed: %s"
Exception: BPF_MAP_UPDATE_BATCH has failed: Bad file descriptor
```

Am I running into a limitation or am I missing something?

Environment:

```
[root@metal ~]# rpm -qa | grep bcc
bcc-tools-0.22.0-3.fc36.x86_64
bcc-0.22.0-3.fc36.x86_64
python3-bcc-0.22.0-3.fc36.noarch

[root@metal ~]# python --version
Python 3.10.7
```

**Comment by chenhengqi** [comment]
From userspace's perspective, value of a HASH_OF_MAPS should be fd (file descriptor of another BPF map).

**Comment by buraks78** [comment]
Ah, that essentially means I cannot populate that map in python since I don't have the file descriptors defined yet. I guess the solution is to stick with conventional approaches (search/replace/inject map definitions into the bpf template). Thank you.

**Comment by chenhengqi** [comment]
There is a `get_fd()` method available for such use cases.

**Comment by buraks78** [comment]
Thanks again.
