### ISSUE TITLE
python error ： Exception: Failed to detach BPF from kprobe

### ISSUE THREAD

**Issue by lk137095576** [iovisor/bcc#4348]
the /usr/share/bcc/tools/tcptop  can run, but the hellow_world.py get error.
**I install bcc from source.**

python hellow_world.py
`
Traceback (most recent call last):
  File "hello_world.py", line 12, in <module>
    BPF(text='int kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1326, in trace_print
    line = self.trace_readline(nonblocking=False)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1302, in trace_readline
    trace = self.trace_open(nonblocking)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1259, in trace_open
    self.tracefile = open("%s/trace_pipe" % TRACEFS, "rb")
IOError: [Errno 2] No such file or directory: '/sys/kernel/debug/tracing/trace_pipe'
open(/sys/kernel/debug/tracing/kprobe_events): No such file or directory
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1506, in cleanup
    self.detach_kprobe_event(k)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 721, in detach_kprobe_event
    raise Exception("Failed to detach BPF from kprobe")
Exception: Failed to detach BPF from kprobe
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1506, in cleanup
    self.detach_kprobe_event(k)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 721, in detach_kprobe_event
    raise Exception("Failed to detach BPF from kprobe")
Exception: Failed to detach BPF from kprobe`

The python --version is 2.7 default, so I try 
'python3 hellow_world.py'
I got anothe error:

`Traceback (most recent call last):
  File "hello_world.py", line 12, in <module>
    BPF(text='int kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1326, in trace_print
    line = self.trace_readline(nonblocking=False)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1302, in trace_readline
    trace = self.trace_open(nonblocking)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1259, in trace_open
    self.tracefile = open("%s/trace_pipe" % TRACEFS, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/tracing/trace_pipe'
open(/sys/kernel/debug/tracing/kprobe_events): No such file or directory
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1506, in cleanup
    self.detach_kprobe_event(k)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 721, in detach_kprobe_event
    raise Exception("Failed to detach BPF from kprobe")
Exception: Failed to detach BPF from kprobe
`

whereis python 
`/usr/bin/python3.6 /usr/bin/python2.7 /usr/bin/python3.6-config /usr/bin/python3.6m-config /usr/bin/python3.6m /usr/bin/python /usr/lib/python3.6 /usr/lib/python2.7 /usr/lib/python3.7 /usr/lib/python3.8 /etc/python3.6 /etc/python2.7 /etc/python /usr/local/lib/python3.6 /usr/local/lib/python2.7 /usr/include/python3.6 /usr/include/python3.6m /usr/share/python`

Ubuntu18.04.1
5.4.0-128-generic

**Comment by lk137095576** [comment]
> Look like you don't have tracefs mounted.

I work in docker, so how I tracefs mounted? the tutorial not mention

**Comment by chenhengqi** [comment]
```shell
$ mount -t tracefs nodev /sys/kernel/tracing
```

**Comment by lk137095576** [comment]
@chenhengqi  

1. I have mount it, but the same errro with python2 and python3

`
Traceback (most recent call last):
  File "hello_world.py", line 12, in <module>
    BPF(text='int kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1326, in trace_print
    line = self.trace_readline(nonblocking=False)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1302, in trace_readline
    trace = self.trace_open(nonblocking)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1259, in trace_open
    self.tracefile = open("%s/trace_pipe" % TRACEFS, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/tracing/trace_pipe'
open(/sys/kernel/debug/tracing/kprobe_events): No such file or directory
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1506, in cleanup
    self.detach_kprobe_event(k)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 721, in detach_kprobe_event
    raise Exception("Failed to detach BPF from kprobe")
Exception: Failed to detach BPF from kprobe

`

2.the dir /sys/kernel/debug is empty.

**Comment by chenhengqi** [comment]
Please mount debugfs.

**Comment by lk137095576** [comment]
> 

@chenhengqi   Thanks, It works, good job.
