### ISSUE TITLE
bpf: Failed to load program: Invalid argument

### ISSUE THREAD

**Issue by xhtechxposed** [iovisor/bcc#4360]
bpf: Failed to load program: Invalid argument

Traceback (most recent call last):
  File "examples/hello_world.py", line 12, in <module>
    BPF(text='int kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 351, in __init__
    self._trace_autoload()
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1097, in _trace_autoload
    fn = self.load_func(func_name, BPF.KPROBE)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 391, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program kprobe__sys_clone: Invalid argument

**Comment by xhtechxposed** [comment]
how to fix it ？

**Comment by chenhengqi** [comment]
What's the result of `cat /proc/kallsyms | grep sys_clone` ?

**Comment by vladd12** [comment]
Maybe it's happens cause you use python 2.7?

**Comment by xhtechxposed** [comment]
cat /proc/kallsyms | grep sys_clone result:ffffff979b554cd0 t sys_clone

**Comment by xhtechxposed** [comment]
root@localhost:/bcc-master# execsnoop
bpf: Failed to load program: Invalid argument

Traceback (most recent call last):
  File "/usr/share/bcc/tools/execsnoop", line 172, in <module>
    b.attach_kprobe(event=execve_fnname, fn_name="syscall__execve")
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 650, in attach_kprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 391, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program syscall__execve: Invalid argument
all script error is this result

**Comment by xhtechxposed** [comment]
i was compile android 12 ,android and open bpf kernel tracing, and run this demo is tip this text,pls brother help me

**Comment by woodpenker** [comment]
Does your kernel compiled with CONFIG_KPROBES enable? You can check that by `zcat /proc/config.gz`(if /proc/config.gz exists) or `grep KPROBE /boot/config-$(uname -r)`
