### ISSUE TITLE
Exception: Failed to attach BPF program b'do_count' to kprobe b'account_page_dirtied'

### ISSUE THREAD

**Issue by chn-lee-yumi** [iovisor/bcc#4434]
OS: Debian 11.2

Kernel: `5.19.0-0.deb11.2-amd64`

When I run `cachestat-bpfcc`, it shows:

```
cannot attach kprobe, probe entry may not exist
Traceback (most recent call last):
  File "/usr/sbin/cachestat-bpfcc", line 99, in <module>
    b.attach_kprobe(event="account_page_dirtied", fn_name="do_count")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 683, in attach_kprobe
    raise Exception("Failed to attach BPF program %s to kprobe %s" %
Exception: Failed to attach BPF program b'do_count' to kprobe b'account_page_dirtied'
```

Logs in `/sys/kernel/debug/tracing/error_log`:

```
[  805.005493] trace_kprobe: error: Invalid probed address or symbol
  Command: p:kprobes/p_account_page_dirtied_bcc_9672 account_page_dirtied
                                                     ^
```

**Comment by chn-lee-yumi** [comment]
It seems due to the version of the kernel. I degraded it to `5.10.0-18-amd64`, and those tools work fine.
