### ISSUE TITLE
compiling error happens when executing ./biolatency.py -D

### ISSUE THREAD

**Issue by 10033908** [iovisor/bcc#4485]
`$ ./biolatency.py -D`

### Then it fails to compile like this:
```
/virtual/main.c:37:18: error: incompatible integer to pointer conversion initializing 'struct request *' with an expression of type 'unsigned long' [-Wint-conversion]
 struct request *req = ctx->di;
                 ^ __ ~~~~~~~

/virtual/main.c:49:18: error: incompatible integer to pointer conversion initializing 'struct request *' with an expression of type 'unsigned long' [-Wint-conversion]
 struct request *req = ctx->di;
                 ^     ~~~~~~~

/virtual/main.c:64:139: error: incompatible integer to pointer conversion passing 'u64' (aka 'unsigned long long') to parameter of type 'const void *' [-Wint-conversion]
    void *__tmp = (void *)({ typeof(struct gendisk *) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&req->rq_disk); _val; })->disk_name;
                                                                                                                                           ^~~~~~~~~~~~~~~~~~

3 errors generated.
Traceback (most recent call last):
  File "/home/ytcui22/bpf/bcc/tools/./biolatency.py", line 204, in <module>
    b = BPF(text=bpf_text)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bcc/__init__.py", line 476, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```
`I use clearlinux5.15  and kernel is 5.15.39 (x86_64). Not all bcc tools will fail like funclatency can work.`

**Comment by chenhengqi** [comment]
What's your BCC and LLVM versions ?

Please try build from source.

**Comment by 10033908** [comment]
> What's your BCC and LLVM versions ?
> 
> Please try build from source.
Yeah, you are right. I just git clone the source code and directly use the py scripts in /tools. 
I build bcc and now everything is ok
