### ISSUE TITLE
Getting fatal error: './include/linux/kconfig.h' file not found

### ISSUE THREAD

**Issue by srikanth007m** [iovisor/bcc#4503]
Hi @rtomayko, 

I am running bcc on 6.1 kernel and can not use memleak due to below error. 

I have installed the headers too.
`
root@localhost:/usr/share/bcc/tools# python3 memleak
<built-in>:1:10: fatal error: './include/linux/kconfig.h' file not found
#include "./include/linux/kconfig.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "memleak", line 445, in <module>
    bpf = BPF(text=bpf_source)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 479, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
`

**Comment by yuxuanyan** [comment]
got same error, have you resolved it?

**Comment by yuxuanyan** [comment]
for newer kernel version, check /sys/kernel/kheaders.tar.xz

**Comment by chillsoul** [comment]
> for newer kernel version, check /sys/kernel/kheaders.tar.xz

hi dude, have you resolved it?

i've unzip kheaders.tar.xz at /lib/modules/$(uname -r)/build , however there isn't any change.

**Comment by oraSC** [comment]
I get the same issue in kernel-6.1, have you resolved it @chillsoul @yuxuanyan

**Comment by severecold** [comment]
Android device ?
checkout this patch for kernel6.1 bazel build, it will store the correct header files rather than symlinks in kheaders.tar.xz.
https://android-review.googlesource.com/c/kernel/common/+/2635289

**Comment by oraSC** [comment]
@severecold It works! thanks
