### ISSUE TITLE
AttributeError: module 'distutils' has no attribute 'filelist'

### ISSUE THREAD

**Issue by galv** [iovisor/bcc#4514]
I get the following when I try to install bcc from source on ubuntu 20.04, following [these instructions](https://github.com/iovisor/bcc/blob/master/INSTALL.md#install-and-compile-bcc-1):

Specifically I get this stack trace right after doing:

```
export LLVM_ROOT=/usr/lib/llvm-12/
cmake ..
make
```

```
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    setup(name='bcc',
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 44, in run
    self.run_command('egg_info')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 297, in run
    self.find_sources()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 304, in find_sources
    mm.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 535, in run
    self.add_defaults()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 587, in add_defaults
    self.filelist.graft(ei_cmd.egg_info)
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 442, in graft
    found = [
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 445, in <listcomp>
    for item in distutils.filelist.findall(match_dir)
AttributeError: module 'distutils' has no attribute 'filelist'
```

It looks like bcc depends upon an older version of distutils than I have?

**Comment by galv** [comment]
Problem was that PYTHONPATH was set to "/usr/lib/python3/dist-packages". Deleting the environment variable fixed this.
