### ISSUE TITLE
example strlen_count.py work on Android

### ISSUE THREAD

**Issue by b-ripper** [iovisor/bcc#4515]
On Android, libc is /apex/omandroid.runtime/lib6/bionic/libc.so.

I modified strlen_count.py for this:
```
b.attach_uprobe(name="apex/com.android.runtime/lib64/bionic/libc.so", sym="strlen", fn_name="count")
error: Failed to attach BPF to uprobe
```
```
static int bpf_attach_probe(int progfd, enum bpf_probe_attach_type attach_type,
                            const char *ev_name, const char *config1, const char* event_type,
                            uint64_t offset, pid_t pid, int maxactive,
                            uint32_t ref_ctr_offset)
```
the env_name is p__apex_com_android_runtime_lib64_bionic_libc_so_0xf9544  , ref_ctr_offset is 1

```
bpftrace -v -e 'u:/apex/com.android.runtime/lib64/bionic/libc.so:strlen {}'
```
It succeed:
the env_name is p__apex_com_android_runtime_lib64_bionic_libc_so_f9544_1   , ref_ctr_offset is 0

```
trace.py -s /apex/omandroid.runtime/lib6/bionic/libc.so 'p:c:strlen'
```

```
Note: Kernel bpf will report stack map with ip/build_id
Can't mix strings and bytes in path components

**Comment by b-ripper** [comment]
Could ou help to have a look, @michalgr , very thanks!

**Comment by chenhengqi** [comment]
Try running with `-v` and paste the output here.

**Comment by b-ripper** [comment]
the output of python3 -v trace.py -s /apex/omandroid.runtime/lib6/bionic/libc.so 'p:c:strlen'
```
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# /lib/python3.10/encodings/__pycache__/__init__.cpython-310.pyc matches /lib/python3.10/encodings/__init__.py
# code object from '/lib/python3.10/encodings/__pycache__/__init__.cpython-310.pyc'
# /lib/python3.10/__pycache__/codecs.cpython-310.pyc matches /lib/python3.10/codecs.py
# code object from '/lib/python3.10/__pycache__/codecs.cpython-310.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06f1bc40>
# /lib/python3.10/encodings/__pycache__/aliases.cpython-310.pyc matches /lib/python3.10/encodings/aliases.py
# code object from '/lib/python3.10/encodings/__pycache__/aliases.cpython-310.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06d693f0>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06f1bac0>
# /lib/python3.10/encodings/__pycache__/utf_8.cpython-310.pyc matches /lib/python3.10/encodings/utf_8.py
# code object from '/lib/python3.10/encodings/__pycache__/utf_8.cpython-310.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06d69390>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# /lib/python3.10/__pycache__/io.cpython-310.pyc matches /lib/python3.10/io.py
# code object from '/lib/python3.10/__pycache__/io.cpython-310.pyc'
# /lib/python3.10/__pycache__/abc.cpython-310.pyc matches /lib/python3.10/abc.py
# code object from '/lib/python3.10/__pycache__/abc.cpython-310.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06d698a0>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06d69690>
# /lib/python3.10/__pycache__/site.cpython-310.pyc matches /lib/python3.10/site.py
# code object from '/lib/python3.10/__pycache__/site.cpython-310.pyc'
# /lib/python3.10/__pycache__/os.cpython-310.pyc matches /lib/python3.10/os.py
# code object from '/lib/python3.10/__pycache__/os.cpython-310.pyc'
# /lib/python3.10/__pycache__/stat.cpython-310.pyc matches /lib/python3.10/stat.py
# code object from '/lib/python3.10/__pycache__/stat.cpython-310.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06d6bd30>
# /lib/python3.10/__pycache__/_collections_abc.cpython-310.pyc matches /lib/python3.10/_collections_abc.py
# code object from '/lib/python3.10/__pycache__/_collections_abc.cpython-310.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06d6be80>
# /lib/python3.10/__pycache__/posixpath.cpython-310.pyc matches /lib/python3.10/posixpath.py
# code object from '/lib/python3.10/__pycache__/posixpath.cpython-310.pyc'
# /lib/python3.10/__pycache__/genericpath.cpython-310.pyc matches /lib/python3.10/genericpath.py
# code object from '/lib/python3.10/__pycache__/genericpath.cpython-310.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06da2ec0>
import 'posixpath' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06da0160>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06d6a950>
# /lib/python3.10/__pycache__/_sitebuiltins.cpython-310.pyc matches /lib/python3.10/_sitebuiltins.py
# code object from '/lib/python3.10/__pycache__/_sitebuiltins.cpython-310.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06d6ba30>
Processing user site-packages
Processing global site-packages
Adding directory: '/lib/python3.10/site-packages'
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06d6a320>
Python 3.10.6 (tags/v3.10.6-dirty:9c7b4bd, Dec  9 2022, 09:44:20) [Clang 12.0.8 (https://android.googlesource.com/toolchain/llvm-project c935d99d7 on linux
Type "help", "copyright", "credits" or "license" for more information.
# /lib/python3.10/__pycache__/__future__.cpython-310.pyc matches /lib/python3.10/__future__.py
# code object from '/lib/python3.10/__pycache__/__future__.cpython-310.pyc'
import '__future__' # <_frozen_importlib_external.SourceFileLoader object at 0x7a0630f700>
# /lib/python3.10/site-packages/bcc/__pycache__/__init__.cpython-310.pyc matches /lib/python3.10/site-packages/bcc/__init__.py
# code object from '/lib/python3.10/site-packages/bcc/__pycache__/__init__.cpython-310.pyc'
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
# /lib/python3.10/ctypes/__pycache__/__init__.cpython-310.pyc matches /lib/python3.10/ctypes/__init__.py
# code object from '/lib/python3.10/ctypes/__pycache__/__init__.cpython-310.pyc'
# /lib/python3.10/__pycache__/types.cpython-310.pyc matches /lib/python3.10/types.py
# code object from '/lib/python3.10/__pycache__/types.cpython-310.pyc'
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0x7a0630c490>
# extension module '_ctypes' loaded from '/lib/python3.10/lib-dynload/_ctypes.cpython-310.so'
# extension module '_ctypes' executed from '/lib/python3.10/lib-dynload/_ctypes.cpython-310.so'
import '_ctypes' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7a0630c310>
# /lib/python3.10/__pycache__/struct.cpython-310.pyc matches /lib/python3.10/struct.py
# code object from '/lib/python3.10/__pycache__/struct.cpython-310.pyc'
# extension module '_struct' loaded from '/lib/python3.10/lib-dynload/_struct.cpython-310.so'
# extension module '_struct' executed from '/lib/python3.10/lib-dynload/_struct.cpython-310.so'
import '_struct' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7a06e15450>
import 'struct' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06e15630>
# /lib/python3.10/ctypes/__pycache__/_endian.cpython-310.pyc matches /lib/python3.10/ctypes/_endian.py
# code object from '/lib/python3.10/ctypes/__pycache__/_endian.cpython-310.pyc'
import 'ctypes._endian' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06e143d0>
import 'ctypes' # <_frozen_importlib_external.SourceFileLoader object at 0x7a0630d120>
# extension module 'fcntl' loaded from '/lib/python3.10/lib-dynload/fcntl.cpython-310.so'
# extension module 'fcntl' executed from '/lib/python3.10/lib-dynload/fcntl.cpython-310.so'
import 'fcntl' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7a0630ca30>
# /lib/python3.10/json/__pycache__/__init__.cpython-310.pyc matches /lib/python3.10/json/__init__.py
# code object from '/lib/python3.10/json/__pycache__/__init__.cpython-310.pyc'
# /lib/python3.10/json/__pycache__/decoder.cpython-310.pyc matches /lib/python3.10/json/decoder.py
# code object from '/lib/python3.10/json/__pycache__/decoder.cpython-310.pyc'
# /lib/python3.10/__pycache__/re.cpython-310.pyc matches /lib/python3.10/re.py
# code object from '/lib/python3.10/__pycache__/re.cpython-310.pyc'
# /lib/python3.10/__pycache__/enum.cpython-310.pyc matches /lib/python3.10/enum.py
# code object from '/lib/python3.10/__pycache__/enum.cpython-310.pyc'
import 'enum' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06dff760>
# /lib/python3.10/__pycache__/sre_compile.cpython-310.pyc matches /lib/python3.10/sre_compile.py
# code object from '/lib/python3.10/__pycache__/sre_compile.cpython-310.pyc'
import '_sre' # <class '_frozen_importlib.BuiltinImporter'>
# /lib/python3.10/__pycache__/sre_parse.cpython-310.pyc matches /lib/python3.10/sre_parse.py
# code object from '/lib/python3.10/__pycache__/sre_parse.cpython-310.pyc'
# /lib/python3.10/__pycache__/sre_constants.cpython-310.pyc matches /lib/python3.10/sre_constants.py
# code object from '/lib/python3.10/__pycache__/sre_constants.cpython-310.pyc'
import 'sre_constants' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06df84c0>
import 'sre_parse' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06dfd6c0>
import 'sre_compile' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06dfe020>
# /lib/python3.10/__pycache__/functools.cpython-310.pyc matches /lib/python3.10/functools.py
# code object from '/lib/python3.10/__pycache__/functools.cpython-310.pyc'
# /lib/python3.10/collections/__pycache__/__init__.cpython-310.pyc matches /lib/python3.10/collections/__init__.py
# code object from '/lib/python3.10/collections/__pycache__/__init__.cpython-310.pyc'
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# /lib/python3.10/__pycache__/keyword.cpython-310.pyc matches /lib/python3.10/keyword.py
# code object from '/lib/python3.10/__pycache__/keyword.cpython-310.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06de4df0>
# /lib/python3.10/__pycache__/operator.cpython-310.pyc matches /lib/python3.10/operator.py
# code object from '/lib/python3.10/__pycache__/operator.cpython-310.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06de4d30>
# /lib/python3.10/__pycache__/reprlib.cpython-310.pyc matches /lib/python3.10/reprlib.py
# code object from '/lib/python3.10/__pycache__/reprlib.cpython-310.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06de4b20>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06ded750>
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06dfd9f0>
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
# /lib/python3.10/__pycache__/copyreg.cpython-310.pyc matches /lib/python3.10/copyreg.py
# code object from '/lib/python3.10/__pycache__/copyreg.cpython-310.pyc'
import 'copyreg' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06de39d0>
import 're' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06e14070>
# /lib/python3.10/json/__pycache__/scanner.cpython-310.pyc matches /lib/python3.10/json/scanner.py
# code object from '/lib/python3.10/json/__pycache__/scanner.cpython-310.pyc'
# extension module '_json' loaded from '/lib/python3.10/lib-dynload/_json.cpython-310.so'
# extension module '_json' executed from '/lib/python3.10/lib-dynload/_json.cpython-310.so'
import '_json' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7a06de3be0>
import 'json.scanner' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06de3ca0>
import 'json.decoder' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06e14190>
# /lib/python3.10/json/__pycache__/encoder.cpython-310.pyc matches /lib/python3.10/json/encoder.py
# code object from '/lib/python3.10/json/__pycache__/encoder.cpython-310.pyc'
import 'json.encoder' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06de3df0>
import 'json' # <_frozen_importlib_external.SourceFileLoader object at 0x7a0630c730>
import 'errno' # <class '_frozen_importlib.BuiltinImporter'>
# /lib/python3.10/__pycache__/platform.cpython-310.pyc matches /lib/python3.10/platform.py
# code object from '/lib/python3.10/__pycache__/platform.cpython-310.pyc'
# /lib/python3.10/__pycache__/subprocess.cpython-310.pyc matches /lib/python3.10/subprocess.py
# code object from '/lib/python3.10/__pycache__/subprocess.cpython-310.pyc'
# /lib/python3.10/__pycache__/signal.cpython-310.pyc matches /lib/python3.10/signal.py
# code object from '/lib/python3.10/__pycache__/signal.cpython-310.pyc'
import 'signal' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06de1f00>
# /lib/python3.10/__pycache__/threading.cpython-310.pyc matches /lib/python3.10/threading.py
# code object from '/lib/python3.10/__pycache__/threading.cpython-310.pyc'
# /lib/python3.10/__pycache__/_weakrefset.cpython-310.pyc matches /lib/python3.10/_weakrefset.py
# code object from '/lib/python3.10/__pycache__/_weakrefset.cpython-310.pyc'
import '_weakrefset' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06dde8f0>
import 'threading' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06de1ff0>
# /lib/python3.10/__pycache__/warnings.cpython-310.pyc matches /lib/python3.10/warnings.py
# code object from '/lib/python3.10/__pycache__/warnings.cpython-310.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06de0bb0>
# /lib/python3.10/__pycache__/contextlib.cpython-310.pyc matches /lib/python3.10/contextlib.py
# code object from '/lib/python3.10/__pycache__/contextlib.cpython-310.pyc'
import 'contextlib' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06ddd840>
# extension module '_posixsubprocess' loaded from '/lib/python3.10/lib-dynload/_posixsubprocess.cpython-310.so'
# extension module '_posixsubprocess' executed from '/lib/python3.10/lib-dynload/_posixsubprocess.cpython-310.so'
import '_posixsubprocess' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7a06ddd030>
# extension module 'select' loaded from '/lib/python3.10/lib-dynload/select.cpython-310.so'
# extension module 'select' executed from '/lib/python3.10/lib-dynload/select.cpython-310.so'
import 'select' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7a06ddc910>
# /lib/python3.10/__pycache__/selectors.cpython-310.pyc matches /lib/python3.10/selectors.py
# code object from '/lib/python3.10/__pycache__/selectors.cpython-310.pyc'
# /lib/python3.10/collections/__pycache__/abc.cpython-310.pyc matches /lib/python3.10/collections/abc.py
# code object from '/lib/python3.10/collections/__pycache__/abc.cpython-310.pyc'
import 'collections.abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06dda740>
# extension module 'math' loaded from '/lib/python3.10/lib-dynload/math.cpython-310.so'
# extension module 'math' executed from '/lib/python3.10/lib-dynload/math.cpython-310.so'
import 'math' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7a06dda650>
import 'selectors' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06ddb250>
import 'subprocess' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06de2980>
import 'platform' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06de2dd0>
# /lib/python3.10/site-packages/bcc/__pycache__/libbcc.cpython-310.pyc matches /lib/python3.10/site-packages/bcc/libbcc.py
# code object from '/lib/python3.10/site-packages/bcc/__pycache__/libbcc.cpython-310.pyc'
# /lib/python3.10/site-packages/bcc/__pycache__/perf.cpython-310.pyc matches /lib/python3.10/site-packages/bcc/perf.py
# code object from '/lib/python3.10/site-packages/bcc/__pycache__/perf.cpython-310.pyc'
# /lib/python3.10/site-packages/bcc/__pycache__/utils.cpython-310.pyc matches /lib/python3.10/site-packages/bcc/utils.py
# code object from '/lib/python3.10/site-packages/bcc/__pycache__/utils.cpython-310.pyc'
# /lib/python3.10/__pycache__/traceback.cpython-310.pyc matches /lib/python3.10/traceback.py
# code object from '/lib/python3.10/__pycache__/traceback.cpython-310.pyc'
# /lib/python3.10/__pycache__/linecache.cpython-310.pyc matches /lib/python3.10/linecache.py
# code object from '/lib/python3.10/__pycache__/linecache.cpython-310.pyc'
# /lib/python3.10/__pycache__/tokenize.cpython-310.pyc matches /lib/python3.10/tokenize.py
# code object from '/lib/python3.10/__pycache__/tokenize.cpython-310.pyc'
# /lib/python3.10/__pycache__/token.cpython-310.pyc matches /lib/python3.10/token.py
# code object from '/lib/python3.10/__pycache__/token.cpython-310.pyc'
import 'token' # <_frozen_importlib_external.SourceFileLoader object at 0x7a063176d0>
import 'tokenize' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06da3580>
import 'linecache' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06da3ac0>
import 'traceback' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06dd8be0>
import 'bcc.utils' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06dd90f0>
import 'bcc.perf' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06dd9c00>
import 'bcc.libbcc' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06dd93c0>
# /lib/python3.10/site-packages/bcc/__pycache__/table.cpython-310.pyc matches /lib/python3.10/site-packages/bcc/table.py
# code object from '/lib/python3.10/site-packages/bcc/__pycache__/table.cpython-310.pyc'
import 'bcc.table' # <_frozen_importlib_external.SourceFileLoader object at 0x7a06dd95a0>
# /lib/python3.10/site-packages/bcc/__pycache__/version.cpython-310.pyc matches /lib/python3.10/site-packages/bcc/version.py
# code object from '/lib/python3.10/site-packages/bcc/__pycache__/version.cpython-310.pyc'
import 'bcc.version' # <_frozen_importlib_external.SourceFileLoader object at 0x7a05ea7280>
# /lib/python3.10/site-packages/bcc/__pycache__/disassembler.cpython-310.pyc matches /lib/python3.10/site-packages/bcc/disassembler.py
# code object from '/lib/python3.10/site-packages/bcc/__pycache__/disassembler.cpython-310.pyc'
import 'bcc.disassembler' # <_frozen_importlib_external.SourceFileLoader object at 0x7a05ea6980>
# /lib/python3.10/site-packages/bcc/__pycache__/usdt.cpython-310.pyc matches /lib/python3.10/site-packages/bcc/usdt.py
# code object from '/lib/python3.10/site-packages/bcc/__pycache__/usdt.cpython-310.pyc'
import 'bcc.usdt' # <_frozen_importlib_external.SourceFileLoader object at 0x7a05edcb20>
import 'bcc' # <_frozen_importlib_external.SourceFileLoader object at 0x7a0630fc70>
# /lib/python3.10/__pycache__/argparse.cpython-310.pyc matches /lib/python3.10/argparse.py
# code object from '/lib/python3.10/__pycache__/argparse.cpython-310.pyc'
# /lib/python3.10/__pycache__/gettext.cpython-310.pyc matches /lib/python3.10/gettext.py
# code object from '/lib/python3.10/__pycache__/gettext.cpython-310.pyc'
import 'gettext' # <_frozen_importlib_external.SourceFileLoader object at 0x7a05edf820>
import 'argparse' # <_frozen_importlib_external.SourceFileLoader object at 0x7a0630eb30>
# /lib/python3.10/__pycache__/locale.cpython-310.pyc matches /lib/python3.10/locale.py
# code object from '/lib/python3.10/__pycache__/locale.cpython-310.pyc'
import 'locale' # <_frozen_importlib_external.SourceFileLoader object at 0x7a05edf070>
# /lib/python3.10/__pycache__/shutil.cpython-310.pyc matches /lib/python3.10/shutil.py
# code object from '/lib/python3.10/__pycache__/shutil.cpython-310.pyc'
# /lib/python3.10/__pycache__/fnmatch.cpython-310.pyc matches /lib/python3.10/fnmatch.py
# code object from '/lib/python3.10/__pycache__/fnmatch.cpython-310.pyc'
import 'fnmatch' # <_frozen_importlib_external.SourceFileLoader object at 0x7a05f2e9b0>
# /lib/python3.10/__pycache__/bz2.cpython-310.pyc matches /lib/python3.10/bz2.py
# code object from '/lib/python3.10/__pycache__/bz2.cpython-310.pyc'
# /lib/python3.10/__pycache__/_compression.cpython-310.pyc matches /lib/python3.10/_compression.py
# code object from '/lib/python3.10/__pycache__/_compression.cpython-310.pyc'
import '_compression' # <_frozen_importlib_external.SourceFileLoader object at 0x7a05f2f460>
# destroy bz2
# /lib/python3.10/__pycache__/lzma.cpython-310.pyc matches /lib/python3.10/lzma.py
# code object from '/lib/python3.10/__pycache__/lzma.cpython-310.pyc'
# destroy lzma
import 'shutil' # <_frozen_importlib_external.SourceFileLoader object at 0x7a05f2dc60>
Note: probe:
p:c:strlen FLT=1 ACT=[]/[]
Note: Kernel bpf will report stack map with ip/build_id
Can't mix strings and bytes in path components
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing sys
# cleanup[2] removing builtins
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _thread
# cleanup[2] removing _warnings
# cleanup[2] removing _weakref
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing posix
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing time
# cleanup[2] removing zipimport
# destroy zipimport
# cleanup[2] removing _codecs
# cleanup[2] removing codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing _signal
# cleanup[2] removing _abc
# cleanup[2] removing abc
# cleanup[2] removing io
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing _stat
# cleanup[2] removing stat
# cleanup[2] removing _collections_abc
# cleanup[2] removing genericpath
# cleanup[2] removing posixpath
# cleanup[2] removing os.path
# cleanup[2] removing os
# cleanup[2] removing _sitebuiltins
# cleanup[2] removing site
# destroy site
# cleanup[2] removing __future__
# destroy __future__
# cleanup[2] removing atexit
# cleanup[2] removing types
# cleanup[2] removing _ctypes
# cleanup[2] removing _struct
# cleanup[2] removing struct
# destroy struct
# cleanup[2] removing ctypes._endian
# cleanup[2] removing ctypes
# cleanup[2] removing fcntl
# cleanup[2] removing enum
# cleanup[2] removing _sre
# cleanup[2] removing sre_constants
# destroy sre_constants
# cleanup[2] removing sre_parse
# cleanup[2] removing sre_compile
# cleanup[2] removing itertools
# cleanup[2] removing keyword
# destroy keyword
# cleanup[2] removing _operator
# cleanup[2] removing operator
# destroy operator
# cleanup[2] removing reprlib
# destroy reprlib
# cleanup[2] removing _collections
# cleanup[2] removing collections
# cleanup[2] removing _functools
# cleanup[2] removing functools
# cleanup[2] removing _locale
# cleanup[2] removing copyreg
# cleanup[2] removing re
# cleanup[2] removing _json
# cleanup[2] removing json.scanner
# cleanup[2] removing json.decoder
# cleanup[2] removing json.encoder
# cleanup[2] removing json
# cleanup[2] removing errno
# cleanup[2] removing signal
# cleanup[2] removing _weakrefset
# destroy _weakrefset
# cleanup[2] removing threading
# cleanup[2] removing warnings
# cleanup[2] removing contextlib
# cleanup[2] removing _posixsubprocess
# cleanup[2] removing select
# cleanup[2] removing collections.abc
# cleanup[2] removing math
# cleanup[2] removing selectors
# cleanup[2] removing subprocess
# cleanup[2] removing platform
# cleanup[2] removing token
# destroy token
# cleanup[2] removing tokenize
# cleanup[2] removing linecache
# cleanup[2] removing traceback
# cleanup[2] removing bcc.utils
# cleanup[2] removing bcc.perf
# cleanup[2] removing bcc.libbcc
# cleanup[2] removing bcc.table
# cleanup[2] removing bcc.version
# cleanup[2] removing bcc.disassembler
# cleanup[2] removing bcc.usdt
# cleanup[2] removing bcc
# destroy bcc
# cleanup[2] removing gettext
# destroy gettext
# cleanup[2] removing argparse
# cleanup[2] removing locale
# destroy locale
# cleanup[2] removing fnmatch
# cleanup[2] removing _compression
# destroy _compression
# cleanup[2] removing shutil
# destroy shutil
# destroy argparse
# destroy _sitebuiltins
# destroy json
# destroy platform
# destroy bcc.utils
# destroy bcc.perf
# destroy bcc.libbcc
# destroy bcc.table
# destroy bcc.version
# destroy bcc.disassembler
# destroy bcc.usdt
# destroy atexit
# destroy json.decoder
# destroy json.encoder
# destroy json.scanner
# destroy enum
# destroy sre_compile
# destroy copyreg
# destroy sre_parse
# destroy _sre
# destroy _json
# destroy subprocess
# destroy signal
# destroy threading
# destroy contextlib
# destroy fcntl
# destroy selectors
# destroy _signal
# destroy _posixsubprocess
# destroy math
# destroy select
# destroy traceback
# destroy warnings
# destroy linecache
# destroy tokenize
# destroy itertools
# destroy ctypes
# destroy encodings
# destroy _locale
# destroy fnmatch
# destroy collections
# destroy errno
# destroy re
# destroy io
# cleanup[3] wiping collections.abc
# cleanup[3] wiping functools
# cleanup[3] wiping _functools
# cleanup[3] wiping _collections
# cleanup[3] wiping _operator
# cleanup[3] wiping ctypes._endian
# cleanup[3] wiping _struct
# cleanup[3] wiping _ctypes
# cleanup[3] wiping types
# cleanup[3] wiping os
# destroy abc
# destroy posixpath
# cleanup[3] wiping genericpath
# cleanup[3] wiping _collections_abc
# cleanup[3] wiping stat
# cleanup[3] wiping _stat
# destroy _stat
# cleanup[3] wiping _abc
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping time
# cleanup[3] wiping _frozen_importlib_external
# cleanup[3] wiping posix
# cleanup[3] wiping marshal
# cleanup[3] wiping _io
# cleanup[3] wiping _weakref
# cleanup[3] wiping _warnings
# cleanup[3] wiping _thread
# cleanup[3] wiping _imp
# cleanup[3] wiping _frozen_importlib
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
# destroy posix
# destroy _frozen_importlib_external
# destroy _imp
# destroy io
# destroy marshal
# destroy _warnings
# destroy stat
# destroy genericpath
# destroy _collections_abc
# destroy _weakref
# destroy _collections
# destroy collections.abc
# destroy _abc
# destroy _functools
# destroy _operator
# destroy _frozen_importlib
# destroy codecs
# destroy encodings.aliases
# destroy encodings.utf_8
# destroy _codecs
# destroy functools
# destroy time
# destroy builtins
# destroy _thread
# clear sys.audit hooks
```

**Comment by chenhengqi** [comment]
`-v` should pass to trace.py

**Comment by b-ripper** [comment]
the output od python3 strlen_count.py -v
```
cannot attach uprobe, Invalid argument
Traceback (most recent call last):
  File "strlen_count.py", line 43, in <module>
    b.attach_uprobe(name="/apex/com.android.runtime/lib64/bionic/libc.so", sym="strlen", fn_name="count")
  File "/lib/python3.10/site-packages/bcc/__init__.py", line 1377, in attach_uprobe
    raise Exception("Failed to attach BPF to uprobe")
Exception: Failed to attach BPF to uprobe
```

**Comment by b-ripper** [comment]
I modified src/cc/libbpf.c
from
```
   return bpf_attach_probe(progfd, attach_type,
                           ev_name, binary_path, "uprobe",
                           offset, pid, -1, ref_ctr_offset);
```
to
```
  return bpf_attach_probe(progfd, attach_type,
                          ev_name, binary_path, "uprobe",
                          offset, pid, -1, 0);

```
python3 strlen_count.py -v will work.

but the python3 trace.py -v -s /apex/com.android.runtime/lib6/bionic/libc.so 'p:c:strlen' still fail with the same error, I think it's flow of format parsing has problem.

**Comment by b-ripper** [comment]
with the hard code modified above, 
python3 trace.py /apex/com.android.runtime/lib64/bionic/libc.so:strlen  works.

**Comment by chenhengqi** [comment]
How do you build BCC for Android ?

**Comment by b-ripper** [comment]
yes, it's my problem of building bcc.
