### ISSUE TITLE
Exception: Failed to attach BPF program b'kprobe__sys_clone' to kprobe b'sys_clone', it's not traceable (either non-existing, inlined, or marked as "notrace")

### ISSUE THREAD

**Issue by lxy417** [iovisor/bcc#4565]
My ubuntu kernel：Linux ubuntu 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
The following error occurred when I ran sudo python3 hello_world.py
```
cannot attach kprobe, probe entry may not exist
Traceback (most recent call last):
  File "./hello_world.py", line 12, in <module>
    BPF(text='int kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
  File "/usr/lib/python3/dist-packages/bcc-0.27.0+9371e844-py3.8.egg/bcc/__init__.py", line 487, in __init__
  File "/usr/lib/python3/dist-packages/bcc-0.27.0+9371e844-py3.8.egg/bcc/__init__.py", line 1456, in _trace_autoload
  File "/usr/lib/python3/dist-packages/bcc-0.27.0+9371e844-py3.8.egg/bcc/__init__.py", line 845, in attach_kprobe
Exception: Failed to attach BPF program b'kprobe__sys_clone' to kprobe b'sys_clone', it's not traceable (either non-existing, inlined, or marked as "notrace")
```
Why is that?

**Comment by lxy417** [comment]
I checked that the kprobes enabled
![image](https://user-images.githubusercontent.com/33677809/232054408-5fe9efa4-07fc-45dc-a46d-9e778a884ca2.png)
but it still can't run

**Comment by lxy417** [comment]
I know what caused it
I want to use bcc in Android, then I used a emulator called linzhuo, this emulator used linux kernel, so I can easily trace android art native library. But I found that if I open this emulator, I can't hook the functions of the linux kernel. 
I don't know why this is happening, but it shouldn't be your problem.

**Comment by chenhengqi** [comment]
You should trace `__x64_sys_clone` instead.

**Comment by ceddie** [comment]
> I want to use `bpf_override_return()` on Android, but I get the same error. (Duplicate of [#2485 (comment)](https://github.com/iovisor/bcc/issues/2485#issuecomment-1589432879))
> 
> I set up the kernel parameter.
> 
> ```
> root@localhost:/bpfonandroid# zcat /proc/config.gz | grep -E "CONFIG_FUNCTION_ERROR_INJECTION|KPROBE_OVERRIDE"
> CONFIG_BPF_KPROBE_OVERRIDE=y
> CONFIG_FUNCTION_ERROR_INJECTION=y
> ```
> 
> And I checked if openat has `ALLOW_ERROR_INJECTION`
> 
> ```
> root@localhost:/bpfonandroid# cat /proc/kallsyms | grep _eil_addr | grep __x64_sys_openat
> ffffffff84b93ba0 d _eil_addr___x64_sys_openat
> ffffffff84b93bb0 d _eil_addr___x64_sys_openat2
> ```
> 
> And when I try to attach a kretprobe to `__x64_sys_openat` I get the error:
> 
> ```
> ioctl(PERF_EVENT_IOC_SET_BPF): Invalid argument
> Traceback (most recent call last):
>   File "/bpfonandroid/./main.py", line 116, in <module>
>     main()
>   File "/bpfonandroid/./main.py", line 82, in main
>     b.attach_kretprobe(event="__x64_sys_openat", fn_name="test")
>   File "/usr/lib/python3/dist-packages/bcc-0.27.0+a078cbc7-py3.9.egg/bcc/__init__.py", line 889, in attach_kretprobe
> Exception: Failed to attach BPF program b'test' to kretprobe b'__x64_sys_openat', it's not traceable (either non-existing, inlined, or marked as "notrace")
> ```
> 
> I use the following Kernel for Android 12
> 
> ```
> root@localhost:/bpfonandroid# uname -r
> 5.10.177-android12-9-gb82903573e48-dirty
> ```
> 
> And the same thing works on Linux kernel 5.10.177.
> 
> **Has anybody some advise?**

I just found out that the same code runs on Android 13 with Kernel 5.15.106.
```
# uname -r
5.15.106-android13-8-g19c0ed55a470-dirty
```

**Comment by chenhengqi** [comment]
Maybe you can figure it out by comparing the two kernel configs ?

**Comment by Wh1isper** [comment]
> You should trace __x64_sys_clone instead.

I can trace `__do_sys_clone` instead of `__x64_sys_clone`


```python
# Not working
BPF(text='int kprobe____x64_sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
```

```
Exception: Failed to attach BPF program b'kprobe____x64_sys_clone' to kprobe b'sys_clone', it's not traceable (either non-existing, inlined, or marked as "notrace")
```


```python
# Worked!
BPF(text='int kprobe____do_sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
```


```
$ grep sys_clone /proc/kallsyms
0000000000000000 t __do_sys_clone
0000000000000000 T __x64_sys_clone
0000000000000000 t __do_sys_clone3
0000000000000000 T __x64_sys_clone3
0000000000000000 d _eil_addr___x64_sys_clone3
0000000000000000 d _eil_addr___x64_sys_clone
```

**Comment by LLeavesG** [comment]
> I want to use `bpf_override_return()` on Android, but I get the same error.
> 
> I set up the kernel parameter.
> 
> ```
> root@localhost:/bpfonandroid# zcat /proc/config.gz | grep -E "CONFIG_FUNCTION_ERROR_INJECTION|KPROBE_OVERRIDE"
> CONFIG_BPF_KPROBE_OVERRIDE=y
> CONFIG_FUNCTION_ERROR_INJECTION=y
> ```
> 
> And I checked if openat has `ALLOW_ERROR_INJECTION`
> 
> ```
> root@localhost:/bpfonandroid# cat /proc/kallsyms | grep _eil_addr | grep __x64_sys_openat
> ffffffff84b93ba0 d _eil_addr___x64_sys_openat
> ffffffff84b93bb0 d _eil_addr___x64_sys_openat2
> ```
> 
> And when I try to attach a kretprobe to `__x64_sys_openat` I get the error:
> 
> ```
> ioctl(PERF_EVENT_IOC_SET_BPF): Invalid argument
> Traceback (most recent call last):
>   File "/bpfonandroid/./main.py", line 116, in <module>
>     main()
>   File "/bpfonandroid/./main.py", line 82, in main
>     b.attach_kretprobe(event="__x64_sys_openat", fn_name="test")
>   File "/usr/lib/python3/dist-packages/bcc-0.27.0+a078cbc7-py3.9.egg/bcc/__init__.py", line 889, in attach_kretprobe
> Exception: Failed to attach BPF program b'test' to kretprobe b'__x64_sys_openat', it's not traceable (either non-existing, inlined, or marked as "notrace")
> ```
> 
> I use the following Kernel for Android 12
> 
> ```
> root@localhost:/bpfonandroid# uname -r
> 5.10.177-android12-9-gb82903573e48-dirty
> ```
> 
> And the same thing works on Linux kernel 5.10.177.
> 
> **Has anybody some advise?**


Is there any solution to your problem please, I'm having the same problem with Android 5.10 kernel, thanks bro! @ceddie
