### ISSUE TITLE
make test throwing error for all usdt tests

### ISSUE THREAD

**Issue by dubeyabhishek** [iovisor/bcc#4631]
2/4 Testing: py_test_usdt
2/4 Test: py_test_usdt
Command: "/home/abhishek/bcc/build/tests/wrapper.sh" "py_test_usdt" "sudo" "/home/abhishek/bcc/tests/python/test_usdt.py"
Directory: /home/abhishek/bcc/tests/python
"py_test_usdt" start time: Jun 09 20:24 IST
Output:
----------------------------------------------------------
<stdin>:23:17: warning: null character(s) preserved in literal
<stdin>:28:17: warning: null character(s) preserved in literal
E
======================================================================
ERROR: test_attach1 (__main__.TestUDST.test_attach1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abhishek/bcc/tests/python/test_usdt.py", line 145, in test_attach1
    u.enable_probe(probe="probe_point_1", fn_name="do_trace1")
  File "/home/abhishek/bcc/build/src/python/bcc-python3/bcc/usdt.py", line 161, in enable_probe
    raise USDTException(
bcc.usdt.USDTException: Failed to enable USDT probe 'probe_point_1':
the specified pid might not contain the given language's runtime,
or the runtime was not built with the required USDT probes. Look
for a configure flag similar to --with-dtrace or --enable-dtrace.
To check which probes are present in the process, use the tplist tool.

----------------------------------------------------------------------
Ran 1 test in 1.438s

FAILED (errors=1)
Failed
<end of output>
Test time =   2.98 sec
----------------------------------------------------------
Test Failed.
"py_test_usdt" end time: Jun 09 20:24 IST
"py_test_usdt" time elapsed: 00:00:02
----------------------------------------------------------

Which runtime needs to be configured with "--with-dtrace or --enable-dtrace".  I don't find any bcc compilation step for same.

**Comment by Lan-ce-lot** [comment]
I have the same problem.
```
Failed to enable USDT probe 'operation_start_std':
the specified pid might not contain the given language's runtime,
or the runtime was not built with the required USDT probes. Look
for a configure flag similar to --with-dtrace or --enable-dtrace.
To check which probes are present in the process, use the tplist tool.
```
