### ISSUE TITLE
undefined symbol: bpf_module_create_b

### ISSUE THREAD

**Issue by TwilightTechie** [iovisor/bcc#4671]
Hi, I am using ubuntu based system. I recently tried to install bcc and use tools. However, I am getting this error when executing the following commands:

anup@yoga:~/bcc/bcc/tools$ python3 offcputime.py 
Traceback (most recent call last):
  File "/home/anup/bcc/bcc/tools/offcputime.py", line 19, in <module>
    from bcc import BPF
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 27, in <module>
    from .libbcc import lib, bcc_symbol, bcc_symbol_option, bcc_stacktrace_build_id, _SYM_CB_TYPE
  File "/usr/lib/python3/dist-packages/bcc/libbcc.py", line 20, in <module>
    lib.bpf_module_create_b.restype = ct.c_void_p
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_module_create_b

I tried doing a couple of things still the issue is there.

**Comment by TwilightTechie** [comment]
I removed the preinstalled bpfcc-tools and also run sudo python offcputime.py and it work

**Comment by waydenlee** [comment]
@TwilightTechie Can you explain little bit more about this? Have similar issue.

===
root@aks-nodepool1-18472169-vmss000003:/usr/share/bcc/tools# sudo python tcptracer
Traceback (most recent call last):
  File "/usr/share/bcc/tools/tcptracer", line 18, in <module>
    from bcc import BPF
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 27, in <module>
    from .libbcc import lib, bcc_symbol, bcc_symbol_option, bcc_stacktrace_build_id, _SYM_CB_TYPE
  File "/usr/lib/python3/dist-packages/bcc/libbcc.py", line 20, in <module>
    lib.bpf_module_create_b.restype = ct.c_void_p
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_module_create_b

===
root@aks-nodepool1-18472169-vmss000003:/usr/share/bcc/tools# ./tcptracer
Traceback (most recent call last):
  File "/usr/share/bcc/tools/./tcptracer", line 18, in <module>
    from bcc import BPF
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 27, in <module>
    from .libbcc import lib, bcc_symbol, bcc_symbol_option, bcc_stacktrace_build_id, _SYM_CB_TYPE
  File "/usr/lib/python3/dist-packages/bcc/libbcc.py", line 20, in <module>
    lib.bpf_module_create_b.restype = ct.c_void_p
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_module_create_b

===
Installation step
1. https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary
2. https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source

I followed your step but still have same issue.
