### ISSUE TITLE
tunnel_monitor examples lacks chord-transitions.git

### ISSUE THREAD

**Issue by LincZero** [iovisor/bcc#4685]
/bcc/examples/networking/tunnel_monitor/setup.sh

```
...
git clone https://github.com/iovisor/chord-transitions.git
...
```

But the warehouse does not exist.

And I try to use `https://github.com/sghall/chord-transitions.git` to stand it, but it still goes wrong:

```
bower                           ENOENT No bower.json present
```

**Comment by LincZero** [comment]
if ignore setup.sh error and run `main.py`, it wrong:
```
Traceback (most recent call last):
  File "./main.py", line 80, in <module>
    sim.start()
  File "./main.py", line 36, in start
    with self.ipdb.create(ifname="br100", kind="bridge") as br100:
  File "/usr/local/lib/python3.8/dist-packages/pyroute2/ipdb/main.py", line 1202, in create
    return self.interfaces.add(kind, ifname, reuse, **kwarg)
  File "/usr/local/lib/python3.8/dist-packages/pyroute2/ipdb/interfaces.py", line 1230, in add
    raise CreateException("interface %s exists" % ifname)
pyroute2.ipdb.exceptions.CreateException: interface br100 exists
```
