### ISSUE TITLE
Failed to load BPF program %s: %s" % Exception: Failed to load BPF program b'collector': Argument list too long

### ISSUE THREAD

**Issue by LaironSk** [iovisor/bcc#4687]
I'm using a application that is using bcc, the BPFCollector. I'm trying to run a InfluxDB server and I keep receiving this error coming from bcc package:

Traceback (most recent call last):
  File "InDBClient.py", line 49, in <module>
    collector = InDBCollector.InDBCollector(int_dst_port=args.int_port,
  File "InDBCollector.pyx", line 61, in InDBCollector.InDBCollector.__init__
    self.fn_collector = self.bpf_collector.load_func("collector", BPF.XDP)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 522, in load_func
    raise Exception("Failed to load BPF program %s: %s" %
Exception: Failed to load BPF program b'collector': Argument list too long

How do I fix it?

**Comment by yonghong-song** [comment]
There are many cases error code -E2BIG could be returned to kernel. This error typically indicates something is off the limit. If you can have a self-reproducible test case, somebody in the community might be able to help you.

**Comment by LaironSk** [comment]
I followed this README https://gitlab.com/tunv_ebpf/BPFCollector and ran

``sudo python3 InDBClient.py veth_1``
