### ISSUE TITLE
BPF module compile fail

### ISSUE THREAD

**Issue by danburkert** [iovisor/bcc#475]
Hi, I'm trying to get started with bcc on a Fedora 23 system using the Fedora binary install instructions from INSTALL.md.  I've checked that the kernel is new enough (`4.4.6-300.fc23.x86_64`), and has all of the required configuration flags.  After installing the nightly bcc package (`Release: 107.git.31571b4`), I'm unable to run any of the examples or tools.  The error is:

```bash
$ sudo /usr/share/bcc/examples/hello_world.py
chdir(/lib/modules/4.4.6-300.fc23.x86_64/build): No such file or directory
Traceback (most recent call last):
  File "/usr/share/bcc/examples/hello_world.py", line 11, in <module>
    BPF(text='void kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); }').trace_print()
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 165, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module
```

Is there any way to get additional info on why the compilation failed?

**Comment by danburkert** [comment]
Turns out I was missing the `kernel-devel` package.
