### ISSUE TITLE
mysqld_qslower-bpfcc does not work on Ubuntu 20.04.1

### ISSUE THREAD

**Issue by jacmath** [iovisor/bcc#4761]
mysqld_qslower-bpfcc script fails to run on Ubuntu 20.04.1 with the following error

`Traceback (most recent call last):
  File "/usr/sbin/mysqld_qslower-bpfcc", line 97, in <module>
    u.enable_probe(probe="query__start", fn_name="do_start")
  File "/usr/lib/python3/dist-packages/bcc/usdt.py", line 151, in enable_probe
    raise USDTException(
bcc.usdt.USDTException: failed to enable probe 'query__start'; a possible cause can be that the probe requires a pid to enable
`

the USDT probes are available in the mariadb 10.6.12 version I am using.

`./tplist-bpfcc -p 3126532 | grep query
b'/proc/3126532/root/usr/sbin/mariadbd' b'mysql':b'query__exec__start'
b'/proc/3126532/root/usr/sbin/mariadbd' b'mysql':b'query__exec__done'
b'/proc/3126532/root/usr/sbin/mariadbd' b'mysql':b'query__cache__miss'
b'/proc/3126532/root/usr/sbin/mariadbd' b'mysql':b'query__cache__hit'
b'/proc/3126532/root/usr/sbin/mariadbd' b'mysql':b'query__start'
b'/proc/3126532/root/usr/sbin/mariadbd' b'mysql':b'query__done'
b'/proc/3126532/root/usr/sbin/mariadbd' b'mysql':b'query__parse__start'
b'/proc/3126532/root/usr/sbin/mariadbd' b'mysql':b'query__parse__done'
`

**Comment by jacmath** [comment]
To add more context, mariadb is running in a container within the Ubuntu host. It used to work in previous version of Ubuntu. So something seems to have changed in epbf interaction with containerized applications
