### ISSUE TITLE
could not open bpf map: events, error: Operation not permitted

### ISSUE THREAD

**Issue by 123130** [iovisor/bcc#4804]
I ran a command like "sudo ./sockdump.py /tmp/vsomeip* --format pcap --output someip", but there is an error like:
`could not open bpf map: events, error: Operation not permitted
Traceback (most recent call last):
  File "/opt/sockdump/./sockdump.py", line 420, in <module>
    main(args)
  File "/opt/sockdump/./sockdump.py", line 355, in main
    b = BPF(text=text)
  File "/usr/lib/python3/dist-packages/bcc-0.28.0+22fc152b-py3.10.egg/bcc/__init__.py", line 479, in __init__
Exception: Failed to compile BPF module <text>`
<img width="879" alt="image" src="https://github.com/iovisor/bcc/assets/58681779/be3f64fa-f378-48e0-95ec-680ce6d74d1b">

**Comment by chenhengqi** [comment]
Please run with `strace` and paste the output here.

**Comment by 123130** [comment]
@chenhengqi The output is too long:
execve("/usr/bin/python3", ["python3", "hello_world.py"], 0x7fff4eee5c28 /* 13 vars */) = 0
brk(NULL)                               = 0x5632d4cc3000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffd9c4e1c30) = -1 EINVAL (Invalid argument)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faa46a5d000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=15215, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 15215, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7faa46a59000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=940560, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 942344, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7faa46972000
mmap(0x7faa46980000, 507904, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe000) = 0x7faa46980000
mmap(0x7faa469fc000, 372736, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x8a000) = 0x7faa469fc000
mmap(0x7faa46a57000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe4000) = 0x7faa46a57000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libexpat.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=194872, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 196792, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7faa46941000
mprotect(0x7faa46945000, 172032, PROT_NONE) = 0
mmap(0x7faa46945000, 126976, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7faa46945000
mmap(0x7faa46964000, 40960, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x23000) = 0x7faa46964000
mmap(0x7faa4696f000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2d000) = 0x7faa4696f000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=108936, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 110776, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7faa46925000
mprotect(0x7faa46927000, 98304, PROT_NONE) = 0
mmap(0x7faa46927000, 69632, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7faa46927000
mmap(0x7faa46938000, 24576, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x13000) = 0x7faa46938000
mmap(0x7faa4693f000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19000) = 0x7faa4693f000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
……

**Comment by chenhengqi** [comment]
The logs you posted is irrelevant.
