### ISSUE TITLE
failed to compile BPF module

### ISSUE THREAD

**Issue by TahirAhmed916** [iovisor/bcc#484]
I am trying to run bashreadline.py but i got following error
test@ubuntu:/usr/share/bcc/tools$ sudo python bashreadline.py 
/virtual/main.c:9:1: error: unsupported map type: maps/perf_output
BPF_PERF_OUTPUT(events);
^
/virtual/include/bcc/helpers.h:64:4: note: expanded from macro 'BPF_PERF_OUTPUT'
}; \
   ^
/virtual/main.c:19:5: error: expected initialized handle for bpf_table
    events.perf_submit(ctx,&data,sizeof(data));
    ^
2 errors generated.
Traceback (most recent call last):
  File "bashreadline.py", line 51, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/**init**.py", line 126, in **init**
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 

I am able to run some of tools. But in most of the cases i am facing same kind of error

**Comment by drzaeus77** [comment]
Usually this error is due to running an older kernel which doesn't support the perf events map type. Can you share which kernel you are running, and perhaps try upgrading to the latest stable kernel from http://kernel.ubuntu.com/~kernel-ppa/mainline/, since your shell says you are running Ubuntu?

**Comment by TahirAhmed916** [comment]
yes i am using 4.2.0-27-generic.

**Comment by drzaeus77** [comment]
For this particular tool, <4.4 kernel won't work. Ubuntu 16.04 (Xenial) should come with that by default, once it releases.

**Comment by goldshtn** [comment]
I suggest this issue be closed because we seem to have found the root cause.

**Comment by samof76** [comment]
I guess not... I have installed the bcc-tools with 4.4.19-29.55.amzn1.x86_64 linux kernel. And I still get this error.

**Comment by chyld** [comment]
I'm using Ubuntu 16.04 using
`Linux f44c63691935 4.4.20-moby #1 SMP Thu Sep 15 12:10:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by oviliz** [comment]
Same "Failed to compile BPF module" problem on a Scaleway VPS with their Xenial image.

**Comment by pchaigno** [comment]
@chyld See the [QUICKSTART.md guide](https://github.com/iovisor/bcc/blob/master/QUICKSTART.md) for how to run bcc in a Docker container.

**Comment by eljefedelrodeodeljefe** [comment]
@pchaigno that doesn't necessary. Maybe on a local machine, but e.g. in Kubernetes this will still fail. 

I think without really big efforts toward this, adoption is hard, since this will like be a blocker for any container system.

**Comment by drzaeus77** [comment]
@eljefedelrodeodeljefe Do you have expectations of root permissions in your kube cluster? Most of the tools developed so far have an expectation of privilege, in which case I would push for an admin container containing the debug tools for the rest of the node. For instance, I would want a container which has bcc, perf, strace, and so on, at least some of which would need to include non-common dependencies (e.g. kernel headers, specific perf build). If that container exists, there is no reason why it shouldn't be able to monitor the rest of the node.

**Comment by eljefedelrodeodeljefe** [comment]
@drzaeus77 in k8s afaik all containers are privileged, at least in the younger version. I am gonna settle on exactly what you describe. k8s calls it daemonsets, that runs that one privileged container on the N number of nodes. It's easier to make it run and maintain it definitely. Initially I would have wanted to run bcc from within the application to mitigate centralised metrics and host resolution.

Thanks.

**Comment by Akagi201** [comment]
On ubuntu, `sudo apt-get install -y linux-headers-<your kernel version>` fix it.

**Comment by cmurf** [comment]
I'm hitting this on Fedora 26, with a 4.11.3 kernel.

[root@f26h tools]# ./btrfsslower 
chdir(/lib/modules/4.11.3-300.fc26.x86_64/build): No such file or directory
Traceback (most recent call last):
  File "./btrfsslower", line 322, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 284, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 

[root@f26h tools]# ls -l /lib/modules/4.11.3-300.fc26.x86_64/build
lrwxrwxrwx. 1 root root 39 May 25 13:01 /lib/modules/4.11.3-300.fc26.x86_64/build -> /usr/src/kernels/4.11.3-300.fc26.x86_64

That path is empty. Is kernel source really supposed to be installed?

**Comment by axot** [comment]
I'm trying to run bcc in GKE which using cos. Here is how I compiled kernel headers for cos.

```
COS_VERSION=10452.109.0
gsutil cp gs://cos-tools/$COS_VERSION/kernel-src.tar.gz .

cat << EOF >> chromeos/config/base.config
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
# [optional, for tc filters]
CONFIG_NET_CLS_BPF=m
# [optional, for tc actions]
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_HAVE_BPF_JIT=y
# [optional, for kprobes]
CONFIG_BPF_EVENTS=y
EOF

make oldconfig
make-kpkg kernel_headers
```

And then install bcc like this,
```
dpkg -i linux-headers-4.14.22_4.14.22-10.00.Custom_amd64.deb
mkdir -p /lib/modules/4.14.22+/
ln -s /usr/src/linux-headers-4.14.22 /lib/modules/4.14.22+/build

#apt-key adv --keyserver-options http-proxy=http://${PROXY}/ --keyserver keyserver.ubuntu.com --recv-keys D4284CDD
curl -sS "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xD4284CDD" | sed -n "/^-----BEGIN/,/^-----END/p" > /tmp/key.pgp
apt-key add /tmp/key.pgp
echo "deb https://repo.iovisor.org/apt/xenial xenial main" | tee /etc/apt/sources.list.d/iovisor.list
apt-get update
apt-get install -y bcc-tools libbcc-examples
```

I got same `is maps/hash map type enabled in your kernel?` error. And advice?
```
# /usr/share/bcc/tools/biolatency
/virtual/main.c:9:1: error: could not open bpf map: Operation not permitted
is maps/hash map type enabled in your kernel?
BPF_HASH(start, struct request *);
^
/virtual/include/bcc/helpers.h:132:48: note: expanded from macro 'BPF_HASH'
  BPF_HASHX(__VA_ARGS__, BPF_HASH4, BPF_HASH3, BPF_HASH2, BPF_HASH1)(__VA_ARGS__)
                                               ^
/virtual/main.c:10:1: error: could not open bpf map: Operation not permitted
is maps/histogram map type enabled in your kernel?
BPF_HISTOGRAM(dist);
^
/virtual/include/bcc/helpers.h:177:48: note: expanded from macro 'BPF_HISTOGRAM'
  BPF_HISTX(__VA_ARGS__, BPF_HIST3, BPF_HIST2, BPF_HIST1)(__VA_ARGS__)
                                               ^
/virtual/main.c:16:5: error: bpf_table start failed to open
    start.update(&req, &ts);
    ^
/virtual/main.c:26:11: error: bpf_table start failed to open
    tsp = start.lookup(&req);
          ^
4 errors generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/biolatency", line 114, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 318, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text
```

**Comment by dtakis** [comment]
Same problem with new kernels like 5.3
Is there any official guideline where we could install the library and have it working?

**Comment by matinats** [comment]
Same issue in centOS with:
# uname -r
5.0.8-1.el7.elrepo.x86_64


Logs:
# /usr/share/bcc/tools/capable -U
modprobe: FATAL: Module kheaders not found.
chdir(/lib/modules/5.0.8-1.el7.elrepo.x86_64/build): No such file or directory
Traceback (most recent call last):
  File "/usr/share/bcc/tools/capable", line 178, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 325, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text

**Comment by yonghong-song** [comment]
The bcc tries to find `/lib/modules/$(uname -r)/` directory for kernel-devel header files. You might need additional steps, esp. for upgraded kernel.

**Comment by TyKeeling** [comment]
@dtakis I was having the same problem with a 5.4.0-42-generic bionic. 

[Building from source](https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source) fixed for me. Note that the tools are installed to `/usr/share/bcc/tools`. #2119 might also be helpful.

**Comment by rewanthtammana** [comment]
I'm facing same issue with kernel, `5.4.0-1051-aws`

**Comment by rewanthtammana** [comment]
@TyKeeling Working like a charm. Thanks for the help.

**Comment by gewesp** [comment]
Hi, I'm getting a same/similar error with kernel 4.15.0; Ubuntu 18.04 with standard packages .

 Symptoms:

```
ubuntu:~$ sudo execsnoop-bpfcc 
chdir(/lib/modules/4.15.0-50-generic/build): No such file or directory
Traceback (most recent call last):
  File "/usr/sbin/execsnoop-bpfcc", line 131, in <module>
    b = BPF(text=bpf_text.replace("MAXARG", args.max_args))
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 301, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 
ubuntu:~$ uname -a
Linux hostname 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
ubuntu:~$ cat /etc/issue
Ubuntu 18.04.5 LTS \n \l
```

**Comment by harelix** [comment]
@TyKeeling - building from source is the way to go, thanks.

**Comment by bluven** [comment]
I also encountered this problem:
```
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:41:9: warning: '__HAVE_BUILTIN_BSWAP32__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP32__
        ^
<command line>:4:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP32__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:42:9: warning: '__HAVE_BUILTIN_BSWAP64__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP64__
        ^
<command line>:5:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP64__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:43:9: warning: '__HAVE_BUILTIN_BSWAP16__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP16__
        ^
<command line>:3:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP16__ 1
        ^
In file included from /virtual/main.c:4:
In file included from include/linux/tcp.h:19:
In file included from include/net/sock.h:46:
In file included from include/linux/netdevice.h:37:
In file included from include/net/net_namespace.h:35:
In file included from include/net/netns/bpf.h:9:
include/linux/bpf-netns.h:21:7: error: use of undeclared identifier 'BPF_SK_LOOKUP'
        case BPF_SK_LOOKUP:
             ^
In file included from /virtual/main.c:4:
In file included from include/linux/tcp.h:19:
In file included from include/net/sock.h:46:
In file included from include/linux/netdevice.h:41:
In file included from include/net/netprio_cgroup.h:11:
In file included from include/linux/cgroup.h:28:
In file included from include/linux/cgroup-defs.h:22:
In file included from include/linux/bpf-cgroup.h:5:
include/linux/bpf.h:211:35: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_timer'
                memset(dst + map->timer_off, 0, sizeof(struct bpf_timer));
                                                ^     ~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:211:49: note: forward declaration of 'struct bpf_timer'
                memset(dst + map->timer_off, 0, sizeof(struct bpf_timer));
                                                              ^
include/linux/bpf.h:225:10: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_timer'
                t_sz = sizeof(struct bpf_timer);
                       ^     ~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:225:24: note: forward declaration of 'struct bpf_timer'
                t_sz = sizeof(struct bpf_timer);
                                     ^
include/linux/bpf.h:1000:21: error: field has incomplete type 'enum bpf_link_type'
        enum bpf_link_type type;
                           ^
include/linux/bpf.h:1000:7: note: forward declaration of 'enum bpf_link_type'
        enum bpf_link_type type;
             ^
include/linux/bpf.h:1014:17: warning: declaration of 'struct bpf_link_info' will not be visible outside of this function [-Wvisibility]
                              struct bpf_link_info *info);
                                     ^
include/linux/bpf.h:1527:12: warning: declaration of 'union bpf_iter_link_info' will not be visible outside of this function [-Wvisibility]
                                        union bpf_iter_link_info *linfo,
                                              ^
include/linux/bpf.h:1533:14: warning: declaration of 'struct bpf_link_info' will not be visible outside of this function [-Wvisibility]
                                         struct bpf_link_info *info);
                                                ^
include/linux/bpf.h:1582:12: warning: declaration of 'struct bpf_link_info' will not be visible outside of this function [-Wvisibility]
                                struct bpf_link_info *info);
                                       ^
In file included from /virtual/main.c:4:
In file included from include/linux/tcp.h:19:
In file included from include/net/sock.h:46:
In file included from include/linux/netdevice.h:41:
In file included from include/net/netprio_cgroup.h:11:
In file included from include/linux/cgroup.h:28:
In file included from include/linux/cgroup-defs.h:22:
include/linux/bpf-cgroup.h:79:2: error: use of undeclared identifier 'BPF_CGROUP_INET4_GETPEERNAME'; did you mean 'CGROUP_INET4_GETPEERNAME'?
        CGROUP_ATYPE(CGROUP_INET4_GETPEERNAME);
        ^
include/linux/bpf-cgroup.h:55:7: note: expanded from macro 'CGROUP_ATYPE'
        case BPF_##type: return type
             ^
<scratch space>:100:1: note: expanded from here
BPF_CGROUP_INET4_GETPEERNAME
^
include/linux/bpf-cgroup.h:46:2: note: 'CGROUP_INET4_GETPEERNAME' declared here
        CGROUP_INET4_GETPEERNAME,
        ^
include/linux/bpf-cgroup.h:80:2: error: use of undeclared identifier 'BPF_CGROUP_INET6_GETPEERNAME'; did you mean 'CGROUP_INET6_GETPEERNAME'?
        CGROUP_ATYPE(CGROUP_INET6_GETPEERNAME);
        ^
include/linux/bpf-cgroup.h:55:7: note: expanded from macro 'CGROUP_ATYPE'
        case BPF_##type: return type
             ^
<scratch space>:101:1: note: expanded from here
BPF_CGROUP_INET6_GETPEERNAME
^
include/linux/bpf-cgroup.h:47:2: note: 'CGROUP_INET6_GETPEERNAME' declared here
        CGROUP_INET6_GETPEERNAME,
        ^
include/linux/bpf-cgroup.h:81:2: error: use of undeclared identifier 'BPF_CGROUP_INET4_GETSOCKNAME'; did you mean 'CGROUP_INET4_GETSOCKNAME'?
        CGROUP_ATYPE(CGROUP_INET4_GETSOCKNAME);
        ^
include/linux/bpf-cgroup.h:55:7: note: expanded from macro 'CGROUP_ATYPE'
        case BPF_##type: return type
             ^
<scratch space>:102:1: note: expanded from here
BPF_CGROUP_INET4_GETSOCKNAME
^
include/linux/bpf-cgroup.h:48:2: note: 'CGROUP_INET4_GETSOCKNAME' declared here
        CGROUP_INET4_GETSOCKNAME,
        ^
include/linux/bpf-cgroup.h:82:2: error: use of undeclared identifier 'BPF_CGROUP_INET6_GETSOCKNAME'; did you mean 'CGROUP_INET6_GETSOCKNAME'?
        CGROUP_ATYPE(CGROUP_INET6_GETSOCKNAME);
        ^
include/linux/bpf-cgroup.h:55:7: note: expanded from macro 'CGROUP_ATYPE'
        case BPF_##type: return type
             ^
<scratch space>:103:1: note: expanded from here
BPF_CGROUP_INET6_GETSOCKNAME
^
include/linux/bpf-cgroup.h:49:2: note: 'CGROUP_INET6_GETSOCKNAME' declared here
        CGROUP_INET6_GETSOCKNAME,
        ^
include/linux/bpf-cgroup.h:83:2: error: use of undeclared identifier 'BPF_CGROUP_INET_SOCK_RELEASE'
        CGROUP_ATYPE(CGROUP_INET_SOCK_RELEASE);
        ^
include/linux/bpf-cgroup.h:55:7: note: expanded from macro 'CGROUP_ATYPE'
        case BPF_##type: return type
             ^
<scratch space>:104:1: note: expanded from here
BPF_CGROUP_INET_SOCK_RELEASE
^
In file included from /virtual/main.c:4:
In file included from include/linux/tcp.h:19:
In file included from include/net/sock.h:46:
In file included from include/linux/netdevice.h:41:
In file included from include/net/netprio_cgroup.h:11:
In file included from include/linux/cgroup.h:28:
In file included from include/linux/cgroup-defs.h:22:
include/linux/bpf-cgroup.h:79:2: error: duplicate case value: 'BPF_CGROUP_SYSCTL' and 'CGROUP_INET4_GETPEERNAME' both equal '18'
        CGROUP_ATYPE(CGROUP_INET4_GETPEERNAME);
        ^
include/linux/bpf-cgroup.h:55:7: note: expanded from macro 'CGROUP_ATYPE'
        case BPF_##type: return type
             ^
<scratch space>:100:1: note: expanded from here
BPF_CGROUP_INET4_GETPEERNAME
^
include/linux/bpf-cgroup.h:74:2: note: previous case defined here
        CGROUP_ATYPE(CGROUP_SYSCTL);
        ^
include/linux/bpf-cgroup.h:55:7: note: expanded from macro 'CGROUP_ATYPE'
        case BPF_##type: return type
             ^
<scratch space>:95:1: note: expanded from here
BPF_CGROUP_SYSCTL
^
In file included from /virtual/main.c:4:
In file included from include/linux/tcp.h:19:
In file included from include/net/sock.h:46:
In file included from include/linux/netdevice.h:41:
In file included from include/net/netprio_cgroup.h:11:
In file included from include/linux/cgroup.h:28:
In file included from include/linux/cgroup-defs.h:22:
include/linux/bpf-cgroup.h:80:2: error: duplicate case value: 'BPF_CGROUP_UDP4_RECVMSG' and 'CGROUP_INET6_GETPEERNAME' both equal '19'
        CGROUP_ATYPE(CGROUP_INET6_GETPEERNAME);
        ^
include/linux/bpf-cgroup.h:55:7: note: expanded from macro 'CGROUP_ATYPE'
        case BPF_##type: return type
             ^
<scratch space>:101:1: note: expanded from here
BPF_CGROUP_INET6_GETPEERNAME
^
include/linux/bpf-cgroup.h:75:2: note: previous case defined here
        CGROUP_ATYPE(CGROUP_UDP4_RECVMSG);
        ^
include/linux/bpf-cgroup.h:55:7: note: expanded from macro 'CGROUP_ATYPE'
        case BPF_##type: return type
             ^
<scratch space>:96:1: note: expanded from here
BPF_CGROUP_UDP4_RECVMSG
^
In file included from /virtual/main.c:4:
In file included from include/linux/tcp.h:19:
In file included from include/net/sock.h:46:
In file included from include/linux/netdevice.h:41:
In file included from include/net/netprio_cgroup.h:11:
In file included from include/linux/cgroup.h:28:
In file included from include/linux/cgroup-defs.h:22:
include/linux/bpf-cgroup.h:81:2: error: duplicate case value: 'BPF_CGROUP_UDP6_RECVMSG' and 'CGROUP_INET4_GETSOCKNAME' both equal '20'
        CGROUP_ATYPE(CGROUP_INET4_GETSOCKNAME);
        ^
include/linux/bpf-cgroup.h:55:7: note: expanded from macro 'CGROUP_ATYPE'
        case BPF_##type: return type
             ^
<scratch space>:102:1: note: expanded from here
BPF_CGROUP_INET4_GETSOCKNAME
^
include/linux/bpf-cgroup.h:76:2: note: previous case defined here
        CGROUP_ATYPE(CGROUP_UDP6_RECVMSG);
        ^
include/linux/bpf-cgroup.h:55:7: note: expanded from macro 'CGROUP_ATYPE'
        case BPF_##type: return type
             ^
<scratch space>:97:1: note: expanded from here
BPF_CGROUP_UDP6_RECVMSG
^
In file included from /virtual/main.c:4:
In file included from include/linux/tcp.h:19:
In file included from include/net/sock.h:46:
In file included from include/linux/netdevice.h:41:
In file included from include/net/netprio_cgroup.h:11:
In file included from include/linux/cgroup.h:28:
In file included from include/linux/cgroup-defs.h:22:
include/linux/bpf-cgroup.h:82:2: error: duplicate case value: 'BPF_CGROUP_GETSOCKOPT' and 'CGROUP_INET6_GETSOCKNAME' both equal '21'
        CGROUP_ATYPE(CGROUP_INET6_GETSOCKNAME);
        ^
include/linux/bpf-cgroup.h:55:7: note: expanded from macro 'CGROUP_ATYPE'
        case BPF_##type: return type
             ^
<scratch space>:103:1: note: expanded from here
BPF_CGROUP_INET6_GETSOCKNAME
^
include/linux/bpf-cgroup.h:77:2: note: previous case defined here
        CGROUP_ATYPE(CGROUP_GETSOCKOPT);
        ^
include/linux/bpf-cgroup.h:55:7: note: expanded from macro 'CGROUP_ATYPE'
        case BPF_##type: return type
             ^
<scratch space>:98:1: note: expanded from here
BPF_CGROUP_GETSOCKOPT
^
In file included from /virtual/main.c:4:
In file included from include/linux/tcp.h:19:
In file included from include/net/sock.h:59:
include/linux/filter.h:1518:44: error: use of undeclared identifier 'BPF_F_BROADCAST'; did you mean 'IFF_BROADCAST'?
        if (unlikely(!ri->tgt_value) && !(flags & BPF_F_BROADCAST)) {
                                                  ^~~~~~~~~~~~~~~
                                                  IFF_BROADCAST
./include/uapi/linux/if.h:86:2: note: 'IFF_BROADCAST' declared here
        IFF_BROADCAST                   = 1<<1,  /* volatile */
        ^
In file included from /virtual/main.c:4:
In file included from include/linux/tcp.h:19:
In file included from include/net/sock.h:59:
include/linux/filter.h:1533:14: error: use of undeclared identifier 'BPF_F_BROADCAST'; did you mean 'IFF_BROADCAST'?
        if (flags & BPF_F_BROADCAST) {
                    ^~~~~~~~~~~~~~~
                    IFF_BROADCAST
./include/uapi/linux/if.h:86:2: note: 'IFF_BROADCAST' declared here
        IFF_BROADCAST                   = 1<<1,  /* volatile */
        ^
7 warnings and 15 errors generated.
Traceback (most recent call last):
  File "/usr/sbin/tcplife-bpfcc", line 456, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 347, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

My system is ubuntu 20.04
```
 uname -a
Linux bluven 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by federic000** [comment]
@TyKeeling compiling from the source also worked for me, thx
