### ISSUE TITLE
build fails with python 3.12.1

### ISSUE THREAD

**Issue by fefe17** [iovisor/bcc#4906]
$ make
Building sdist for python3
Traceback (most recent call last):
  File "/src/cvs/ebpf/bcc/build/src/python/bcc-python3/setup.py", line 11, in <module>
    setup(name='bcc',
  File "/usr/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 314, in __init__
    self.metadata.version = self._normalize_version(self.metadata.version)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 350, in _normalize_version
    normalized = str(Version(version))
                     ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_vendor/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: '0.29.1+refs/hea'
make[2]: *** [src/python/CMakeFiles/bcc_py_python3.dir/build.make:84: src/python/bcc-python3/dist/bcc-0.29.1+refs/hea.tar.gz] Error 1
make[1]: *** [CMakeFiles/Makefile2:1047: src/python/CMakeFiles/bcc_py_python3.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by fefe17** [comment]
the problem seems to be src/python/bcc-python3/setup.py:

 11 setup(name='bcc',
 12       version='0.29.1+refs/hea',

this is in my build dir, which means it was generated by the build process, which is apparently broken somewhere.
Removing the +refs/hea part makes it build.

**Comment by yonghong-song** [comment]
Yes, you may need to completely remove contends of build directory and do a rebuild.

**Comment by fefe17** [comment]
I removed the build dir, did a git pull, and got the same error.
If you fixed something, it did not work.

**Comment by yonghong-song** [comment]
I don't know the reason. My system has python 3.9 and cannot reproduce your failure. Hopefully you can help debug since you have the environment.

**Comment by AlainKnaff** [comment]
Got a similar issue after compiling from the tar file downloaded from assets, and ended up with a bad version string in ./build/src/python/bcc-python3/setup.py :
```
      version='EAD-HASH-NOTFOUND+GITDIR-N',
```

Fixed it by starting over and cloning directly from github instead. Apparently the build process tried to figure out some stuff by querying git, which doesn't work if there's no .git directory. I wonder why these tar assets are prodived at all if they don't work.

**Comment by AlainKnaff** [comment]
O yes, I needed `setuptools` too, but that was easy to install using `pip install setuptools`
