### ISSUE TITLE
BCC tool execute failed on Android by debianfs

### ISSUE THREAD

**Issue by yklin-vv** [iovisor/bcc#4934]
While running execsnoop or hello_word example on Android by defbianfs, an error occured.

I can't find /tmp//kheaders-6.1.25-android14-11-maybe-dirty.
Where can I find it?

root@localhost:/# bcc/bcc/examples/hello_world.py
chdir(/tmp//kheaders-6.1.25-android14-11-maybe-dirty): No such file or directory
Traceback (most recent call last):
  File "//bcc/bcc/examples/hello_world.py", line 12, in <module>
    BPF(text='int kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/bcc-0.29.1+008ea09e-py3.11.egg/bcc/__init__.py", line 479, in __init__
Exception: Failed to compile BPF module <text>

**Comment by yklin-vv** [comment]
The issue has been solved eventually.

**Comment by yklin-vv** [comment]
On Android & eadb, we should compile kernel kheaders and rename it into "kheaders-6.1.25-android14-11-maybe-dirty".
Then push it.
But on ubuntu, the kheaders can be easily installed by "apt install".
