### ISSUE TITLE
Failed to attach BPF program b'oncpu' to kprobe b'finish_task_switch' offcputime-bpfcc

### ISSUE THREAD

**Issue by p0mvn** [iovisor/bcc#4937]
I'm on Ubuntu 5.15.0-100-generic

built using the instructions for Ubuntu

I run:
```
/sbin/offcputime-bpfcc
```

```
3 warnings generated.
cannot attach kprobe, probe entry may not exist
Traceback (most recent call last):
  File "/sbin/offcputime-bpfcc", line 234, in <module>
    b.attach_kprobe(event="finish_task_switch", fn_name="oncpu")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 683, in attach_kprobe
    raise Exception("Failed to attach BPF program %s to kprobe %s" %
Exception: Failed to attach BPF program b'oncpu' to kprobe b'finish_task_switch'
```

**Comment by yonghong-song** [comment]
Maybe kernel function `finish_task_switch` is completely inlined? You can cat /proc/kallsyms to see whether this is the case or not.

**Comment by portnov** [comment]
Hello
I have a similar problem.
I looked into /proc/kallsyms. There are records like "finish_task_switch.isra.0.cold" and several similar. Should it be this way?
If not, what to do in order for offcputime to work? recompile kernel with disabled optimizations? :)

**Comment by yonghong-song** [comment]
Unfortunately, finish_task_switch is a static function so indeed it could be easily inlined. In the above, it is lined with gcc. in order for offcputime to work, yes, you need to add 'noline' attribute to offcputime function in the kernel.

**Comment by charmingcow** [comment]
@yonghong-song   
Does the below meaning to rebuild kernel image ?
 you need to add 'noline' attribute to offcputime function in the kernel.

**Comment by haukot** [comment]
I got the same problem, in my case there were these functions:

```
$ sudo cat /proc/kallsyms | grep finish_task_switch 
ffffffffa7134a70 t __pfx_finish_task_switch.isra.0
ffffffffa7134a80 t finish_task_switch.isra.0
ffffffffa8031f86 t finish_task_switch.isra.0.cold
```

I've managed to get output with these changes in /usr/sbin/offcputime-bpfcc

```diff
-b.attach_kprobe(event="finish_task_switch", fn_name="oncpu")
+b.attach_kprobe(event="finish_task_switch.isra.0", fn_name="oncpu")
```

**Comment by yonghong-song** [comment]
> @yonghong-song Does the below meaning to rebuild kernel image ? you need to add 'noline' attribute to offcputime function in the kernel.

Adding 'noinline' to the function and rebuild the kernel definitely the safest option. But I do know it may not be possible. So you could use above 'finish_task_switch.isra.0' if it is available. If finish_task_switch is completely inlined in all occurrences, then the tool simply cannot be used.

**Comment by LHG41278** [comment]
thanks a lot @haukot , your solution works for me

**Comment by danielpacak** [comment]
The same problem on my end with:

``` console
$ uname -rm
6.8.0-79-generic x86_64
```

``` console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

``` console
$ sudo cat /proc/kallsyms | grep finish_task_switch
ffffffff8a756650 t __pfx_finish_task_switch.isra.0
ffffffff8a756660 t finish_task_switch.isra.0
ffffffff8b7ae610 t finish_task_switch.isra.0.cold
```

But it seems I have an old version of BCC tools installed with apt for Ubuntu:

```
sudo apt-get install bpfcc-tools linux-headers-$(uname -r)
```

``` console
$ cat $(which offcputime-bpfcc) | grep task_swi
b.attach_kprobe(event="finish_task_switch", fn_name="oncpu")
```
