### ISSUE TITLE
Running bcc tools failed for loongarch64

### ISSUE THREAD

**Issue by zhangzikang01** [iovisor/bcc#5077]
Running bcc tools failed for loongarch64

# /usr/share/bcc/tools/execsnoop 
In file included from <built-in>:4:
In file included from /virtual/include/bcc/helpers.h:54:
In file included from arch/loongarch/include/asm/page.h:9:
In file included from arch/loongarch/include/asm/addrspace.h:16:
arch/loongarch/include/asm/loongarch.h:13:10: fatal error: 'larchintrin.h' file not found
   13 | #include <larchintrin.h>
      |          ^~~~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/execsnoop", line 242, in <module>
    b = BPF(text=bpf_text)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bpfcc/__init__.py", line 479, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

# /usr/share/bcc/tools/biosnoop 
In file included from <built-in>:4:
In file included from /virtual/include/bcc/helpers.h:54:
In file included from arch/loongarch/include/asm/page.h:9:
In file included from arch/loongarch/include/asm/addrspace.h:16:
arch/loongarch/include/asm/loongarch.h:13:10: fatal error: 'larchintrin.h' file not found
   13 | #include <larchintrin.h>
      |          ^~~~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/biosnoop", line 335, in <module>
    b = BPF(text=bpf_text)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bpfcc/__init__.py", line 479, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

**Comment by zhangzikang01** [comment]
This issue appears in the 6.6.0 version loongarch64 kernel
