### ISSUE TITLE
memleak failing under ubuntu 22.04

### ISSUE THREAD

**Issue by djmack465** [iovisor/bcc#5094]
I'm trying to run memleak and I'm seeing this error.  Can anyone provide some insight on how to proceed?  TIA

could not open bpf map: combined_allocs, error: Operation not permitted
Traceback (most recent call last):
  File "/usr/share/bcc/tools/memleak", line 476, in <module>
    bpf = BPF(text=bpf_source)
  File "/usr/lib/python3/dist-packages/bcc-0.31.0+3130fe8c-py3.10.egg/bcc/__init__.py", line 505, in __init__
Exception: Failed to compile BPF module <text>

**Comment by djmack465** [comment]
My bad, I was trying this from within a container in which I can't elevate my privileges.
