### ISSUE TITLE
Exception:Failed to attach BPF program b'trace_req_done' to kprobe b'blk_account_io_done', it's not traceable (either non-existing, inlined, or marked as "notrace")

### ISSUE THREAD

**Issue by zydmtaichi** [iovisor/bcc#5124]
kernel version: 6.8.0-40-generic
system version: ubuntu 22.04
debug info:
```
cannot attach kprobe, Invalid argument
Traceback (most recent call last):
  File "/mnt/sdb/bcc/examples/tracing/bitehist.py", line 39, in <module>
    b.attach_kprobe(event="blk_account_io_done", fn_name="trace_req_done")
  File "/usr/lib/python3/dist-packages/bcc-0.31.0+0d5dcf40-py3.10.egg/bcc/__init__.py", line 881, in attach_kprobe
Exception: Failed to attach BPF program b'trace_req_done' to kprobe b'blk_account_io_done', it's not traceable (either non-existing, inlined, or marked as "notrace")

```

the kernel config is checked as below:
```
CONFIG_KPROBES=y
CONFIG_KPROBES_ON_FTRACE=y
CONFIG_HAVE_KPROBES=y
CONFIG_HAVE_KPROBES_ON_FTRACE=y
CONFIG_KPROBE_EVENTS=y
# CONFIG_KPROBE_EVENTS_ON_NOTRACE is not set
CONFIG_BPF_KPROBE_OVERRIDE=y
# CONFIG_KPROBE_EVENT_GEN_TEST is not set
# CONFIG_SAMPLE_KPROBES is not set
```

and the command `grep blk_account_io_done /proc/kallsyms` output as below:
```
ffffffff9a1c1890 t __pfx_blk_account_io_done
ffffffff9a1c18a0 t blk_account_io_done
```

**Comment by zydmtaichi** [comment]
@chenhengqi

**Comment by we3i** [comment]
@zydmtaichi 
`blk_account_io_done` has become inline function [long time ago](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/block/blk-mq.c?h=v6.13&id=06965037ce942500c1ce3aa29ca217093a9c5720) which means it is not traceable anymore.

**Comment by we3i** [comment]
@zydmtaichi 
`blk_account_io_done` has [become an inline function](https://lore.kernel.org/all/b0662a636bd4cc7b4f84c9d0a41efa46a688ef13.1633781740.git.asml.silence@gmail.com/) even before `__blk_account_io_done` was [moved](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/block/blk-mq.c?h=v6.13&id=450b7879e34517c3ebc3a35a53806fe40e60fac2) from blk-core.c to blk-mq.c. Then, `__blk_account_io_done` has been taken off and its code was merged to `blk_account_io_done` [not long ago](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/block/blk-mq.c?h=v6.13&id=06965037ce942500c1ce3aa29ca217093a9c5720), which means both functions are not traceable anymore.

**Comment by we3i** [comment]
The fix has been merged so please close this issue.

**Comment by zydmtaichi** [comment]
> The fix has been merged so please close this issue.

Hi @we3i , thanks a lot for fixing this failure.
