### ISSUE TITLE
Clang crashes when reporting BPF Table error messages

### ISSUE THREAD

**Issue by vmg** [iovisor/bcc#516]
Here's something that has been bothering me for a while: there are certain compilation errors for which Clang segfaults while trying to print a diagnostic message.

```
#0  0x00000000016a5d97 in clang::Diagnostic::FormatDiagnostic(char const*, char const*, llvm::SmallVectorImpl<char>&) const ()
#1  0x0000000000c7ccaf in clang::TextDiagnosticPrinter::HandleDiagnostic(clang::DiagnosticsEngine::Level, clang::Diagnostic const&) ()
#2  0x00000000016a8550 in clang::DiagnosticIDs::EmitDiag(clang::DiagnosticsEngine&, clang::DiagnosticIDs::Level) const ()
#3  0x00000000016a87b6 in clang::DiagnosticIDs::ProcessDiag(clang::DiagnosticsEngine&) const ()
#4  0x00000000016a1f14 in clang::DiagnosticsEngine::EmitCurrentDiagnostic(bool) ()
#5  0x0000000000a96e52 in clang::DiagnosticBuilder::Emit (
    this=0x7fffffffc420)
    at /usr/lib/llvm-3.7/include/clang/Basic/Diagnostic.h:928
#6  0x0000000000a96e80 in clang::DiagnosticBuilder::~DiagnosticBuilder (
    this=0x7fffffffc420, __in_chrg=<optimized out>)
    at /usr/lib/llvm-3.7/include/clang/Basic/Diagnostic.h:954
#7  0x0000000000aa67ee in ebpf::BTypeVisitor::VisitVarDecl (
    this=0x2ce7200, Decl=0x3a30ca0)
    at /home/vmg/src/bcc/src/cc/frontends/clang/b_frontend_action.cc:620
#8  0x0000000000b5dc24 in clang::RecursiveASTVisitor<ebpf::BTypeVisitor>::WalkUpFromVarDecl (this=0x2ce7200, D=0x3a30ca0)
    at /usr/lib/llvm-3.7/include/clang/AST/DeclNodes.inc:403
#9  0x0000000000b0b621 in clang::RecursiveASTVisitor<ebpf::BTypeVisitor>::TraverseVarDecl (this=0x2ce7200, D=0x3a30ca0)
    at /usr/lib/llvm-3.7/include/clang/AST/RecursiveASTVisitor.h:1872
#10 0x0000000000ac37c7 in clang::RecursiveASTVisitor<ebpf::BTypeVisitor>::TraverseDecl (this=0x2ce7200, D=0x3a30ca0)
    at /usr/lib/llvm-3.7/include/clang/AST/DeclNodes.inc:403
#11 0x0000000000aa6b56 in ebpf::BTypeConsumer::HandleTopLevelDecl (
    this=0x2ce71f0, Group=...)
    at /home/vmg/src/bcc/src/cc/frontends/clang/b_frontend_action.cc:648
#12 0x0000000000c690ad in clang::MultiplexConsumer::HandleTopLevelDecl(clang::DeclGroupRef) ()
#13 0x0000000000df41ce in clang::ParseAST(clang::Sema&, bool, bool) ()
#14 0x0000000000c457ce in clang::FrontendAction::Execute() ()
#15 0x0000000000c1c239 in clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) ()
#16 0x0000000000a95c26 in ebpf::ClangLoader::parse (this=0x2cba0c0, 
    mod=0x2cb9100, tables=0x2cb9148, 
    file="#include <uapi/linux/ptrace.h>\n#include <linux/sched.h>\n\nstruct key_t {\n  u32 prev_pid;\n  u32 curr_pid;\n};\n// map_type, key_type, leaf_type, table_name, num_entry\nBPF_TABLE(\"hash\", struct key_t, u64, "..., in_memory=true, cflags=0x400326e0, ncflags=3)
    at /home/vmg/src/bcc/src/cc/frontends/clang/loader.cc:193
#17 0x0000000000a16bad in ebpf::BPFModule::load_cfile (this=0x2cb90a0, 
    file="#include <uapi/linux/ptrace.h>\n#include <linux/sched.h>\n\nstruct key_t {\n  u32 prev_pid;\n  u32 curr_pid;\n};\n// map_type, key_type, leaf_type, table_name, num_entry\nBPF_TABLE(\"hash\", struct key_t, u64, "..., in_memory=true, cflags=0x400326e0, ncflags=3)
    at /home/vmg/src/bcc/src/cc/bpf_module.cc:325
#18 0x0000000000a19080 in ebpf::BPFModule::load_string (this=0x2cb90a0, 
    text="#include <uapi/linux/ptrace.h>\n#include <linux/sched.h>\n\nstruct key_t {\n  u32 prev_pid;\n  u32 curr_pid;\n};\n// map_type, key_type, leaf_type, table_name, num_entry\nBPF_TABLE(\"hash\", struct key_t, u64, "..., cflags=0x400326e0, ncflags=3)
    at /home/vmg/src/bcc/src/cc/bpf_module.cc:730
#19 0x0000000000a1376c in bpf_module_create_c_from_string (
    text=0x40031ff8 "#include <uapi/linux/ptrace.h>\n#include <linux/sched.h>\n\nstruct key_t {\n  u32 prev_pid;\n  u32 curr_pid;\n};\n// map_type, key_type, leaf_type, table_name, num_entry\nBPF_TABLE(\"hash\", struct key_t, u64, "..., flags=0, cflags=0x400326e0, ncflags=3)
    at /home/vmg/src/bcc/src/cc/bpf_common.cc:40
#20 0x0000000000a1342b in lj_vm_ffi_call ()
#21 0x00000000009f8b66 in lj_ccall_func ()
#22 0x00000000009f9240 in lj_cf_ffi_meta___call ()
#23 0x0000000000a112a6 in lj_BC_FUNCC ()
#24 0x0000000000a05820 in lua_pcall ()
#25 0x00000000009c175e in docall (L=0x40000378, narg=0, clear=1)
    at /home/vmg/src/bcc/src/lua/src/main.c:93
#26 0x00000000009c199b in pmain (L=0x40000378)
    at /home/vmg/src/bcc/src/lua/src/main.c:141
#27 0x0000000000a112a6 in lj_BC_FUNCC ()
#28 0x0000000000a0589a in lua_cpcall ()
#29 0x00000000009c1a3c in main (argc=2, argv=0x7fffffffe428)
    at /home/vmg/src/bcc/src/lua/src/main.c:160
```

They all seem related to bpf tables. For the previous backtrace, it triggers at `b_frontend_action.cc:620`

```cpp
    if (table.fd < 0) {
      error(Decl->getLocStart(), "could not open bpf map: %0\nis %s map type enabled in your kernel?") <<
          strerror(errno) << A->getName();
      return false;
    }
```

It's trivially easy to reproduce: run any probe with a BPF table **without root**. The table will fail to open, and Clang will segfault. The segfault is actually "triggered" by calling `A->getName()` when building the error message. If you change the source code to _not_ report the name, Clang will properly print the error message, and compilation will continue...

Until it reaches `b_frontend_action.cc:309`. Here Clang wants to emit a similar error message, again, and it segfaults because of `Ref->getDecl()->getName()`.

```cpp
        if (table_it == tables_.end()) {
          error(Ref->getLocEnd(), "bpf_table %s failed to open") << Ref->getDecl()->getName();
          return false;
        }
```

If you remove the two `getName()` calls from the error messages, Clang will successfully print all diagnostics and exit cleanly.

Interestingly, I can call `getName()` from the debugger without any issues. What gives? :)

I am not sure of how to debug this. It feels like a bug in libclang itself, but since we're linking it statically, I can't get debug symbols to figure out what's the deal here.

cc @drzaeus77 @4ast

**Comment by vmg** [comment]
Hah, figured it out on my own just by writing down the issue body. PR incoming. :)
