### ISSUE TITLE
Some example does not operate any more

### ISSUE THREAD

**Issue by TaekhoNam** [iovisor/bcc#553]
Some documents are provided for VXLAN example in [IO Visor Github pages](https://github.com/iovisor/bcc/tree/master/examples/networking/tunnel_monitor).
(example files  about VXLAN is located in ``` bcc/examples/networking/tunnel_monitor/ ```)
I refer those documents and follow processes to install and set up for this example. But It doesn't operate properly.
I try to operate a example which is about VXLAN tunnel packet tracing.  But I doesn't operate properly. 

I think that because some dependencies was updated & upgraded, It can't be operated properly anymore.

- Actually, I found that because of the version of pyroute2, ``` bcc/examples/networking/tunnel_monitor/ main.py```) doesn't works. So, When I changed the version of pyroute2 to older one, then It can works properly. 

- But, this example is not still work. I think it is possible that the update of bcc package from 1.7 to 1.8 made this problem. 

Currently, I'm going to solve this problem. If I find the solution, I will share that. And somebody already know how to solve it, Please let me know.

**Comment by TaekhoNam** [comment]
Additionally, How can I get bcc 1.7?

**Comment by zaafar** [comment]
This example was recently fix, so you may need to compile bcc from source in order for this example to work.

Other than that,
you need to install following packages to successfully run setup.sh file. 
sudo apt-get -y install nodejs-legacy npm 

you need to install following packages to successfully run main.py file.
sudo apt-get -y install python-future
pip install --upgrade pyroute2

you need to install following packages to successfully run traffic.sh
sudo apt-get -y install byobu

Also, sometimes I get following error ( I don't know why )
AttributeError: 'NoneType' object has no attribute 'partial'
so if you are getting this error just remove ".commit()" from end of line 68 in simulation.py

**Comment by TaekhoNam** [comment]
At First, I used pyroute2-0.4.1 that is lastest version. But when I operated ``` main.py ``` file, I doesn't operate properly. And then I knew that the version of pyroute2 was updated from 0.3.15 to 0.4.1 and the version of bcc was also updated from 1.7 to 1.8. So I suspect that either updated pyroute2 or bcc occurs this problem.

As a result, I changed the version of pyroute2 from 0.4.1 to 0.3.15. And then ``` main.py ``` works well.

**Comment by TaekhoNam** [comment]
Command, ``` sudo apt-get install python-future ``` , is not works. How can I install the package that named python-future?

**Comment by drzaeus77** [comment]
Try `sudo pip install future`

**Comment by TaekhoNam** [comment]
I already install future using ``` sudo pip install future ``` command. And then I upgraded from pyroute2-0.3.15 to pyroute2-0.4.1. But ``` main.py ``` doesn't still works with following error messages.

```
thnam@ubuntu:~/iovisor/install/bcc/examples/networking/tunnel_monitor$ sudo ./main.py 
Traceback (most recent call last):
  File "./main.py", line 16, in <module>
    ipr = IPRoute()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/__init__.py", line 89, in __new__
    cls.register(cls.registry['class'])
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/__init__.py", line 69, in __getitem__
    [name], 0)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/iproute.py", line 109, in <module>
    from pyroute2.netlink.rtnl.tcmsg import get_htb_parameters
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/rtnl/tcmsg/__init__.py", line 10, in <module>
    from pyroute2.netlink.rtnl.tcmsg import sched_clsact
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/rtnl/tcmsg/sched_clsact.py", line 26, in <module>
    from pyroute2.netlink.rtnl import TC_H_CLSACT
ImportError: cannot import name TC_H_CLSACT
```

**Comment by TaekhoNam** [comment]
To avoid above error messages, I changed version of pyroute2 from 0.4.1 to 0.3.15 again.
``` main.py ```works well again like this,

```
Launching host 1 of 9
Launching host 2 of 9
Launching host 3 of 9
Launching host 4 of 9
Launching host 5 of 9
Launching host 6 of 9
Launching host 7 of 9
Launching host 8 of 9
Launching host 9 of 9
Starting tunnel 1 of 9
Starting tunnel 2 of 9
Starting tunnel 3 of 9
Starting tunnel 4 of 9
Starting tunnel 5 of 9
Starting tunnel 6 of 9
Starting tunnel 7 of 9
Starting tunnel 8 of 9
Starting tunnel 9 of 9
HTTPServer listening on 0.0.0.0:8080
```

**Comment by drzaeus77** [comment]
I haven't seen this one yet, I don't have a theory:
```bash
ImportError: cannot import name TC_H_CLSACT
```

But, I did see the following:
```bash
  File "./main.py", line 35, in start
    host_info.append(self._create_ns("host%d" % i, ipaddr=ipaddr))
  File "/home/bblanco/work/bcc/examples/networking/tunnel_monitor/simulation.py", line 93, in _create_ns
    disable_ipv6)
  File "/home/bblanco/work/bcc/examples/networking/tunnel_monitor/simulation.py", line 68, in _ns_add_ifc
    ns_ipdb.interfaces.lo.up().commit()
  File "/usr/lib/python3.5/site-packages/pyroute2/ipdb/interface.py", line 512, in commit
    if transaction.partial:
AttributeError: 'NoneType' object has no attribute 'partial'
```

To work around that one, I tried the following:
```patch
diff --git a/examples/networking/simulation.py b/examples/networking/simulation.py
index aa9888d..6ee8108 100644
--- a/examples/networking/simulation.py
+++ b/examples/networking/simulation.py
@@ -65,7 +65,8 @@ class Simulation(object):
                 raise
 
         if out_ifc: out_ifc.up().commit()
-        ns_ipdb.interfaces.lo.up().commit()
+        with ns_ipdb.interfaces.lo as lo:
+            lo.up()
         in_ifc = ns_ipdb.interfaces[in_ifname]
         with in_ifc as v:
             v.ifname = ns_ifc
```

This is with latest pyroute2. Please let me know if that helps at all.

@svinota Does the `AttributeError: 'NoneType' object has no attribute 'partial'` ring any bells?

**Comment by TaekhoNam** [comment]
I updated latest(0.4.1) pyroute2 using ``` sudo pip install pyroute2 --upgrade ``` again and again.
I found that It is weird. Whenever I execute ``` main.py ```, I can see messages including same errors ####and also I can see that It works more and more like this:

```
thnam@ubuntu:~/iovisor/install/bcc/examples/networking/tunnel_monitor$ sudo ./main.py 
Launching host 1 of 9
Launching host 2 of 9
Traceback (most recent call last):
  File "./main.py", line 80, in <module>
    sim.start()
  File "./main.py", line 35, in start
    host_info.append(self._create_ns("host%d" % i, ipaddr=ipaddr))
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 95, in _create_ns
    disable_ipv6)
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 43, in _ns_add_ifc
    ns_ipdb.interfaces.lo.up().commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.py", line 493, in commit
    if transaction.partial:
AttributeError: 'NoneType' object has no attribute 'partial'
thnam@ubuntu:~/iovisor/install/bcc/examples/networking/tunnel_monitor$ sudo ./main.py 
Launching host 1 of 9
Launching host 2 of 9
Launching host 3 of 9
Traceback (most recent call last):
  File "./main.py", line 80, in <module>
    sim.start()
  File "./main.py", line 35, in start
    host_info.append(self._create_ns("host%d" % i, ipaddr=ipaddr))
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 95, in _create_ns
    disable_ipv6)
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 43, in _ns_add_ifc
    ns_ipdb.interfaces.lo.up().commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.py", line 493, in commit
    if transaction.partial:
AttributeError: 'NoneType' object has no attribute 'partial'
thnam@ubuntu:~/iovisor/install/bcc/examples/networking/tunnel_monitor$ sudo ./main.py 
Launching host 1 of 9
Launching host 2 of 9
Launching host 3 of 9
Launching host 4 of 9
Traceback (most recent call last):
  File "./main.py", line 80, in <module>
    sim.start()
  File "./main.py", line 35, in start
    host_info.append(self._create_ns("host%d" % i, ipaddr=ipaddr))
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 95, in _create_ns
    disable_ipv6)
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 43, in _ns_add_ifc
    ns_ipdb.interfaces.lo.up().commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.py", line 493, in commit
    if transaction.partial:
AttributeError: 'NoneType' object has no attribute 'partial'
thnam@ubuntu:~/iovisor/install/bcc/examples/networking/tunnel_monitor$ sudo ./main.py 
Launching host 1 of 9
Launching host 2 of 9
Launching host 3 of 9
Launching host 4 of 9
Launching host 5 of 9
Traceback (most recent call last):
  File "./main.py", line 80, in <module>
    sim.start()
  File "./main.py", line 35, in start
    host_info.append(self._create_ns("host%d" % i, ipaddr=ipaddr))
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 95, in _create_ns
    disable_ipv6)
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 43, in _ns_add_ifc
    ns_ipdb.interfaces.lo.up().commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.py", line 493, in commit
    if transaction.partial:
AttributeError: 'NoneType' object has no attribute 'partial'
thnam@ubuntu:~/iovisor/install/bcc/examples/networking/tunnel_monitor$ sudo ./main.py 
Launching host 1 of 9
Launching host 2 of 9
Launching host 3 of 9
Launching host 4 of 9
Launching host 5 of 9
Launching host 6 of 9
Traceback (most recent call last):
  File "./main.py", line 80, in <module>
    sim.start()
  File "./main.py", line 35, in start
    host_info.append(self._create_ns("host%d" % i, ipaddr=ipaddr))
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 95, in _create_ns
    disable_ipv6)
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 43, in _ns_add_ifc
    ns_ipdb.interfaces.lo.up().commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.py", line 493, in commit
    if transaction.partial:
AttributeError: 'NoneType' object has no attribute 'partial'
thnam@ubuntu:~/iovisor/install/bcc/examples/networking/tunnel_monitor$ sudo ./main.py 
Launching host 1 of 9
Launching host 2 of 9
Launching host 3 of 9
Launching host 4 of 9
Launching host 5 of 9
Launching host 6 of 9
Launching host 7 of 9
Traceback (most recent call last):
  File "./main.py", line 80, in <module>
    sim.start()
  File "./main.py", line 35, in start
    host_info.append(self._create_ns("host%d" % i, ipaddr=ipaddr))
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 95, in _create_ns
    disable_ipv6)
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 43, in _ns_add_ifc
    ns_ipdb.interfaces.lo.up().commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.py", line 493, in commit
    if transaction.partial:
AttributeError: 'NoneType' object has no attribute 'partial'
thnam@ubuntu:~/iovisor/install/bcc/examples/networking/tunnel_monitor$ sudo ./main.py 
Launching host 1 of 9
Launching host 2 of 9
Launching host 3 of 9
Launching host 4 of 9
Launching host 5 of 9
Launching host 6 of 9
Launching host 7 of 9
Launching host 8 of 9
Traceback (most recent call last):
  File "./main.py", line 80, in <module>
    sim.start()
  File "./main.py", line 35, in start
    host_info.append(self._create_ns("host%d" % i, ipaddr=ipaddr))
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 95, in _create_ns
    disable_ipv6)
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 43, in _ns_add_ifc
    ns_ipdb.interfaces.lo.up().commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.py", line 493, in commit
    if transaction.partial:
AttributeError: 'NoneType' object has no attribute 'partial'
thnam@ubuntu:~/iovisor/install/bcc/examples/networking/tunnel_monitor$ sudo ./main.py 
Launching host 1 of 9
Launching host 2 of 9
Launching host 3 of 9
Launching host 4 of 9
Launching host 5 of 9
Launching host 6 of 9
Launching host 7 of 9
Launching host 8 of 9
Launching host 9 of 9
Traceback (most recent call last):
  File "./main.py", line 80, in <module>
    sim.start()
  File "./main.py", line 35, in start
    host_info.append(self._create_ns("host%d" % i, ipaddr=ipaddr))
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 95, in _create_ns
    disable_ipv6)
  File "/home/thnam/iovisor/install/bcc/examples/networking/tunnel_monitor/simulation.py", line 43, in _ns_add_ifc
    ns_ipdb.interfaces.lo.up().commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.py", line 493, in commit
    if transaction.partial:
AttributeError: 'NoneType' object has no attribute 'partial'
thnam@ubuntu:~/iovisor/install/bcc/examples/networking/tunnel_monitor$ sudo ./main.py 
Launching host 1 of 9
Launching host 2 of 9
Launching host 3 of 9
Launching host 4 of 9
Launching host 5 of 9
Launching host 6 of 9
Launching host 7 of 9
Launching host 8 of 9
Launching host 9 of 9
Starting tunnel 1 of 9
Starting tunnel 2 of 9
Starting tunnel 3 of 9
Starting tunnel 4 of 9
Starting tunnel 5 of 9
Starting tunnel 6 of 9
Starting tunnel 7 of 9
Starting tunnel 8 of 9
Starting tunnel 9 of 9
HTTPServer listening on 0.0.0.0:8080
```

**Comment by zaafar** [comment]
Just apply the diff drzaeus77 provided in 8th comment and this situation will be solved.

**Comment by TaekhoNam** [comment]
After I already applied the diff that drzaeus77 provided, I encountered this situation. I don't know why this situation occured.

**Comment by zaafar** [comment]
try removing ".commit()" from the end of line 43 of simulation.py
Please note: This is not a solution, I am just trying to bypass this bug.

**Comment by TaekhoNam** [comment]
I applied your comment. I try removing ".commit()" from the end of line 43 of simulation.py.
So, I found new warning messages like this:

```
thnam@ubuntu:~/iovisor/install/bcc/examples/networking/tunnel_monitor$ sudo python main.py 
Launching host 1 of 9
Launching host 2 of 9
WARNING:pyroute2.iproute:link_remove() is obsoleted, use link('del', ...)
Launching host 3 of 9
WARNING:pyroute2.iproute:link_remove() is obsoleted, use link('del', ...)
Launching host 4 of 9
WARNING:pyroute2.iproute:link_remove() is obsoleted, use link('del', ...)
Launching host 5 of 9
WARNING:pyroute2.iproute:link_remove() is obsoleted, use link('del', ...)
Launching host 6 of 9
WARNING:pyroute2.iproute:link_remove() is obsoleted, use link('del', ...)
Launching host 7 of 9
WARNING:pyroute2.iproute:link_remove() is obsoleted, use link('del', ...)
Launching host 8 of 9
WARNING:pyroute2.iproute:link_remove() is obsoleted, use link('del', ...)
Launching host 9 of 9
WARNING:pyroute2.iproute:link_remove() is obsoleted, use link('del', ...)
Starting tunnel 1 of 9
Starting tunnel 2 of 9
Starting tunnel 3 of 9
Starting tunnel 4 of 9
Starting tunnel 5 of 9
Starting tunnel 6 of 9
Starting tunnel 7 of 9
Starting tunnel 8 of 9
Starting tunnel 9 of 9
HTTPServer listening on 0.0.0.0:8080
```

I don't know why it was sometimes executed properly or happened bugs.
Anyway, I can avoid error messages and bypass this bug due to your comment.
Thank you zaafar, Really thanks.

**Comment by zaafar** [comment]
Tested it on pyroute2 master branch, same issue
```
Traceback (most recent call last):
  File "./main.py", line 80, in <module>
    sim.start()
  File "./main.py", line 35, in start
    host_info.append(self._create_ns("host%d" % i, ipaddr=ipaddr))
  File "/usr/share/bcc/examples/networking/tunnel_monitor/simulation.py", line 93, in _create_ns
    disable_ipv6)
  File "/usr/share/bcc/examples/networking/tunnel_monitor/simulation.py", line 68, in _ns_add_ifc
    ns_ipdb.interfaces.lo.up().commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.py", line 512, in commit
    if transaction.partial:
AttributeError: 'NoneType' object has no attribute 'partial'
```

**Comment by svinota** [comment]
Yup. Sorry for that, will be fixed latest on Monday.

**Comment by svinota** [comment]
I hope, this changeset should fix the issue.

**Comment by zaafar** [comment]
Yes thank you, it does solve the issue.
@TaekhoNam Can you check it on your side if everything is working fine and close the ticket.

**Comment by TaekhoNam** [comment]
OK, I will try it again tomorrow after reinstalling pyroute2 from master, and If I have any problem to execute this example, I will write about it and share information in here. Thank you so much, @zaafar  @svinota

**Comment by svinota** [comment]
@TaekhoNam, thanks a lot!

**Comment by TaekhoNam** [comment]
I think that It was fixed properly. After reinstalling pyroute2 from master, It doesn't occur errors any more. 
```
thnam@ubuntu:~/iovisor/bcc/examples/networking/tunnel_monitor$ sudo ./main.py
Launching host 1 of 9
Launching host 2 of 9
Launching host 3 of 9
Launching host 4 of 9
Launching host 5 of 9
Launching host 6 of 9
Launching host 7 of 9
Launching host 8 of 9
Launching host 9 of 9
Starting tunnel 1 of 9
Starting tunnel 2 of 9
Starting tunnel 3 of 9
Starting tunnel 4 of 9
Starting tunnel 5 of 9
Starting tunnel 6 of 9
Starting tunnel 7 of 9
Starting tunnel 8 of 9
Starting tunnel 9 of 9
HTTPServer listening on 0.0.0.0:8080
```

Thanks!
