### ISSUE TITLE
libbcc segfault in perf_reader_poll

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#568]
Try stacksnoop.py with a junk argument. Eg:

```
# python stacksnoop.py foo
write(/sys/kernel/debug/tracing/kprobe_events, "p:kprobes/p_foo foo") failed: No such file or directory
TIME(s)            FUNCTION
Segmentation fault

# gdb `which python`
[...]
(gdb) run stacksnoop.py foo
Starting program: /usr/bin/python stacksnoop.py foo
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: JITed object file architecture unknown is not compatible with target architecture i386:x86-64.
write(/sys/kernel/debug/tracing/kprobe_events, "p:kprobes/p_foo foo") failed: No such file or directory
TIME(s)            FUNCTION

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4363424 in perf_reader_poll () from /usr/lib/x86_64-linux-gnu/libbcc.so.0
(gdb) bt
#0  0x00007ffff4363424 in perf_reader_poll () from /usr/lib/x86_64-linux-gnu/libbcc.so.0
#1  0x00007ffff690ae40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#2  0x00007ffff690a8ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#3  0x00007ffff6b1a68c in _ctypes_callproc () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#4  0x00007ffff6b1ed82 in ?? () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#5  0x00000000004b1153 in PyObject_Call ()
#6  0x00000000004ca5ca in PyEval_EvalFrameEx ()
#7  0x00000000004c2e05 in PyEval_EvalCodeEx ()
#8  0x00000000004ca6b5 in PyEval_EvalFrameEx ()
#9  0x00000000004c2e05 in PyEval_EvalCodeEx ()
#10 0x00000000004c2ba9 in PyEval_EvalCode ()
#11 0x00000000004f20ef in ?? ()
#12 0x00000000004eca72 in PyRun_FileExFlags ()
#13 0x00000000004eb1f1 in PyRun_SimpleFileExFlags ()
#14 0x000000000049e18a in Py_Main ()
#15 0x00007ffff7811830 in __libc_start_main (main=0x49daf0 <main>, argc=3, argv=0x7fffffffdfd8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdfc8) at ../csu/libc-start.c:291
#16 0x000000000049da19 in _start ()
```

**Comment by brendangregg** [comment]
With -g added to CMAKE_C_FLAGS:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4363424 in perf_reader_poll (num_readers=9, readers=0x1cbc7e0, timeout=-1) at /mnt/src/bcc/src/cc/perf_reader.c:258
258	    pfds[i].fd = readers[i]->fd;

(gdb) bt full
#0  0x00007ffff4363424 in perf_reader_poll (num_readers=9, readers=0x1cbc7e0, timeout=-1) at /mnt/src/bcc/src/cc/perf_reader.c:258
        pfds = {{fd = 0, events = 0, revents = 0}, {fd = -10976, events = 32767, revents = 0}, {fd = -10752, events = 32767, revents = 0}, {fd = 4, events = 0, 
            revents = 0}, {fd = -10672, events = 32767, revents = 0}, {fd = -158291797, events = 32767, revents = 0}, {fd = 9, events = 0, revents = 0}, {fd = 30132192, 
            events = 0, revents = 0}, {fd = -1, events = -1, revents = -1}}
        i = 0
#1  0x00007ffff690ae40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
#2  0x00007ffff690a8ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
[...]
```
