### ISSUE TITLE
PT_REGS_RC causing "invalid size of register spill"

### ISSUE THREAD

**Issue by osandov** [iovisor/bcc#575]
When I try to run execsnoop.py, I get the following traceback:

```
┌[root@silver ~/linux/bcc master] :(
└# PYTHONPATH=src/python LD_LIBRARY_PATH=src/cc python2 ./tools/execsnoop.py
In file included from /virtual/main.c:4:
include/linux/fs.h:2653:9: warning: comparison of unsigned enum expression < 0 is always false [-Wtautological-compare]
        if (id < 0 || id >= READING_MAX_ID)
            ~~ ^ ~
1 warning generated.
bpf: Permission denied
0: (bf) r6 = r1
1: (b7) r1 = 0
2: (63) *(u32 *)(r10 -8) = r1
3: (7b) *(u64 *)(r10 -16) = r1
4: (7b) *(u64 *)(r10 -24) = r1
5: (7b) *(u64 *)(r10 -32) = r1
6: (7b) *(u64 *)(r10 -40) = r1
7: (7b) *(u64 *)(r10 -48) = r1
8: (7b) *(u64 *)(r10 -56) = r1
9: (7b) *(u64 *)(r10 -64) = r1
10: (7b) *(u64 *)(r10 -72) = r1
11: (7b) *(u64 *)(r10 -80) = r1
12: (7b) *(u64 *)(r10 -88) = r1
13: (7b) *(u64 *)(r10 -96) = r1
14: (7b) *(u64 *)(r10 -104) = r1
15: (7b) *(u64 *)(r10 -112) = r1
16: (7b) *(u64 *)(r10 -120) = r1
17: (7b) *(u64 *)(r10 -128) = r1
18: (7b) *(u64 *)(r10 -136) = r1
19: (7b) *(u64 *)(r10 -144) = r1
20: (7b) *(u64 *)(r10 -152) = r1
21: (7b) *(u64 *)(r10 -160) = r1
22: (85) call 14
23: (77) r0 >>= 32
24: (63) *(u32 *)(r10 -160) = r0
25: (bf) r1 = r10
26: (07) r1 += -156
27: (b7) r2 = 16
28: (85) call 16
29: (b7) r1 = 1
30: (63) *(u32 *)(r10 -140) = r1
31: (79) r1 = *(u64 *)(r6 +80)
32: (63) *(u32 *)(r10 -8) = r1
invalid size of register spill

Traceback (most recent call last):
  File "./tools/execsnoop.py", line 143, in <module>
    b = BPF(text=bpf_text)
  File "/root/linux/bcc/src/python/bcc/__init__.py", line 179, in __init__
    self._trace_autoload()
  File "/root/linux/bcc/src/python/bcc/__init__.py", line 562, in _trace_autoload
    fn = self.load_func(func_name, BPF.KPROBE)
  File "/root/linux/bcc/src/python/bcc/__init__.py", line 219, in load_func
    raise Exception("Failed to load BPF program %s" % func_name)
Exception: Failed to load BPF program kretprobe__sys_execve
```

I originally encountered this by trying to use PT_REGS_RC(ctx)/ctx->ax in my own bcc script and then confirmed that it was happening with the bundled tools as well.

I'm on Arch Linux with clang/LLVM version 3.8.0.

**Comment by 4ast** [comment]
that should be fixed by commit 19de99f70b87 ("bpf: fix matching of data/data_end in verifier")

**Comment by brendangregg** [comment]
hit this too, thanks Alexei! Is this making it's way via net-next into the kernel? (should I expect it in rc4 or something?).

**Comment by 4ast** [comment]
it's sitting in 'net'. Should be in rc5

**Comment by brendangregg** [comment]
Just checked on latest (pre-4.8-rc1), and execsnoop now works again. Thanks, closing ticket.
