### ISSUE TITLE
Fix string type handling in attach_kprobe()

### ISSUE THREAD

**Issue by markdrayton** [iovisor/bcc#623]
As discovered in #615, `attach_kprobe()` with `from __future__ import unicode_literals` makes an assertion failure:

```
# ./cachetop.py
Traceback (most recent call last):
  File "./cachetop.py", line 255, in <module>
    curses.wrapper(handle_loop, args)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "./cachetop.py", line 177, in handle_loop
    b.attach_kprobe(event="add_to_page_cache_lru", fn_name="do_count")
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 362, in attach_kprobe
    assert isinstance(event, str), "event must be a string"
AssertionError: event must be a string
```

The assert exists because we later use the key type to determine how to unregister a kprobe:

https://github.com/iovisor/bcc/blob/f4bf27517d1fe59ed915d7f8cb3610d4a58583ae/src/python/bcc/__init__.py#L770

We can probably make this more robust by splitting the probe types or filtering in a way that matches all string types.

**Comment by markdrayton** [comment]
closed via #632.
