### ISSUE TITLE
BPF program load error

### ISSUE THREAD

**Issue by goldshtn** [iovisor/bcc#751]
I think I found a bug. Can't load a very simple BPF program, getting a verifier error.

Repro:

``` python
# This is error.py
from bcc import BPF                                                             

 prog = """                                                                      
 #include <linux/ptrace.h>                                                       

 static inline int dummy(struct pt_regs *ctx, void *dest, size_t len) {          
   switch(ctx->ip) {                                                             
   case 0x55e29a4ce2a4ULL: *((uint64_t *)dest) = (uint64_t)ctx->si; return 0;    
   case 0x55e29a4ce7abULL: *((uint64_t *)dest) = (uint64_t)ctx->bp; return 0;    
   }                                                                             
   return -1;                                                                    
 }                                                                               

 int do_start(struct pt_regs *ctx)                                               
 {                                                                               
         u64 arg1 = 0;                                                           
         dummy(ctx, &arg1, sizeof(arg1));                                        
         if (arg1 != 0) {                                                        
             bpf_trace_printk("Hi\\n");                                          
         }                                                                       

         return 0;                                                               
 }                                                                                                                                                         
 """                                                                             

 BPF(text=prog).load_func("do_start", BPF.KPROBE)                                
```

Results:

```
# uname -r
4.8.0-1.vanilla.knurd.1.fc23.x86_64

# python error.py
bpf: Permission denied
0: (79) r2 = *(u64 *)(r1 +128)
1: (18) r3 = 0x9a4ce7ab
3: (1d) if r2 == r3 goto pc+5
 R1=ctx R2=inv R3=inv R10=fp
4: (18) r3 = 0x9a4ce2a4
6: (5d) if r2 != r3 goto pc+11
 R1=ctx R2=inv R3=inv R10=fp
7: (07) r1 += 104
8: (05) goto pc+1
10: (79) r1 = *(u64 *)(r1 +0)
R1 invalid mem access 'inv'

Traceback (most recent call last):
  File "/home/vagrant/error.py", line 27, in <module>
    BPF(text=prog).load_func("do_start", BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 255, in load_func
    raise Exception("Failed to load BPF program %s: %s" % (func_name, errstr))
Exception: Failed to load BPF program do_start: Permission denied
```

Adding a bit more code so that `arg1` isn't the first local being used makes the error go away. Removing one of the cases makes the error go away. 

/cc @4ast @drzaeus77 @brendangregg

**Comment by goldshtn** [comment]
@4ast Any chance you could take a quick look at this? I was able to work around it in my specific use-case, but it does seem like weird behavior, possibly a verifier issue.

**Comment by 4ast** [comment]
To explain the problem i have to point out that bpf program view
on ctx != kernel view. In case of kprobe program type,
struct pt_regs for program == struct pt_regs for kernel,
but all other program types do different rewrite.
bpf_prog_type=perf_event has
```
struct bpf_perf_event_data {
        struct pt_regs regs;
        __u64 sample_period;
};
```
whereas the kernel sees 'ctx==r1' as a pointer to:
```
struct bpf_perf_event_data_kern {
        struct pt_regs *regs;
        struct perf_sample_data *data;
};
```
The rewrite happens inside the kernel in pe_prog_convert_ctx_access() function.

Back to the asm:
```
7: (07) r1 += 104
8: (05) goto pc+1
10: (79) r1 = *(u64 *)(r1 +0)
```
though r1 is a valid offset within ctx verifier cannot rewrite it.
It only supports 'r1+user_off' -> 'r1+kern_off'.
since it's often impossible to do insn rewrite
along all the paths.
Like here insn 10 could be reached via different paths.
In one path it could be:
```
r1 += offX;
goto 10;
10: r1 = *(u64 *)(r1 +0)
```
in another
```
r1 += offY;
goto 10;
10: r1 = *(u64 *)(r1 +0)
```
and one insn 10 will represent two different accesses that
potentially should be rewritten differently.
I don't know how to fix this issue.
Best we can do is to teach llvm to avoid such code generation.
