### ISSUE TITLE
nodejs_http_server.py fails to load do_trace

### ISSUE THREAD

**Issue by affansyed** [iovisor/bcc#829]
@brendangregg your example for USDT tracing of a node application is failing to load the ebpf program. 

It seems to be related to bug here (https://github.com/iovisor/bcc/issues/751), but really cant figure out how to resolve. 

Using the nightly build for bcc from  Nov 28th, 2016. 

commenting out this line allows the ebpf code to be hooked. 

//bpf_probe_read(&path, sizeof(path), (void *)addr);

Affan
`$ sudo ./nodejs_http_server.py 6615
bpf: Permission denied
0: (79) r3 = *(u64 *)(r1 +32)
1: (b7) r7 = 0
2: (7b) *(u64 *)(r10 -8) = r7
3: (07) r3 += -4312
4: (bf) r1 = r10
5: (07) r1 += -8
6: (b7) r2 = 8
7: (85) call 4
8: (79) r3 = *(u64 *)(r10 -8)
9: (bf) r6 = r10
10: (07) r6 += -144
11: (bf) r1 = r6
12: (b7) r2 = 128
13: (85) call 4
invalid indirect read from stack off -144+0 size 128

Traceback (most recent call last):
  File "./nodejs_http_server.py", line 44, in <module>
    b = BPF(text=bpf_text, usdt_contexts=[u])
  File "/usr/local/lib/python2.7/dist-packages/bcc/__init__.py", line 243, in __init__
    usdt_context.attach_uprobes(self)
  File "/usr/local/lib/python2.7/dist-packages/bcc/usdt.py", line 156, in attach_uprobes
    addr=addr, pid=pid)
  File "/usr/local/lib/python2.7/dist-packages/bcc/__init__.py", line 758, in attach_uprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/local/lib/python2.7/dist-packages/bcc/__init__.py", line 290, in load_func
    raise Exception("Failed to load BPF program %s: %s" % (func_name, errstr))
Exception: Failed to load BPF program do_trace: Permission denied`

**Comment by goldshtn** [comment]
I'm assuming this is fixed in #1151.
