### ISSUE TITLE
error on vagrant fedora binary install

### ISSUE THREAD

**Issue by ceeaspb** [iovisor/bcc#848]
Runtime error following fedora binary install on vagrant fedora 23.
https://atlas.hashicorp.com/fedora/boxes/23-cloud-base

```
[root@localhost ~]# /usr/share/bcc/tools/filetop
chdir(/lib/modules/4.2.3-300.fc23.x86_64/build): No such file or directory
Traceback (most recent call last):
  File "/usr/share/bcc/tools/filetop", line 153, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 240, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 
```

**Comment by pchaigno** [comment]
@ceeaspb I had the same error and had to install `kernel-devel-4.2.3-300.fc23.x86_64` to fix it.

**Comment by ceeaspb** [comment]
thanks @pchaigno
