### ISSUE TITLE
user lock contention tool

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#892]
Now that bcc has USDT support, a tool can be written to report on user lock contention using the libpthread probes. These:

```Shell
# /bcc/tools/tplist.py -p 28651
[...]
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:pthread_start
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:pthread_create
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:pthread_join
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:pthread_join_ret
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:mutex_init
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:mutex_destroy
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:mutex_acquired
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:mutex_entry
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:mutex_timedlock_entry
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:mutex_timedlock_acquired
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:mutex_release
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:rwlock_destroy
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:rdlock_acquire_read
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:rdlock_entry
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:wrlock_acquire_write
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:wrlock_entry
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:rwlock_unlock
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:cond_init
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:cond_destroy
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:cond_wait
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:cond_timedwait
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:cond_signal
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:cond_broadcast
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:lll_lock_wait_private
/lib/x86_64-linux-gnu/libpthread-2.23.so libpthread:lll_lock_wait
[...]
```

(Does a tool already exist that uses these? They've been in libpthread for a while now.)

Such a tool could measure, for each of the lock types:
- lock wait time (contention): measured in different ways. As milliseconds per second, as a histogram showing the distribution of each event. And by lock type.
- lock hold time: measured in different ways...
- optionally include stack traces (that requires Linux 4.6+).

As examples of how these can be presented, I liked the Solaris lockstat/plockstat outputs. Here's some old screenshots I posted:
- http://www.solarisinternals.com/wiki/index.php/DTrace_Topics_Locks

**Comment by goldshtn** [comment]
Possible duplicate of #378, where we discussed this about a year ago. I started building this but with the older stack walking mechanism, and tried to do something a bit more generic than just for mutexes in libc. I also have this as an [exercise in my Linux tracing workshop](https://github.com/goldshtn/linux-tracing-workshop/blob/master/lockstat.py). This would be a nice tool to have.

**Comment by goldshtn** [comment]
BTW I think it would be valuable to get the wait time and hold time distribution for individual locks, not just lock types. Recording this might be a bit more expensive, so maybe with a non-default option, but very valuable to understand which lock exactly is causing trouble. This can be done even if stack traces are not available.

**Comment by brendangregg** [comment]
@goldshtn Wow, so you already did this. Using your [lockstat-solution tool](https://github.com/goldshtn/linux-tracing-workshop/blob/master/lockstat-solution.py) from your [contention lab](https://github.com/goldshtn/linux-tracing-workshop/blob/master/bpf-contention.md):

```Shell
# ./lockstat-solution.py 7939
thread 7941
	mutex 0x7ffd13575940 [/tmp/perf-7939.map] ::: wait time 28487.80us ::: hold time 35239.98us ::: enter count 6842
		primes_loop+0x35 [/root/parprimes] (4009f0)
		primes_thread+0x20 [/root/parprimes] (400a44)
		start_thread+0xca [/lib/x86_64-linux-gnu/libpthread-2.23.so] (7f230267270a)

thread 7942
	mutex 0x7ffd13575940 [/tmp/perf-7939.map] ::: wait time 371.58us ::: hold time 453.93us ::: enter count 76
		primes_loop+0x35 [/root/parprimes] (4009f0)
		primes_thread+0x20 [/root/parprimes] (400a44)
		start_thread+0xca [/lib/x86_64-linux-gnu/libpthread-2.23.so] (7f230267270a)

thread 7943
	mutex 0x7ffd13575940 [/tmp/perf-7939.map] ::: wait time 213.26us ::: hold time 237.09us ::: enter count 38
		primes_loop+0x35 [/root/parprimes] (4009f0)
		primes_thread+0x20 [/root/parprimes] (400a44)
		start_thread+0xca [/lib/x86_64-linux-gnu/libpthread-2.23.so] (7f230267270a)

thread 7944
	mutex 0x7ffd13575940 [/tmp/perf-7939.map] ::: wait time 121.15us ::: hold time 149.74us ::: enter count 26
		primes_loop+0x35 [/root/parprimes] (4009f0)
		primes_thread+0x20 [/root/parprimes] (400a44)
		start_thread+0xca [/lib/x86_64-linux-gnu/libpthread-2.23.so] (7f230267270a)

     wait time (us)      : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 32       |                                        |
         4 -> 7          : 6942     |****************************************|
         8 -> 15         : 9        |                                        |
        16 -> 31         : 1        |                                        |
     hold time (us)      : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 0        |                                        |
         4 -> 7          : 6970     |****************************************|
         8 -> 15         : 14       |                                        |
thread 7941
	mutex 0x7ffd13575940 [/tmp/perf-7939.map] ::: wait time 50880.76us ::: hold time 62887.44us ::: enter count 12201
		primes_loop+0x35 [/root/parprimes] (4009f0)
		primes_thread+0x20 [/root/parprimes] (400a44)
		start_thread+0xca [/lib/x86_64-linux-gnu/libpthread-2.23.so] (7f230267270a)

thread 7942
	mutex 0x7ffd13575940 [/tmp/perf-7939.map] ::: wait time 756.99us ::: hold time 905.15us ::: enter count 152
		primes_loop+0x35 [/root/parprimes] (4009f0)
		primes_thread+0x20 [/root/parprimes] (400a44)
		start_thread+0xca [/lib/x86_64-linux-gnu/libpthread-2.23.so] (7f230267270a)

thread 7943
	mutex 0x7ffd13575940 [/tmp/perf-7939.map] ::: wait time 400.26us ::: hold time 471.96us ::: enter count 76
		primes_loop+0x35 [/root/parprimes] (4009f0)
		primes_thread+0x20 [/root/parprimes] (400a44)
		start_thread+0xca [/lib/x86_64-linux-gnu/libpthread-2.23.so] (7f230267270a)

thread 7944
	mutex 0x7ffd13575940 [/tmp/perf-7939.map] ::: wait time 244.36us ::: hold time 291.36us ::: enter count 51
		primes_loop+0x35 [/root/parprimes] (4009f0)
		primes_thread+0x20 [/root/parprimes] (400a44)
		start_thread+0xca [/lib/x86_64-linux-gnu/libpthread-2.23.so] (7f230267270a)

     wait time (us)      : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 52       |                                        |
         4 -> 7          : 12410    |****************************************|
         8 -> 15         : 14       |                                        |
        16 -> 31         : 6        |                                        |
     hold time (us)      : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 0        |                                        |
         4 -> 7          : 12465    |****************************************|
         8 -> 15         : 17       |                                        |
^CTraceback (most recent call last):
  File "./lockstat-solution.py", line 205, in <module>
    run(int(sys.argv[1]))
  File "./lockstat-solution.py", line 176, in run
    sleep(5)
KeyboardInterrupt
```

Are you interested in polishing that as a tool? Some changes (probably obvious):
- missing "\n" between outputs.
- add a -T to include timestamp.
- I'd have default output collect until Ctrl-C, not the 5 sec interval, which also means,
- Ctrl-C shouldn't error, it should print out the current state.
- args can be something like: [-p PID] [interval [count]].
- are they total wait and hold times or averages? I could read the tool, but would be nice to say so on the output. Also, if possible, keep the output <= 80 chars width. :)
- are those histograms a summary for those metrics. Needs a title, "process-wide summaries:" so we know it's not for individual locks. Of course, it would also be good to have an option that did these histograms for individual locks -- like a -v for verbose maybe?
- can call it plockstat after process lockstat, and have a klockstat for kernel. If it stays as lockstat and intends to do both, it could have -u for user and -k for kernel. I don't know what the default should be.

And right, I'd even commented on #378, although that's for both kernel and user locks. Considering that user will be USDT, and kernel will be kprobes (no tracepoints?), it may make sense to implement these as two different tools (and leave these as two tickets?). Or not.

Yes, I meant for individual locks. Just wanted to mention the lock types so the author doesn't forget to hit up all the USDT probes.

**Comment by kennyyu** [comment]
@brendangregg @4ast Related to user locks, I've been working on a tool to detect potential deadlocks in running programs. It does so by tracing `pthread_mutex_lock` and `pthread_mutex_unlock` calls. More details here: https://github.com/iovisor/bcc/pull/936

**Comment by irozzo-1A** [comment]
@goldshtn any reason why https://github.com/goldshtn/linux-tracing-workshop/blob/master/lockstat.py has not been submitted?
